### ISSUE TITLE
Include Wild Web Developer in a standalone IDE

### ISSUE THREAD

**Issue by PhaserEditor2D** [eclipse/wildwebdeveloper#100]
Hi,

I am close to publish a product that includes Wild Web Developer. But I want to provide a self-contained product, something that user can unzip and run. I see WWD requires node and VSCode, as external software dependecies (no packed as plugins).

1- I would like to pack node and VSCode as plugins, so my concern is how much of VSCode we need to pack?

2- Is it possible to pack a platform-independent base of VSCode?

3- If I have to include the complete VSCode "installation", can I use the node executable provided by VSCode?

I am using 0.1.0 version of WWD and it works great, there some missing features but for sure all of these will be implemented. Thanks!

**Comment by mickaelistria** [comment]
> I see WWD requires node and VSCode, as external software dependecies (no packed as plugins).

That's currently true for node ( #23 ) but not for VSCode, the necessary bits of VSCode are packaged inside the bundles.

> 1- I would like to pack node and VSCode as plugins, so my concern is how much of VSCode we need to pack?

None.

> 2- Is it possible to pack a platform-independent base of VSCode?

Yes, and it should be already done by Wild Web Developer

> 3- If I have to include the complete VSCode "installation", can I use the node executable provided by VSCode?

You don't need a complete VSCode installation.

>  there some missing features but for sure all of these will be implemented.

Let's hope so! And any help would be welcome on that matter.

**Comment by PhaserEditor2D** [comment]
Yes, I installed a VM with empty windows and VSCode is not required. I was confused because of the method: https://github.com/eclipse/wildwebdeveloper/blob/361dad906e5a47945ffa8d4e02f4d6519c256313/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java#L35

**Comment by PhaserEditor2D** [comment]
I missed to say thanks :)

**Comment by mickaelistria** [comment]
>  I was confused because of the method:

That understandable. If this.method is not used, feel free to submit a PR that removes it.
