### ISSUE TITLE
Selection highlighting not working

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#104]
Hello,

I'm having trouble with the highlight feature. When I select a variable, I would expect all occurrences to be highlighted, however, this is not the case. Note that I have the _Toggle Highlight_ option enabled. See screenshot below:
![screenshot 128](https://user-images.githubusercontent.com/10694593/50441691-31b16180-08fc-11e9-84e4-54981ab0fa9d.png)

Thanks in advance for your help!

Cheers,

Pyves

**Comment by mickaelistria** [comment]
The connection and request with the Language Server seem correct, but the LS returns a "wrong" result. It's most likely an issue to report to https://github.com/theia-ide/typescript-language-server . Would you like to report it?

**Comment by PyvesB** [comment]
Thank you for your response. I've submitted an issue [here](https://github.com/theia-ide/typescript-language-server/issues/94). I'm not too familiar with that project or how language servers work in general, but hopefully it makes sense.

**Comment by PyvesB** [comment]
Update on this: I sent a PR to the Typescript Language server, https://github.com/theia-ide/typescript-language-server/pull/125. [Bug 536232](https://bugs.eclipse.org/bugs/show_bug.cgi?id=536232) will also need to be resolved before highlighting can become functional in WWD and other LSP-based plugins.

**Comment by PyvesB** [comment]
26c8c68faadf1afda0d8d7632faa826e008f0898 finally pulled in the aforementioned fix. I can confirm that the problem is now resolved on Windows, closing. :)
