### ISSUE TITLE
Typescript analysis broken after update

### ISSUE THREAD

**Issue by ZeeD** [eclipse/wildwebdeveloper#1070]
After updating wwd I have this popup in the lower left corner with the error:

```
LSP (JavaScript-TypeScript Language Server)
Inlay Hints request failed. Requires TypeScript 4.4+.
```

every time I open a `.ts` file. and then the autocomplete is broken (the syntax colors still works)

a quick check on the running processes showed me

```
$ ps aux | grep typescript
a206719281       29496   0,0  1,2  7189320 392144 s000  T    10:02am   0:06.18 /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/.node/node-v18.12.1-darwin-x64/bin/node /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/../../../../../.p2/pool/plugins/org.eclipse.wildwebdeveloper_1.0.1.202211171559/node_modules/@angular/language-server/index.js --ngProbeLocations /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/../../../../../.p2/pool/plugins/org.eclipse.wildwebdeveloper_1.0.1.202211171559/node_modules/@angular/language-service --tsProbeLocations /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/../../../../../.p2/pool/plugins/org.eclipse.wildwebdeveloper_1.0.1.202211171559/node_modules/typescript --stdio --logVerbosity terse
a206719281       29605   0,0  0,0  4259848    420 s000  R+   10:03am   0:00.00 grep --color=auto typescript
a206719281       29502   0,0  0,2  6006784  72476 s000  T    10:02am   0:00.33 /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/.node/node-v18.12.1-darwin-x64/bin/node /Users/a206719281/eclipse-workspace/ocellus-js-sdk-src/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/a206719281/Library/Caches/typescript/3.9 --typesMapLocation /Users/a206719281/eclipse-workspace/ocellus-js-sdk-src/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
a206719281       29501   0,0  0,9  7160708 311168 s000  T    10:02am   0:06.62 /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/.node/node-v18.12.1-darwin-x64/bin/node /Users/a206719281/eclipse-workspace/ocellus-js-sdk-src/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --cancellationPipeName /private/var/folders/mn/0hdhd2fx0sd9bd3j5nx0v7bm0000gn/T/ad060e57d6f04070dac4cc326400012b/tscancellation* --globalPlugins typescript-plugin-css-modules,typescript-lit-html-plugin --pluginProbeLocations /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/../../../../../.p2/pool/plugins/org.eclipse.wildwebdeveloper_1.0.1.202211171559/node_modules/typescript-plugin-css-modules,/Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/../../../../../.p2/pool/plugins/org.eclipse.wildwebdeveloper_1.0.1.202211171559/node_modules/typescript-lit-html-plugin --locale en --validateDefaultNpmLocation
a206719281       29499   0,0  0,2 17299540  52640 s000  T    10:02am   0:00.55 /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/.node/node-v18.12.1-darwin-x64/bin/node /Users/a206719281/eclipse/java-latest/Eclipse.app/Contents/Eclipse/../../../../../.p2/pool/plugins/org.eclipse.wildwebdeveloper_1.0.1.202211171559/node_modules/typescript-language-server/lib/cli.js --stdio
$
```

shows me that there is a `/Users/a206719281/Library/Caches/typescript/3.9` invoked. But this cache has been created by eclipse+wwd themselfs

I have recreated this problem from a clean installation of eclipse (latest - 2023-03) and just WWD (latest)

**Comment by mickaelistria** [comment]
As a workaround, I suggest you just remove the cache. Typescript 3.9 shouldn't be used. Wild Web Developer embeds typescript 4.9.4 as you can see in https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/package.json#L5

**Comment by ZeeD** [comment]
hi @mickaelistria I have already removed /Users/a206719281/Library/Caches/typescript totally. 
for some reason wwd created it

**Comment by mickaelistria** [comment]
Could it be that your project has TypeScript 3.9 in its node_modules?

**Comment by ZeeD** [comment]
Uhm... I am looking at the Error Log panel I see that
```
[Info]	[lspserver] Using Typescript version (workspace) 3.9.10 from path "/Users/a206719281/eclipse-workspace/ocellus-js-sdk-src/node_modules/typescript/lib/tsserver.js"
```
witch seems to match your doubt, @mickaelistria .

but... this seems wrong to me: the IDE tools should not relies on the worspace internal stuff...

**Comment by mickaelistria** [comment]
> the IDE tools should not relies on the worskpace internal stuff...

While I agree with you, I believe it's actually an issue of typescript/tsserver in general.

**Comment by mickaelistria** [comment]
In the meantime, a better workaround would be then that you ugrade your project to a newer typescript if possible.

**Comment by ZeeD** [comment]
uhm... specifically for my project(s) it may be possible, but I'm the only one using eclipse and it will not make a good impression :/

more generally, I don't get the flow: *what* is `lspserver` (in the eclipse Error log) and by what reason do it "choose" to launch the `tsserver.js` implementation in my workspace?

**Comment by mickaelistria** [comment]
> uhm... specifically for my project(s) it may be possible, but I'm the only one using eclipse and it will not make a good impression :/

If because of this bad impression, more people use newer versions of typescript; then the net result is positive: Eclipse IDE encourages usage of more up-to-date software and this is usually a major quality criterion for sustainability of the project being developed by the users. So in the end, the impact on the code being developed is positive, and that matters more on the long run than some impressions ;)
To be honest, the Eclipse community has evolved lately: the dogma is not to be compatible with everything from the past anymore, but just to remain good with the present things, so I don't see much hope of people investing effort to better support older technologies (unless they get paid for it by people who need this critically).

>  what is lspserver (in the eclipse Error log) and by what reason do it "choose" to launch the tsserver.js implementation in my workspace?

See https://github.com/typescript-language-server/typescript-language-server ; this component provides the language smartness, Eclipse IDE is "just" orchestrating the queries and presenting the results to user. This is where tsserver is chosen.

**Comment by ZeeD** [comment]
sorry, I wanted to say something a little different.
I know that - at least from some time - eclipse doesn't have an "internal" ts parser to do the syntax highlight and the autocomplete and the other stuff, but relies on external processes (the lsp servers) to gain this information.

But keep in mind that I work on many projects at the same time. I have probably 10+ different tsserver copies on my hard drive, from multiple node_modules, from different IDEs (I also use vscode and idea) etc..

what I don't know is: what "piece" of eclipse (wwd? lsp4e? another plugin?) has the responsibility to choose what is the `tsserver` implementation to launch? Is there a way to configure it?

**Comment by mickaelistria** [comment]
> what I don't know is: what "piece" of eclipse (wwd? lsp4e? another plugin?) has the responsibility to choose what is the tsserver implementation to launch? Is there a way to configure it?

Wild Web Developer includes and uses https://github.com/typescript-language-server/typescript-language-server ; the language server takes care of chosing tsserver to use for a given file.

**Comment by ZeeD** [comment]
I agree with you.

but also looking at https://github.com/typescript-language-server/typescript-language-server#initializationoptions t-s-s expect to receive some `initializationOptions` via the `initialize` request. I suspect this call is already used, as - for example - it should be used to set the server logs verbosity / target file. This information is also directly configurable from the eclipse preferences, in language server logs > logs, so I suspect this eclipse config is then "proxed" to t-s-s.

as I see that in that `TsserverOptions` there is also a way to set the path of the `tsserver.js` I was hoping that this could set "in the same place" where the eclipse plugin keep track of the logs configurations

**Comment by mickaelistria** [comment]
The issue is then about the other way round: if a new Typescript/tsserver is released and Wild Web Developer is not updated to use it, then the features of new typescript/tsserver are not available to user. While picking the project tsserver allows to be "forward" compatible.
IMO, forward compatibility is better for the domain than backward compatibility.

**Comment by vrubezhny** [comment]
@lrozenblyum I suppose the latest snapshot contains the fix, so you can try installing/updating WWD from the [latest  snapshot](https://download.eclipse.org/wildwebdeveloper/snapshots/)

**Comment by lrozenblyum** [comment]
Thanks @vrubezhny! The snapshot really works much better than the release!

**Comment by howlger** [comment]
Thanks @vrubezhny for the [1.0.2 release](https://github.com/eclipse/wildwebdeveloper/blob/master/RELEASE_NOTES.md#102). It would be nice if 1.0.2 would make it into Eclipse 2023-03.

**Comment by lorenzodallavecchia** [comment]
Today all TypeScript language features stopped working in my workspace.
The following error is logged.

```
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request initialize failed with message: ENOENT: no such file or directory, lstat 'D:\work\eclipse\plugins\org.eclipse.wildwebdeveloper_1.0.2.202302250247\node_modules\typescript\lib\tssserver.js'
```

If you look closely, it is attempting to start `tssserver.js` (with three `s`) instead of `tsserver.js`.
It seems that the wrong file name was introduced by the commit that fixed this issue.

https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/blob/70a2f86e1b333fb86b50a849e27bddec87817369/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java#L59

It's very weird. How could everyone not be affected by this problem until now? My workspace also worked fine up to last week. Am I missing something?

**Comment by vrubezhny** [comment]
@lorenzodallavecchia Thanks for reporting!

You can set up you project to use project's TS Server version, thus skipping this buggy path, but then you have to configure the correct tsserver version to be bundled with your project:

![Screenshot from 2023-12-31 20-43-44](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/620781/d5c5463c-201b-418d-acf2-6cadbd45906f)

See also: https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1308

**Comment by vrubezhny** [comment]
@lorenzodallavecchia  I hope the issue you've faced is fixed now. 

Please try updating WWD from the latest snapshot: 

> With [Help > Install New Software...](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.user/tasks/tasks-124.htm) with p2 repo https://download.eclipse.org/wildwebdeveloper/snapshots

**Comment by lorenzodallavecchia** [comment]
@vrubezhny Yes, it works fine now. Thank you!
