### ISSUE TITLE
[TypeScript] Implement tslint

### ISSUE THREAD

**Issue by edertone** [eclipse/wildwebdeveloper#110]
Hi,

Finally we have a decent web development support in eclipse. 

For typescript development it is really good, but i was wondering if it is possible to add tslint support to the editor?

**Comment by mickaelistria** [comment]
This is an upstream improvement in the language server we're using for typescript. I've opened https://github.com/theia-ide/typescript-language-server/issues/95 to track this. Once it's available in the Language Server, then just upgrading it should be enough without particular development.

**Comment by edertone** [comment]
Hi, this looks like great news!

**Comment by mickaelistria** [comment]
@edertone Can you please provide a minimal file or set of file that triggers some tslint messages? Those would help in implementing/testing the feature. Ideally, this could be provided as a pull-request for a unit test.

**Comment by edertone** [comment]
I have uploaded two files: a class.ts file containing some basic ts code and a tslint.json containing the tslint rules to validate it.

with this setup, following errors should be generated by tslint:

[tslint] trailing whitespace (no-trailing-whitespace)
[tslint] Documentation must exist for private properties. (completed-docs)

[tslint.zip](https://github.com/eclipse/wildwebdeveloper/files/2721183/tslint.zip)

**Comment by mickaelistria** [comment]
@jabby Would you be interested and available to look at this?

**Comment by jabby** [comment]
I am interested but I'm not sure I will be available soon for this. In fact, I need to prepare a conference in Montpellier for mid january. If it's ok to wait the end of the month I will take care of this.

**Comment by mickaelistria** [comment]
@edertone would you be interested in trying to contribute this support? I think it's mostly a matter of 1. adding https://www.npmjs.com/package/typescript-tslint-plugin to https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/language-servers/package.json and then 2. update https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java to configure initializeOptions defining the location of the typescript-tslint-plugin as explained in https://github.com/theia-ide/typescript-language-server/issues/95#issuecomment-450856416

**Comment by edertone** [comment]
Hi @mickaelistria I would be interested in doing this contribution, but since i've never done any eclipse plugin development I may require some time to setup the environment and get used to it. If I do it it will be on spare time and I don't know how much time will it take

**Comment by mickaelistria** [comment]
You need "Eclipse Plugin Developer Environment" installed in your IDE.
Then you clone this repo and run `mvn clean verify`.
You can use `File > Open projects from filesystem` to open the repo in the IDE.
Then in the IDE or in command-line, you can tweak things and then run `mvn clean verify` to rebuild the npm dependencies. Once it's done, either you can try from the IDE to do `Run As > Eclipse Application` from the `org.eclipse.wildwebdeveloper` project, or install the build output in `repository/target/repository` in your current IDE to see the effect (but that will replace a working installation with your work-in-progress one), or you can also have a separated and dedicated "test" Eclipse instnace where you only install your work in progress and see the effect.

**Comment by edertone** [comment]
Thanks @mickaelistria I will try to find some weekend to check this out...

**Comment by mickaelistria** [comment]
TSLint is now deprecated: https://www.infoq.com/news/2019/02/tslint-deprecated-eslint
We won't build support for deprecated technologies.
Support for the recommended typescript-eslint can be discussed in #145
