### ISSUE TITLE
Typescript `override` keyword is not highlighted

### ISSUE THREAD

**Issue by lorenzodallavecchia** [eclipse/wildwebdeveloper#1106]
The `override` keyword (added in TS 4.3) is not highlighted.
I would expect it to use the same style of other keywords, like `class` and `extends`.

![immagine](https://user-images.githubusercontent.com/15628014/221550044-24f63e04-d90c-4a02-9055-2f34f83ea4f0.png)

**Comment by mickaelistria** [comment]
It's indeed a bug, but it's not clear whether the bug comes from the used TextMate grammer (maybe Wild Web Developer should just update it?) or whether the grammar is correct but TM4E fails at processing it as expected...

**Comment by vrubezhny** [comment]
In my case 'override' is colored. Not like other keywords like  `private`, `public`, `class`, `extends` etc., but...

![Screenshot from 2023-03-03 11-07-58](https://user-images.githubusercontent.com/620781/222692732-003307e7-b74a-4628-b0b7-d81b9e08e5cb.png)

**Comment by vrubezhny** [comment]
Typescript and Javascript grammars need to be updated. The PR #1115 completely fixes the issue for me.
