### ISSUE TITLE
Add Debug Adapter tab to launch configuration

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/wildwebdeveloper#111]
This is to take advantage of the new API in lsp4e.debug added in [Bug 543279](https://bugs.eclipse.org/bugs/show_bug.cgi?id=543279). In provides another tab that looks like below to enable (advanced?) users to access debug adapter settings not exposed with SWT controls:

![image](https://user-images.githubusercontent.com/679236/50861414-7fb07580-1390-11e9-93f6-c44f189bfc32.png)

**Comment by mickaelistria** [comment]
@akurtakov @jabby @PhaserEditor2D What do you think about it?

**Comment by akurtakov** [comment]
This sounds good to me. Providing easy way to play with the debug adapter is a nice to have.

**Comment by jabby** [comment]
Looks good to me. 👍

**Comment by mickaelistria** [comment]
Hey @jonahgraham , what's the overall status here? Is something still missing in LSP4E?

**Comment by jonahgraham** [comment]
It is ready to merge, I have rebased the change to make it easier. See PR #113

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/commit/6ddcd5ca709c11675376d57cf79e23f4bf570c79 , thanks @jonahgraham
