### ISSUE TITLE
Installation of latest release fails

### ISSUE THREAD

**Issue by sebthom** [eclipse/wildwebdeveloper#1118]
Installation of latest release from https://download.eclipse.org/wildwebdeveloper/releases/latest/ fails with
```
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group 1.0.2.202302072133
[ERROR]   Missing requirement: org.eclipse.wildwebdeveloper.embedder.node 1.0.2.202212140804 requires 'java.package; org.apache.commons.compress.archivers 1.22.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group 1.0.2.202302072133 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper.embedder.node [1.0.2.202212140804,1.0.2.202212140804]
```

Maybe **org.apache.commons.compress.archivers** needs to be included in the updatesite?

It is apparently loaded from maven central during build time https://github.com/eclipse/wildwebdeveloper/blob/master/target-platform/target-platform.target#L79

The required version 1.22 is also not in the orbit repo at https://download.eclipse.org/tools/orbit/downloads/drops/R20221123021534/repository

**Comment by mickaelistria** [comment]
Indeed, it should be part of the p2 reposutory. I don't get why it's not included in the p2 repo while it's part of the product though...
