### ISSUE TITLE
Wild web developer has useful code that could be used in other places

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/wildwebdeveloper#112]
I would like to move a little bit of code higher up the stack from wildwebdeveloper to lsp4e.debug. Specifically InitializeLaunchConfigurations to make it easier for CDT's debug adapter and wildwebdeveloper's adapter to be more consistent on where to get node from.

I see this as a pre-cursor to having Node shipped in some way with CDT/wildwebdev.

The corresponding bug in lsp4e is [Bug 543280](https://bugs.eclipse.org/bugs/show_bug.cgi?id=543280)

**Comment by mickaelistria** [comment]
I think this somehow relates to #23 and detection of node.js should be in a separate bundle and not in main LSP4E bundle.
What do you think about Wild Web Developer hosting those node utils and CDT reusing them?

**Comment by jonahgraham** [comment]
> What do you think about Wild Web Developer hosting those node utils and CDT reusing them?

OK, but only as a separate bundle.

**Comment by mickaelistria** [comment]
> OK, but only as a separate bundle.

Of course!

**Comment by guw** [comment]
@jonahgraham @mickaelistria What is the decision/action items on this one? I have a similar requirement, i.e. I'm about to build an Eclipse plug-in that ships a language server which requires Node at runtime. For best out of the box experience I'm investigating embedding Node in Eclipse.

I like to re-use anything that's been created here.

**Comment by jonahgraham** [comment]
Hi @guw, +1 to what Mickael said. I would love to find the time to work on this, but it is low priority for me too. At the moment my energy is on a special project :-) https://twitter.com/JonahGrahamKC/status/1098531058100944898

**Comment by mickaelistria** [comment]
Related https://github.com/eclipse/wildwebdeveloper/issues/23

**Comment by mickaelistria** [comment]
The node.js detector/embedder is now in place, in its own feature, and documented for external usage: https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.embedder.node/README.md . The current state IMO covers the initial request, so I'm closing it.
Testing, feedback and improvements are highly welcome (in new issues and new PRs).

**Comment by jonahgraham** [comment]
Thank you @mickaelistria - I will encourage CDT devs to consume that code.
