### ISSUE TITLE
Duplicate toggle highlight buttons

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#115]
Hello,

I noticed that the toggle highlight button seemed to get duplicated, I've observed up to three of them being displayed next to each other in the toolbar:

![duplicate_highlight png](https://user-images.githubusercontent.com/10694593/51268343-cc5f0680-19b7-11e9-8069-3eeee0676880.jpg)

This only seems to happen on my Eclipse installation that runs Wild Web Developer and a quick search on Eclipse's Bugzilla didn't return anything related, which lead me to think it might be an issue with this project.

Let me know if I can provide any additional information.

Cheers,

Pyves

**Comment by mickaelistria** [comment]
Tracked at https://bugs.eclipse.org/bugs/show_bug.cgi?id=534325

**Comment by PyvesB** [comment]
Good spot! I was looking using the keyword "duplicate" and therefore wasn't getting anything back... Thanks.

**Comment by mickaelistria** [comment]
This is an Eclipse Platform bug, which is fixed in current nightly build and will be available in next release.
Closing as it's not actionable from Wild Web Developer in any way.
