### ISSUE TITLE
ESLint errors not showing in jsx files

### ISSUE THREAD

**Issue by wesleybl** [eclipse/wildwebdeveloper#1150]
ESLint errors not showing in `jsx` files in Eclipse 2023-03. I'm using: master of wildwebdeveloper

Steps to reproduce:

- Clone: https://github.com/wesleybl/test-eslint
- Run `npm install`inside the folder `test-eslint`
- Open the test-eslint folder as an Eclipse project.
- See that no errors are shown in the `src/test.jsx` file.

At first I thought it might be something to do with #1133. But I think it's something different, since the ESLint server constructor is not even called, when we open a `jsx` file.

Obs:

With wildwebdeveloper 1.0.1 works.
I have not tested with 1.0.2.
In 1.0.3 we also have the error.

**Comment by vrubezhny** [comment]
It looks  like an upstream issue in [vscode-eslint](https://github.com/microsoft/vscode-eslint/pull/1611).

There is also a problem occurring with `TestTypeScript.testHTMLinTSXFile` JUnit test in some latest PRs which looks like also related.
