### ISSUE TITLE
How to run a single test?

### ISSUE THREAD

**Issue by wesleybl** [eclipse/wildwebdeveloper#1155]
How do I run a single test? I know that when I run `mvn clean verify`, at the end it runs the tests. But this command takes too long and runs all the tests. I believe that after this command, it should be possible to run a single test, either on the command line or in Eclipse. How do I do it? This could be documented in:

https://github.com/eclipse/wildwebdeveloper/blob/master/CONTRIBUTING.md

**Comment by vrubezhny** [comment]
Use the following commands, for example:

```
$ cd <WildWebDeveloper project root directory>

# In order to run `org.eclipse.wildwebdeveloper.tests.TestHTML` use the following command:
$ mvn clean verify -Dtest=TestHTML   
```
In case you need to work on tests or repeatedly execute several tests, it's easier and faster to build everything then run only the tests:

```
$ cd <WildWebDeveloper project root directory>

# Build WWD: 
$ mvn clean install -DskipTests
  
# In order to run `org.eclipse.wildwebdeveloper.tests.TestHTML` use the following command:
$ cd org.eclipse.wildwebdeveloper.tests/
$ mvn clean verify -Dtest=TestHTML   

#`Repeat running TestHTML or run any other tests, for example:
$ mvn clean verify -Dtest=TestJSON   
```

HTH

**Comment by wesleybl** [comment]
@vrubezhny fantastic! I tested it and it worked. It would be great to have this documented in:

https://github.com/eclipse/wildwebdeveloper/blob/master/CONTRIBUTING.md

By Eclipse,, I right click on:

https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestHTML.java

And I went to `Run As -> JUinit-plugin Test`. This works too, after running `mvn clean install -DskipTests`, correct?

**Comment by vrubezhny** [comment]
Right, because of the need to download/install the embedded Node.js executables, Language Servers and other NPM dependency modules first, you need to build it with `npm clean install -DskipTests`. After that you can try running the JUnit tests from Eclipse.
