### ISSUE TITLE
Cannot install in 2019-03 from marketplace

### ISSUE THREAD

**Issue by wimjongman** [eclipse/wildwebdeveloper#117]
Dragging into the 2019-03 nightly Eclipse IDE (base IDE + marketplace) does not prompt for installation but prompts the marketplace search box instead.

**Comment by mickaelistria** [comment]
Is it any different for other marketplace solutions? I think the 2019-03 compatibility is still missing on Marketplace.

**Comment by mickaelistria** [comment]
https://github.com/eclipse/wildwebdeveloper#installation describes alternative installation steps.

**Comment by wimjongman** [comment]
Thanks I did find that one.
