### ISSUE TITLE
Wild Web Developer is not findable through Eclipse website

### ISSUE THREAD

**Issue by wimjongman** [eclipse/wildwebdeveloper#118]
I was trying to find a repository or code base for the wild web developer on the eclipse.org site. There is nothing that points me to this site nor is there a landing page for wild web developer on eclipse org.

**Comment by mickaelistria** [comment]
Information can be found from https://projects.eclipse.org/projects/tools.wildwebdeveloper which is available if you browse all projects.
We don't plan to create a landing page as it seems much more profitable to work on code.

**Comment by mickaelistria** [comment]
There is no marketing department ;)
I think some activity on social media and Reddit linking to the README + making the README nicer would be a more profitable investment if you want to grow the popularity of the project. But at the moment, there is still enough stuff in the backlog to focus effort on development.

**Comment by wimjongman** [comment]
So no landing page then. I'm not that active on social media so you have to find someone else to do this.
