### ISSUE TITLE
[BUG, v1.0.5] Weird tooltips shows in plugin.yml

### ISSUE THREAD

**Issue by Jimmy-sheep** [eclipse/wildwebdeveloper#1185]
The tooltips shows weird, its not good to read, there's a big space between every letter.

This is it actually shows, please fix it soon, thanks.
`
 # # # #   B u k k i t   p l u g i n \ . y m l     A   u s e r \ - f r i e n d l y   d e s c r i p t i o n   f o r   a   c o m m a n d \ .     S o u r c e :   [ p l u g i n . y m l ] ( s c h e m a s e r v i c e : / / c o m b i n e d S c h e m a / f i l e % 3 A % 2 F % 2 F % 2 F D % 3 A % 2 F e c l i p s e - w o r k s p a c e % 2 F S h e e p R P G % 2 F p l u g i n . y m l ) 
`

![image](https://user-images.githubusercontent.com/65125836/235642032-fbf6f3ac-bc8e-4f61-9bb2-cc406354553a.png)

**Comment by vrubezhny** [comment]
The YAML LS reports the hover contents in the way that every character is separated with `&emsp;` ("em space") character.  
```
[2023-05-02T13:30:21.714459582+02:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.yaml:
{"jsonrpc":"2.0","id":"354","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///home/jeremy/projects/examples/eliasbalasis/runtime-workspace/minimal/plugin.yml"},"position":{"line":14,"character":11}}}

[2023-05-02T13:30:21.727038733+02:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.wildwebdeveloper.yaml:
{"jsonrpc":"2.0","id":"354","result":{"contents":{"kind":"markdown","value":"&emsp;#&emsp;#&emsp;#&emsp;#&emsp; &emsp;B&emsp;u&emsp;k&emsp;k&emsp;i&emsp;t&emsp; &emsp;p&emsp;l&emsp;u&emsp;g&emsp;i&emsp;n&emsp;\\&emsp;.&emsp;y&emsp;m&emsp;l&emsp;\n&emsp;\n&emsp;A&emsp; &emsp;u&emsp;s&emsp;e&emsp;r&emsp;\\&emsp;-&emsp;f&emsp;r&emsp;i&emsp;e&emsp;n&emsp;d&emsp;l&emsp;y&emsp; &emsp;d&emsp;e&emsp;s&emsp;c&emsp;r&emsp;i&emsp;p&emsp;t&emsp;i&emsp;o&emsp;n&emsp; &emsp;f&emsp;o&emsp;r&emsp; &emsp;a&emsp; &emsp;c&emsp;o&emsp;m&emsp;m&emsp;a&emsp;n&emsp;d&emsp;\\&emsp;.&emsp;\n&emsp;\n&emsp;S&emsp;o&emsp;u&emsp;r&emsp;c&emsp;e&emsp;:&emsp; &emsp;[&emsp;p&emsp;l&emsp;u&emsp;g&emsp;i&emsp;n&emsp;.&emsp;y&emsp;m&emsp;l&emsp;]&emsp;(&emsp;s&emsp;c&emsp;h&emsp;e&emsp;m&emsp;a&emsp;s&emsp;e&emsp;r&emsp;v&emsp;i&emsp;c&emsp;e&emsp;:&emsp;/&emsp;/&emsp;c&emsp;o&emsp;m&emsp;b&emsp;i&emsp;n&emsp;e&emsp;d&emsp;S&emsp;c&emsp;h&emsp;e&emsp;m&emsp;a&emsp;/&emsp;f&emsp;i&emsp;l&emsp;e&emsp;%&emsp;3&emsp;A&emsp;%&emsp;2&emsp;F&emsp;%&emsp;2&emsp;F&emsp;%&emsp;2&emsp;F&emsp;h&emsp;o&emsp;m&emsp;e&emsp;%&emsp;2&emsp;F&emsp;j&emsp;e&emsp;r&emsp;e&emsp;m&emsp;y&emsp;%&emsp;2&emsp;F&emsp;p&emsp;r&emsp;o&emsp;j&emsp;e&emsp;c&emsp;t&emsp;s&emsp;%&emsp;2&emsp;F&emsp;e&emsp;x&emsp;a&emsp;m&emsp;p&emsp;l&emsp;e&emsp;s&emsp;%&emsp;2&emsp;F&emsp;e&emsp;l&emsp;i&emsp;a&emsp;s&emsp;b&emsp;a&emsp;l&emsp;a&emsp;s&emsp;i&emsp;s&emsp;%&emsp;2&emsp;F&emsp;r&emsp;u&emsp;n&emsp;t&emsp;i&emsp;m&emsp;e&emsp;-&emsp;w&emsp;o&emsp;r&emsp;k&emsp;s&emsp;p&emsp;a&emsp;c&emsp;e&emsp;%&emsp;2&emsp;F&emsp;m&emsp;i&emsp;n&emsp;i&emsp;m&emsp;a&emsp;l&emsp;%&emsp;2&emsp;F&emsp;p&emsp;l&emsp;u&emsp;g&emsp;i&emsp;n&emsp;.&emsp;y&emsp;m&emsp;l&emsp;)&emsp;"},"range":{"start":{"line":14,"character":4},"end":{"line":14,"character":15}}}}
```
The hover content is generated either by the YML LS or is read as is from the schema (I suppose it's "Bukkit plugin.yml - Schema for Minecraft Bukkit plugin description files (bukkit-plugin.json" or similar)

**Comment by vrubezhny** [comment]
Looks like a known issue in YAML LS:  https://github.com/redhat-developer/yaml-language-server/issues/875

**Comment by vrubezhny** [comment]
YAML LS is now updated to v.1.13.0  - https://github.com/eclipse/wildwebdeveloper/pull/1218 - which fixes the "weird tooltip" issue: 

![Screenshot from 2023-05-23 15-26-18](https://github.com/eclipse/wildwebdeveloper/assets/620781/0b90122b-9349-4736-86c1-ec9c7a6618b5)
