### ISSUE TITLE
Updates for commons-compress 1.23.0 are available

### ISSUE THREAD

**Issue by merks** [eclipse/wildwebdeveloper#1223]
Updates available:

https://github.com/merks/simrel-maven/blob/main/wwd/REPORT.md

 - [org.apache.commons](https://repo1.maven.org/maven2/org/apache/commons/)
    - [commons-compress](https://repo1.maven.org/maven2/org/apache/commons/commons-compress/) **[1.22](https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.22)** < [1.23.0](https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.23.0/)

**Comment by vrubezhny** [comment]
@merks Thanks for sharing this info!

**Comment by merks** [comment]
Thanks for being awesomely responsive.
