### ISSUE TITLE
Language Server preferences not persisted between sessions

### ISSUE THREAD

**Issue by thedailycommute** [eclipse/wildwebdeveloper#1236]
I recently (two weeks ago) installed a clean copy of the latest version of Eclipse (2023-03 - 4.27.0), and created a new workspace for my projects. I also updated the WWD plugin to the latest version a few moments ago.

I mention this because I'm not certain if the problem mentioned in the subject is due to Eclipse (seems unlikely) or the plugin itself.

Basically _every_ time I (re)start Eclipse I have to update my preferences in the "Language Servers" page, activating the "Typescript (Javascript-Typescript Language Server)" option and deactivating the "Typescript (Angular Language Server)" and "HTML (Angular Language Server)" options.

It's not difficult to do, but it is annoying because the error markers that appear have to be manually deleted after disabling the two Angular options (affected, open files are, apparently, not reparsed after preferences are changed).

I need to disable the Angular options because our app's frontend is built using (legacy) Angular v2.

**Comment by vrubezhny** [comment]
@thedailycommute The preferences are workspace-wide, so if you're switching between different workspaces the preferences get reloaded. 
If you restart your Eclipse using the same workspace, the preferences values should persist between sessions.

Could you please check if there are any exceptions logged to `.log` and/or `.bak_X.log`  files in  `<your workspace>/.metadata/` directory when you save new preferences or restarting your eclipse after the preferences are changed?  Please share, if any.

**Comment by vrubezhny** [comment]
@thedailycommute Still not sure, but it looks that TypeScript LS enable preference malfunctioning is  highly likely  an issue with Oomph or it's configuration then. 

Regarding the Stack Trace you provided -looks like an issue in TypeScript LS - I found several similar issues reported for different versions of `tsserver` some of them are fixed.

Anyway, glad your problem is solved. Thanks for reporting.
