### ISSUE TITLE
XML LS is started multiple times

### ISSUE THREAD

**Issue by akurtakov** [eclipse/wildwebdeveloper#124]
I have opened 3 xml files from different projects and this ended up starting xml ls 3 times. Can it be made so same xml ls is reused?
3642 ?        Sl     0:03 java -classpath /home/akurtakov/opt/411/eclipse/plugins/org.eclipse.wildwebdeveloper_0.1.0.201901231330/language-servers/server/org.eclipse.lsp4xml-all.jar org.eclipse.lsp4xml.XMLServerLauncher
 3721 ?        Sl     0:03 java -classpath /home/akurtakov/opt/411/eclipse/plugins/org.eclipse.wildwebdeveloper_0.1.0.201901231330/language-servers/server/org.eclipse.lsp4xml-all.jar org.eclipse.lsp4xml.XMLServerLauncher
 3862 ?        Sl     0:02 java -classpath /home/akurtakov/opt/411/eclipse/plugins/org.eclipse.wildwebdeveloper_0.1.0.201901231330/language-servers/server/org.eclipse.lsp4xml-all.jar org.eclipse.lsp4xml.XMLServerLauncher

**Comment by akurtakov** [comment]
@yanxi0830 , please investigate. @mickaelistria if you have pointers for Xi please put them here

**Comment by mickaelistria** [comment]
Whether a language server can be reused or not for a document/file is in LSP4E's `LanguageServerWrapper.canOperate(...)` method. It could be that either LSP4E's condition here isn't capturing well the multi-file capability of XML-LS, or that XML-LS doesn't declare well this capacity.

**Comment by yanxi0830** [comment]
Thanks @mickaelistria , I think the issue here is that XML-LS doesn't support multiple project folders, so `canOperate` will return false whenever it checks `supportWorkspaceFolderCapability`. Adding `WorkspaceServerCapabilities` to lsp4xml seems to solve the issue.

**Comment by mickaelistria** [comment]
Ok, thanks for the investigation. Is there any other capability sent by lsp4xml that you think can be used in canOperate in place of supportsWorkspaceFolderCapability?

**Comment by yanxi0830** [comment]
> Is there any other capability sent by lsp4xml that you think can be used in canOperate in place of supportsWorkspaceFolderCapability?

I think here are the capabilities sent by XML-LS, but I'm not sure if they can be used in place of supportsWorkspaceFolderCapability?
https://github.com/yanxi0830/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/settings/capabilities/ServerCapabilitiesInitializer.java

Adding something like this solves the issue:
https://github.com/yanxi0830/lsp4xml/commit/fd2d5311293f1306b51eceefe7d9fbc312e6541f

**Comment by mickaelistria** [comment]
LSP4XML developers currently question whether defining workspaceFolders compatibility is the best thing here. The thing is that we know no better way at the moment, and https://github.com/Microsoft/language-server-protocol/issues/674 should be a long term solution.

**Comment by DKLEEE** [comment]
Can these Processes at least be closed, if the last Editor is closed?

I can´t reproduce exactly when a new Process is opened, sometimes i have only two, but in extreme cases my TaskManager looked like this, with no open Editor in Eclipse

![grafik](https://user-images.githubusercontent.com/16030367/54930245-3eebe580-4f17-11e9-98d4-8efcc0475f1c.png)

All of these Processes regularly open and close these tasklist/ findststr processes, which caused a lot of CPU usage.

Eclipse 4.11
Wild Web Developer - Web edition in Eclipse IDE (Experimental)	0.3.0.201903201538

**Comment by mickaelistria** [comment]
The framework you're using is supposed to close the process when editor is closed.
We'll investigate, but if in the meantime you find some determistic simple case to reproduce the issue, that would be an interesting hint.

**Comment by angelozerr** [comment]
I'm not sure with my comment, but perhaps it's the same issu ethan https://github.com/angelozerr/lsp4xml/issues/328

**Comment by mickaelistria** [comment]
> I can´t reproduce exactly when a new Process is opened, sometimes i have only two, but in extreme cases my TaskManager looked like this, with no open Editor in Eclipse

Please report a dedicated issue about it.

**Comment by mickaelistria** [comment]
Fixed with newer LSP4E snapshot build + https://github.com/eclipse/wildwebdeveloper/commit/8d1c4797619cf932aa6021553e01627ef40cbb0e
