### ISSUE TITLE
Javascript Code completion doesnt't work

### ISSUE THREAD

**Issue by Kavboy** [eclipse/wildwebdeveloper#129]
Hello,
i'm having issues to get the JavaScript code completion to work. I looked for similar issues but it didn't seem like they matched my problem.

System:               Windows 10 64bit
Eclipse Version:   Eclipse IDE for Enterprise Java Developers 2018-12 64bit
Node version:     10.15.1 64bit

The log produces this output:
LSP4E to org.eclipse.wildwebdeveloper.jsts:Content-Length: 1182

LSP4E to org.eclipse.wildwebdeveloper.jsts:{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":23928,"rootPath":"/C:/Users/Kevin/eclipse-workspace/test/","rootUri":"file:///C:/Users/Kevin/eclipse-workspace/test/","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true}},"hover":{},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{},"rangeFormatting":{},"definition":{},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{}}},"clientName":"Eclipse IDE","trace":"off"}}
org.eclipse.wildwebdeveloper.jsts to LSP4E:{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"triggerCharacters":[".","\"","'","/","@","<"],"resolveProvider":true},"codeActionProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["_typescript.applyWorkspaceEdit","_typescript.applyCodeAction","_typescript.applyRefactoring","_typescript.organizeImports","_typescript.applyRenameFile"]},"hoverProvider":true,"renameProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"workspaceSymbolProvider":true,"implementationProvider":true,"typeDefinitionProvider":true,"foldingRangeProvider":true,"callsProvider":true}}}
LSP4E to org.eclipse.wildwebdeveloper.jsts:Content-Length: 52

LSP4E to org.eclipse.wildwebdeveloper.jsts:{"jsonrpc":"2.0","method":"initialized","params":{}}

I hope this can be solved easily.

**Comment by mickaelistria** [comment]
Are you using the "Generic Editor" to open your .js file?

**Comment by Kavboy** [comment]
Ok I just noticed, that the completion and proposals work in the Generic Text Editor but not in the JavaScript Editor like I would expect it. Is this like it should work?

**Comment by mickaelistria** [comment]
Yes, the JavaScript editor is not related to Wild Web Developer. It's actually usually better to uninstall Webtools (WTP) HTML, CSS and JS editors when using Wild Web Developer.

**Comment by Kavboy** [comment]
Ok and how can I use syntax highlighting then?

**Comment by Kavboy** [comment]
Ok thank you
