### ISSUE TITLE
Conflicting keybindings

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#133]
If I start my Eclipse with JDT and wildwebdeveloper I see:

Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1124dd79,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@335cdd2,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.ui 4 4 2019-02-27 11:25:54.498
!MESSAGE Plugin org.eclipse.wildwebdeveloper.xml, extension org.eclipse.ui.editors: Unknown editor with id: org.eclipse.ui.genericeditor.GenericEditor

**Comment by mickaelistria** [comment]
It's https://bugs.eclipse.org/bugs/show_bug.cgi?id=527785
