### ISSUE TITLE
Typescript comment toggle

### ISSUE THREAD

**Issue by emvidi** [eclipse/wildwebdeveloper#135]
Hi there, 
     I am trying some typescript dev on eclipse with this plugin and noticed that is not possible to toggle a comment like in java with `CTRL + /`. Is there another keyboard shortcut or is not possible at the moment?

**Comment by mickaelistria** [comment]
It's supposed to be either `Ctrl+Shift+C` or `Ctrl+Shift+/`. Look in Window > Preferences > General > Keys and see the binding for "toggle comments` which belongs to the "TM4E" category.

**Comment by emvidi** [comment]
Nothing for typescript, but the one for javascript does work when I change .ts to .js
![screenshot from 2019-02-28 15-36-14](https://user-images.githubusercontent.com/37313823/53573935-df482780-3b6e-11e9-9fce-c4e0a04a5e7e.png)

**Comment by mickaelistria** [comment]
Can you check which version of plugin `org.eclipse.tm4e.languageconfiguration` is installed (Help > About > Installation Details > Plugins) ?
Your screenshot here seems to miss important features of TM4E.

**Comment by emvidi** [comment]
![screenshot from 2019-02-28 15-51-12](https://user-images.githubusercontent.com/37313823/53574890-ccceed80-3b70-11e9-92ee-f55668ea505b.png)

**Comment by mickaelistria** [comment]
Ok, so it seems like Wild Web Developer doesn't explicility declare the dependency to org.eclipse.tm4e.languageconfiguration. I'm adding it in a patch and hope it'll fix your issue.

**Comment by emvidi** [comment]
![screenshot from 2019-02-28 15-58-33](https://user-images.githubusercontent.com/37313823/53575393-bd9c6f80-3b71-11e9-8e0c-bd76b951a629.png)

Sorry for wasting your time, I have reinstalled and now works. I was missing the language plugin. Thanks for the help

**Comment by mickaelistria** [comment]
The languageconfiguration plugin should have been installed automatically. So you found an actual bug, and a workaround ;)

**Comment by emvidi** [comment]
Glad could help, thanks for the work on this plugin :)
