### ISSUE TITLE
[XML] Preferences page for XML

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#139]
The lsp4xml provides a lot of preferences that you can see at https://github.com/redhat-developer/vscode-xml#supported-vs-code-settings

It should be cool if WWD provides a preference page to configure XML formatting, XML catalog, XML file associations, etc

An idea is to provide XML preferences page like this:

 * Language Servers
   * Formatting (commons formatting preferences (like for any language server (`tabSize `and `insertSpaces` -> https://github.com/eclipse/lsp4j/blob/master/org.eclipse.lsp4j/src/main/xtend-gen/org/eclipse/lsp4j/FormattingOptions.java#L27). This preference page should b ehosted in LSP4E)
   * XML (just a main page with no preferences)
     * Formatting (specific XML formattings options with a link to LSP4E commons Formattin preference page)
     * XML Catalogs
     * XML Files associations
     * Validation    

@mickaelistria @jabby @yanxi0830  what do you think about that?

**Comment by mickaelistria** [comment]
Implementing preference pages is quite specific and expensive. While I think there is value in it, I'd rather see Wild Web Developer focusing first on supporting more things better out of the box in an hardcoded way (YAML, shemas associations, Angular, Vue, React, TSLint...) as it provides much more value and will attract much more contributors and users.

TabSize and InsertSpaces should not require additional preference nor preference page since the General > Editor > Text Editor already has a way to set them. Those preferences should be used directly to configure the language server(s) and requests.
This could indeed be the topic of a dedicated ticket in LSP4E.

**Comment by angelozerr** [comment]
> While I think there is value in it, I'd rather see Wild Web Developer focusing first on supporting more things better out of the box in an hardcoded way 

I agree with you, but IMHO I think if we wish to show that lsp4xml is a a competitor of WTM/XML Editor, we should provide thoses XML preferences page.

**Comment by jabby** [comment]
By default, I think it's a good idea to have user preferences pages. I understand that implementing specific pages is expensive but it provides great values for user. 
I don't know how to create good preference page but I wonder if we can generate some of them or just the content of a page from package.json configuration in vscode-clients. See https://github.com/redhat-developer/vscode-xml/blob/master/package.json#L62-L199

**Comment by yanxi0830** [comment]
I've actually started with this in https://github.com/yanxi0830/wildwebdeveloper/tree/xml-preference, which provides a "Formatting" and "XML Catalog" page under a XML main page. It's still a work in progress, let me know if you have any suggestions.

**Comment by angelozerr** [comment]
@yanxi0830 you read in my mind, that's very cool!

It should be fantastic if you could manage too

 * Validation preferences
 * XML file associations

I have few comments about your work:

 * label should be externalized in messages properties (NLS.bind ...). I think we should have a message properties file per language server, but it's just my opinion.

 * in your buildCustomSettings, instead of using Map (like https://github.com/yanxi0830/wildwebdeveloper/commit/96ab1fc915d66895ef67e72faf3d7354e6642306#diff-356f9ab74eaacba22c2cedb3ae1ff481R90) , you could use the real class options like https://github.com/angelozerr/lsp4xml/blob/1301e9386c1bc1885f1637015fd6e95c5b8b4497/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/settings/XMLFormattingOptions.java from lsp4xml and use GSON to serialize it.

**Comment by mickaelistria** [comment]
@yanxi0830 cool, thanks. That said, I suggest you don't spend too much effort on such pages at the moment (you can complete the current work though) until we get feedback from end-users expressing the need for it. WTP/SSE/XML is not the best UX of these days, we shouldn't mimic without clear ROI. We should avoid building more things that necessary as it creates a time cost for us and a cognitive cost for end-users.
@angelozerr what do you mean by `XML file associations`? The generic place to deal with file-associations in the IDE is the Content-Type preference page. Do we need anything more?

**Comment by angelozerr** [comment]
> @angelozerr what do you mean by XML file associations?

It's a cool feature to associate your XML file (by using pattern name) with an XML Schema
See https://github.com/redhat-developer/vscode-xml/wiki/Preferences#file-associations and https://github.com/angelozerr/lsp4xml/wiki/Configuration#file-associations for more info.

**Comment by mickaelistria** [comment]
Ok, so it's mostly like a catalog entry then?

**Comment by mickaelistria** [comment]
Or by "XML Catalog" you mean "XML namespaces catalog"?

**Comment by yanxi0830** [comment]
@angelozerr @mickaelistria Thanks for the feedback! I'll take a look.

> WTP/SSE/XML is not the best UX of these days, we shouldn't mimic without clear ROI. We should avoid building more things that necessary as it creates a time cost for us and a cognitive cost for end-users.

I agree. I was thinking it might be more beneficial to mimic what vscode is doing by allowing end-users to directly edit json configurations for custom settings, which could be re-used for all LS. But I'm not sure how it can be integrated in the preference page without a json editor.

**Comment by mickaelistria** [comment]
I'm also curious about how much end-users like to edit the .json settings in VSCode.
In my opinion, whenever a end-user has to change settings, it highlights an issue in the application either not configured properly out of the box or not being smart enough to sort out some decent configuration from the context. I would like this stack to reduce the "load" on the user and move the challenging parts of configuration as smartness inside the LS.

**Comment by angelozerr** [comment]
>  I'm also curious about how much end-users like to edit the .json
settings in VSCode.

It's very cool since you can benefit with JSON completion settings.

Le lun. 4 mars 2019 à 17:16, Mickael Istria <notifications@github.com> a
écrit :

**Comment by angelozerr** [comment]
> Ok, so it's mostly like a catalog entry then? Or by "XML Catalog" you mean "XML namespaces catalog"?

At first XML file association is an idea coming from the project https://github.com/microclimate-devops/xml-language-server

It's a non standard mean to bind a XML file with a XML Schema with pattern (like **/*po*.xml). XML Catalog has this feature but without pattern.

**Comment by mickaelistria** [comment]
Is there a public XML Schema/file association we can use, which would be similar to https://schemastore.azurewebsites.net/api/json/catalog.json

**Comment by angelozerr** [comment]
> I'm also curious about how much end-users like to edit the .json settings in VSCode.

I discover it and I love it because you can update settings from UI or directly in the .json file and you benefit with completion, validation. It should be cool if preferences Eclipse could provide this kind of feature.

![VSCodeSettingsDemo](https://user-images.githubusercontent.com/1932211/60330439-b99f2380-9992-11e9-8fa3-b540db2f5c5b.gif)

IMHO WWD should really provide preferences to configure XML LS like XML Catalog, File Associations, Enable CodeLens, Disable Symbol by using pattern file (very helpful when some XML file are very big to avoid freezing VSCode/Eclipse Outline)

**Comment by mickaelistria** [comment]
> It should be cool if preferences Eclipse could provide this kind of feature.

Ability to edit preferences textually a topic to bring to the Eclipse Platform, not something we can tackle in LSP4E. And it actually shouldn't be too hard to have something usable in Platform.

> WWD should really provide preferences to configure XML LS like XML Catalog

I don't think it is likely to reach the top of our todo-list soon because their are good workarounds (by good I mean practices that are more generally valuable as they would improve the IDE at large or the support in other IDEs), but I agree it'd be nice to have.

> XML Catalog,

A valid workaround is to set a valid URI in the `xmlns` attribute IIRC

> File associations

Eclipse IDE already has solid support for File Association

> Enable CodeLens

That would have to be in LSP4E, and if codelens are really good, there is never need to disable them (just like one never wants to disable completion or syntax highlighting or hover) so adding an option seems unnecessary, and probably hiding deeper issues.

> Disable Symbol by using pattern file (very helpful when some XML file are very big to avoid freezing VSCode/Eclipse Outline

The freeze is a bug and should be fixed, no option should be required to avoid a freeze.

**Comment by tomaswolf** [comment]
> but I agree it'd be nice to have

It's more than a nice-to-have. Having the XML language server always go download XSDs means poor XML/XSD editing support when there's no Internet connection or the XSD for some other reason cannot be downloaded.

org.eclipse.wst.xml does have support for XML catalogs already; to ease migration, www's XML catalog handling should be able to migrate or directly re-use these settings. Maybe even the preference page implementations can be re-used.

> > XML Catalog,
> 
> A valid workaround is to set a valid URI in the `xmlns` attribute IIRC

No it isn't if
* XSD cannot be downloaded for some reason (server down, no Internet connection, ...)
* new XSD being developed and not published yet.

**Comment by mickaelistria** [comment]
FWIW, if anyone is willing to contribute this feature, we'll review it with high priority. Technically what's needed is
1. a new preference page allowing to add/delete catalog locations
2. define a preference where to store that
3. pass that preference to the XML Language Server at initialization.

It's not a hard task, however it's not one me or my team-mates are likely to work on very soon nor very certainly.

**Comment by mickaelistria** [comment]
Closing this one, as there have been a XML preference page for some time now.
Further improvements should be tracked in separate issues.

**Comment by LorenzoBettini** [comment]
Sorry if I go back to this issue, but where is the preference page for the XML editor (provided by wildwebdeveloper and used, as I understand, as the new default editor for POM files)? I mean the setting to insert spaces instead of tabs...

**Comment by LorenzoBettini** [comment]
And setting spaces instead of tabs will influence also Java editors, which I don't want...
I'm going to revert (again) to the good ol' XML editor that used to work like magic...

**Comment by angelozerr** [comment]
> And setting spaces instead of tabs will influence also Java editors, which I don't want...

I totally understand, but it means that LSP4e should be improved because when format si processed it send the spaces and tabs preferences from Editor UI preferences https://github.com/eclipse/lsp4e/blob/b5055d9afcc65dded8ce0ed9f15673e453e138c3/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java#L73

I have some ideas how to fix that. 

@LorenzoBettini I wonder if the configuration with spaces/tabs done with .editorconfig could be good for you?

**Comment by LorenzoBettini** [comment]
@angelozerr I'm not familiar with editorconfig.. if it works..

**Comment by angelozerr** [comment]
Let me investigate how we could have an UI space/tabs preferences for XML.

Could you create an issue for that please. Have you some other issues with LemMinX compares to WTP?
If you have some issues could create them in WWD please. Thanks!
