### ISSUE TITLE
[XML] Support for autoCloseTags

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#143]
XML language server supports a custom command to manage auto close tag (which is very nice when you are editing XML content).

I have started to implement this feature with `org.eclipse.ui.genericeditor.autoEditStrategies`: 

```xml
 <extension
         point="org.eclipse.ui.genericeditor.autoEditStrategies">
      <autoEditStrategy
            class="org.eclipse.lsp4e.xml.CloseTagAutoEditStrategy"
            contentType="org.eclipse.core.runtime.xml">
      </autoEditStrategy>
   </extension>

```
See https://github.com/angelozerr/lsp4e-xml/blob/master/org.eclipse.lsp4e.xml/plugin.xml#L139 and https://github.com/angelozerr/lsp4e-xml/blob/7e14cc109c2bcc80809c6625d310568f8052f421/org.eclipse.lsp4e.xml/src/org/eclipse/lsp4e/xml/CloseTagAutoEditStrategy.java

To be honnest with you, I don't remember if it works well, but vscode-xml consumes it and works well.

@yanxi0830 is there any chance that you could work on this issue? Thanks!

**Comment by yanxi0830** [comment]
Sure thing! I'll take a look.

**Comment by mickaelistria** [comment]
I'd rather not rely on custom commands. LSP offers the `workspace/applyEdit` server to client message for auto-edits. This is standard and already supported in LSP4E. I don't think we need anything else to cover tis job, so let's stick to standard.

**Comment by angelozerr** [comment]
> Sure thing! I'll take a look.

Thanks!

> I'd rather not rely on custom commands. LSP offers the workspace/applyEdit

I don't remember how it works, but if lsp4xml needs some change, please create an issue for that with some explanation. Thanks!

**Comment by mickaelistria** [comment]
> I don't remember how it works, but if lsp4xml needs some change, please create an issue for that with some explanation.

Ok, I will.
I suggest we do not change anything in Wild Web Developer and get it more mainstream in LSP4XML then.

**Comment by mickaelistria** [comment]
See https://github.com/angelozerr/lsp4xml/issues/324

**Comment by angelozerr** [comment]
@mickaelistria we have a lot of discussion about this feature but IMHO I think WWD should provide this custom auto close tag request for XML and HTML both (see https://github.com/eclipse/wildwebdeveloper/issues/208)

I'm not sure that HTML LS will provide this feature with workspace/applyEdit and we have a lot of users who complains about this missing feature which I think it's very important when you write XML or HTML.

**Comment by mickaelistria** [comment]
How does HTML LS implement it?

**Comment by angelozerr** [comment]
I noticed that HTML LS provides now a new custom request (I think we should do the same thing for XML). See https://github.com/microsoft/vscode/blob/5323a5374639a302e00d77c0ff2f9027826ad9eb/extensions/html-language-features/client/src/htmlClient.ts#L27

**Comment by mickaelistria** [comment]
Can you please remind me why `onTypeDocumentFormatting` can't do that already?
