### ISSUE TITLE
Better support TypeScript debugging

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#144]
TypsScript debugging needs to be a better citizen:

1. it was never tried nor reported as working
2. how to should be documented
3. Tests added
4. Overall workflow improved

**Comment by mickaelistria** [comment]
The node debugger seems to have some capabilities for such files, by relying on sourceMaps. However, sourceMaps support is currently disabled (to prevent from other failures in the debug adapter). Work should be done in trying to re-enable sourceMaps in the LS so we could try to run directly .ts files.

**Comment by AObuchow** [comment]
For the case of debuging a website written in TypeScript, see https://github.com/eclipse/wildwebdeveloper/blob/master/TIPS_and_FAQ.md#debug-a-website-developed-in-typescript

**Comment by vrubezhny** [comment]
An issue is reported on lsp4e: Bug 564070 - Launch goes into an endless loop when a launch is failed: https://bugs.eclipse.org/bugs/show_bug.cgi?id=564070 and a PR is provided:  https://git.eclipse.org/r/164428
