### ISSUE TITLE
Support for angular-cli with Terminal / Wizard / Launches

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#147]
As wwd will provide Angular support, it should be cool if wwd could provide angular-cli support as I had done at https://github.com/angelozerr/angular-eclipse/wiki/AngularCLI

This feature requires improve of TM Terminal (to track command in the terminal to react according the commands (ex : ng-new must generate an Eclipse Project, ng-server must open a Web Browser, etc). See https://bugs.eclipse.org/bugs/show_bug.cgi?id=496109

**Comment by paulvi** [comment]
I would if vuejs CLI would need similar work.

**Comment by mickaelistria** [comment]
I can keep the issue open, but I don't think we'll ever work on this. It requires a lot of effort to be implemented properly and we already have the integrated Terminal in Eclipse IDE to deal with this kind of issues.

**Comment by mickaelistria** [comment]
No news for a while, let's close.
