### ISSUE TITLE
Eliminate dep on org.apache.commons.io

### ISSUE THREAD

**Issue by mbooth101** [eclipse/wildwebdeveloper#149]
The dependency on org.apache.commons.io can be entirely eliminated by using a try-with-resources style block to remove the need for using IOUtils.closeQuietly().

**Comment by jabby** [comment]
I just created #159

**Comment by jabby** [comment]
The MR #159 was merged by @mickaelistria 
A snapshot version of Wild Web Developer is available here https://download.eclipse.org/wildwebdeveloper/snapshots/
