### ISSUE TITLE
[JS/TS] html and css within tagged template strings

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#151]
Please provide 
- "Syntax highlighting" and 
- "Content Assist/Code Completion" 
for html and css inside of JavaScript and TypeScript tagged template strings within wwdevs "generic editor".

For example:
```

..
  render() {
    return html`
     <style>
      p { font-size: 12px;}
     </style>
      <p>${this.myString}</p>
      <ul>
        ${this.myArray.map(i => html`<li>${i}</li>`)}
      </ul>
    `;
  }

```

**Comment by mickaelistria** [comment]
We use TextMate grammars for syntax highlighting. I guess highlighting HTML tags is mostly a matter of finding a better grammar. Are you aware of some good grammar you'd recommend?
For code completion, we use the typescript-language-server from https://github.com/theia-ide/typescript-language-server . Can you please request it on that project and then link to the newly created issue?

**Comment by nimo23** [comment]
Ok, created code completion issue:

https://github.com/theia-ide/typescript-language-server/issues/106

**Comment by nimo23** [comment]
Searching for textmate grammers for html and css..

- https://github.com/desandro/CSS3.tmbundle
- https://github.com/drnic/html-tmbundle
- https://github.com/bingeboy/TextMate-HTML5-Bundle

**Comment by jabby** [comment]
@nimo23 Do you need syntax highlighting for jsx / tsx files ? 
If yes I think we can use the following grammar from vscode: https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json

**Comment by angelozerr** [comment]
* "Syntax highlighting" and

As @mickaelistria explained, it's managed with TextMate with tm4e which is able to manage injection of another grammar https://github.com/eclipse/tm4e/wiki/UI#external-grammar-injection . Angular Eclipse uses that https://github.com/angelozerr/angular-eclipse/blob/master/ts.eclipse.ide.angular.ui/plugin.xml#L274

 * "Content Assist/Code Completion"
for html and css inside of JavaScript and TypeScript tagged template strings within wwdevs "generic editor".

As @mickaelistria explained, it's managed with  https://github.com/theia-ide/typescript-language-server To support custom completion, you can write a TypeScript plugin (like angular language service https://github.com/eclipse/wildwebdeveloper/issues/138) and register it -> see https://github.com/eclipse/wildwebdeveloper/pull/146

**Comment by nimo23** [comment]
>Do you need syntax highlighting for jsx / tsx files ?

Syntax highlighting within tagged template literals should work with **js/jsx/tsx**, 
because in all of those files "tagged template literals" can be used.

**Comment by angelozerr** [comment]
> For code completion, we use the typescript-language-server from https://github.com/theia-ide/typescript-language-server . Can you please request it on that project and then link to the newly created issue?

I don't think it's teh goal of thea-ide. It's a plugin TypeScript that you must use like

 * for CSS -> https://github.com/mrmckeb/typescript-plugin-css-modules
 * for HTML -> https://github.com/Microsoft/typescript-lit-html-plugin

IMHO wwd should provide a property or preferences page to select typescript plugins to start. It will follow the same idea than vscode settings.json https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/schemas/package.schema.json

**Comment by mickaelistria** [comment]
Thanks Angelo, we'll try to add those typescript plugins in Wild Web Developer soon.

**Comment by mickaelistria** [comment]
Ok, I opened the following CQs to request IP approval to use 

- Newer TextMate grammars: http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19425
- TypeScript+CSS plugin http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19433
- TypeScript+HTML plugin http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19434

**Comment by mickaelistria** [comment]
All CQs approved.

**Comment by mickaelistria** [comment]
So do I get it right that the .jsx/.tsx files should use the React grammar while plain .js/.ts should keep using the regular grammar?

**Comment by nimo23** [comment]
**There are 2 distinctions:**
- The grammar for "xml/html/css **within** ES-Template-Literal should be used for **js/ts/jsx/tsx**.
- The grammer for "react", where xml/html-syntax can be used without ES-Template-Literal should only be within jsx/tsx.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/wildwebdeveloper/pull/160
We're reusing grammars from VSCode, and VSCode grammars seem to only allow the 2nd case and not provide so good syntax highlighting for case 1.

**Comment by nimo23** [comment]
Okay, simple solution: **use grammar for jsx/tsx also for js/ts.**, because jsx/tsx is nothing more than js/ts with xml/html embeeded.

**Comment by nimo23** [comment]
By the way, a lot of users use *.js even when using html within react-files..

**Comment by nimo23** [comment]
vs code also allows/hightslights this xml-syntax even for simple js/ts files:

<img width="530" alt="grafik" src="https://user-images.githubusercontent.com/3045549/55156822-32f06580-515b-11e9-8e09-ce17c6230ce6.png">

**Comment by nimo23** [comment]
And this is a js-file within VS Code with html inside of template literals (code completion and syntax highlighting for css/html works also for js-files).

<img width="395" alt="grafik" src="https://user-images.githubusercontent.com/3045549/55157374-80210700-515c-11e9-8303-395a658a840b.png">

**Comment by mickaelistria** [comment]
I merged a patch adding some support, and snapshots are available for testing at http://download.eclipse.org/wildwebdeveloper/snapshots . Please open more specific tickets for defects you may find.

**Comment by nimo23** [comment]
@mickaelistria I updated to 

Wild Web Developer - Web Dev in Eclipse IDE 1.0.0.05-cLopnh7735K397I5973
and also updated 

<img width="662" alt="grafik" src="https://user-images.githubusercontent.com/3045549/55172503-6e4e5c80-517a-11e9-8877-0d533ba15631.png">


**However, few problems:**

- syntax highlighting does **not** work for html and css in "js, jsx, ts, tsx"
- syntax highlighting for jsx does not work for **any** syntax
- code completion does not work for html or css in "js, jsx, ts, tsx"
- auto-close brackets for "js, jsx, ts, tsx" does also not work

So I do not see any difference after update wwdev from http://download.eclipse.org/wildwebdeveloper/snapshots

Configuration:
- Wild Web Developer - 0.3.0.201903281320
- org.eclipse.tm4e.languageconfiguration: v0.3.2.201901202045

**Comment by mickaelistria** [comment]
I tried locally on a fresh IDE and I could see most of the things you mention working well, with the same version of dependencies.
Where is this " 1.0.0.05-cLopnh7735K397I5973" coming from. Could it be possible that you have installed another plugin that conflicts with Wild Web Developer?

**Comment by nimo23** [comment]
I installed wwdev from marketplace at first. Then I added http://download.eclipse.org/wildwebdeveloper/snapshots to update wwdev. Now I have the updated version of wwdev. 

You see the "1.0.0.05-cLopnh7735K397I5973" at the bottom of the picture:

<img width="610" alt="grafik" src="https://user-images.githubusercontent.com/3045549/55177127-c9844d00-5182-11e9-923b-ea5e5a440e08.png">

Maybe, wwdev conflicts with another plugin called 

<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/3045549/55177270-2253e580-5183-11e9-9137-262714483b07.png">


I think so because darkest dark adds some TextMate-Themes within TextMate-Plugin:

<img width="622" alt="grafik" src="https://user-images.githubusercontent.com/3045549/55177043-9e99f900-5182-11e9-9159-e1d703522538.png">

Can you install this plugin and check if it works with wwdev?

**Comment by TatuLund** [comment]
@mickaelistria why the patch has not been merged to master yet, it has been long time and there seems to be two other tickets requesting this feature as well?

**Comment by mickaelistria** [comment]
>  why the patch has not been merged to master yet,

Which patch? Is there an opened Pull Request to review?

**Comment by TatuLund** [comment]
@mickaelistria I probably understood this comment wrong then.

https://github.com/eclipse/wildwebdeveloper/issues/151#issuecomment-477626711
