### ISSUE TITLE
include chromium browser

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#152]
Would be nice to include "chromium browser" with support for opening the "web developer tools" within eclipse. With this, all the web developer experience from chrome is automatically included within eclipse.. For example, when opening "index.html" with "Open With->Chrome Browser". Maybe the wwdev tools can integrate it like this:

http://blog.diniscruz.com/2013/09/opening-up-native-chrome-browser-window.html

or better this:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=405031#c59
https://github.com/maketechnology/chromium.swt

**Comment by mickaelistria** [comment]
As the bug you linked highlights, that is something that needs to be first enabled in Eclipse Platform directly.

**Comment by mickaelistria** [comment]
Another approach, that's likely to be implemented at some point, is to add the Chromium and/or Firefox debug adapter. This will allow to run/debug a web page (and JS) by starting it in the browser.

**Comment by mickaelistria** [comment]
I'm closing this issue as it's not actionable from Wild Web Developer perspective.

**Comment by mickaelistria** [comment]
I think this is covered by #230: you can now do Right-Click > Debug As > Chrome to get the page loaded in Chrome and debug-able.
