### ISSUE TITLE
Add more screenshots to marketplace

### ISSUE THREAD

**Issue by paulvi** [eclipse/wildwebdeveloper#153]
Please add more screenshots to https://marketplace.eclipse.org/content/eclipse-wild-web-developer-html-css-javascript-typescript-json-yaml-xml-nodejs

#58

**Comment by mickaelistria** [comment]
Do you have some metrics or actual end-user reports confirming that adding more screenshots lead to more installations?

**Comment by paulvi** [comment]
well, I would say that it will actually decrease number of installation, as some can evaluate project fit, without actually installing :-E

**Comment by paulvi** [comment]
P.S. The current only screenshot is likely just too old.

**Comment by mickaelistria** [comment]
If you want to take care of taking a few interesting screenshots, that'd be welcome.

**Comment by mickaelistria** [comment]
I added a new screenshot that shows the debugger.
