### ISSUE TITLE
Migrate Nodeclipse users

### ISSUE THREAD

**Issue by paulvi** [eclipse/wildwebdeveloper#154]
I see with latest development here, particularly Node.js debugging,  
it is maybe good idea for Web/Node.js developer not to install @Nodeclipse tools at all

And https://nodeclipse.github.io/ could just point to WWD for Web/Node.js  tools.

**Comment by mickaelistria** [comment]
Thanks.
That would be welcome. It seems like Wild Web Developer (With Language Server and Debug Adapters) is the most consensual project for Web development in Eclipse IDE these day. Any project that is fine self-deprecating and redirecting to Wild Web Developer is welcome to do it!

**Comment by paulvi** [comment]
In reality Nodeclipse Node.js tools had no development within https://github.com/Nodeclipse/nodeclipse-1 for 3-4 years, and the latest js additions actually came from Albert @de-jcup work.

The project went from early period when people were joining to just bring pieces that could add value,  
to some middle period when new users were just demanding.

And mainly I have not been using Node.js even for longer.  
As one can see on https://nodeclipse.github.io/  site, that got many others, not so mainstream tools.

**Comment by mickaelistria** [comment]
I'm closing this one as there is no concrete things we can do from Wild Web Developer side on that matter.
