### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by paulvi** [eclipse/wildwebdeveloper#155]
Is there some roadmap of planned development to share?

**Comment by mickaelistria** [comment]
Nope. All the backlog is available as GitHub issues and discussions on the ticket help to figure out what's likely to be implemented in the next weeks. As it's a distributed project and most contributors are navigating between various projects, I don't think we can build a finer grain roadmap that what the issue tracker provides, nor commit on resolution of issue X on day Y. It's an agile open-source project: we don't know what people want to work on, we don't know what contributors we'll get, so we cannot really plan a roadmap ;)
