### ISSUE TITLE
tsx and jsx must be within textmate language configuration

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#157]
Actually, only *.ts and *.js are registered in wwd-TextMate-Configuration (Grammar, Language Config). 

Please add "*.tsx" and ".jsx" also.

**Comment by mickaelistria** [comment]
In which cases are those .jsx/.tsx files used?

**Comment by nimo23** [comment]
Cases are the nearly the same as for "js" and "ts" files:

https://www.reactenlightenment.com/react-jsx/5.1.html

- jsx files are typical for react in javascript 
- tsx are typical for react in typescript.

However, such files are generally used when using html/xml syntax within javascript.

Textmate config for jsx:
https://github.com/jjeising/javascript-jsx.tmbundle

I am not sure if jsx-textmate can also be used for tsx.

**Comment by angelozerr** [comment]
> In which cases are those .jsx/.tsx files used?

tsserver is able to support completion, hove etc for jsx/tsx.

wwd should use `TypeScriptReact.tmLanguage.json`  like https://github.com/angelozerr/typescript.java/blob/master/eclipse/jsdt/ts.eclipse.ide.jsdt.ui/plugin.xml#L789

**Comment by angelozerr** [comment]
IMHO wwd should use:

 * for TypeScript (ts, tsx)-> https://github.com/Microsoft/vscode/tree/master/extensions/typescript-basics/syntaxes

 * for JavaScript (js, jsx) -> https://github.com/Microsoft/vscode/tree/master/extensions/javascript/syntaxes

**Comment by mickaelistria** [comment]
Are tsx file valid TypeScript files, are jsx files valid JavaScript files or do they have some incompatibilties?

**Comment by nimo23** [comment]
tsx is a superset of ts and jsx is a superset of js.

The only difference is to provide xml/html like syntax within jsx/tsx, which is not eligible in js/ts.

**Comment by mickaelistria** [comment]
I've added jsx and tsx support, exactly in the same way as js and ts (using the same grammars and same language server). I think it's enough to cover the initial request. Please give a try to snapshots and open new tickets for further requests.

**Comment by Christopher-Chianelli** [comment]
Requesting issue to be reopened, as `.tsx` is not supported by Wild Web Developer 0.2.0.201903111934. It appears the TextMate Typescript Grammar and the Typescript language server does not list "tsx" as a supported filetype. However, "jsx" is listed. Installed on a fresh Eclipse installation on Fedora 30 via the "Install additional software..." dialog.

**Comment by mickaelistria** [comment]
Reopened as per request.

**Comment by mickaelistria** [comment]
Can you please first try to upgrade to latest release? See the build is from March 11th while this issue was marked as resolved on March 26th. You'll probably need to have an Eclipse IDE up-to-date (2019-06) to get the latest release of Wild Web Developer.

**Comment by Christopher-Chianelli** [comment]
@mickaelistria just tried that; it fixed it! Thanks; (although Eclipse should notify about new stable version + dnf package should be more up to date, but that a separate issue)
