### ISSUE TITLE
jQuery auto complete

### ISSUE THREAD

**Issue by pebbles186** [eclipse/wildwebdeveloper#158]
Please add support for jQuery when editing JavaScript code. This would be very helpful.
Or is there already support for this and I am doing something wrong?

**Comment by mickaelistria** [comment]
Is https://stackoverflow.com/a/32052431/2427750 a viable workaround?

**Comment by pebbles186** [comment]
Yes, this works for me.
Installed it with
`npm install @types/jquery`
Thanks for the quick reply!
