### ISSUE TITLE
Wild Web Developer install jdt.core

### ISSUE THREAD

**Issue by zulus** [eclipse/wildwebdeveloper#163]
It's really important?

**Comment by jabby** [comment]
Hello @zulus I don't understand what is your problem. 
I don't see any link to jdt.core in Wild Web Developer for end-user. Is it relative to the target platform?

**Comment by zulus** [comment]
Something have this plugins in dependencies. While installing wild web developer into Eclipse for PHP jdt.core was added.

**Comment by angelozerr** [comment]
Is it because of this unit dependency ?

https://github.com/eclipse/wildwebdeveloper/blob/master/target-platform/target-platform.target#L16

**Comment by mickaelistria** [comment]
Having some bundle declared in TP is not enough to make it a requirement for installation.
I see org.eclipse.jdt.core is also installed in the Rust IDE package, so it could be something in LSP4E that trigger it. IIRC, PDE has a "Plugin Dependencies" tools that would help a lot troubleshooting that: define the PHP/Corrosion/Wild Web Developer IDE as target platform and use the Plugin Depdencies view to see what's going on.

**Comment by jabby** [comment]
FYII checked with the plugin dependencies view and the only plugin I saw from jdt is the `org.eclipse.jdt.annotation`. 
It's a dependency of lsp4e.

**Comment by nitind** [comment]
It's in your M3 EPP package: https://ci.eclipse.org/packaging/job/simrel.epp-tycho-build/426/artifact/org.eclipse.epp.packages/archive/20190530-0926_eclipse-javascript-2019-06-M3-linux.gtk.x86_64.tar.gz . Is it supposed to be?

**Comment by mickaelistria** [comment]
In an ideal world, it shouldn't be in; but we probably won't be able to fix this bug in time, and having jdt.core in doesn't harm much (beyond the disk space and network cost).

**Comment by akurtakov** [comment]
I just found that org.eclipse.mylyn.context.ui imports org.eclipse.jdt.core so why do we need it first?

**Comment by mickaelistria** [comment]
So do I get it right that
* Installing Wild Web Developer does *not* install org.eclipse.jdt.core, and
* the EPP package includes org.eclipse.jdt.core as a transitive dependency of Mylyn?
If so, I'll close the bug here as this is more about EPP.

**Comment by mickaelistria** [comment]
Closing as not actionable in Wild Web Developer.
