### ISSUE TITLE
Add JSON formatting

### ISSUE THREAD

**Issue by KhlaponinIO** [eclipse/wildwebdeveloper#164]
Cannot format JSON neither through Ctrl+Shift+F nor through RMB->Format (this menu item even inactive). On the other hand, code completion works as expected.

OS: Centos 7, Java 8, Eclipse 2018-12

**Comment by mickaelistria** [comment]
The current JSON language server used by Wild Web Developer (the one from VSCode 1.25) doesn't declare the "format" capability. I'll try some newer  language server.

**Comment by mickaelistria** [comment]
I tried with newer Language Server (in VSCode 1.33) and it still doesn't bring formatting easily.
It has some handling of formatting, but the enablement seems really tied to VSCode `settings.xml` description: https://github.com/Microsoft/vscode/tree/master/extensions/json-language-features/server .  We don't want to use this in Wild Web Developer.
I think it's an upstream issue in VSCode, I'm going to open a ticket.

**Comment by mickaelistria** [comment]
See https://github.com/Microsoft/vscode/pull/72124 & https://github.com/Microsoft/vscode/pull/72125

**Comment by mickaelistria** [comment]
So VSCode isn't really interested in the simple approach because of VSCode-specific issues, I'll make a hack on Wild Web Developer side tweaking the LS ;)

**Comment by KhlaponinIO** [comment]
Sounds good :)

**Comment by mickaelistria** [comment]
Fixed with c980f55f7a5de3dcbebbfb3bdfd240ed669634fc . Will be available in snapshots p2 repository within a few minutes.

**Comment by KhlaponinIO** [comment]
Good job! Thanks for such a quick fix :)
