### ISSUE TITLE
Build video demo of Angular component edition

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#167]
Build video demo of Angular component in TypeScript files

**Comment by pivan9911** [comment]
Is somewhere some Info, about  Angular,Angular-CLI  development in WWD ?

**Comment by mickaelistria** [comment]
Unfortunately, the video demo about Angular support in TypeScript file has been removed from Youtube by its author. But basically, opening an Angular typescript file gives some validation and completion in the `template` annotation.
Support for Angular CLI is tracked in #147 but it's currently quite low priority as there are already ways to integrate this efficiently in Launch Configuration and Project Builders just like any external application; so rather than creating specific code for it, I'd rather see some efforts placed on gathering the user-stories and documenting how they can already be covered by what's already in Wild Web Developer.

**Comment by pivan9911** [comment]
My guess is, the Launchers and Builders for Angular, will easiest be constructed,  using Angular_CLI under the hub.

**Comment by mickaelistria** [comment]
This will also be important for inclusion in release notes.

**Comment by mickaelistria** [comment]
Donc at https://www.screencast.com/t/6GTi4jf6svR
