### ISSUE TITLE
Javascript Code completion does not work

### ISSUE THREAD

**Issue by Gilles-France** [eclipse/wildwebdeveloper#169]
Hi, the WWD seems a great tool ! (according to the demo https://www.screencast.com/t/BaC9DxHIqD ). 
Unfortunately it is impossible for me to make it work properly on a fresh Eclipse package (2019-03). 
The JAVASCRIPT completion does not work. 
As a beginner in javascript devt, I need the main steps for installation and **configuration** of WWD (I mean : what configuration on global Eclipse options, but also what configuration on the project to make completion and other main features work). 
Thank you very much. Best regards.

**Comment by jabby** [comment]
Hello, 
First I'm glad you try this plugin. I'm sorry to hear you can't use it now. 

In order to help you,  can you provide the exact version of Eclipse IDE you used. 
In the IDE, you can go to `Help > About Eclipse IDE > Right clic on the text from the popup > Copy build ID information to clipboard`, then paste it in a new comment here. 
Do you have any error message when you open the editor?

Other question, have you try another completion? For example create a new empty css file and add the following code in it. 

````css
a {
  color: 
}
````

Then after `color: `, try the completion. Did you have any proposal?

**Comment by Gilles-France** [comment]
Hello, 
thank you very much for your fast reply. 

My problem was linked with my PATH variable that does not contain NODE.JS. 
I did not pay attention to a popup alert telling me that Node.js could not be found (the message does not contain any origin).
![missing_nodejs](https://user-images.githubusercontent.com/50808694/58051587-e1f56000-7b52-11e9-805b-dc1610462ebd.png)

In the past, I have uncompressed NODEJS into a folder (no install, no SYSTEM PATH update) to allow me to choose among several versions.
Today for Eclipse and WWD, as a workaround, I launched Eclipse thru a cmd file that contains only 2 lines : 

```
set PATH=M:\bustools\node-v8.11.1-win-x64;%PATH%
start eclipse.exe
```

And it works : 
![image](https://user-images.githubusercontent.com/50808694/58051974-db1b1d00-7b53-11e9-9cff-baf5a8f8cc40.png)


**Now my question is : how to set and adjust NodeJS’ path for WWD use in a better way ? (rather than my workaround and without depending on system path).**

And I have a comment : while editing big JS files (more than 600 lines) the eclipse generic editor seems to become a little sluggish, how to adjust or turn off WWD temporarily ?

Thanx a lot
Best regards
Gilles

( I've attached a document to reproduce the issue step by step... )
[wildwebdeveloper_Javascript Code completion does not work #169.zip](https://github.com/eclipse/wildwebdeveloper/files/3199838/wildwebdeveloper_Javascript.Code.completion.does.not.work.169.zip)

**Comment by Gilles-France** [comment]
missing info : 
```
Eclipse IDE for JavaScript and Web Developers
Version: 2019-03 (4.11.0)
Build id: 20190314-1200
OS: Windows 8.1, v.6.3, x86_64 / win32
Java version: 1.8.0_191
```

**Comment by mickaelistria** [comment]
>  how to set and adjust NodeJS’ path for WWD use in a better way ? (rather than my workaround and without depending on system path).

As you can see in https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java#L61 , you can use a Java system property (usually set in the eclipse.ini with a `-Dkey=value` line after `-vmargs`) to enforce a specific location to Node.js.
There are already opened issues addressing better control of node.js for end-users, or even inclusion of node.js directly. So I think this is already fully covered in the backlog.

>  while editing big JS files (more than 600 lines) the eclipse generic editor seems to become a little sluggish, how to adjust or turn off WWD temporarily ?

Please open a new bug about performance and we'll investigate. Wild Web Developer will not accept any patch to disable itself, we don't have the manpower to waste it on workarounds and we should focus on fixing things.
