### ISSUE TITLE
How to use the Polymer Language server with wild web.

### ISSUE THREAD

**Issue by bsutton** [eclipse/wildwebdeveloper#177]
Is it possible to use the Polymer IDE language server with Wild Web?

https://github.com/Polymer/tools/tree/master/packages/editor-service

If so how is it configured?

**Comment by mickaelistria** [comment]
Wild Web Developer currently doesn't include Polymer support.
It certainly could be added, so if you're interested in contributing this, that's highly welcome.
You can also experiment locally: install the language server where you want, create a "External Launch Configuration > Program" describing how to start it, and then in Preferences > Language Servers, you can associate this launch with HTML files. If you're lucky, it works.

**Comment by bsutton** [comment]
For others the item is actually 'External Tools Configuration...' available from the button bar next to the debug/run icons.
I'm going to use this issue to dump some notes as I work through the process after which I will attempt to put some formal doco together.

1) install node as per
https://github.com/nodesource

2) install the polymer cli
`npm install -g polymer-cli`

3) find the location of the polymer cli tool 
`which polymer`

4) Create an external tool configuration
'External Tools Configuration...'
Select the 'Program' option and click the new button.

5) Change the name of the new configuration to 'Polymer Server'.

6) On the 'Main' tab in the 'Location' field enter the path to polymer (as per step 3).
On my system this was:
`/usr/local/bin/polymer`

7) In the 'Arguments' field enter
serve

8) In the 'Working Directory' field enter the root of you html/javascript src files from your workspace.

The objective of the above steps is to start polymer in serve mode so we can connect to the process as a language server.

9) do a test run of the Polymer server by running the launch tool configuration for the polymer server we just created.
In your eclipse console window you should see something similar to:

Files in this directory are available under the following URLs
      applications: http://127.0.0.1:8081
      reusable components: http://127.0.0.1:8081/components/bsutton/
10) Now associate your html files with the polymer server
Select Window | Preferences | Language Servers
...

**Comment by bsutton** [comment]
Note: early experimentation has the eclipse UI locking up for extended periods of time with log messages such as 'LanguageServer not initialised after 10s'.

**Comment by mickaelistria** [comment]
It's also a practice that is not well documented, but there are tests about it: In https://git.eclipse.org/c/lsp4e/lsp4e.git/tree/org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/CreateAndRegisterContentTypeLSPLaunchConfigMapping.java#n65 you can see how using Run Configurations works in unit tests, there seem to be at least 2 important things you may need for your experiment: the "Run In Background" option and the "Log to console" one. It could be that if those are missing, then the stream cannot be read properly.

**Comment by mickaelistria** [comment]
Does Polymer Language Server requires integration in tsserver or something like that? If not, it could probably be a separate plugin which just invokes the Language Server. See for example how the Yaml Language Server support in implemented in Wild Web Developer, you could probably mimic it.

**Comment by mickaelistria** [comment]
@bsutton Do you plan to implement Polymer support in Wild Web Developer?

**Comment by bsutton** [comment]
@mickaelistria sorry but no.

**Comment by mickaelistria** [comment]
:closing then
