### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by bsutton** [eclipse/wildwebdeveloper#178]
I've googled all over and I can't find any documentation on the Wild Web.

Where is the doco?

Can we get a link to the doco from the readme page as well as from the official eclipse page.

**Comment by mickaelistria** [comment]
There is no documentation. If you're interested in contributing some, it would be very welcome and should leave in a `documentation` folder in the Git repo.

**Comment by bsutton** [comment]
I need some doco to work out how to use it so I can write some doco!

**Comment by nhnb** [comment]
I noticed that for example TypeScript errors, linting and autocomplete does work, if you install the IDE via the Eclipse Installer.

But I have no idea on how to get it working starting from the Java IDE and adding Wild Web via the marketplace. Syntax highlight works, but nothing else. Perhaps I need to install some additional packages for the language servers. But looking at the list of plugins in the working installation does not yield any obvious candidates.

**Comment by mickaelistria** [comment]
In the current state, the answer is "There is no documentation", I'm closing it as it answers the question.
Addition of documentation is welcome as pull request.
