### ISSUE TITLE
Wild Web Developer plugin does not work

### ISSUE THREAD

**Issue by yowelin** [eclipse/wildwebdeveloper#179]
I install JDK 12, then Eclipse for PHP developers, then I installed Wild Web Developer plugin via help->Eclipse Marketplace.
I open JavaScript Perspective and created a JavaScript Project. I created a file "test.js" in root folder of this project. I typed "console." But nothing happened: I cannot see any proposals

**Comment by mickaelistria** [comment]
The JavaScript perspective doesn't come from Wild Web Developer but from Eclipse JSDT.
To get the Wild Web Developer feature, you need to open the file with the Generic Editor (right-click > Open With > Generic Editor)

**Comment by akurtakov** [comment]
Closing as there is there was wrong editor used.
