### ISSUE TITLE
Wrong path to nodeDebug.js

### ISSUE THREAD

**Issue by barix** [eclipse/wildwebdeveloper#180]
Hi,

trying to run a Node.js application in eclipse I get the following error (note the double `C:\`):
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\C:\eclipse\plugins\org.eclipse.wildwebdeveloper_0.3.0.201906060852\language-servers\node_modules\node-debug2\out\src\nodeDebug.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
Looking at the corresponding launch configuration there is the entry `listEntry`:
```
<launchConfiguration ...>
...
    <listAttribute key="org.eclipse.lsp4e.debug.model.ATTR_DSP_ARGS">
      <listEntry value="/C:/eclipse/plugins/org.eclipse.wildwebdeveloper_0.3.0.201906060852/language-servers/node_modules/node-debug2/out/src/nodeDebug.js"/>
...
    </listAttribute>
</launchConfiguration>
```
My guess is the the leading slash causing the double `C:\`. 

In the classes files NodeAttachDebugDelegate (in line 56) and NodeRunDAPDebugDelegate (in line 86) I've found the following line:
```
wc.setAttribute(DSPPlugin.ATTR_DSP_ARGS, Collections.singletonList(FileLocator.toFileURL(getClass().getResource("/language-servers/node_modules/node-debug2/out/src/nodeDebug.js")).getPath())); //$NON-NLS-1$
```
Maybe the used `org.eclipse.core.runtime.FileLocator` or org.eclipse.core.internal.runtime.Activator.getURLConverter() causing this behavior.

Is there a possible workaround by setting an environment variable?

Installation details:
- Windows 10
- Eclipse IDE Version 2019-06 (4.12.0)
- Wild Web Developer - Web edition in Eclipse IDE (Experimental)	0.4.1.201906280859	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project

Kind regards

Sven

**Comment by mickaelistria** [comment]
No workaround from command-line as far as I'm aware of.
But you can edit the .launch file directly in the meantime.

> My guess is the the leading slash causing the double C:\.

I guess your guess is right ;)
Would you be able to debug the code and check when this leading `/` appears?

**Comment by mickaelistria** [comment]
@PyvesB It seems like you're using Windows. Do you also see this issue?

**Comment by mickaelistria** [comment]
You can actually debug plain js with the debugger, debugging a hello world works.

**Comment by PyvesB** [comment]
A debugging session highlighted that [the fileUrl here](https://github.com/eclipse/wildwebdeveloper/blob/1ea187b713dc9dff63eaa40a8cb60670510d9976/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/NodeRunDAPDebugDelegate.java#L77) was equal to `file:/C:/Users/***/Java/eclipse-rcp/eclipse/../../workspace-rcp/wildwebdeveloper/org.eclipse.wildwebdeveloper/language-servers/node_modules/node-debug2/out/src/nodeDebug.js`.

Here's the call stack I obtained when stepping into the relevant methods:
```
File.slashify(String, boolean) line: 652	
File.toURL() line: 686 [local variables unavailable]	
FileBundleEntry.getFileURL() line: 103	
BundleURLConnection.getFileURL() line: 139	
BundleURLConverter.toFileURL(URL) line: 38	
FileLocator.toFileURL(URL) line: 261	
NodeRunDAPDebugDelegate.launch(ILaunchConfiguration, String, ILaunch, IProgressMonitor) line: 77	
LaunchConfigurationWorkingCopy(LaunchConfiguration).launch(String, IProgressMonitor, boolean, boolean) line: 862	
LaunchConfigurationWorkingCopy(LaunchConfiguration).launch(String, IProgressMonitor, boolean) line: 720	
DebugUIPlugin.buildAndLaunch(ILaunchConfiguration, String, IProgressMonitor) line: 1020	
DebugUIPlugin$2.run(IProgressMonitor) line: 1234	
Worker.run() line: 63	
```

A bit of digging around led me to the [following StackOverflow question](https://stackoverflow.com/questions/6164448/convert-url-to-normal-windows-filename-java). I noticed we were doing the right thing in other places, for example [here](https://github.com/eclipse/wildwebdeveloper/blob/21bfb25748e459a169b17270472ba3443baddaad/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/html/HTMLLanguageServer.java#L43). A pull request will be landing very soon!

**Comment by mickaelistria** [comment]
@barix Please give a try to https://download.eclipse.org/wildwebdeveloper/snapshots/ which should include a fix.
We'll try to release Wild Web Developer 0.4.1 very soon from this snapshot.

**Comment by barix** [comment]
@mickaelistria My Node.js application run configuration runs perfectly in eclipse. Thanks for the work.  The installed Version is 0.4.1.201907221412 (newest from [https://download.eclipse.org/wildwebdeveloper/snapshots/](https://download.eclipse.org/wildwebdeveloper/snapshots/)). 

An additional thanks for the "Debug Adapter"-Tab, it is a pleasure to be able to customize my run configurations this way.

**Comment by PyvesB** [comment]
@barix thanks for the feedback, glad your issue is now solved!
