### ISSUE TITLE
TypeScript 3.x support

### ISSUE THREAD

**Issue by akurtakov** [eclipse/wildwebdeveloper#187]
Support for TypeScript 3.x is missing

**Comment by akurtakov** [comment]
I'll file CQs shortly.

**Comment by akurtakov** [comment]
CQ for typescript https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20338

**Comment by jabby** [comment]
Thanks.

**Comment by akurtakov** [comment]
CQ for typescript-language-server https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20339

**Comment by akurtakov** [comment]
> CQ for typescript-language-server https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20339

APPROVED now.

**Comment by mickaelistria** [comment]
Did you try upgrading then?
The combination of node_modules is relatively fragile, and upgrading is getting more and more complex. Fortunately the tests are there to detect issues early.

**Comment by akurtakov** [comment]
Upgrade typescript? Yes, see the attached PR.

**Comment by akurtakov** [comment]
> CQ for typescript https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20338

APPROVED too

**Comment by akurtakov** [comment]
Adding angulara/language-service to the mix as version 8.0.0 added support for typescript 3.x. CQ is https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19296

**Comment by akurtakov** [comment]
Sigh CQ is https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20410

**Comment by akurtakov** [comment]
> Sigh CQ is https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20410

Approved.

**Comment by akurtakov** [comment]
CQ for typescript-plugin-css-modules 1.2.1  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20423

**Comment by akurtakov** [comment]
> CQ for typescript-plugin-css-modules 1.2.1 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20423

Approved now.
