### ISSUE TITLE
SyntaxError-Messages running Eclipse

### ISSUE THREAD

**Issue by Ludwig-K** [eclipse/wildwebdeveloper#190]
Hi all,
I come from Eclipse PDT/Eclipse WTP and want to use willdwebdeveloper because of unsufficient support of "namespaced" Javascript-Functions ala
```
var test = {};
test.my_func = function(){
   alert("Test");
};
```
Im running eclipse on debian9 with Java openjdk version "1.8.0_212"

I made fresh installs of actual eclipse 2019-06 and 2019-03 (Platform Runtime Binary), added wildwebdeveloper via Help>Install New Software.

I can start eclipse via terminal without problems, but whenever I try to create or open a simple js-File or click inside opened file in editor I get tons of errors in terminal:
```
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ludwig/eclipse/plugins/org.eclipse.wildwebdeveloper_0.3.1.201907091951/language-servers/node_modules/typescript-language-server/lib/lsp-connection.js:9:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
/home/ludwig/eclipse/plugins/org.eclipse.wildwebdeveloper_0.3.1.201907091951/language-servers/node_modules/vscode-languageserver/lib/main.js:405
    showErrorMessage(message, ...actions) {
                              ^^^

```
and eclipse-error-log:
```
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at ...

java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at ...
```

**Comment by jabby** [comment]
Hello @Ludwig-K
Thanks for reporting this issue.

Do you have node.js in your path and which version do you use? 

Thanks for your answers.

**Comment by Ludwig-K** [comment]
Hello jabby,

when I first installed wildwebdeveloper eclipse indeed complained "Could not find node.js..."

I installed node.js via "apt install nodejs", nodejs --version => "v.4.8.2", but eclipse still complained, and including "/usr/bin/nodejs" to PATH didn't change this.

After some googling I found a solution (?) via "ln -s /usr/bin/nodejs /usr/bin/node", afterwards I could start eclipse without complains about missing node.js, but with the problems described in my first question.

**Comment by jabby** [comment]
Ok I think I know why there is a problem. The version of node.js is toonold. I'm not sure but versions above 8.x will be good. 

I'm actually in a train so let me check in few hours. I will update my answer about node.js version.

I will also update the error message with a proper information about the version of node.js we need.

By the way, I suggest for managing node.js versions on your laptop to use nvm (node version manager). It can help a lit when you need to switch between different versions of node.js.

**Comment by jabby** [comment]
We use language servers from vscode 1.25. You should use the node version `8.9.2`.

I keep this issue open to track the modification about proper message about node.js version.

**Comment by angelozerr** [comment]
It seems again a problem with node runtime. I'm sorry to insist again with that, but IMHO https://github.com/eclipse/wildwebdeveloper/issues/23 should be supported.

**Comment by Ludwig-K** [comment]
Hi jabby,
thanks for the fast support.

I managed to update nodejs zu Version 10.16.0 following the guide on https://tecadmin.net/install-latest-nodejs-npm-on-debian/

Afterwards installed wildwebdeveloper

First impression after switching the associated editor from "JavaScript editor" to "Generic Text Editor": 

No more errors, everything is looking good and best of all: 

the long missed Javascript-namespace-support is there!

Many thanks to all developers...

**Comment by mickaelistria** [comment]
> IMHO #23 should be supported.

I agree that would usually fix everything.
But at the moment, this is not something we can afford to implement. It requires more effort that what our team at Red Hat can deliver soon (as we're involved in many many other projects).
If anyone else wants to take care of it, both either legally or technically, that would be highly welcome.

> I keep this issue open to track the modification about proper message about node.js version.

+1, I'll rename the issue accordingly.

**Comment by mickaelistria** [comment]
Closing as it's a dup of #55
