### ISSUE TITLE
Auto-closing tags in HTML

### ISSUE THREAD

**Issue by AirBashX** [eclipse/wildwebdeveloper#208]
你好开发者,这一款插件给了我很好的体验,但是唯一不足的是我在html页面输入一个标签以后不能补全标签的后半部分,可能是我没有找到相关的设置,请问一下是否有相关设置?

**Comment by yanxuedesaonian** [comment]
Hello developer, this plugin gives me a good experience, but the only downside is that I can't automatically complete the second half of the tag after entering the tag on the html page.
Maybe I didn't find the relevant settings.
Is there a setting?
This is what I translated with Google.Forgive me if there is a problem with the translation.

**Comment by mickaelistria** [comment]
Can you please share exact steps to reproduce: a simple example file, what action you run, what do you expect and what do you get?

**Comment by yanxuedesaonian** [comment]
For example, after I type the <a> tag, I want to automate the rest</a>

**Comment by yanxuedesaonian** [comment]
For example, after I type the <a> tag, I want to automate the rest</a>

**Comment by yanxuedesaonian** [comment]
For example, after I type the `<a>` tag, I want to automate the rest`</a>`

**Comment by mickaelistria** [comment]
So it's only about auto-insertion of closing tag?

**Comment by jabby** [comment]
FYI, I tried to add the `html.autoClosingTags` property in didChangeConfiguration but it does not work.

**Comment by yanxuedesaonian** [comment]
> 仅供参考，我尝试`html.autoClosingTags`在didChangeConfiguration中添加属性，但它不起作用。

thank you

**Comment by mickaelistria** [comment]
Can you please re-title the issue to English?

**Comment by mickaelistria** [comment]
This should be a feature added to the HTML language server upstream (maybe as an option), and then Wild Web Developer should simply consume it.

**Comment by angelozerr** [comment]
Like we have done on lsp4xml, HTML language server supports auto closing tags with a custom closeTag request.

**Comment by angelozerr** [comment]
I have started to manage closeTag for xml un https://github.com/angelozerr/lsp4e-xml/blob/master/org.eclipse.lsp4e.xml/src/org/eclipse/lsp4e/xml/CloseTagAutoEditStrategy.java but i dont remember if it worked well

**Comment by angelozerr** [comment]
@mickaelistria  this issue is fixed with https://github.com/eclipse/wildwebdeveloper/pull/865
