### ISSUE TITLE
Support node.js 12

### ISSUE THREAD

**Issue by rombert** [eclipse/wildwebdeveloper#220]
I am using the "current" version of Node.js, which is is 12. I keep getting popups (one per file type I guess, it would be nice to get just one per session at least ) saying that my version of node is not supported, although things seem to mostly work.

![image](https://user-images.githubusercontent.com/21237/63414829-e739a380-c3fc-11e9-9da8-f5c5a7a55ce2.png)

It would be great to fully support Node.js fully.

**Comment by mickaelistria** [comment]
What is it you call current? Latest release or latest snapshot.
@jabby isn't this alredy fixed?

**Comment by rombert** [comment]
@mickaelistria  - I mean Node.js current - https://nodejs.org/en/download/current/ . On the Eclipse side I am using Wild Web Developer - Web edition in Eclipse IDE (Experimental) 0.4.1.201907221412 .

**Comment by mickaelistria** [comment]
Can you please try latest snapshot build at http://download.eclipse.org/wildwebdeveloper/snapshots/ ?

**Comment by jabby** [comment]
@mickaelistria I did not update this. I will provide a patch in few minutes.

**Comment by jabby** [comment]
I created PR #221
I think there is a misunderstanding between the message and what version of node the developer can use for nide projects. 

@rombert If I understand correctly, the message is about the version of node for your project. Am I right? 
To be clear, it's version of node used by Wild Web Developer to enable features like completion / diagnostics / ...

**Comment by rombert** [comment]
Thanks @jabby . To be honest I am not sure about what version of node it is talking about :-) I did not use debugging, launching, etc. I mostly used it for editing SASS and HTML files.

**Comment by mickaelistria** [comment]
Patch merged, issue should be fixed by using upcoming snapshot build.
Thanks @jabby !

**Comment by rbr9292** [comment]
Good morning, sorry to reopen this issue but I'm having the same problem... Already tested node v10 and v12 and still having the same popup... I'm using KDE Neon, latest stable version, and Eclipse latest version as well. 

Thanks in advance,
Renan

![popup](https://user-images.githubusercontent.com/47678800/78889539-38ed7780-7a3a-11ea-8cc2-97d68378f5dc.png)

![node](https://user-images.githubusercontent.com/47678800/78889440-06dc1580-7a3a-11ea-9f35-49df5cf00ba6.png)

**Comment by mickaelistria** [comment]
Please open a new ticket for your case with more details about your OS, how you installed `node`, and what `node --version` returns

**Comment by rbr9292** [comment]
Thanks for the response, actually it was my fault on the node.js installation, and my distro wasn't able to get the correct version, now the popup was gone :+1:
