### ISSUE TITLE
Integrate Firefox Debugger

### ISSUE THREAD

**Issue by AObuchow** [eclipse/wildwebdeveloper#224]
I've started integrating the Firefox debugger into Wild Web Developer.
[Here is a demo of my current WIP.](https://youtu.be/-4Uh1Flhf1Q)

Any feedback or ideas regarding this integration are appreciated :)

**Comment by mickaelistria** [comment]
Great work and demo @AObuchow !
One thing I noticed is that you're using a Run Configuration to Debug. It should instead only be a DebugConfiguration. This can be set in the extension for launch configuration by having the `mode` only being `debug` (and not `run`).
As the way to run an index.html is to open it with some web browser and there are already shortcuts to open with a web browser or another, I don't think we need a "Run" for this case.

**Comment by AObuchow** [comment]
Thank you Mickael!
Yes you're right about the run configuration. I've now changed it to only have a debug configuration.

**Comment by jabby** [comment]
@AObuchow really interesting feature.

**Comment by mickaelistria** [comment]
@AObuchow I'm working on some debug adapter feature that I believe the Firefox debugger could help me to test the features I'm adding. Do you already have the code available for testing somewhere, do you have a public branch with your work in progress?
Also, feel free to submit a PR whenever you think this feature is usable without aiming for immediate perfection, we can merge a 1st working iteration and then deal with remaining details in dedicated issues.

**Comment by AObuchow** [comment]
@mickaelistria I'll make a public branch with my current WIP sometime today so that you can check it out.  And OK sounds good - will submit the PR soon afterwards.

**Comment by mickaelistria** [comment]
Done and merged, thanks @AObuchow !
