### ISSUE TITLE
Embed Node.js Runtime

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#23]
Provide embed node.js runtime like I have done for typescript.java. It will give the capability to consumes LSP without installing node.js (VSCode does like this I think).

If you are interested, I could do a PR.

**Comment by mickaelistria** [comment]
How likely it is that a frontend developer doesn't have nodejs installed?
I don't think it's worth the effort.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, at Red Hat Developers <https://developers.redhat.com/> community

**Comment by angelozerr** [comment]
If you are developping JEE Application and you wish to benefit with HTML, CSS features you don't need node.js. IMHO, I think Bluesky should work without any other program installation like node.js. VSCode works like this I think.

**Comment by mickaelistria** [comment]
There are package managers such as rpm for that. I don't think the burden should be carried by BlueSky, especially as it would drastically grow the download size and may lead users to inconsistencies ("why don't Eclipse and command-line behave the same...?  [3 hours later] Ok, it's not using the same node.js!").
A simple warning pop-up if node.js is not available or version is too old should be enough.

**Comment by angelozerr** [comment]
> There are package managers such as rpm for that. 

Take a sample. I have a computer where node.js is not installed and I want to develop HTML, CSS, JavaScript application:

 * I install VSCode, it works.
 * I install Eclipse IDE + BlueSky, it doesn't work. I don't need node.js, so I telll me why I must install node.js. I give up BlueSky and uses VSCode. 

None offense with your idea, I would like just to give you some feedback with typescript.java where user like the embed node.js feature.

> it would drastically grow the download size

The update site provides (like typescript.java) an optional installation of the embed node.js

**Comment by mickaelistria** [comment]
Ok, so it could simply be a change in https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/InitializeLaunchConfigurations.java#L56 to use alternative strategies:
* If node is in PATH, use it (current)
* If not and node is found in the Eclipse IDE installation (we could/should consume the node.js runtime packaged into some Eclipse plugin.

Doesn't JSDT already provided an embedded node.js that we could reuse (instead of writing yet-another-bundle including nodejs?) - cc @ibuziuk
Or maybe we could simply reuse the bundle that's in typescript.java

**Comment by ibuziuk** [comment]
> Doesn't JSDT already provided an embedded node.js that we could reuse
Unfortunately, no. We wanted to bundle node.js with JSDT and opened CQ[1] (which has been approved for a couple of month by now) but  literally had no bandwidth to implement it.

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi

**Comment by angelozerr** [comment]
@ibuziuk thanks for your answer. Your CQ link is good? 

I think it should be very cool to have an official embedjs nodejs runtime which could be consumed by tern.java, typescript.java an lsp4e/bluesky.

**Comment by ibuziuk** [comment]
@angelozerr good catch. I have updated CQ[1] link - `node.js Version: 4.4.3` 

[1] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11306

**Comment by angelozerr** [comment]
@ibuziuk current node.js is `v6.11.2` . I don't remember but I think I had some trouble with tssererver/protractor or tern.java with this version. IMHO I think we should consume  `v6.11.2`

**Comment by ibuziuk** [comment]
@angelozerr than new CQ should be created and one for 4.4.3 should be used as a piggyback

**Comment by jabby** [comment]
I have a little question : is node.js runtime embedded in other IDE like Netbeans and Intellij IDEA ?
I don't think that embed node.js runtime is a killer feature. A good warning should be sufficient.

**Comment by boniatillo-com** [comment]
I think that there are many Eclipse projects right now using nodejs, maybe the better is to create a third project, something like the NodeRT for Eclipse project, that is just about to bundle the node runtime so it creates consistency across the different projects that require this runtime.

Then the end users can install node into eclipse optionally, and the node runtime can be updated via eclipse updates, or different versions of the runtime can be installed at the same time and the projects can use the one they need.

**Comment by mickaelistria** [comment]
@boniatillo-com That is a good idea and it was already wished/discussed in the past without much action emerging from it. You could bring this to the appropriate Eclipse.org mailing-list and lead this initiative.

**Comment by JoyeLuo** [comment]
I was wondering that is it possible that we can use it without node.js?

**Comment by mickaelistria** [comment]
All language servers internally used by BlueSky to compute completion, hover and so on do require node.js. So node.js is a strong requirement for complete feature set.
If you're interested to contribute inclusion and shipping of node.js inside BlueSky to remove the dependency, that'd be welcome.

**Comment by paulvi** [comment]
That was @angelozerr initial proposal to do PR if there is interest,

**Comment by mickaelistria** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=542488 where CDT folks also consider shipping a node.js runtime.

**Comment by PhaserEditor2D** [comment]
And VSCode is not required too?

**Comment by mickaelistria** [comment]
> And VSCode is not required too?

Nope, VSCode is not required, its interesting parts are embedded in the jars at build time.

**Comment by PhaserEditor2D** [comment]
I think a quick solution about node is to do similar to JRE. The user (or product developers) can place node in a node folder next to the eclipse executable.

**Comment by PhaserEditor2D** [comment]
Another simple solution is first to try with a system property, something like 

```
-Dorg.eclipse.wildwebdeveloper.nodepath=/path/to/node
```

**Comment by PhaserEditor2D** [comment]
Users can change it in the eclipse.ini and plugin developers can change it at runtime.

**Comment by mickaelistria** [comment]
> Users can change it in the eclipse.ini and plugin developers can change it at runtime.

A preference should be preferred for that.

In any case, independently of the packaging we target in fine, the method `InitializeLaunchConfigurations.getNodeJSLocation()` could be augmented to support more heuristic like
* reading a preference,
* reading a system property
* look inside a specific folder relative to the launcher
* ....

There is no.restriction on what conventionq we could support, as long as they seem reusable by multiple clients, so feel free to submit PRs.

**Comment by zulus** [comment]
Is there any progress on that? I can't find anything interesting about this point on bugzilla

**Comment by mickaelistria** [comment]
AFAIK, no-one is working on it.
From our Red Hat packaging perspective, we're pushing for usage of Flatpak, in which we have installed the right Node.js version for Wild Web Developer to work, so we've reduced priority on this issue and aren't likely to work on it soon.
However, it's still quite interesting, and the current issue isn't technical but still legal (can we ship node.js at all?). I'll open a question to Eclipse IP team about it and post here about the progress. Then -once we have a legal clearance- anyone interested can take care of creating those node.js fragments or bundle.

**Comment by mickaelistria** [comment]
I opened CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21763

**Comment by zulus** [comment]
Thanks! From Linux perspective this probably is enough, but for windows/Mac i preferer to be sure that user have correct version always available (for example in my local env I had perfectly worked v8 until one of the packed forced me to upgrade). 

I'm in CC now ;)

**Comment by mickaelistria** [comment]
The CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21763 is approved, we're now legally free to ship Node.js runtimes! Now it needs some work ;)

**Comment by zulus** [comment]
I can test on macOS ;)

**Comment by angelozerr** [comment]
> Now it needs some work ;)

I dis that in typescript.java, If you like it, you can see, :

 * exsd schema at https://github.com/angelozerr/typescript.java/blob/master/eclipse/ts.eclipse.ide.core/schema/nodeJSInstalls.exsd
 * Java classes which manages this schema https://github.com/angelozerr/typescript.java/tree/master/eclipse/ts.eclipse.ide.core/src/ts/eclipse/ide/internal/core/nodejs
 * all implementation for each OS at 
https://github.com/angelozerr/typescript.java/tree/master/eclipse/embed

**Comment by mickaelistria** [comment]
I'm actually more thinking about using fragments than extension points, and make the fragments providing the node.js install directly in their root.

**Comment by mickaelistria** [comment]
FWIW, I personally don't plan to work on it before June release. But anyone else able to spend some time to work on it before I do it entirely welcome!

**Comment by zulus** [comment]
> * all implementation for each OS at
>   https://github.com/angelozerr/typescript.java/tree/master/eclipse/embed

Can Eclipse project just re-use existing third-party binary? I remember strict requirement that it have to be built (and signed) on foundation infra. Maybe I missed change.

**Comment by mickaelistria** [comment]
> Can Eclipse project just re-use existing third-party binary?

Yes, I think so. but as node.js will be included in some feature or bundle, it will be signed anyway.
We typically do that for all language servers.

**Comment by akurtakov** [comment]
Mickael, should this be in wildweb or in some other project? EPP? I ask as a shellwax maintainer and shipping correct nodejs version could be of interest there too?

**Comment by akurtakov** [comment]
@mbooth101 Mat, how would this affect flatpaks? Please raise your concerns and requirements so it's not done in a way making shipping as flatpaks harder.

**Comment by mickaelistria** [comment]
IMO, as I don't see immediate gain in using another project, let's start with Wild Web Developer, and make it a dedicated feature that can be used by others.
Then, if later we feel it'd be better to extract it into a separate project, we'll do it.

**Comment by mbooth101** [comment]
> @mbooth101 Mat, how would this affect flatpaks? Please raise your concerns and requirements so it's not done in a way making shipping as flatpaks harder.

Hmm, I'm not too concerned. In flatpak we only ship the nodejs executable for the user's running architecture. Will this be shipping fragments for all the architectures that Eclipse supports?

**Comment by akurtakov** [comment]
> > @mbooth101 Mat, how would this affect flatpaks? Please raise your concerns and requirements so it's not done in a way making shipping as flatpaks harder.
> 
> Hmm, I'm not too concerned. In flatpak we only ship the nodejs executable for the user's running architecture. Will this be shipping fragments for all the architectures that Eclipse supports?

Fragments for all archs will be available but only the current one being installed via proper filters.

**Comment by mickaelistria** [comment]
I've started some work about it on https://github.com/mickaelistria/wildwebdeveloper/tree/nodejs . Currently, it's only showing some structure for fragments and hacking a bit the resolution of node.js location accordingly.

**Comment by akurtakov** [comment]
@vrubezhny ^^

**Comment by AObuchow** [comment]
When this bug is resolved, it might be useful to allow Node to be invokable by an extension point or something similar. This would allow Eclipse project builders to be created which run JS or an npm script during auto builds. For example, being able to run Prettier from the project's node_modules directory on project save.

**Comment by nitind** [comment]
What happens now on platforms where the embedded node isn't available, like ppc64le?

**Comment by mickaelistria** [comment]
> What happens now on platforms where the embedded node isn't available, like ppc64le?

The noxe manager will identify node isn't embedded and will then try to find node in PATH, just like it used to happen for other platforms before node embedder.

**Comment by nitind** [comment]
Maybe I've got this backwards, but is WWD supposed to *require* the embedder?

<img width="816" alt="Screen Shot 2021-02-11 at 3 59 56 PM" src="https://user-images.githubusercontent.com/2684153/107698427-894ceb80-6c82-11eb-85bf-fdb1241640e4.png">

**Comment by mickaelistria** [comment]
IIRC, it's an optional greedy requirement, so it gets installed by default, and then users can uninstall it.
But it's a bit messy from user perspective, https://bugs.eclipse.org/bugs/show_bug.cgi?id=562679 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=562678 would need some love to better cover this story.
