### ISSUE TITLE
Integrate Chrome debugger

### ISSUE THREAD

**Issue by AObuchow** [eclipse/wildwebdeveloper#230]
I'm going to start working on integrating the chrome debugger as the vscode extension for it has a debuger adapter which is very similar to the node debugger's adapter.

**Comment by mickaelistria** [comment]
@AObuchow, I'm answering here the questions/comments you made on internal Slack

> So far I haven't had too much success with the chrome debugger unfortunately
Maybe I'm just missing something but looking at https://github.com/microsoft/vscode-chrome-debug/blob/master/src/chromeDebugAdapter.ts
I realized there isn't any outer-most function call (function which gets called when the file is loaded)
there's only function declarations
so running node chromeDebugAdapter.js won't work
I was however, able to get the extension to work within vscode

One possibility is that when you get it working with vscode, you run some `ps aux | grep node` command to see what's the command invoked by VSCode. It may indeed be a different entry point to use.

**Comment by mickaelistria** [comment]
It seems like we should instead use https://github.com/microsoft/vscode-chrome-debug/blob/master/src/chromeDebugAdapter.ts (so include the vscode-chrome-debug module)

**Comment by mickaelistria** [comment]
Great @AObuchow . 
To embed it, you can mimic what was done in https://github.com/eclipse/wildwebdeveloper/pull/231/commits/b1f39b6daa79e4848cf1fd3b287c9de0b7b56469#diff-f5f4550a2038c2e52d1c95b8af5eb02e (pom.xml)

**Comment by mickaelistria** [comment]
Main patch in this story is merged. However I see that the Chrome Debug shortcut on right click starts a node.js debugger.
I think this is addressed in #251

**Comment by AObuchow** [comment]
> Main patch in this story is merged. However I see that the Chrome Debug shortcut on right click starts a node.js debugger.
> I think this is addressed in #251

Yes you're right. I just did a local rebase of my refactoring branch and the issue seems to be fixed there. Going to submit a PR now.

**Comment by mickaelistria** [comment]
Refactoring was merged and includes all the fix. The Chrome Debugger seems usable enough now. Thanks @AObuchow !

**Comment by AObuchow** [comment]
My pleasure :)!
