### ISSUE TITLE
question: how to install correctly

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#232]
I want to use the snapshot versions and I am wondering, which items I need to select for for a complete and correct install:

![eclipse-wwd](https://user-images.githubusercontent.com/3045549/63932832-49775180-ca58-11e9-92da-1157d55d1bba.png)

Should I also select the "**Dependencies**" (Generic and Ext Text Editor + Xbase Runtime Lib)? Or do I only need the last ("WebDev in Eclipse IDE") already selected?

**Comment by mickaelistria** [comment]
Only the last one should be selected. The "depedencies" will be fetched transitively.
I'll rework the labels to hopefully make that clearer.

**Comment by nimo23** [comment]
ok, thanks!
