### ISSUE TITLE
theme changing and textmate binding issues

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#235]
There are missing textmate bindings:

![textmate-wwd](https://user-images.githubusercontent.com/3045549/64003017-ae3fb400-cb0b-11e9-83d5-5d74a6225f8f.png)

There is a `source.css.less`, but  `source.less` is missing
There is a `source.css.scss`, but  `source.scss` is missing
There is a `source.js.jsx`, but  `source.jsx` is missing.

Please add `source.less`, `source.scss` and `source.jsx`.

For example, I have a filename with `source.jsx`, the textmate theme does not use the provided theme configured by `source.js.jsx`.

**Comment by nimo23** [comment]
I guess, there is another issue: Configuring the textmate theme for jsx does not work. Other theme configurations (for example, changing css theme from solarized light to eclipse light) works. However, changing jsx themes does not work.

**Comment by mickaelistria** [comment]
IMO, the first comment is not a bug. The names are technical and internal names used by the textmate grammars, it seems like you're overinrterpreting them and that leads you to erroneous conclusions.
Or maybe you can re-explain your issue as a user-story (ie what do you want to do, how do you try it, what's the expected result vs what do you get)?

About the 2nd issue of theme not changing property for JS and JSX, I cannot reproducing. If you can reproduce it with more details, please open a separate bug.
