### ISSUE TITLE
renaming jsx file endings issues

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#236]
When I rename the file 

`app.jsx`

to 

`app.js.jsx`

and rename it back to 

`app.jsx`

and opening it with **wwd generic editor**, then I get this error:

`Resource '/.../...../app.jsx' does not exist.`

But it exits (I can see it), refreshing the whole workspace does **not** help. 

The same error in the editor is shown: `Resource...app.jsx does not exist.`

Only if I restart the IDE, then it works and wwd generic editor can open the file.

I dont know if this is also for other endings (for example, css, tsx,..) with generic editor..

**Comment by mickaelistria** [comment]
No news for more than 3 years, let's close.
