### ISSUE TITLE
SCSS formatter

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/wildwebdeveloper#237]
Hey, 

as far as I can see there is no option to format neither HTML nor SCSS. 

Maybe it is possible to use [prettier](https://prettier.io/) for this?

**Comment by angelozerr** [comment]
It was a long time but I created an issue for vscode CSS LS to support formatting. The idea is to configure the CSS Language Server with a JS formatter like jsbeautify or prettier. See https://github.com/microsoft/vscode/issues/39088 but it requires a PR.

Once this PR will be done, we could having formatting for CSS with LS without adding extra code.

**Comment by mickaelistria** [comment]
As @angelozerr , this is something that needs to be fixed upstream, in VSCode language Servers.

**Comment by jonas-jonas** [comment]
For HTML as well? I see why this would be desirable in the LS, but wouldn't it make sense to also provide some other formatter as well? See tons of VSCode plugins...

**Comment by mickaelistria** [comment]
The scope of Wild Web Developer is to leverage language servers and redirect most language smartness effort into the language server. So, yes, even for HTML, Wild Web Developer won't use or host another formatter. If some want to put some development effort to implement formatting, then this effort has to be directed to VSCode, and then Wild Web Developer will enable it for free.

**Comment by vogella** [comment]
+1 for the suggestion. @mickaelistria can you open an upstream bug?

**Comment by angelozerr** [comment]
> For HTML as well?

I think HTML Language Server should provide the capability to configure a given formatter like explained in https://github.com/eclipse/wildwebdeveloper/issues/237#issuecomment-526584992

**Comment by angelozerr** [comment]
>  So, yes, even for HTML, Wild Web Developer won't use or host another formatter. 

@mickaelistria it seems vscode supports html format. It seems that it is enable with dynamic settings https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/server/src/htmlServerMain.ts#L175

**Comment by mickaelistria** [comment]
Thanks a lot for those pieces of information @angelozerr . I'm preparing a PR to enable HTML formatting.

**Comment by mickaelistria** [comment]
Thanks to @angelozerr 's hint, HTML formatter was added and will be available in next snapshots (and next release).

**Comment by mickaelistria** [comment]
So HTML is supported and CSS is tracked in #38 , let's close.

**Comment by angelozerr** [comment]
My current PR https://github.com/eclipse/wildwebdeveloper/pull/925#issuecomment-1292923816 activate CSS formatter but without preferences.
