### ISSUE TITLE
Why does wildweb do "/bin/bash -c which node" ?

### ISSUE THREAD

**Issue by mbooth101** [eclipse/wildwebdeveloper#238]
I noticed that wildweb does ```/bin/bash -c which node```

Some platforms don't use bash as their default shell, so this could fail out-of-the-box. And AFAIK the "which" command is not even a bash built-in, so invoking the shell seems redundant. It should be sufficient to simply call ```which node```

**Comment by mickaelistria** [comment]
Ok. Can you please submit a PR for that?

**Comment by PyvesB** [comment]
You need to invoke a new shell with `/bin/bash -c which node` as the PATH variable set by the Eclipse will probably not contain the Node executable, therefore `which node` will not return anything. See [this StackOverflow thread](https://stackoverflow.com/a/48831940/3527464) for more information. I would even argue it should be `/bin/bash -c -l which node`, as I've documented in my investigation on [this other thread](https://stackoverflow.com/questions/55436162/programmatically-get-full-paths-of-external-programs-from-within-eclipse).

**Comment by PyvesB** [comment]
Probably not much to add here for the time being, shall we close this issue?
