### ISSUE TITLE
[Debug] Add right-click on project -> Debug As.. context menu for Node/Firefox debugging

### ISSUE THREAD

**Issue by AObuchow** [eclipse/wildwebdeveloper#243]
We should add support for the "Debug As..." right-click context menu which is available when right clicking on a project in the Project Explorer. The user should be able to launch a Node or Firefox debug session.

**Comment by mickaelistria** [comment]
We might need to add an adapter to ILaunchable like aCute does in https://github.com/eclipse/aCute/blob/master/org.eclipse.acute/plugin.xml#L395 to make the Debug/Run As menu show up.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/commit/504e002f5fcb2f302612ab6bf1f8c78c2eefbfa5

**Comment by mickaelistria** [comment]
Reopening, wrong issue.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/pull/250
