### ISSUE TITLE
[Firefox Debug] Java projects shouldn't be able to launch with Firefox

### ISSUE THREAD

**Issue by AObuchow** [eclipse/wildwebdeveloper#248]
With a java project opened, right-clicking on the editor or project and selecting `Debug as...` gives Firefox as a launch option. This doesn't make sense for java projects and must be removed.  
![image](https://user-images.githubusercontent.com/10300119/64349773-821daa80-cfc5-11e9-85d3-040fed14e7b3.png)

**Comment by mickaelistria** [comment]
I'm working on that part (filtering launchers, pre-populating them) right now.

**Comment by AObuchow** [comment]
Ok great, thanks.

**Comment by mickaelistria** [comment]
@AObuchow my patch doesn't fix it, feel free to work on it if you have the opportunity.
