### ISSUE TITLE
tsserver does not work if windows user folder contains spaces

### ISSUE THREAD

**Issue by edertone** [eclipse/wildwebdeveloper#254]
A tsserver error appears on the eclipse console when the current windows user folder contains spaces:

[Error]	[tsserver] "c:\Users\myuser" not recognized as an internal or external command

When the user folder is "c:\Users\myuser name"

**Comment by mickaelistria** [comment]
I'm afraid it could be a bug in the typescript-language-server we're using.
I'll need to try this on Linux to see if I can reproduce it here to and then sort out which component is responsible for it.
However, I'm busy with other things so I won't be able to spend time on it so soon, so if you can (or find someone who can) begin a deeper investigation, that would really help.

**Comment by PyvesB** [comment]
Hi @edertone, I just tried using an Eclipse installation path + workspace both containing spaces in the path, which _should_ have the same effect as a space in the user name by the looks of the error message. However, I am not able to reproduce this error. Could you give us some more information? Do you have a sample project we could use?

**Comment by edertone** [comment]
Hi @PyvesB, I am sorry but my fix to this problem was to effectively change the username for my windows installation and remove all spaces, so now I can't reproduce the problema cause everything works fine...

**Comment by mickaelistria** [comment]
@edertone Can you reproduce this issue with latest release?

**Comment by edertone** [comment]
Hi mickael, to try to reproduce it i would need to change my windows sername so it has spaces, and it is not possible now... I am sorry

**Comment by mickaelistria** [comment]
OK, so let's close and anyone feel free to comment if this can be reproduced.
