### ISSUE TITLE
Make html projects debuggable with Firefox/Chrome on right-click context menu

### ISSUE THREAD

**Issue by AObuchow** [eclipse/wildwebdeveloper#258]
The user should be able to debug a project containing a index.html file by right clicking on the project (in the project/package explorer) and selecting Debug As... -> Chrome (or Firefox).

**Comment by mickaelistria** [comment]
I think it shouldn't be only projects, but any container (ie can also be a folder).
Also, it should be enabled whenever there is an `index.html` or whenever there is only one HTML file in the folder (which would become the debugged file then).

**Comment by jabby** [comment]
In fact it shouldn't be only projects with an `index.html`. Actually I work on a project with React and Node.JS. There is no `*.html` file at all. But this kind of feature will be helpful.

**Comment by AObuchow** [comment]
> In fact it shouldn't be only projects with an `index.html`. Actually I work on a project with React and Node.JS. There is no `*.html` file at all. But this kind of feature will be helpful.

Yes you're right. In a later iteration, it should allow web app projects (projects with a package.json?) to be launched from right click as well.

**Comment by mickaelistria** [comment]
> Yes you're right. In a later iteration, it should allow web app projects (projects with a package.json?) to be launched from right click as well.

I think it's going to be a totally different beast to enable debug for projects that have server side and client-side in JS... I suggest we really ignore fully this complex case at the moment.
