### ISSUE TITLE
Use user facing names for marketplace entries

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#259]
I watched a user yesterday using the market place client and she
did NOT select Wild Web Developer when offered MP solutions for css
files. I asked her why and she told me that the name is scary or "too wild" as she said.

Maybe avoid using the name in user facing and simply use descriptive
names, like "CSS editor" or "CSS editor based on language server
protocol" or "CSS editor - default for the Eclipse packages".

**Comment by mickaelistria** [comment]
@AObuchow what's your opinion on this one?

**Comment by vogella** [comment]
Maybe use  a postfix? Like "HTML, CSS, JavaScript, TypeScript, Node.js, Angular, JSON, YAML (+Kubernetes), XML... support in Eclipse IDE powered by the Wild Web Developer project"

**Comment by vogella** [comment]
@jnerlich @jonas-jonas WDYT?

**Comment by mickaelistria** [comment]
Here is what the dialog looks like at the moment when trying to open some CSS file without support available

![marketplace](https://user-images.githubusercontent.com/469058/65318444-e6cc2e00-db9d-11e9-9a59-5ac9bedb0272.png)

I don't think the name is what makes the difference.
I'm more curious about what's the reason for HTML Editor to show up first here. I don't find a good explanation.

**Comment by jonas-jonas** [comment]
> Maybe use a postfix? Like "HTML, CSS, JavaScript, TypeScript, Node.js, Angular, JSON, YAML (+Kubernetes), XML... support in Eclipse IDE powered by the Wild Web Developer project"

I do not like having the "tags" in there at all. A typical user would look for one or two of those technologies and would be intimidated by the shear number of things that are in there or might not even see the for him relevant things. 
See https://marketplace.visualstudio.com/ for example. Most plugins have concise names.

I think the marketplace needs to be improved here as well. Show more recent entries first, the sorting seems to be weird, too.

**Comment by AObuchow** [comment]
I agree with @mickaelistria's that the name/branding being important to help distinguish the plugin (at least until it's the first entry of its kind on the marketplace).

However, @jonas-jonas has a point that the tags in the title can be a bit overwhelming. 
Perhaps shortening the plugin title to "Eclipse Wild Web Developer" and listing the tags a bit earlier in the description (eg. "Provides support for HTML, CSS, JavaScript, TypeScript, Angular, JSON, YAML (+Kubernetes), XML edition as well as debuging in Node.js, Firefox...") would be beneficial.

It also seems that only the `fileExtension_xyz` tags are being used for the plugin's _actual_ tags. If the name were to be shortened, I would suggest adding the tags used in the current title to the plugin's tags so that WWD would continue to come up in MP search queries. (To illustrate my point, if you search "Kubernetes", WWD comes up. I don't want a shorter plugin title to change this)

**Comment by mickaelistria** [comment]
Ok, I reworked a bit the marketplace entry. Please have a look in Marketplace client.
However, I may change it back later when we're post-enough release to have reliable daily install numbers and sort out how good/bad the number are affected by a change or another.
It could be that the user mentioned by @vogella was actually an exception and that most other people are more likely to select Wild Web Developer with the list of tags. Some former experiments a few months ago seemed to show that expliciting features in title led for more clicks, I'll retry it.

**Comment by vogella** [comment]
Mickael, please also check the user experience for unknown type extension
by the marketplace client.

Scenario:

- install MPC in SDK
- open .CSS file -> MPC shows a popup with available extensions but iirc it
shows the feature id.

I think it show show something more meaningful. I add this here because I
think you created that extension.



Mickael Istria <notifications@github.com> schrieb am Fr., 20. Sep. 2019,
15:32:

**Comment by mickaelistria** [comment]
> but iirc it shows the feature id.

Can you please confirm that this "iirc" is the actual behavior? It doesn't seem so to me.
Also, please avoid polluting the specific Wild Web Developer bug with things for other plugins; a link to another bug would be preferred.

**Comment by vogella** [comment]
You lost my involvement in the discussion with the phrase "polluting".

Mickael Istria <notifications@github.com> schrieb am Fr., 20. Sep. 2019,
15:43:

**Comment by mickaelistria** [comment]
The title was improved: many non payload terms were removed, but as previous measurements have highlighted keeping keyword in title increase the download numbers, I've kept them.
