### ISSUE TITLE
I just installed wild web dveloper in eclipse IDE version: 2019-06.

### ISSUE THREAD

**Issue by syedhamzamohiuddin** [eclipse/wildwebdeveloper#264]
![Screenshot from 2019-09-24 19-49-35](https://user-images.githubusercontent.com/35479390/65522784-b8838100-df04-11e9-852e-caff72906890.png)
I installed wildwebdeveloper in eclipse IDE version:2019-06 by dragging and dropping the install icon on eclipse market place. After restart I get a prompt to install node.js.
I closed the modal, created new javascript project ,created a new js file but nothing happened.
no autocompletion, no suggestion etc

**Comment by syedhamzamohiuddin** [comment]
I installed wildwebdeveloper in eclipse  IDE version:2019-06 by dragging and dropping the install icon on eclipse market place. After restart I get a prompt to install node.js.
I closed the modal, created new javascript project ,created a new js file but nothing happened.
no autocompletion, no suggestion etc.

**Comment by mickaelistria** [comment]
Did you install node.js as requested?

**Comment by syedhamzamohiuddin** [comment]
no I didn't. Is it compulsory?

**Comment by mickaelistria** [comment]
Isn't the message in the popup clear enough?
```
Could not find node.js. This will result in editors missing key features.
Please make sure node.js is installed and that your PATH environment variable contains the location to the `node` executable.
```

**Comment by syedhamzamohiuddin** [comment]
Yes it is. It appeared to me that it was only needed if I were use node js. I will let you know if it works after that. Thank you

**Comment by syedhamzamohiuddin** [comment]
It is working now. Thanks 😊

**Comment by wnm3** [comment]
I found that no matter what I did on MacOS wrt to having the path point to /usr/local/bin which is where the node executable is located, I could not avoid getting the message above after starting eclipse and attempting to click on a menu entry. After reading the source code, what I found worked was to add a line to the eclipse.ini in the Eclipse.app/Content/Eclipse folder that specified the path as follows:
```
-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=/usr/local/bin/node
```
Note this reflects the path and executable file name (node).

**Comment by mickaelistria** [comment]
@wnm3 Can you please open a new dedicated issue about it?

**Comment by wnm3** [comment]
Please see https://github.com/eclipse/wildwebdeveloper/issues/287

**Comment by mauromol** [comment]
This requirement to install node.js separately is annoying. I don't remember a prompt to install it, but I have the "missing node.js" message every time I open an editor (json, js, css, etc.) in 2019-12. Couldn't it be installed automatically with WWD? Is there a licensing issue?

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/wildwebdeveloper/issues/23
