### ISSUE TITLE
Formatting a file does not preserve markers

### ISSUE THREAD

**Issue by nitind** [eclipse/wildwebdeveloper#265]
Formatting a file erases all markers: breakpoints, tasks, bookmarks, etc. The data entered by the user is lost.

**Comment by mickaelistria** [comment]
Can you please provide a test file and some steps to reproduce? I tried it with a .js file here and didn't see problems or breakpoints disappearing.

**Comment by nitind** [comment]
Odd. I definitely saw this at the time but I'm not able to reproduce it now.
