### ISSUE TITLE
Refactoring in js files not working

### ISSUE THREAD

**Issue by pebbles186** [eclipse/wildwebdeveloper#267]
Hey guys,
I am not sure if it is a bug or missing feature.
When editing a JS file, I don't have the possibility to refactor code, e.g. extract method or extract local variable.

**Comment by mickaelistria** [comment]
Support for code-actions/refactorings is being built in Eclipse LSP4E. Once it's there, some refactoring should become available.

**Comment by pebbles186** [comment]
Okay, will ask for it there. Thanks!

**Comment by mickaelistria** [comment]
No need to ask, it's already WIP: https://bugs.eclipse.org/bugs/show_bug.cgi?id=528943
