### ISSUE TITLE
Incorrect default Node.js location for macOS

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#268]
The code that sets the default Node.js location when not found on the macOS PATH does not work as intended:
https://github.com/eclipse/wildwebdeveloper/blob/88cad00cafd837260df54a1020b5434e5700011a/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java#L57

`res` cannot be `null` as this point due to the 3 previous lines of code:
```
if (res == null) {
    res = "/path/to/node";
}
```

We should also probably include sensible defaults for other operating systems. I will submit a pull request shortly.

Cheers,

Pyves

**Comment by mickaelistria** [comment]
Fixed with #269.
