### ISSUE TITLE
AngularLanguageService is dumping logs into Desktop

### ISSUE THREAD

**Issue by megaza** [eclipse/wildwebdeveloper#273]
Wildwebdeveloper: 0.7.0.201910021333

On every new Eclipse restart, new random AngularLanguageService log directory is created:
```
[Info]	Angular LS probe location: C:\Users\ninom\Desktop
[Info]	Success: @angular/language-service loaded
[Info]	Log file: ng_heIC59\ngserver.log
[Warning]	Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.
```

Should it be in some user temp directory and removed previous one?

**Comment by PyvesB** [comment]
Similar issue here. I'm surprised though, I've never used Angular, why would the server automatically be started?

**Comment by mickaelistria** [comment]
There may be 2 issues:
1. We could investigate how to reduce the messaging/logging from the Angular Language Service to only show errors in the console
2. We need to refine when the Angular Language Service is connected. Currently, it's attached to any HTML or TS file (with content-type), we'd need to find a way to dynamically assign a specialized content-type to those files according to whether a `angular.json` file exists for instance.

**Comment by megaza** [comment]
OS: Windows 10
Eclipse: 2019-06 (4.12.0)
Wildwebdeveloper: 0.7.0.201910021333
Node: 10.16.3

Question also why it creates log directories in current working directory (where eclipse.exe was opened):
![ng-log-issue](https://user-images.githubusercontent.com/6707617/66350438-96095300-e95b-11e9-9f92-3c225accdc95.png)

**Comment by mickaelistria** [comment]
> We could investigate how to reduce the messaging/logging from the Angular Language Service to only show errors in the console
> ...
> why it creates log directories in current working directory

See https://github.com/eclipse/wildwebdeveloper/pull/274 on this topic. I don't think it fixes everything though, but it may improve a few things.

**Comment by megaza** [comment]
Fixed with 0.7.0.201910080537

**Comment by mickaelistria** [comment]
Thanks for testing and reporting!

**Comment by PyvesB** [comment]
>     2. We need to refine when the Angular Language Service is connected. Currently, it's attached to any HTML or TS file (with content-type), we'd need to find a way to dynamically assign a specialized content-type to those files according to whether a `angular.json` file exists for instance.

Is this currently possible in Eclipse? Another common use-case would be for files without extensions but starting with a shebang.

**Comment by mickaelistria** [comment]
> Is this currently possible in Eclipse? Another common use-case would be for files without extensions but starting with a shebang.

I *think* (not sure at all) it could be possible, as it seems to me the XML content-types from WebTools can inspect content to refine XML into a child of XML (such as "persistence.xml" or "servlet-mapping.xml"). But that'd need to be verified.
