### ISSUE TITLE
Autocomplete angular .html template without open .ts

### ISSUE THREAD

**Issue by megaza** [eclipse/wildwebdeveloper#278]
Wild Web Developer: 0.7.0.201910102046

In case if only open .html without .ts it triggers empty autocomplete popup and outputs to the lsp4e.LanguageServerWrapper console:
```
[Error]	Failed to find project for c:\Users\ninom\Desktop\angular-app\src\app\app.componentWithHtml.html
```

> The language service should not produce the error `Failed to find project for foo.html`.
It means the language service was able to find a tsconfig file for the html, but was unable to find a project that corresponds to the tsconfig.
The fix is pending upgrade to TS 3.6, I filed https://github.com/angular/vscode-ng-language-service/issues/411 to keep track of this.

_Originally posted by @kyliau in https://github.com/eclipse/wildwebdeveloper/issues/272#issuecomment-540714323_

**Comment by mickaelistria** [comment]
With upgrade of Language Servers and other dependencies submitted in #306 , this will get fixed as a side-effect.

**Comment by mickaelistria** [comment]
This is working since 0.8.1 and update of the language servers.
