### ISSUE TITLE
Autocomplete order is not right during typing

### ISSUE THREAD

**Issue by ninomagazinovic** [eclipse/wildwebdeveloper#281]
Wild Web Developer: 0.7.0.201910102046

Code completion tested in .scss file by triggering CTRL+SPACE and typing `width` but it does not put it first on the list during input:
![autocomplete-order](https://user-images.githubusercontent.com/6707617/66647102-4317f000-ec28-11e9-98e5-c7c27d864341.png)

Closing the popup and triggering again CTRL+SPACE on property `width` it does order correctly:
![autocomplete-order-ok](https://user-images.githubusercontent.com/6707617/66647223-9e49e280-ec28-11e9-8e81-b28bbb572583.png)

**Comment by mickaelistria** [comment]
There are multiple possible cause:
* One is LSP itself being unclear on sorting/filtering: https://github.com/microsoft/language-server-protocol/issues/898
* The other can be a bug in LSP4E heuristics and should be reported to LSP4E https://bugs.eclipse.org/bugs/enter_bug.cgi?product=lsp4e

**Comment by jabby** [comment]
I can't reproduce with the latest version of Wild Web Developer. @megaza  Can you upgrade to latest and try again?

**Comment by mickaelistria** [comment]
No news for a while, let's close.
