### ISSUE TITLE
Errors in eclipse problem view are displayed only after file open

### ISSUE THREAD

**Issue by ninomagazinovic** [eclipse/wildwebdeveloper#283]
Would be great that lint errors and typescript type errors are automatically refreshed in eclipse problem view without the need to open the file.

Scan all files defined by tsconfig.json (or something configurable and generic by calling lint and tsc):
```
"include": [
  "src/**/*.ts"
]
```

**Comment by megaza** [comment]
Maybe it is related to support for typescript-eslint #145

**Comment by mickaelistria** [comment]
The LSP specification (that is used by Wild Web Developer and vscode-eslint) clearly mentions that "diagnostics" -aka problem markers in Eclipse IDE- are to be shown only on open editors and discarded when closing. This is not something that Wild Web Developer can change.
