### ISSUE TITLE
Solving Eclipse Warning: Could not find node.js for MacOS

### ISSUE THREAD

**Issue by wnm3** [eclipse/wildwebdeveloper#287]
I found that no matter what I did on MacOS wrt to having the path point to /usr/local/bin which is where the node executable is located, I could not avoid getting the message above after starting eclipse and attempting to click on a menu entry. After reading the source code, what I found worked was to add a line to the eclipse.ini in the Eclipse.app/Contents/Eclipse folder that specified the path as follows:
```
-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=/usr/local/bin/node
```
Note this reflects the path and executable file name (node). Others have suggested creating a symbolic link but that did not work for me.

**Comment by mickaelistria** [comment]
I don't use a Mac so cannot repeoduce and AFAIK, none of the main
contributors do. So please consider finding a patch on your end and
submitting it.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by wnm3** [comment]
There may be some confusion. By adding the declaration as specified above to the eclipse.ini, the problem is solved.  There were confusing and inconsistent solutions elsewhere on the web talking about creating symbolic links, or using -Dorg.eclipse.wildwebdeveloper.nodepath (incorrect). So, I was merely documenting the solution above.

I suspect the way programs are launched on MacOS without benefit of the user specified PATH is causing confusion in the message displayed that discusses adding the node executable location to the PATH environment variable (see https://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications). This article discusses a solution , however, I think setting the eclipse.ini variable declaration is the cleanest solution for MacOS.

**Comment by PyvesB** [comment]
Hello @wnm3! What release of Wild Web Developer are you using? I was facing issues as well, but the commit I made a few weeks ago solved the problem (https://github.com/eclipse/wildwebdeveloper/commit/88cad00cafd837260df54a1020b5434e5700011a). The location you described is also the default I specified in another commit (https://github.com/eclipse/wildwebdeveloper/commit/5af3dcd3f4440418c0f324aa0f72d139773217b0).

**Comment by wnm3** [comment]
I'm using the latest update for the 2019-09 Eclipse:
```
Wild Web Developer - Web edition in Eclipse IDE (Experimental)	0.4.2.201909061612	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
```
I probably read your code to figure out the appropriate setting for the eclipse.ini file.

**Comment by PyvesB** [comment]
That version won't contain my fixes. I suggest you try adding the following update site to Eclipse and update Wild Web Developer (_Help -> Install New Software..._):
https://download.eclipse.org/wildwebdeveloper/releases/0.7.0

You can also use this one if you always want to point to the latest release:
https://download.eclipse.org/wildwebdeveloper/releases/latest

And if you're feeling adventurous and enjoy testing out nightly builds like myself:
http://download.eclipse.org/wildwebdeveloper/snapshots

**Comment by gubjack** [comment]
@wnm3 Thanks! This helped me as well.

@PyvesB The problem appears on a Mac with in a fresh installation of STS with Node via Homebrew and WWD out of marketplace. - Please let me know if I can assist somehow.

MacOS - 10.14.6
Spring Tool Suite 4 - Version: 4.5.0.RELEASE - Build Id: 201912171052
Node via Homebrew - 13.3.0
Wild Web Developer - 0.7.2.201911151547

**Comment by PyvesB** [comment]
@gubjack what is the output of `which node` in a terminal?

**Comment by gubjack** [comment]
/usr/local/bin/node
/usr/local/bin/node -> ../Cellar/node/13.3.0/bin/node

**Comment by PyvesB** [comment]
Hmmm, Eclipse should find it if it appears on your path with the `which` command. Worse case scenario, it's the default path for macOS, which should be used as a fallback: https://github.com/eclipse/wildwebdeveloper/blob/efd1873d875bd35af97a7265ac0887fb183bff27/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java#L89

Is this a fresh install of Wild Web Developer? Or did you already have it installed on a previous Eclipse installation on the same machine? At some point my Eclipse was claiming that it was using an up-to-date version of WWD, but some new functionality was clearly not there. Digging through the installation folders, it appeared that a much older version was being used and that the version displayed in the installation details was completely wrong. I'm wondering whether you encountered the same problem.

If you've asserted that for sure you're using the latest version, you could download the sources and debug the following method to see what's happening: https://github.com/eclipse/wildwebdeveloper/blob/efd1873d875bd35af97a7265ac0887fb183bff27/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/InitializeLaunchConfigurations.java#L43

**Comment by gubjack** [comment]
My installation of WWD is completely new - and by the way I already like it!

Regarding debugging - I'll get into that at a later point.  I'm absolutely new to eclipse plugin development and so I need some time to get into it.

**Comment by mickaelistria** [comment]
Is there anything still to work on here or should we close the ticket?

**Comment by wnm3** [comment]
My issues were addressed so okay to close by me. Thx

**Comment by mickaelistria** [comment]
Thanks for the feedback!
