### ISSUE TITLE
No Documentation on how to use 

### ISSUE THREAD

**Issue by rbrown3rd** [eclipse/wildwebdeveloper#288]
I have an Eclipse installation with wildwebdeveloper installed. There appear to be no particular projects available for the web applications, no getting started documentation, and no instructions for how to use the plugin.

I have also searched the Github site, the Eclipse site (which refers to the Github site) and the general Internet for some kind of instruction on how to create a project, how to test and debug using it, and any instruction related to setting it up.  There appears to be nothing anywhere except nice screen shots of the plugin being used to create an Angular app.

Could someone write some kind of guide for using this plugin, or at least ut up some links to user documentation???

Thank you.

**Comment by mickaelistria** [comment]
Wild Web Developer doesn't require nor ship any project type (nature), nor specific wizards.
Just create any form of project you like (can be general one) and opening the files should show the right editor with edition assistance built-it.

**Comment by rbrown3rd** [comment]
Thanks for the reply.

It might be a good idea to point out what you just told me either on the Eclipse of Github web page, so that dummies like me won't get stuck trying to use it.

That having been said, documentation would still be useful -- especially for those beginners (like me) who want to use it to create projects for development using things like Angular or just Typescript. I am sure that there is some kind of setup required for compiling and debugging an Angular- based web page (for example). Unfortunately I have no clue as to what to do to set up such a development environment. A minimal "getting started" page that describes how to set things up would be very helpful -- unless, of course, this plugin is intended to only provide editors for these different files without any test or debugging capabilities...

**Comment by mickaelistria** [comment]
Ok. Feel free to submit pull request adding some documentation where you think it makes sense.

**Comment by rbrown3rd** [comment]
Are you suggesting that I add the documentation, or that I document what documentation should be added? If the former, that would be somewhat difficult since I am, after all, a beginner who is looking for documentation on how to start/test/debug applications made using this plugin. If the latter, I will be happy to tell what is needed.

Please advise.

**Comment by mickaelistria** [comment]
> Are you suggesting that I add the documentation

Yes

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by rbrown3rd** [comment]
Interesting...

  In other words, you want me to provide documentation about something I do not know, have no way of learning about without documentation (unless, of course, you want to help me learn?), and have come here to discuss the need for documentation about?

    I am a pretty good development engineer, but I am not that good.

   I think instead I will document, somewhere in Github, what needs to be documented in order to make this plugin usable. That information I can provide...

**Comment by AObuchow** [comment]
> I think instead I will document, somewhere in Github, what needs to be documented in order to make this plugin usable. That information I can provide...

If you provide this information then I can help work on documentation. Any help is greatly appreciated.

**Comment by rbrown3rd** [comment]
Greetings

   Sorry it took so long to get back to folks here. I had a number of big changes I had to go through, including a major job change. I also had a bunch of issues that occupied my time as well.

In any event, attached is a Word document that describes what I see as necessary documentation for the WWD. Keep in mind that this documentation was written from the perspective of a beginner who needs to know how to set up, test, and deploy Typescript- based client applications.

I also include suggestions for improvement of the WWD, based on some commercial development software that I am currently using for Angular development.

[WWD.docx](https://github.com/eclipse/wildwebdeveloper/files/3998308/WWD.docx)

**Comment by mickaelistria** [comment]
Why a docx document for such discussion? Posting comments on the ticket would have been more efficient.
Also, the document does list some suggestions. The issues are used for that. Please open one new issue for each one of your suggestions.

**Comment by TomGo71** [comment]
Hi
I would like to have a documentation how to configure Chrome Debug and Firefox Debugger in Eclipse. I always get "Debug command unspecified", when starting debugger with Chrome or Firefox.
If I start with "Chromium Debugger", I the error "Unable to run Chrome / Chromium", but I have already configured "Chrome / Chromium Runtime" in Eclipse -> Preferences -> JavaScript -> Runtimes.
Kind regads,
Tom

**Comment by mickaelistria** [comment]
Please report a separate bug for this specific issue.
