### ISSUE TITLE
ES7 linter?

### ISSUE THREAD

**Issue by Mrodent** [eclipse/wildwebdeveloper#293]
I don't really know that this qualifies as an issue.

I've found this project because I'm trying to find an ES7-capable linter for Eclipse. This led me to look for  Tern... as referenced [here](https://stackoverflow.com/a/44366782/595305).  But Tern (github page) is said to be "outdated" and replaced by Wild Web Developer.

Does this project help do that? If so could you point me to setup instructions?

**Comment by mickaelistria** [comment]
To me, it's a subtask of #145 . Closing as duplicate then.
