### ISSUE TITLE
Attach firefox debugger doesn't work

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#295]
I'm trying the "Running Firefox Debugger" debug configuration, unsuccessfully so far (the configuration get stuck at initializing)

My file
```html
<html>
<head>
<script type="application/javascript">
function foo() {
    console.log("hey");
}
</script>
</head>
<body>
<button onclick="foo()">Touch me!</button>
</body>
</html>
```

Then, in CLI `firefox --start-debugger-server 9229`, in the new firefox window open the HTML file.
From the IDE, create a "Running Firefox Debugger" debug configuration for `localhost` on port 9229, Launch => attaching debugger is stuck.

**Comment by AObuchow** [comment]
Have you configured Firefox to allow remote debugging?
From [vscode-firefox-debug](https://github.com/firefox-devtools/vscode-firefox-debug#attach):

> To use attach mode, you have to launch Firefox manually from a terminal with remote debugging enabled. Note that you must first configure Firefox to allow remote debugging. To do this, open the Firefox configuration page by entering about:config in the address bar, search for **devtools.debugger.remote-enabled** and toggle it to **true**.

Side-note: this is something I should probably document somewhere (could be part of #288)

**Comment by PyvesB** [comment]
Why not add a similar message in the launch configuration tab itself? Users will be less likely to miss it.

**Comment by AObuchow** [comment]
> @AObuchow why not add a similar message in the launch configuration tab itself? Users will be less likely to miss it.

I totally agree. I'll submit a patch for this when I have a moment :)

**Comment by mickaelistria** [comment]
I have this `devtools.debugger.remote-enabled` set to true, and still don't manage to connect with the debugger as described in initial report.

**Comment by AObuchow** [comment]
Ok, so it turns out you also need `devtools.chrome.enabled` set to `True` to enable remote debugging. Otherwise, Firefox won't be listening on any ports. Let me know if that fixes it.

**Comment by mickaelistria** [comment]
Thanks Andrew. I could attach to Firefox.

**Comment by mickaelistria** [comment]
I added a note about how to configure firefox on the Launch Configuration tab.

**Comment by AObuchow** [comment]
> I added a note about how to configure firefox on the Launch Configuration tab.

Awesome, thanks for doing that Mickael.
