### ISSUE TITLE
How should ESLint dependencies be handled? 

### ISSUE THREAD

**Issue by AObuchow** [eclipse/wildwebdeveloper#303]
I'm currently working on adding ESLint support thanks to https://github.com/Quramy/typescript-eslint-language-service.

However, I don't have much experience using ESLint and it's expected workflow.

Should users be expected to have ESLint (+ it's dependencies) installed in the `node_modules` folder of the project they are working on? 

Or are they expecting ESLint (+ dependencies) to be installed already when they install Wild Web Developer?

The issue with the second workflow is that ESLint looks for it's dependencies relative to the location of it's configuration file `.eslintrc` (which are configured on a per-project-basis), so the user would have to specify the path to the Wild Web Developer bundle location in this configuration. This would also probably cause some issues with Eclipse running in Flatpak.

**Comment by AObuchow** [comment]
@angelozerr @Christopher-Chianelli @edertone @Mrodent tagging you all since you've shown some interest in ESLint support for Wild Web Developper. All input is appreciated.

**Comment by AObuchow** [comment]
Personally, I'm leaning towards user having to install ESLint and it's dependencies in their project, so that they can continue to use ESLint configuration files from existing projects that use ESLint (without having to modify the configuration).

**Comment by Christopher-Chianelli** [comment]
Typically (in my experience), `eslint` is installed in `node_modules` for each project that use it. +1 to the first approach (users be expected to have ESLint (+ it's dependencies) installed in the node_modules folder of the project they are working on).

**Comment by AObuchow** [comment]
> Typically (in my experience), `eslint` is installed in `node_modules` for each project that use it. +1 to the first approach (users be expected to have ESLint (+ it's dependencies) installed in the node_modules folder of the project they are working on).

Thanks for your input Chris! :)

**Comment by PyvesB** [comment]
First approach seems like the best to me as well. However, it would be nice to avoid starting the language server systematically, even for projects that don't use ESLint. There were some similar discussions around the Angular language server in #273.

**Comment by mickaelistria** [comment]
It's not a language server, it's a typescript language service plugin (ie it extends the behavior of tsserver), We cannot control the lifecycle of those extensions, and whether to start the extension or not inside tsserver is more the responsiblity of the extension itself.

**Comment by PyvesB** [comment]
> It's not a language server, it's a typescript language service plugin (ie it extends the behavior of tsserver), We cannot control the lifecycle of those extensions, and whether to start the extension or not inside tsserver is more the responsiblity of the extension itself.

Thanks for clarifying, I was not aware of that.

**Comment by jabby** [comment]
@AObuchow same experience for me. All projects with eslint have the eslint in node_modules. 

About extention. If we don't have any projetcs in workspace with corresponding dependency (eslint here and angular for #276) maybe we should not load the plugin.

**Comment by AObuchow** [comment]
> About extention. If we don't have any projetcs in workspace with corresponding dependency (eslint here and angular for #276) maybe we should not load the plugin.

That's a good point. Although I'm not sure if we can load the plugin after the tsserver has been started (for the case where a user creates/imports a new project that uses ESLint). If typescript language service plugins can be dynamically loaded, then this is something we should definetly consider.

**Comment by AObuchow** [comment]
Closing this issue as ESLint support in Wild Web Developer is now merged.
