### ISSUE TITLE
Launch called from the wrong thread?

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#309]
Hi there!

I noticed that the following line of code fires the launch asynchronously:
https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/AbstractDebugAdapterLaunchShortcut.java#L157

However, the Javadocs for `DebugUITools.launch` state the following: 

> This method must be called in the UI thread.

I'm unsure what the consequences of calling this method from a different thread are, but this is probably something worth looking into.

**Comment by AObuchow** [comment]
Good catch! 
> I'm unsure what the consequences of calling this method from a different thread are, but this is probably something worth looking into.

I'm also uncertain of the consequences of calling this method asynchronously, but it should probably be fixed for peace of mind.
Feel free to submit a PR to call it from the UI thread (or I'll get around to it when I have a moment, sometime soon).

**Comment by PyvesB** [comment]
> Feel free to submit a PR to call it from the UI thread

Done!
