### ISSUE TITLE
Option to download node.js via the UI

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#311]
AFAICS Wild Webdeveloper requires node.js to work fine. Could the tooling offer to download node.js if it is not installed?

**Comment by PyvesB** [comment]
Sounds like a good idea, my [Ruby plugin](https://github.com/PyvesB/eclipse-solargraph) does that as well when the Solargraph language server is not yet installed.

**Comment by akurtakov** [comment]
Does solargraph install ruby if not available too? Cause I'm afraid this is what we speak about here.

**Comment by PyvesB** [comment]
Ah no, you're right, Ruby is assumed to be installed!

**Comment by mickaelistria** [comment]
I think working on #23 would be more profitable.

**Comment by akurtakov** [comment]
Linux users would better start using Eclipse from flathub https://flathub.org/apps/details/org.eclipse.Java - there we already make sure that node is preinstalled.

**Comment by vogella** [comment]
@mickaelistria sounds reasonable. Please mark this one as dup of #23

**Comment by mickaelistria** [comment]
> Please mark this one as dup of #23

Thanks, done.
