### ISSUE TITLE
CSS color code mining depends on node.js?

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#312]
@enbewe reported that the CSS color picker does not work for him under Windows without a node.js installation.

This is how is looks like for me:

![image](https://user-images.githubusercontent.com/139910/70134145-c03f6e80-1687-11ea-9fa1-04f60491a60a.png)

Depends the code mining annotation for colors on node.js or is this a window issue?

@angelozerr

**Comment by eNBeWe** [comment]
![grafik](https://user-images.githubusercontent.com/3796429/70137079-79ed0e00-168d-11ea-98f5-ed53df4bcca6.png)

This is how it looks without node.js on windows

**Comment by mickaelistria** [comment]
All the CSS rich edition features (color preview, completion, validation and so on) use the language server that needs node.js to start. So yes, nodejs is required to CSS color code mining.
