### ISSUE TITLE
[YAML] Move yaml support in a new project org.eclipse.wildwebdeveloper.yaml

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#317]
As YAML supports defines custom classes like preference page, I think we should have a custom project `org.eclipse.wildwebdeveloper.yaml` for that like we have for XML.

**Comment by mickaelistria** [comment]
In general, splitting the nodejs-based language servers into different projects would result in duplicated node libraries and bigger download size.
I'm not yet seeing what added-value we can offer with separate bundles that we couldn't offer with a single bundle. As long as there is no clear value, we'll avoid this relatively big effort.

**Comment by angelozerr** [comment]
Ok I understand, thanks for this information @mickaelistria

**Comment by mickaelistria** [comment]
I'm closing it as there is no urge for this, and there are some identified drawback in term of bundle size if we split the Language servers.
