### ISSUE TITLE
Dozens of nodejs dialogs pop of although nodejs is installed

### ISSUE THREAD

**Issue by ctron** [eclipse/wildwebdeveloper#322]
From: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559110

When starting up a workspace with 2019-12, which worked fine with 2019-09, dozens of "Node JS" dialog boxes pop up, although nodejs is installed (see screenshot).

![Selection_645](https://user-images.githubusercontent.com/202474/72261552-59618d80-3615-11ea-81ba-9b2d55cebd86.png)

**Comment by mickaelistria** [comment]
Are you using Flatpak? Is your Eclipse IDE started with the same PATH as you terminal?
Can you please check in Help > About > Installation Details > Configuration whether your PATH variable seems complete?

**Comment by ctron** [comment]
No, I was using the Eclipe Installer. No flatpak involved. I start it using a double-click from Nautilus.

My path is weird, but it matches:

---

HOME=/home/jreimann
PATH=/usr/lib64/qt-3.3/bin:/home/jreimann/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin://home/jreimann/.local/bin:/home/jreimann/bin:**/home/jreimann/Downloads/nodejs/current/bin**:/home/jreimann/node_modules/.bin:/home/jreimann/go/bin:/home/jreimann/Downloads/go/current/bin:/home/jreimann/gems/bin:/home/jreimann/.local/bin:/home/jreimann/bin:/home/jreimann/.cargo/bin

---

~~~
$ echo $HOME
/home/jreimann
$ which node
~/Downloads/nodejs/current/bin/node
~~~

**Comment by mickaelistria** [comment]
In the code, it looks like `/home/jreimann/Downloads/nodejs/current/bin/node -v` is invoked to get the version. Can you please try it? Maybe this `-v` became deprecated and `--version` must be used instead?

**Comment by ctron** [comment]
~~~
$ /home/jreimann/Downloads/nodejs/current/bin/node -v
v10.14.2
~~~

Whatever the root cause of "not detecting is", the dialog is super annoying. And there is no way of checking of box like "don't show this error again".

I ended up uninstalling the wild wild developer, as it basically made the IDE unusable.

**Comment by mickaelistria** [comment]
I've submitted https://github.com/eclipse/wildwebdeveloper/pull/323 to at least have the popup only once per IDE session.

**Comment by mickaelistria** [comment]
@ctron we're planning a release very soon, and it'd be great if we can have this strange bug fixed. Have you tried http://download.eclipse.org/wildwebdeveloper/snapshots ? Does it reproduce the issue? If the issue is still here, I'll try to add more logs to get more clues about cause/fix.

**Comment by akurtakov** [comment]
@ctron IMHO https://flathub.org/apps/details/org.eclipse.Java will provide what you need as it ensures that decent jvm/node/gtk is what your eclipse runs with.

**Comment by mickaelistria** [comment]
Actually, I checked and there might already be some information in the error log when the popup is shown. Can you please check?

**Comment by jabby** [comment]
According to nodejs website, versions 8 and 9 of nodejs runtime are not really downloaded this days. 
I suggest to change `SUPPORT_NODEJS_MAJOR_VERSIONS` and remove 8 and 9 versions of nodejs runtime.

I also checked on flatpak packaging it will not affect users as the version of nodejs is 10.

**Comment by cdietrich** [comment]
is there a shipment date for this issue?

**Comment by mickaelistria** [comment]
This has been fixed since 0.8.1 release.

**Comment by cdietrich** [comment]
ahh ok. looks like this release was never contributed to simrel milestones. so i will wait for RC1 to be available

**Comment by mickaelistria** [comment]
Those release are from January, so after SimRel.
Wild Web Developer doesn't follow the SimRel schedule; it joins SimRel (to be part of EPP), but releases whenever there is enough substance and doesn't do RCs and so on.
If you want the latest release of Wild Web Developer, just use the https://download.eclipse.org/wildwebdeveloper/releases/latest p2 repo and you'll get updates whenever they happen, independently of SimRel schedule.

**Comment by cdietrich** [comment]
I mean the simrel update site /2020-03 which we use in oomph to get the current milestone. So I simply wait until it appears there and avoid opening html files in eclipse
