### ISSUE TITLE
Autocompletion fails with CancellationException

### ISSUE THREAD

**Issue by Crischan** [eclipse/wildwebdeveloper#324]
Hi,
I am using Eclipse IDE 2019-09 on Ubuntu 18.04 with WildWebDeveloper, which was installed using the 'Drag to install' option in the Marketplace.

While editing any .ts or .html file (did not test others yet) in the Generic Text Editor, the autocompletion fails with the an java.util.concurrent.CancellationException.

![Bildschirmfoto vom 2020-01-17 11-48-57](https://user-images.githubusercontent.com/799977/72607029-1444a080-3920-11ea-952a-75a38b0ded3c.png)

Also, when right-clicking into a file, it takes about 6 seconds to open the context menu.

Am I missing something that has to be installed, or what might be wrong here?

Regards, Christian

**Comment by mickaelistria** [comment]
Do you have `node` available in your PATH? Is it a recent enough version?

**Comment by Crischan** [comment]
I just updated from node 9 to 13, and now it works.

Thank you very much!

**Comment by mickaelistria** [comment]
@jabby: it seems like node 9 doesn't work very well for recent language servers. What do you think is the minimal popular node version to put in the version check popup? Are most people using node 10?

**Comment by jabby** [comment]
According to nodejs website, versions 8 and 9 of nodejs runtime are not really downloaded this days.
I suggest to change SUPPORT_NODEJS_MAJOR_VERSIONS and remove 8 and 9 versions of nodejs runtime.

I also checked on flatpak packaging it will not affect users as the version of nodejs is 10.

**Comment by mickaelistria** [comment]
Thanks Gautier. Are you available to make the PR?

**Comment by jabby** [comment]
Yes I am.

**Comment by jabby** [comment]
I forget to share the link where I found the information. 
https://nodejs.org/metrics/
