### ISSUE TITLE
JSON LS doesn't work

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#327]
I tried latest release of Wild Web Developer (0.8.1) and cannot get the JSON Language Server to return proper values..

**Comment by AObuchow** [comment]
@mickaelistria is the JSON LS even starting? I remember they added a new requirement to the initialization request in the latest version of the JSON LS. If it starts however, then this is another issue.

**Comment by mickaelistria** [comment]
Yes, it's starting and logging stuff. But it's usually returning nothing, and sometimes I see a JavaScript error message (missing property 'create' of undefined).

**Comment by mickaelistria** [comment]
Strange thing is that the test did pass a few days ago...

**Comment by mickaelistria** [comment]
Actually, I could see it working in another workspace (while I saw it failing in Flatpak). It might be a node version issue.

**Comment by mickaelistria** [comment]
It might "just" be some new necessary option for diagnostics to be sent. When schema is set, I can get hover and completion.

**Comment by mickaelistria** [comment]
I was actually looking at the wrong file pointer in this modular projets. With the right file, all seems file.
