### ISSUE TITLE
Is it possible to use default eclipse keyboard shortcuts?

### ISSUE THREAD

**Issue by qfz** [eclipse/wildwebdeveloper#336]
WWD seems to mimic vscode's keyboard shortcuts (e.g.F2 for rename). I have a java project with typescript files in it. It gets frustrating to have to context switch between keyboard shortcuts.

Is there a way to configure WWD to use eclispe java's keyboard shortcuts?

**Comment by mickaelistria** [comment]
F2 for rename has been an Eclipse IDE shortcut forever, way before VSCode was even imagined; and Wild Web Developer doesn't specify addition shorcuts.
You can change shortcuts in Window > Preferences > General > Keys.

I don't think the is anything to fix on Wild Web Developer here.

**Comment by PyvesB** [comment]
Related discussion about using both shortcuts (given that F2 doesn't work properly on some operating systems): https://bugs.eclipse.org/bugs/show_bug.cgi?id=538244
