### ISSUE TITLE
ESLint support doesn't seem to work for JS files (works for TS)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#338]
ESLint support doesn't seem to work for JS files (works for TS)

**Comment by njake** [comment]
After adding "checkJs": true to tsconfig.json errors shows in eclipse, but rules not working at all from .eslintrc file.

**Comment by AObuchow** [comment]
@njake what OS and Node.js version are you using?

**Comment by njake** [comment]
> 
> 
> @njake what OS and Node.js version are you using?

Windows 10 64 bit
Node v12.18.2
Eclipse 2020-06

When writing this message i try to reinstall plugin to eclipse using this 
URL http://download.eclipse.org/wildwebdeveloper/snapshots and it seems to work now.
Previous install was from URL http://download.eclipse.org/wildwebdeveloper/releases/latest/

So snapshot version is working one for me. All depended npm packages are on latest versions too!

**Comment by AObuchow** [comment]
@njake awesome to hear! Thanks for the update. Can we close this issue now? CC: @mickaelistria

**Comment by mickaelistria** [comment]
This has been fixed with f2e66aa3cb4653f5ad55293e31942a9a18762323

**Comment by vito-detullio-finconsgroup** [comment]
is the fix in a release or do I still need a snapshot?
