### ISSUE TITLE
Ctrl+1 on JS file crashes IDE

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#339]
Often, using Ctrl+1 when editing a JS file will crash IDE.
It looks like an infinite loop is running.

**Comment by mickaelistria** [comment]
@AObuchow That is probably related to the implementation of Code Actions in LSP4E.

**Comment by AObuchow** [comment]
Thanks for making me aware of this, I'll have to debug the implementation of code actions in LSP4E to investigate further. Do you happen to have an exemplary .js project that I can use to reproduce the crash?

**Comment by mickaelistria** [comment]
This is now fixed in LSP4E
