### ISSUE TITLE
Add content assist for CSS classes/ids in HTML file

### ISSUE THREAD

**Issue by humphreygao** [eclipse/wildwebdeveloper#342]
希望WWD能够实现如下三个功能：
- 在HTML文件中，对CSS中定义的class和id的名称进行代码提示。当然这些class和id的来源有三种：
    + 本HTML引入的本地CSS文件
    + `<style>`标签中定义的样式
    + 通过`<link>`标签引入的外部CDN资源
- 在HTML的`<script>`标签中，当按下井号(#)或者句号(.)时，能够对CSS中的class和id的名称进行代码提示。
- Ctrl+左键能够从HTML中的class或者id属性跳转到CSS文件的对应位置。

When editing HTML, I want WWD to provide content assist for class/id names defined in CSS included in the project or loaded from a URL(CDN).

If inside a script block on an HTML page, it would be nice to perform CSS classes/ids auto completion after pressing "#" or "."

The last feature I want WWD to support is quick navigation to CSS from HTML files based on class/id.

**Comment by mickaelistria** [comment]
The HTML language server is coming from VSCode. I've opened https://github.com/microsoft/vscode/issues/90343 where the fix needs to happen. Then, when fixed on VSCode side, just upgrading the language servers should be enough.

**Comment by mickaelistria** [comment]
This is actually a dup of #8
