### ISSUE TITLE
Invalid id for NodeAttachDebugDelegate

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/wildwebdeveloper#343]
The ID is valid as an internal constant as `org.eclipse.wildwebdeveloper.launchConfiguration.nodeAttach` (see https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/debug/node/NodeAttachDebugDelegate.java#L40)
However, the plugin.xml uses `org.eclipse.wildwebdeveloper.launchConfiguration.nodeDebugAttach` (see https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/plugin.xml#L483)
Also for consumers wanted to create such config without UI, would be fine to have it as public

**Comment by mickaelistria** [comment]
Thanks @jeffmaury , we'll look at it ASAP.
However, if you can submit a pull request before we get started coding it, that would obviously be welcome ;)

> would be fine to have it as public

At the moment, I think it's too early to publish those ids as API (nothing in Wild Web Developer is API).
But it's something we can consider for a future release (like around June), if we see people start consuming the launch configurations, we can consider just exposing some symbols.
Please open a separate issue to discuss that.
