### ISSUE TITLE
Allow launch configuration to be consumed as APIs

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/wildwebdeveloper#344]
At JBoss Tools, we've starting integrating WildWebDev and mainly the Node remote debugger. In order to do that, we need to create the launch configuration through the debug API. We are missing public constants to do that mainly the launch configuration type ID plus some configuration values (address and port). See #343

**Comment by mickaelistria** [comment]
Exposing constant is relatively easy and low risk, and the request seems to have a good value to justify the effort.
We'll investigate that for a future release around June.

**Comment by mickaelistria** [comment]
Closing by lack of interest (no news, no PR)
