### ISSUE TITLE
Allow localRoot and remoteRoot to be specified through UI for Running NodeJS application

### ISSUE THREAD

**Issue by jeffmaury** [eclipse/wildwebdeveloper#345]
When connecting to a remote NodeJS application (ex container), in order for breakpoints to be correctly managed, user needs to specify an addition JSON settings with the fields `localRoot` and `remoteRoot`. It would be convenient if those fields could be specified through UI

**Comment by mickaelistria** [comment]
Thanks for this proposal.
I'll try to implement it this week, so it will be part of upcoming release.
1 question: do you plan to release JBoss Tools with Wild Web Developer soon? Sooner than we release Wild Web Developer? If so, I can try an extra effort to "import" the JSON settings you may already used as explicit fields to ease migration of existing launch configurations. However, if Wild Web Developer releases before JBoss Tools or you don't think this "migration" it's worth the specific effort, I can gladly skip it.

**Comment by jeffmaury** [comment]
I don't need this for JBoss Tools as we are creating the launch config through the Debug API. Otherwise code freeze for JBoss Tools TP is on Feb 25th

**Comment by mickaelistria** [comment]
So we did it: https://github.com/eclipse/wildwebdeveloper/blob/master/RELEASE_NOTES.md#easily-define-root-mapping-for-remote-nodejs-debugger . We'll hopefully release Wild Web Developer next week (only 1 CQ is pending).
