### ISSUE TITLE
Provide XML/XSL language support

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#35]
Provide XML language support with :

 * syntax coloration for XML, XSL
 * language configuration for XML, XSL

The XML Language Server doesn't exists for the moment https://github.com/Microsoft/vscode/issues/1440

That's shame -(

**Comment by angelozerr** [comment]
If you wish I can do a PR for that. I can create a new project `org.eclipse.bluesky.xml` or add xml support inside existing  `org.eclipse.bluesky` project.

@mickaelistria tell me what you prefer.

**Comment by mickaelistria** [comment]
Is there a language server available for XML already?

**Comment by angelozerr** [comment]
> Is there a language server available for XML already?

No, perhaps  https://github.com/Microsoft/vscode/issues/1440#issuecomment-281164002 could work?

But my PR is for syntax coloration + language configuration (auto close) like VSCode provides. I think basic XML/XSL support is important for BlueSky which is defined as "Web dev in Eclipse IDE".

**Comment by mickaelistria** [comment]
Is the result better in term of features and UX that what Eclipse XML editor already offers?

**Comment by angelozerr** [comment]
> Is the result better in term of features and UX that what Eclipse XML editor already offers?

No, but it's like JSON support. IMHO "Web dev in Eclipse IDE" should provide XML support if you qualify your plugin as "Web".

**Comment by mickaelistria** [comment]
> No, but it's like JSON support.
>
JSon support in VSCode LS has json schema support; which IIRC is missing
from Eclipse WTP JSon Editor.


> IMHO "Web dev in Eclipse IDE" should provide XML support if you qualify
> your plugin as "Web".
>

Ok, we could consider including the WTP XML feature in the BlueSky feature
for completeness.

**Comment by angelozerr** [comment]
> JSon support in VSCode LS has json schema support; which IIRC is missing from Eclipse WTP JSon Editor.

No Eclipse WTP JSON Editor provides JSON Schema support (completion is working, but not validation if I remember).

> Ok, we could consider including the WTP XML feature in the BlueSky feature for completeness.

I don't like this idea. Eclipse WTP XML Editor will host a lot of other plugins. I would like to have a clean XML Editor where "looks and feels" looks for other editor than HTML, JavaScript, etc

It's one of reason why I would like to migrate to bluesky for my "Angular Eclipse" project. Having editors where  "looks and feels" are the same.

**Comment by mickaelistria** [comment]
I'm not convinced that these days, it's worth spending so much effort in
creating a new XML editor that would ultimately be weaker than the existing
one in WTP.
Some of WTP editors are weak and are worth being replaced. For the XML one,
I'm not sure achieving the same level of features is achievable with a TM +
language server approach.
BlueSky could welcome a new XML editor when we at least have the promise it
would be more valuable than WTP's one. At the moment, I'm very skeptical.
Prove me wrong ;)

**Comment by angelozerr** [comment]
> Prove me wrong ;)

That's hard today because it doesn't exists XML Language Server. 

My idea is to provide a basic XML Editor (like VSCode does) with syntax coloration and auto close. Once an XML Editor will exists we could consume it.

Provide a basic XML editor with language-configuration and textmate takes me 10 minutes, so I find it's shame that bluesky doesn't provide it.

**Comment by mickaelistria** [comment]
I think we can come up with a good trade-off: as part of the generic editor initiative, some validation and IAutoIndentStrategies and Syntax Highlighter were created for XML-based files (.project. .target). Those extensions are for the vast majority XML-generic. So instead of a language server, you could work on Platform side (directly) to extract out the XML-specific extensions into a org.eclipse.ui.genericeditor.xml plugin. This XML-based generic editor would be part of Platform directly. Me, @scela and @lucasbullen would really support this work and you'd get prompt review and early merge ASAP.

**Comment by mickaelistria** [comment]
Not that the proposal above doesn't include a Language Server for XML for Eclipse-specific XML extensions o generic editor. I think at the moment, it's really what would provide the best effort/value ratio, and not only for bluesky but for the Platform as a whole.

**Comment by angelozerr** [comment]
> Me, @scela and @LucasBullen would really support this work and you'd get prompt review and early merge ASAP.

Cool:) But to be honnest with you, I'm very busy with other toipcs like language configuration (match bracket, etc), CSS color,  and editorconfig (a topic that I think it's very important for eclipse).

**Comment by angelozerr** [comment]
@mickaelistria I promise you, it's the last time that I try to convince you to provide XML/XSL support with language configuration and syntax color by using tm4e. With 4 files we will have thoses very helpful supports (matching bracket will come too).

If you don't want to support XML/XSL with bluesky, you can close this issue.

**Comment by mickaelistria** [comment]
The question remains: is it any better than the WTP/XML editors in term of
value delivered to users?

**Comment by angelozerr** [comment]
> The question remains: is it any better than the WTP/XML editors in term of
value delivered to users?

For the moment, no, but in the future when language server will be available, I think yes. The thing that I like with tm4e is that we have the same syntax coloration for any languages (HTML, JSON, CSS and I hope with this issue XML/XSL)

**Comment by mickaelistria** [comment]
Ok, so let's first create the additional value, and then we'll ship this to
user. In the meantime, as long as the WTP XML editor is better, it's the
one we should include if we want XML support.Then we can change later on
when another XML editor gets better.

**Comment by angelozerr** [comment]
Thanks @mickaelistria to have taken time to answer me. Hope XML Language Server will come soon.

**Comment by angelozerr** [comment]
@mickaelistria an another pros to support XML/XSL editor with GenericEditor is that we will benefit to customize the editor with .editorconfig with https://github.com/angelozerr/ec4e

For the moment only `indent_style `and `indent_size `are supported  I'm implementing trim trailling and other properties. In other words it should be cool to have XML/XSL support to benefit with those features.

**Comment by angelozerr** [comment]
@mickaelistria are you OK that I create a PR to support XML support and consume https://github.com/microclimate-devops/xml-language-server ? Today it supports only validation, but if you are OK, I think I could contribute to xml-language-server for other features.

**Comment by mickaelistria** [comment]
I still have the impression that including a reference to the WTP XML editor for XML would provide more value to users than building on top of this LS at the moment. We could consider adding a XML LS in BlueSky when the value is superior to the one WTP XML editor, but it doesn't really make sense before that.

**Comment by apupier** [comment]
Given the level of feature of WTP XML editor and that the current state of the current LSP XML level, I would say that the best would be to create a new LS for XML which is embedding WTP xml editor, it will also allows to provide good Maven pom.xml support.
Not sure how hard it will be.

**Comment by angelozerr** [comment]
> I still have the impression that including a reference to the WTP XML editor for XML would provide more value to users than building on top of this LS at the moment.

WTP XML has a lot of dependencies, and I would like to consume tm4e for syntax coloration for having the same look and feel of other grammar (json, css, html, etc)

> We could consider adding a XML LS in BlueSky when the value is superior to the one WTP XML editor, but it doesn't really make sense before that.

I understand, I have created an issue at https://github.com/microclimate-devops/xml-language-server/issues/9 to provide advanced features like completion, symbol provider, etc

> Given the level of feature of WTP XML editor and that the current state of the current LSP XML level, I would say that the best would be to create a new LS for XML which is embedding WTP xml editor, it will also allows to provide good Maven pom.xml support.
Not sure how hard it will be.

I have started to study this solution, but it's very hard (don't remember why I have given this solution). The benefit to use WTP is that the DOMDocument is managed with incremental mean.

My wish is to have a clean XML Editor which works like other grammar.

**Comment by angelozerr** [comment]
@mickaelistria as you know, it exists today 3 XML Language Server work in process:

 * https://github.com/gorkem/xml-ls
 * https://github.com/microclimate-devops/xml-language-server
 * https://github.com/angelozerr/xml-languageserver

In my case, I'm working on https://github.com/angelozerr/xml-languageserver and to test it, I have added XML support in BlueSky. Can I just push my work only with :

 * XML content type
 * XML syntax coloration with tm4e
 * XML language configuration

**Comment by angelozerr** [comment]
> I'm still unsure that XML fits so well in BlueSky user story. 

IMHO I think XML support should be hosted in BlueSky, because:

 * "Simple and productive Web Development Tools in the Eclipse IDE" needs XML support like web.xml, xsl, etc
 * XML is used like config file like JSON, YAML, etc. BlueSky provides JSON, YAML, so why XML is not supported

> It would IMO make more sense to have a separate repo and marketplace entry for this.

Ok I have created this support at https://github.com/angelozerr/lsp4e-xml but I hope one day I will convince you to host it in BlueSky

@apupier @jabby @PhaserEditor2D I'm curious to know your opinion about providing XML/XSL support in BlueSky?

**Comment by mickaelistria** [comment]
The idea behind bluesky is mostly to have an offer dedicated to front-end web development. Not sure XML is part of the typical front-end stack these days and that many node.js developers do use it.
Is there XML support in webstorm?

**Comment by apupier** [comment]
> @apupier I'm curious to know your opinion about providing XML/XSL support in BlueSky?

I would give same answer than Mickael. If Web developers are using xml, go for it, otherwise don't include it.
As @angelozerr pointed that it is provided in Webstorm I guess that it is used by web developers then I would say that it would be better to include xml LS in Bluesky.

**Comment by mickaelistria** [comment]
mmhhh...
Ok Angelo, you won ;)
Please bring a XML LS support in bluesky whenever you want. But since we
plan to move BlueSky to Eclipse Fdn soon, please do so only if the LS is
licence-compatible with EPLv2.

**Comment by mickaelistria** [comment]
Implemented bt @yanxi0830 . Thanks Xi!
Let's open new tickets for further issues.
