### ISSUE TITLE
[request for feature] Quick way to run npm scripts

### ISSUE THREAD

**Issue by tYYGH** [eclipse/wildwebdeveloper#350]
In _Typescript IDE_, `package.json` was presented as a folder in the tree-view, and when you opened it, it would show one line per script defined in the file (`start`, `serve`, `mock-server`… depending on what scripts are defined in `package.json`).

For example, if I unfolded `package.json` and right-clicked on the `mock-server` child-entry, then clicked on “Run as NPM script”, it would launch the command `npm run-script mock-server` in the directory containing `package.json`.

Would it be possible to have this feature in WWD?

(For reference: https://github.com/angelozerr/typescript.java/issues/248)

**Comment by mickaelistria** [comment]
I don't think we'll implement such "drill-down" on short term. However, upcoming release already has features to speed up and ease usage of npm: https://github.com/eclipse/wildwebdeveloper/blob/master/RELEASE_NOTES.md#npm-launch-shortcut

**Comment by angelozerr** [comment]
> In Typescript IDE, package.json was presented as a folder in the tree-view

It's a feature coming from WTP, not from TypeScript IDE.

**Comment by tYYGH** [comment]
Ah, OK. Thanks for the tip.

**Comment by AObuchow** [comment]
Although this probably won't get implemented any time soon (and it'd be better for a language server to deal with this), I found out `npm run` will[ list out available scripts](https://github.com/npm/npm/pull/5184) from a package.json, which could then be parsed.

The output ressembles the following:
```
Scripts available in webpack-demo1 via `npm run-script`:
  dev
    webpack-dev-server --open
  build
    webpack -p
```

**Comment by mickaelistria** [comment]
The NPM Launch shortcut seems good enough for this case.
