### ISSUE TITLE
Error Message, when Starting Debugging with Chrome or Firefox

### ISSUE THREAD

**Issue by TomGo71** [eclipse/wildwebdeveloper#358]
Starting a debug session with Chrome or Firefox, an error message appears with "Debug command unspecified".
Starting a debug session using "Chromium Debugger", the error "Unable to run Chrome / Chromium" appears, although "Chrome / Chromium Runtime" is configured in Eclipse -> Preferences -> JavaScript -> Runtimes.

It should be fixed, if it's a bug.
It should be documented, if the configuration would be wrong.

**Comment by mickaelistria** [comment]
Can you please go into details of how you start the debug session with Firefox for instance?

> Starting a debug session using "Chromium Debugger", the error "Unable to run Chrome / Chromium" appears, although "Chrome / Chromium Runtime" is configured in Eclipse -> Preferences -> JavaScript -> Runtimes.

Those entries are not coming from Wild Web Developer.

**Comment by TomGo71** [comment]
I press the "Bug"-Button and open the Debug Configurations.
The Chrome and Firefox entries on the left pane are new since the installation of WildWebDevelopper (see attached Screenshot).
![Eclipse_Debug](https://user-images.githubusercontent.com/61194685/75186857-15e85c00-5749-11ea-9a4f-cca0c76e07a9.jpg)
When I press the Debug Button, a message box with "Debug command unspecified" appears.

**Comment by AObuchow** [comment]
@TomGo71 Do you have Node.JS installed? Looking at the [implementation](https://git.eclipse.org/r/plugins/gitiles/lsp4e/lsp4e/+/b8dcd9bfa9eaa0815168b0e3ea0719671d6760e4/org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java#80) and through my own testing, the debug command should be the path to the Node executable (on Linux it's something like `/usr/bin/node`). In your case, the debug command is being set to null, probably because Node.JS cannot be located on your machine.

**Comment by TomGo71** [comment]
Hi

No, not yet !
I will try that as soon as possible and then testing again.

Tom


Am 24.02.2020 um 21:18 schrieb Andrew O.:

**Comment by AObuchow** [comment]
> Hi No, not yet ! I will try that as soon as possible and then testing again.

Sounds good! Just a FYI, Node.JS is required for almost all functionality provided by Wild Web Developer, so you're certainly going to need it :) 

Keep us updated!

**Comment by mickaelistria** [comment]
There have been no news for 2 weeks and this is working locally for most users.
So I'm closing this ticket.
Feel free to reopen with more information if this is still happening after processing the various suggestions made by @AObuchow
