### ISSUE TITLE
Provide custom register of JSON Schema associations

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#36]
Today JSON Schema associations is hard coded https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/json/JSonLanguageServer.java#L66

So it's not possible to contribute with custom JSON Schema (from user preferences or plugins). It should be better to provide the capability to regsiter JSON Schema association:

 * with plugin via extension point.
 * with user preferences.

To do that we must extract the JSON languag in a new plugin `org.eclipse.bluesky.json` and provide a JSON Schema extension point like this:

```xml
   <extension
         point="org.eclipse.bluesky.json.schemaAssociations">
      <schemaAssociation
            fileMatch="package.json",
            url="http://json.schemastore.org/package">
      </schemaAssociation>
   </extension>
```

`url` can be a file.

Like https://code.visualstudio.com/docs/languages/json#_mapping-in-the-user-settings

**Comment by angelozerr** [comment]
@mickaelistria I can do a PR if you wish and if you are OK that I extract JSON language in a new plugin.

**Comment by mickaelistria** [comment]
Sure!

**Comment by mickaelistria** [comment]
I believe it would be much more interesting to place this registry in a sttandalone bundle in WTP-JSON and to consume this common registry in BlueSky. Factorization and common work always pay back.

**Comment by angelozerr** [comment]
If we do that, it requires installation of WTP JSON and you will have 2 JSON Editors. IMHO I think bluesky should not depend on WTP.

**Comment by mickaelistria** [comment]
I said "standalone bundle" as a new bundle not requiring WTP JSon Editor nor other layers of WTP. If WTP is open to host such a bundle, it's where it should be.
We cannot work on a totally separate stack if there is no value for it. Placing some stuff in WTP is highly profitable for BlueSky (as there would be shared maintenance) and WTP.

**Comment by angelozerr** [comment]
> I said "standalone bundle" as a new bundle not requiring WTP JSon Editor nor other layers of WTP.

Sorry I had not understood. My fear is that we will wait for a long time to have this plugin. 

Developping this extension point is easy, but I agree with you if WTP could provides that it should cool (I  think about UI preferences)

To be honnest with you, I'm a little discouraged with WTP which takes a long time to accept PR. Do like you think. Me I would prefer developping the extension point which is quick.

**Comment by mickaelistria** [comment]
> Sorry I had not understood. My fear is that we will wait for a long time
to have this plugin.
> To be honnest with you, I'm a little discouraged with WTP which takes a
long time to accept PR. Do like you think. Me I would prefer developping
the extension point which is quick.

Implementing it in WTP takes as much time as implementing it in aCute. Once
the patch is submitted, I'm pretty sure some committers will review it
promptly and merge it as soon as it's good enough and that it could be
consumed as part of next milestone of WebTools.
There are parts of WTP that are reviewed quickly, JSON is one of them.

**Comment by mickaelistria** [comment]
Some work is being done directly on the LS side: https://github.com/Microsoft/vscode/issues/26289
It doesn't allow custom schemas association, but it seems more valuable as use who have specific schema that are not in the schemastore should add it in the .json file for portability across tools.
If we implement this user registry, we'll basically add responsibility to user (add usage complexity) and encourage a bad practice which is to *not* specify the schema URL in the file for non-declared file/schema association.
I'm closing this one as I'd rather not see Wild Web Developer enable users with such bad practices.
