### ISSUE TITLE
Add support for TypeScript 3.8

### ISSUE THREAD

**Issue by akurtakov** [eclipse/wildwebdeveloper#361]
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/

**Comment by mickaelistria** [comment]
That might be relatively easy, just a matter of upgrading the typescript dependency and the grammar.

**Comment by mickaelistria** [comment]
We'd first need to check whether any change is required. IIRC the typescript language server can resolve and use the newer version of typescript/tsserver declared used by the project.

**Comment by mickaelistria** [comment]
Done with an example screenshot in the RELEASE_NOTES and tweeted about it.
