### ISSUE TITLE
JSON Format support

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#37]
The JSON language server provides the capability to support format, but it requires before fix of LP4E https://bugs.eclipse.org/bugs/show_bug.cgi?id=510275

**Comment by mickaelistria** [comment]
As mentioned on the Eclipse bug, I believe the fix(es) should rather be in
the language server directly.

**Comment by mickaelistria** [comment]
Can't formatter be enabled with initializationOptions?

**Comment by mickaelistria** [comment]
Formatting JSON is working with current release.
