### ISSUE TITLE
Add debug flag to start XML Language Server in debug mode

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#373]
To ease the development and debugging of XML language server and related extension when integrated in the Eclipse IDE, we should offer a debug option to turn on debugger on some specific port.

**Comment by AObuchow** [comment]
Agreed.
Do you think this should just be a preference or some commandline flag that can be set when launching Eclipse?

**Comment by angelozerr** [comment]
@mickaelistria me I can debug XML Language Server and extension. To do that, I'm using LSP4E launch capability.

**Comment by mickaelistria** [comment]
I've a patch working it that I'm going to submit as PR ASAP. I'm using a system property, simple and good enough.

**Comment by angelozerr** [comment]
See my explanation at https://github.com/eclipse/wildwebdeveloper/issues/266#issuecomment-535386454

**Comment by mickaelistria** [comment]
Launch is overkill and tests a different integration than the one we're targeting https://git.eclipse.org/r/#/c/152751/ . Adding a system property is trivial and allows to test much more easily an integration that's much closer to what we'll ship to end-users.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/wildwebdeveloper/pull/374

**Comment by mickaelistria** [comment]
Fixed with #374.
