### ISSUE TITLE
In outline view,How to prevent the expanded element(like js class)  to be collapsed automatically

### ISSUE THREAD

**Issue by AlexLuya** [eclipse/wildwebdeveloper#377]
My Installation:
```
Ubuntu 18.04 64bit + Unity Desktop(not gnome)
Eclipse 2019-12 
WWD:0.8.3.202003111701
Oracle JDK 12
```
After expanding element like left,then click an js opened by WWD,element will be collapsed automaticaly like right like blow,How to prevent this auto-collapsing?

![Workspace 1_937](https://user-images.githubusercontent.com/303353/76582844-6c5be580-6512-11ea-9da6-d14b2af507e5.png)

**Comment by mickaelistria** [comment]
Can you please report it with exact steps to reproduce to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=lsp4e ?

**Comment by AlexLuya** [comment]
> Can you please report it with exact steps to reproduce to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=lsp4e ?
@mickaelistria 
Others like PyDev,PDE haven't this problem,so I think this should be a WWD only problem

**Comment by mickaelistria** [comment]
PyDev and PDE don't use LSP4E framework. I think this problem also affects other LSP4E-based plugins (Corroosion, ShellWax, Solargraph Ruby...), so please open the bug ;)

**Comment by mickaelistria** [comment]
Issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=561533 is fixed, installing LSP4E from https://download.eclipse.org/lsp4e/snapshots/ should fix stuff.
I'm leaving the ticket open until we have a build of Wild Web Developer that does include the newer LSP4E.

**Comment by AlexLuya** [comment]
@mickaelistria ,Thanks,after installing LSP4E snapshot,the problem gone

**Comment by AlexLuya** [comment]
@mickaelistria,can it make js class be expanded(unfolded) by default,or get somewhere to set it folded/unfolded by default.

**Comment by mickaelistria** [comment]
Please request this to LSP4E: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=lsp4e
