### ISSUE TITLE
HTML highlighting in JS Template Literals 

### ISSUE THREAD

**Issue by AugustNagro** [eclipse/wildwebdeveloper#378]
Hi, really enjoying this plugin! It's awesome being able to use one IDE for all my Java, C, and Web dev needs. The one issue I have is regarding HTML template literals in normal ecmascript JS files. Here's an example:

<img width="589" alt="template-literal-highlighting" src="https://user-images.githubusercontent.com/6350134/76644359-da110d00-6524-11ea-9641-dadf6f54732d.png">

While I'm using plain javascript, frameworks like [Google's Polymer](https://www.polymer-project.org/) also use this pattern. In the newer versions of IDEA, highlighting works fine (older versions you can add a `//lang=HTML` above the string. In VIM I've used [this plugin](https://github.com/jonsmithers/vim-html-template-literals).

It seems that #151 was closed, but I don't see highlighting with a clean install from the Eclipse marketplace?

**Comment by mickaelistria** [comment]
Just for the time of an experiment, can you please check that renaming the file to .jsx works?
If so, do you think we could safely apply the .jsx syntax highlighting to .js files as well? (cc @jabby )

**Comment by AugustNagro** [comment]
<img width="432" alt="Screen Shot 2020-03-19 at 12 57 32 PM" src="https://user-images.githubusercontent.com/6350134/77099018-471f1980-69e1-11ea-9597-c7c79cf27d63.png">

**Comment by angelozerr** [comment]
Perhaps I'm wrong, but I'm not sure TextMate can support that.

I suggest you that you try with vscode, if it doesn't work I'm afraid that
it's not possible (or perhaps the HTML TextMate grammar should be improved?)

Le jeu. 19 mars 2020 à 18:58, August Nagro <notifications@github.com> a
écrit :

**Comment by TatuLund** [comment]
> I just verify in VS Code. There is no syntax coloring for template literals.

@jabby With lit-plugin syntax highlighting in literals and more are enabled

https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin

**Comment by mickaelistria** [comment]
Duplicates #239
