### ISSUE TITLE
CSS Format support

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#38]
CSS Language Server doesn't provide this feature, I have created an issue for that at https://github.com/Microsoft/vscode-css-languageservice/issues/44

**Comment by angelozerr** [comment]
If you wish that CSS Language Server supports Format please help read my comments https://github.com/Microsoft/vscode-css-languageservice/issues/44#issuecomment-327837372

I have quickly implemented my idea and it works great. I can format my CSS content. Hope guys of CSS language service will accept my idea. Please help me!

**Comment by angelozerr** [comment]
Good news, @aeschli is aware to customize CSS Language Server with a given CSS formatter. See 
https://github.com/Microsoft/vscode-css-languageservice/issues/44#issuecomment-329424640

**Comment by AObuchow** [comment]
It seems that official formatter extension support [might not come to the CSS LS](https://github.com/microsoft/vscode/issues/39088#issuecomment-544623146).

I am currently in the process of[ setting up prettier to format CSS in an Eclipse plugin project](https://github.com/AObuchow/Eclipse-Spectrum-Theme/pull/95). When I have a moment, I'd like to write some instructions on setting up prettier in an Eclipse workspace as a workaround to get CSS formatting. 

If someone see's this comment & wants to format their CSS in Eclipse, please @ me to remind me to post some instructions here.

**Comment by AObuchow** [comment]
A better solution to using Eclipse's build actions would be to try using the prettier plugin for eslint https://github.com/prettier/eslint-plugin-prettier. This could work really well as Wild Web Developer already has support for eslint. I still need to try this out however.

**Comment by AObuchow** [comment]
> A better solution to using Eclipse's build actions would be to try using the prettier plugin for eslint https://github.com/prettier/eslint-plugin-prettier. This could work really well as Wild Web Developer already has support for eslint. I still need to try this out however.

There is a chance this might not work, as I'm not sure if it's possible to get eslint to lint CSS files since it's coming from the Typescript language server, which processes .js, .ts, .jsx, .tsx files.

**Comment by AObuchow** [comment]
> > A better solution to using Eclipse's build actions would be to try using the prettier plugin for eslint https://github.com/prettier/eslint-plugin-prettier. This could work really well as Wild Web Developer already has support for eslint. I still need to try this out however.
> 
> There is a chance this might not work, as I'm not sure if it's possible to get eslint to lint CSS files since it's coming from the Typescript language server, which processes .js, .ts, .jsx, .tsx files.

[Confirmed](https://github.com/prettier/eslint-plugin-prettier/issues/312#issuecomment-651280054) that using eslint-plugin-prettier won't help for CSS.

**Comment by angelozerr** [comment]
CSS format is working but it uses default preferences. To uses UI preferences, see https://github.com/eclipse/wildwebdeveloper/pull/962

**Comment by AObuchow** [comment]
FYI: Using ESLint to format CSS may now be possible? For years it wasn't possible, but this recently changed: https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/38#issuecomment-652200023. Also see https://github.com/prettier/eslint-plugin-prettier/pull/743

It also seems like https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/962 was not completed, though finishing that work might be easier? I'm not sure.
