### ISSUE TITLE
Plugin makes opening files horrendously slow 

### ISSUE THREAD

**Issue by AugustNagro** [eclipse/wildwebdeveloper#381]
Using mac OS, eclipse 2019-12, latest WWD version.

**Comment by mickaelistria** [comment]
Can you please elaborate? Does the whole IDE freeze for some time? In this case, can you run jstack when frozen to see what's specifically stuck? Or is the IDE just slow? What about other apps on the system?

**Comment by angelozerr** [comment]
Which files kind are you trying to open (js, css, html, etc files?). The problem comes from with any files kind?

**Comment by AugustNagro** [comment]
Yes, it is for files of any type, even when I open with an editor that is
not the 'generic text editor'.

With the plug-in is uninstalled eclipse opens files in less than a second,
but with the plug-in I get a spinner wheel, lag, and it takes about 8
seconds.

**Comment by nitind** [comment]
Did you, at some point, get a pop up mentioning that node was not found?

**Comment by AugustNagro** [comment]
No, at the time I did not. (I do have node installed on my machine)

**Comment by danigiri** [comment]
I have experienced a very similar issue, like really slow loading times, spinning beach ball, no autocompletion, etc.
I did some investigation, at least in MacOS X the plugin seems to use` /bin/<shell> -c -li which node` to find the node path so it can launch the language server. 

I have fortune running on my login shell, and as -li runs the login shell configuration, the command spits out fortune and not the location of node. Disabling fortune makes it work and pretty snappy again.

I am wondering about the -li flags as if they were not used I would be able to check in .zshrc if we are in a 'login' shell and then launch fortune or any other commands like keychain, ssh key agents, etc. I assume it is to make sure path to node is setup in config files, but it kinda breaks convention here and I don't see how to work around it (except adding some vodoo to check the parent process and similar hacks).

workarounds:
- progressively disable stuff in your .zshrc, .bashrc and any other shell configuration files until you get it back to speed, can cripple you if you need to launch stuff at login you need
- ability to configure the node path, or node finding command in the language server configuration(which I seem to be unable to do with Eclipse Version: 2020-06 (4.16.0) Build id: 20200615-1200)
- ability to configure node location or node finding command  in WWW plugins

**Comment by mickaelistria** [comment]
I suggest you try the snapshot from https://download.eclipse.org/wildwebdeveloper/snapshots/ and install the "Node.js embedder" that is currently under transtive dependencies. This should replace invocation of the external node (and usage of the shell) by an internal one.
Please try it and report whether it does fix your issue.

**Comment by danigiri** [comment]
installing the 'node.js embedder' transitive dep under snapshots does not seem to activate the feature, when doing a watch 'ps -fA|grep node' I still get the `/usr/local/bin/node` running

will try to install all WWW from the snapshot as opposed to the transitive dep on top of the release WWW and report back

**Comment by mickaelistria** [comment]
> installing the 'node.js embedder' transitive dep

Sorry, I wasn't clear enough: please try installing the version that's in snapshot (ie upgrading the feature) + install the embedder.
If you install the embedder without upgrading, it's simply not used.

**Comment by danigiri** [comment]
Done! I suspected as much. Indeed the snapshot fires an embedded node instance which works well on first try.
Indeed either embedding or fine-grained configuration on the node to be use are the way forward.

Thanks for the help, will use the snapshot for a while and report anything unsound

**Comment by mickaelistria** [comment]
Cool. I'm going to close this ticket then. Please open new ones for further issues.
