### ISSUE TITLE
Angular: Editor does not recognize nested projects are using parents tsconfig

### ISSUE THREAD

**Issue by bes1002t** [eclipse/wildwebdeveloper#383]
I have an angular9 project with two subprojects in 'projects' directory. I imported the subprojects using 'configure > Configure and detect nested projects' from context menu. So I have 3 projects in eclipse, but two of them are subprojects.

In my main project I configured "experimentalDecorators": true' in tsconfig, but in the subprojects I always get this error: "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning."

**Comment by mickaelistria** [comment]
I'm not much familiar with Angular project. Are you sure the tsconfig settings are supposed to be propagated to children in that case? I though it's one tsconfig per "module".
Note that you don't need all 3 projects, you can totally work with a single project (the top level one) and code directly from folders of this project. However, if you prefer 3 projects, it should be fine too.

**Comment by bes1002t** [comment]
@mickaelistria angular documentation says yes: "Project-specific TypeScript configuration files inherit from the workspace-wide tsconfig.json"

so there are project specific 'tsconfig.app.json' files, but they inehrit everything from main projects tsconfig.json.

**Comment by mickaelistria** [comment]
> @mickaelistria <https://github.com/mickaelistria> angular documentation
> says yes: "Project-specific TypeScript configuration files inherit from the
> workspace-wide tsconfig.json"
>

OK, and is it made explicit what "workspace-wide" means technically?

**Comment by bes1002t** [comment]
> Note that you don't need all 3 projects, you can totally work with a single project (the top level one) and code directly from folders of this project. However, if you prefer 3 projects, it should be fine too.

yes I don't need three projects, but its easier to handle them this way instead of clicking through the projects directory. Because with this way I only import the projects I want and not all subprojects.

> OK, and is it made explicit what "workspace-wide" means technically?

the workspace in angular is everything inside the main projects directory. From Angular doc: "All projects within a workspace share a CLI configuration context. The top level of the workspace contains workspace-wide configuration files, configuration files for the root-level application, and subfolders for the root-level application source and test files."

**Comment by mickaelistria** [comment]
Can you please try latest release of Wild Web Developer and report whether this issue still happens?

**Comment by bes1002t** [comment]
The latest version is broken. I've updated, now there is no editor anymore and .ts files are opened via chrome per default...
After the update I'm not able to work with this plugin anymore.

**Comment by mickaelistria** [comment]
Have you verified Wild Web Developer is correctly installed?

**Comment by bes1002t** [comment]
How do I verify that? I used the Eclipse market place to install the plugin.

I worked with it for months without an issue -> updated -> nothing works anymore. Uninstalled it, reinstalled it, still nothing works. I'm going to update Eclipse tomorrow and hope the latest version of booth tools are working together.

**Comment by mickaelistria** [comment]
Can you look in the eclipse log (<workspace>/.metadata/.log) if there is anything interesting?

**Comment by bes1002t** [comment]
While installing the current version, I get the following error:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Wild Web Developer 0.10.5.202012011111 (org.eclipse.wildwebdeveloper.feature.feature.group 0.10.5.202012011111)
  Missing requirement: Manager for embedded Node.js 0.2.1.202011222154 (org.eclipse.wildwebdeveloper.embedder.node 0.2.1.202011222154) requires 'osgi.bundle; org.eclipse.core.runtime 3.18.0' but it could not be found
  Cannot satisfy dependency:
    From: Wild Web Developer: web development in Eclipse IDE 0.5.13.202012011111 (org.eclipse.wildwebdeveloper 0.5.13.202012011111)
    To: osgi.bundle; org.eclipse.wildwebdeveloper.embedder.node 0.2.0
  Cannot satisfy dependency:
    From: Wild Web Developer 0.10.5.202012011111 (org.eclipse.wildwebdeveloper.feature.feature.group 0.10.5.202012011111)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper [0.5.13.202012011111,0.5.13.202012011111]

**Comment by mickaelistria** [comment]
Are you using latest release of the Eclipse IDE?

**Comment by bes1002t** [comment]
Not yet, otherwhise I could not update eclipse :D

**Comment by bes1002t** [comment]
Ok Update:

New Eclipse version:
- TS support is now working again.
- the experimental support now works

But I will switch to VSCode because Scala-IDE for Eclipse is not longer maintained.

Thanks a lot for your help :)
