### ISSUE TITLE
More readable colors in YAML editor.

### ISSUE THREAD

**Issue by garretwilson** [eclipse/wildwebdeveloper#389]
I discovered Wild Web Developer today because it came as an incubated project in [Eclipse Enterprise 2020-03](https://www.eclipse.org/downloads/packages/release/2020-03/r). I had been using the third-party [Eclipse Yaml Editor](https://github.com/de-jcup/eclipse-yaml-editor) plugin until now.

But it's nice that YAML support will be included in Eclipse, so I uninstalled Eclipse Yaml Editor and upgraded to Eclipse Enterprise 2020-03 with WWD included.

Suddenly my YAML files are almost unreadable. Everything is neon turquoise, neon light blue, neon yellow, etc. It's bright, it's light (that is, low color saturation level), and it all blends together. It's like it's reaching out and hitting my eyes. How can I adjust this? Why doesn't it follow a similar color theme to my Java editor?

I'm not sure if I can take this, and it may be worse than no syntax highlighting at all. I may just reinstall Eclipse Yaml Editor; it was working fine.

**Comment by mickaelistria** [comment]
Right-click on Editor > Switch to Theme... > Eclipse Light, and/or
Window > Preferences > TextMate > select `source.yaml` then > Theme > Edit > Eclipse Light.

**Comment by garretwilson** [comment]
> Right-click on Editor > Switch to Theme... > Eclipse Light, and/or
> Window > Preferences > TextMate > select `source.yaml` then > Theme > Edit > Eclipse Light.

Sorry, your instructions don't seem to match what I'm seeing in Eclipse Enterprise 2020-03-R (on Ubuntu 16.04). Maybe you could post a screen shot?

**Comment by garretwilson** [comment]
> Right-click on Editor > Switch to Theme... > Eclipse Light, and/or …

Ah, capitalizing "Editor" confused me; I was looking for an "Editor" menu option.

When I right-clicked on the editor, I found the "Switch to Theme..." option. The "Light" theme is not perfect, but it's much better and maybe tolerable, thank you.
