### ISSUE TITLE
Looking for a typescript declaration but I'm just using es6. how to disable these hints?

### ISSUE THREAD

**Issue by tschallacka** [eclipse/wildwebdeveloper#393]
>Could not find a declaration file for module '@tschallacka/parameter_to_object'. 'c:/,,,./npm/node_modules/@tschallacka/parameter_to_object/
 parameter_to_object.js' implicitly has an 'any' type. Try `npm install @types/tschallacka__parameter_to_object` if 
 it exists or add a new declaration (.d.ts) file containing `declare module '@tschallacka/parameter_to_object';`

That's the error hint i'm getting. And it annoys me because I'm not coding typescript, it's just normal javascript/es6, and I'm also getting these warning for other libraries. like select2, lazysizes, pickadate, so it's not something purely in my own libararies.

How can I disable evaluating as typescript?

![image](https://user-images.githubusercontent.com/8638425/77559008-f2394280-6ebb-11ea-8b9d-a5d6a1de4275.png)

**Comment by mickaelistria** [comment]
This comes from `tsserver` that's used under the hood for TypeScript and JavaScript parsing/code asisstance. It doesn't mean your code is interpreted as TypeScript. I suggest you look at how tsconfig.json can be configured to avoid such errors.
I'm closing it here as there is not much action we can take in Wild Web Developer (as it's a behavior coming from tsserver)

**Comment by tschallacka** [comment]
Would you have any hints what settings for a dead normal pure javascript setup to do?
Also, I won't be the only one to ask this I gather, so having some documentation would be nice.

Setting to noImplicitAny to false doesn't work.  Restarting eclipse after adding the tsconfig.json doesn't work.

```json
{
  "compilerOptions": {
    "allowJs": true,
    "lib": ["es6"],
    "moduleResolution": "node",
    "strict": false,
    "noImplicitAny": false
  },
  "exclude": ["node_modules"]
}
```
![image](https://user-images.githubusercontent.com/8638425/77626137-29076b00-6f45-11ea-8ff8-d7696baedd90.png)

What should the tsconfig be if I just want to develop in javascript and don't want these type warnings to appear.

**Comment by tschallacka** [comment]
I've made a repository that demonstrates the issue.  

https://github.com/tschallacka/normal_javascript_interpreted_as_typescript_wild_west_developer

This is a major negative point for me on the wild west development enviroment, especially as this is undocumented, and there is no easy findable way how to resolve this. There's no setting, and no discoverable way of setting up a tsconfig that it interprets everything as node js javascript.

Please resolve this.

**Comment by mickaelistria** [comment]
I see the same issue with VSCode. That confirms this comes from tsserver. Please report the issue to tsserver.
I don't know how to get rid of this issue. If you find a solution and want to document it in Wild Web Developer, a pull request is welcome.

**Comment by tschallacka** [comment]
I might have found the magic combination of tsconfig.json settings.
I'm now left with a new error though, one that also plagues typescript:

> File is a commonjs module it may be converted to an es6 module

but it only occurs on the first line.

A disadvantage is that these settings disable the jump to declaration with f3. I can jump to files within my workspace just fine. But if I want to see the declaration of the node module that's now dead.

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "allowJs": true,
        "sourceMap": true,
        "target": "ESNEXT",
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "lib": [
            "es2016"
    ],
    "exclude": [
        "node_modules"
    ]
}
```
