### ISSUE TITLE
textmate themes cannot be adjusted

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#395]
According to https://github.com/eclipse/wildwebdeveloper/issues/235#issuecomment-526503012 I wanted to select a different theme for different file types. 

However, when selecting a different theme and close the dialog with apply (or apply and close), the wwd generic editor for that file type is not decorated by the selected theme (maybe because wwd will not save my settings?).

![wwd-theme](https://user-images.githubusercontent.com/3045549/77754787-4d8a4280-702c-11ea-979d-118aa273fc3f.png)

I use the actual version of wwd.

**Comment by mickaelistria** [comment]
Thanks for the report.
If you use Right-Click on editor > Switch Theme..., do the themes all work? I'm trying to figure out wheither it's some specific themes that have bugs in general, or more the association mechanism.

**Comment by nimo23** [comment]
>If you use Right-Click on editor > Switch Theme..., do the themes all work?

No it does not work.

> or more the association mechanism.

very likely.

**Comment by mickaelistria** [comment]
Does right-click on editor > Switch theme... not work for all file types (.js, .css, .html...) and all themes (Solarized Light, Light, Eclipse Light, Monokai, Dark, Monokai) ?
Although I didn't try all combinations, this does work for me on the few files/themes I tried.
When switching them fail, do you see any related message in the Error Log or in <workspace>/.metadata/.log file?

**Comment by nimo23** [comment]
>Does right-click on editor > Switch theme... not work for all file types (.js, .css, .html...)

I have tried it for xhtml, jsx, css. It does not work. 

> all themes (Solarized Light, Light, Eclipse Light, Monokai, Dark, Monokai)

no theme works but only the default wwd theme.  

> Error Log or in /.metadata/.log file?

There is no error shown in the log when switching themes.

**Comment by mickaelistria** [comment]
Is this still happening if you use latest release of Wild Web Developer, and TM4E ?

**Comment by nimo23** [comment]
It works with the latest release without problems. Thanks!
