### ISSUE TITLE
Eclipse Warning: Could not find node.js for FreeBSD

### ISSUE THREAD

**Issue by daemonblade** [eclipse/wildwebdeveloper#396]
I'm running Eclipse 2020-03 on FreeBSD, and have just installed Wild Web Developer 0.9.0.202003192213. However, on startup on FreeBSD and on startup, it complains with "Could not find node.js...".

However, I do have node installed:
```
onyx:~,10:30am> which node
/usr/local/bin/node
onyx:~,11:13am> node --version
v13.10.1
```

I have looked at "InitializeLaunchConfigurations.java", and the which() method incorrectly assumes that "/bin/bash" exists. This is a Linuxism. Wouldn't it be better to inspect $PATH and then see if an executable file exists with the name "node"?

Adding hack in getDefaultNodePath() wouldn't quite work for FreeBSD as it's not one of the return values defined in Platform.getOS().

**Comment by daemonblade** [comment]
Something like the following, perhaps:
```
public static String which(String program) {
    String paths [] = System.getenv ("PATH").split (System.getProperty ("path.separator"));
    for (String path : paths) {
        File node = new File (path, program);
        if (node.canExecute ())
            return node.getAbsolutePath ();
    }
    return null;
}
```

**Comment by mickaelistria** [comment]
Do you think you can provide a pull request for that?

**Comment by daemonblade** [comment]
Thanks!

**Comment by mickaelistria** [comment]
Build including fix should be available in a dozen of minutes at https://download.eclipse.org/wildwebdeveloper/snapshots/

**Comment by daemonblade** [comment]
FYI: Build 0.9.0.202003301134 works perfectly.
