### ISSUE TITLE
Failed install of plugin in Eclipse 2019-09

### ISSUE THREAD

**Issue by thomasjoscht** [eclipse/wildwebdeveloper#398]
Hey, 

I cannot install Wild Web Developer in Eclipse 2019-09 (all available updates installed). Tried install WWD version 0.8.2 via Marketplace and also 0.8.3 via repository https://download.eclipse.org/wildwebdeveloper/releases/0.8.3/

Error Message is:
> Cannot complete the install because of a conflicting dependency.
  Software being installed: Wild Web Developer 0.8.3.202003111701 (org.eclipse.wildwebdeveloper.feature.feature.group 0.8.3.202003111701)
  Software currently installed: Eclipse Platform 4.13.0.v20190916-1323 (org.eclipse.platform.feature.group 4.13.0.v20190916-1323)
  Only one of the following can be installed at once: 
    Console 3.8.600.v20190815-2020 (org.eclipse.ui.console 3.8.600.v20190815-2020)
    Console 3.5.300.v20140424-1437 (org.eclipse.ui.console 3.5.300.v20140424-1437)
    Console 3.9.0.v20191126-0912 (org.eclipse.ui.console 3.9.0.v20191126-0912)
  Cannot satisfy dependency:
    From: Eclipse Platform 4.13.0.v20190916-1323 (org.eclipse.platform.feature.group 4.13.0.v20190916-1323)
    To: org.eclipse.equinox.p2.iu; org.eclipse.ui.console [3.8.600.v20190815-2020,3.8.600.v20190815-2020]
  Cannot satisfy dependency:
    From: Wild Web Developer: web development in Eclipse IDE 0.5.5.202002262342 (org.eclipse.wildwebdeveloper 0.5.5.202002262342)
    To: osgi.bundle; org.eclipse.ui.console 3.9.0
  Cannot satisfy dependency:
    From: Wild Web Developer 0.8.3.202003111701 (org.eclipse.wildwebdeveloper.feature.feature.group 0.8.3.202003111701)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper [0.5.5.202002262342,0.5.5.202002262342]

I've installed org.eclilpse.ui.console 3.8.600v20190815-2020.

What can I do? Thx

Regards
Thomas

**Comment by mickaelistria** [comment]
Please upgrade to Eclipse IDE 2020-03 first https://wiki.eclipse.org/FAQ_How_do_I_upgrade_Eclipse_IDE%3F#Upgrading_existing_Eclipse_IDE_and_Installed_Features_to_newer_release
If you can't upgrade, then you'll need to use an older version of Wild Web Developer.
You can try to contribute a patch that reduces the minimal version requirement on org.eclipse.ui.console , we would review and probably merge it so you would be able to use newer snapshots. But adopting 2020-03 is probably best for everyone.
I'm closing the issue. Feel free to open a PR if you want to change the console version requirement.
