### ISSUE TITLE
file explorer not opened when clicking on log path

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#399]
One little issue:

Go to Eclipse Preferences->LanguageServer->Logs and click on file logs (near File Logs are stored in: "). The path opens an eclipse import dialog instead of opening the host file explorer (in my case it should open the "Finder" on Mac OS instead of an eclipse import dialog).

Eclipse: Version: 2020-03 (4.15.0)
WWD Version: current snapshot

**Comment by mickaelistria** [comment]
This is an issue to report to LSP4E, bit it's actually intentional.
