### ISSUE TITLE
Angular Language Server appears to be run when using PyDev

### ISSUE THREAD

**Issue by demongolem** [eclipse/wildwebdeveloper#400]
This also perhaps relates to #390 in some fashion.  When I run a PyDev application, I get 4 new selections in the console window involving Angular Language Server including one that says a new server process has been started.  

> [Info]	Angular language server process ID: 75209

Why would this plugin be invoked if I am running PyDev?  Or is this simply a symptom of #390 where work I did a few weeks ago when I was doing node.js programming has not been cleared from the console and is stale?

**Comment by mickaelistria** [comment]
This language server may startup when editing some plain .html files.
Realistically, the issue is more that the console does log this useless message and disturbs users. Such log should simply be avoided. See also https://github.com/angular/vscode-ng-language-service/pull/584

**Comment by mickaelistria** [comment]
Dup of #438
