### ISSUE TITLE
ESLint not working running on Windows

### ISSUE THREAD

**Issue by goesling** [eclipse/wildwebdeveloper#402]
I tried to test ESLint support in Eclipse 2020-03 running on Windows 10 with latest snapshot version of WWD. When using a simple Project similar to /org.eclipse.wildwebdeveloper.tests/testProjects/eslint/ no ESLint Messages will get shown, neither in any .ts, .tsx or .js file.

After that I tried to use the same Test Project on Linux. Using eclipse 2020-03 on Linux (Ubuntu 18.04 based on Windows Subsystem for Linux (2)) with latest snapshot version of WWD ESLint is working fine. Expected ESLint messages got shown.

It seems ESLint support does not work using Windows.

**Comment by mickaelistria** [comment]
Which version of node are you running on Windows vs Linux?

**Comment by goesling** [comment]
Windows: v12.16.2
Linux: v10.20.0

**Comment by goesling** [comment]
I did an update for Linux, now Linux and Windows are using node v12.16.2.

By the way... for now I concentrated on TypeScript (ts and tsx files). But ESLint also does not work for JS or JSX files on Linux. Only for TS and TSX Files ESLin ist working on Linux (And to clarify: On Windows neither for TS / TSX nor JS / JSX files ESLint is working)

**Comment by mickaelistria** [comment]
ESLint+JS failing is already tracked at #338 
@jabby IIRC you're often using Windows. Do you reproduce the issue?

**Comment by goesling** [comment]
With latest update  0.10.1.202006102037 ESLint support seems to work on Windows.

**Comment by mickaelistria** [comment]
Great news! Let's close then.
@vrubezhny some positive side effects with your npm modules updates ;)
