### ISSUE TITLE
Feature propose,group of constants folding/unfolding in outline view

### ISSUE THREAD

**Issue by AlexLuya** [eclipse/wildwebdeveloper#404]
![Workspace 1_963](https://user-images.githubusercontent.com/303353/79293455-63da3e80-7f06-11ea-94d5-c8cb1e346329.png)
As image shown,these constants are better can be folded/unfolded

**Comment by mickaelistria** [comment]
Good idea. I opened https://github.com/theia-ide/typescript-language-server/issues/147 as this it's a feature to provide by the language server.
We'll keep the issue open and will close it when Wild Web Developer uses a version of the language server which supports this feature.

**Comment by mickaelistria** [comment]
Closed upstream, let's close here.
