### ISSUE TITLE
Node version cannot be determined popup on RHEL while being installed

### ISSUE THREAD

**Issue by sbouchet** [eclipse/wildwebdeveloper#409]
Hi,

I'm using latest WildWebDeveloper 0.8.3 with eclipse 4.15 and I get the popup dialog saying node path location cannot be found but it is installed correctly in my system. 

See the image below : 
which returns a path and the node version is 10.14.1

![Capture d’écran de 2020-04-17 16-29-52](https://user-images.githubusercontent.com/600414/79580536-6d5fd400-80c9-11ea-9c51-0164f2aef865.png)

**Comment by mickaelistria** [comment]
There was a change about this in latest 0.9.0 release. Can you please try it?

**Comment by sbouchet** [comment]
thanks, it resolves the issue !
