### ISSUE TITLE
Path too long on Windows

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#411]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=559701
This is mostly caused by https://github.com/redhat-developer/yaml-language-server/issues/253

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/pull/410

**Comment by ynnenu** [comment]
instead of so much work you can just try https://longpathtool.com
