### ISSUE TITLE
Node.js 14 support

### ISSUE THREAD

**Issue by vincenzocaselli** [eclipse/wildwebdeveloper#412]
Hi,
after latest **Node.js 14** upgrade I am getting the following popup every time I start Eclipse

> ![image](https://user-images.githubusercontent.com/3648713/80378849-90467100-889d-11ea-927c-b31b69187da7.png)

I am using
Wild Web Developer	0.9.1.202004210722	
from 
http://download.eclipse.org/wildwebdeveloper/snapshots/

My env is:
Eclipse IDE for Enterprise Java Developers.
Version: 2020-03 (4.15.0)
Build id: 20200313-1211
OS: Linux, v.5.4.35-1-lts, x86_64 / gtk 3.24.17, WebKit 2.28.2
Java version: 14.0.1

Should I use a different Update Site for WWD?
TIA
Vincenzo Caselli

**Comment by jabby** [comment]
@mickaelistria I will take care of this.

**Comment by mickaelistria** [comment]
Done with https://github.com/eclipse/wildwebdeveloper/commit/4030c2dc9c68dd9fe97c3429fd519153cdb273cc

**Comment by jabby** [comment]
Sorry I had some problem to work on this. My bad. 
Thanks @mickaelistria for thaking care of this.
