### ISSUE TITLE
[feature] Add support for passing customization to XML language server and extensions (didChangeConfiguration)

### ISSUE THREAD

**Issue by gayanper** [eclipse/wildwebdeveloper#416]
When starting XML language server it would be nice if the language server launcher can inject some system properties from the host JVM to language server JVM

**Why?**
XML extensions such as lemminx-maven depends on several configuration parameters such as the global maven config, user config, and local repository path. Since the extensions can't directly depend on the host IDE for these settings, the above mechanism can be used inside eclipse to pass in the required m2e configuration as JVM properties. 

**How?** 
The XML language server launcher can introduce a JVM property namespace like `lemminx.` . lemminx-maven can define system properties like `lemminx.m2.global.config`, `lemminx.m2.repo` for example. All these properties under the `lemminx.` namespace are injected into the XML language server JVM by the XML language server launcher.

@angelozerr @mickaelistria I would like to hear your thoughts about this proposal.

**Comment by mickaelistria** [comment]
I think it a good idea and we'll need it at some point.
Instead of system property conventions, I'd rather allow the extension point allowing to pass directly some extra system properties when launching LemMinX.

**Comment by angelozerr** [comment]
> Instead of system property conventions, I'd rather allow the extension point allowing to pass directly some extra system properties when launching LemMinX.

You mean user settings like https://github.com/redhat-developer/vscode-xml#supported-vs-code-settings

If it that it's possible today to get those settings from a LemMinx extension and I think it gives the capability to manage complex structure settings (array of string, etc)

**Comment by mickaelistria** [comment]
>
> You mean user settings like
> https://github.com/redhat-developer/vscode-xml#supported-vs-code-settings
>

No, I mean more like settings reading the Eclipse PreferenceStore (ie m2e
preferences for local repository) and using it to pass some system
properties to LemMinX and it's extension (ie -Dmaven.repo.local=...).
-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by AObuchow** [comment]
> You mean user settings like https://github.com/redhat-developer/vscode-xml#supported-vs-code-settings
> No, I mean more like settings reading the Eclipse PreferenceStore (ie m2e preferences for local repository) and using it to pass some system properties to LemMinX and it's extension (ie -Dmaven.repo.local=...). 

My initial idea was to use an environment variable for these settings, and modify M2E to set these environment variables. However this would probably required Eclipse IDE to be restarted to apply the changes, so I think your suggested approach with system properties is better. (Just wanted to give my input)

**Comment by angelozerr** [comment]
If you speak about preference store its exactly what i mean because its the
same thing than vscode settings.json. More it will manage update of
settings which is lsp specification

**Comment by mickaelistria** [comment]
OK, I get it better. This is indeed something to consider, instead of using system properties at startup, send some `didChangeConfiguration`. Is this what you have in mind?

**Comment by angelozerr** [comment]
> Is this what you have in mind?

Exactly and LemMinx support already that. All extensions reacts from settings on startup and when settings changed (it works pretty well on vscode).

For extension side, you need to implement doSave like https://github.com/eclipse/lemminx/blob/f12cf5d1cbd47f59bdb4b632bed57b11b8195be2/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/ContentModelPlugin.java#L92

**Comment by mickaelistria** [comment]
Blocks:
* https://github.com/eclipse/lemminx-maven/issues/45
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=562787

**Comment by angelozerr** [comment]
And I suggest that you use the same preferred name than vscode-xml in the preference store.

**Comment by mickaelistria** [comment]
Support for initializationOptions was added in https://github.com/eclipse/wildwebdeveloper/commit/cf48e6f3ba655660c81ac15725f09583bca6d89f .
There is nothing specific to do for didChangeConfiguration, each downstream plugin can invoke LSP4E directly to achieve that. See for instance https://git.eclipse.org/c/m2e/m2e-core.git/diff/org.eclipse.m2e.editor.lemminx/src/org/eclipse/m2e/editor/lemminx/MavenRuntimeClasspathProvider.java?id=378fd03452686bc79dadd1f810ec08ae77cbb194

**Comment by mickaelistria** [comment]
Support for initializationOptions was added in https://github.com/eclipse/wildwebdeveloper/commit/cf48e6f3ba655660c81ac15725f09583bca6d89f .
There is nothing specific to do for didChangeConfiguration, each downstream plugin can invoke LSP4E directly to achieve that. See for instance https://git.eclipse.org/c/m2e/m2e-core.git/diff/org.eclipse.m2e.editor.lemminx/src/org/eclipse/m2e/editor/lemminx/MavenRuntimeClasspathProvider.java?id=378fd03452686bc79dadd1f810ec08ae77cbb194
