### ISSUE TITLE
How desactive auto-closing pairs ? 

### ISSUE THREAD

**Issue by blacombe33** [eclipse/wildwebdeveloper#420]
the autocompletion is very bad, and slow my writing . How can I deactivate it, or I preferred it on Ctrl+space (like usually on eclipse).
And then if I press the quote "'" , it add another " quote are very very bad . For example if I write  "var a=fg;"
but I forget the quote before "f", then I put my cursor before "f" and I press  a quote"'", eclipse add 2 quote then I get "var a=''fg" , then I must remove the quote to get "var a='fg", ....
The computer don't help me it slow me .... ;-((

**Comment by mickaelistria** [comment]
You may be able to disable those, in the Window > Preferences > TextMate > Language Configurations, then select the one for the desired language and go to "auto closing pairs" and uncheck "Enable...".

**Comment by blacombe33** [comment]
super, . If i understand TextMate is the preference page of Wildwebdevelopper ?

**Comment by mickaelistria** [comment]
The syntax highlighting and the auto-closing stuff actually comes from TextMate support. Wild Web Developer is more an "assembly" project, most of the smartness comes from Eclipse TM4E and Wild Web Developer, which have their own preference pages.
