### ISSUE TITLE
How desactive  autocompletion ?

### ISSUE THREAD

**Issue by blacombe33** [eclipse/wildwebdeveloper#423]
The autocompletion is very bad, and slow my writing . 
How can I deactivate it or (best) can I use "Ctrl+space" (like usually on eclipse) to autocomplete ?

**Comment by mickaelistria** [comment]
What's the difference with #420? Can you please provide examples?

**Comment by mickaelistria** [comment]
We won't work on disabling auto-completion because it's bad. Efforts should be directed towards making the completion not bad.
