### ISSUE TITLE
XML icon is not scaled properly

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#425]
Hello,

When opening an XML file with the generic text editor, the XML icon is not scaled properly:
<img width="159" alt="Screenshot 2020-05-11 at 11 12 38" src="https://user-images.githubusercontent.com/10694593/81545363-12906400-9379-11ea-810d-dc7c7b958b9c.png">

Note that I'm observing this behaviour on macOS 10.15, not sure about other operating systems.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/pull/427

**Comment by PyvesB** [comment]
Thanks!
