### ISSUE TITLE
Opening a yaml file should not produce "Node.js vXXX is not supported" warning dialog

### ISSUE THREAD

**Issue by ben-spiller** [eclipse/wildwebdeveloper#426]
Since the introduction of the wildwebdeveloper plug-in into eclipse we're seeing a new warning dialog for our users "Node.js vXXX is not supported" the first time a .yaml file is opened - which is annoying for users who aren't even trying to do any web development (or to use this plugin) but just want to view a yaml file (of course yaml is used for many things, not just this plugin). 

This is a regression as eclipse would previously open yaml files just fine without caring what node.js you do/don't have on your path. 

Displaying such a warning is OK(ish!) if you're explicitly trying to do something with the wildwebdeveloper plugin, but really not at all appropriate if you're just opening up a yaml file. 
Suggest downgrading this to a warn log message when the plugin first loads. 

btw there's a bigger discussion of the node.js dependency at GH-23, but this bug is kept to separate to focus on the specific aspect of the warning dialog.

In the meantime we're going to need to disable this entire plugin to prevent this dialog from confusing our users when they open a yaml file, which is really a shame as apart from the dialog there is no problem.

**Comment by mickaelistria** [comment]
What's specifically is `XXX` here?

**Comment by ben-spiller** [comment]
XXX is just whatever version of node.js I happen to have on my PATH. Since I'm not planning to do any web development with eclipse, what node.js I have or have not on my machine and/or PATH env var shouldn't affect my experience of editing (non-web related) yaml files. And anyway there's still a message even if node.js isn't present at all. 

(of course, if I'd explicitly configured this plugin to use a  particular node.js then it'd be completely reasonable for it to complain.... but just because it's on my PATH doesn't mean I want eclipse to use it)

**Comment by mickaelistria** [comment]
Ok, if you don't want to install a compatible node version, then you simply cannot use the yaml or most other edition features of Wild Web Developer at the moment.
#23 would be the solution here, and I don't see better possible action from your report. So let's close.

**Comment by ben-spiller** [comment]
Please consider this a bit more before closing - the issue GH-23 is clearly a much bigger/more controversial and complex one which has been open for several years now (that's why I took out some time to help you out by writing this problem up as a separate ticket :) ) and I'm worried that if we rely on GH-23 we may not get a quick fix. 

The Wild Web Developer plugin needs to be more conscious of other users now that it's included in standard packages like the Eclipse IDE for Enterprise Java Developers. So whatever needs this plugin may or may not have for node.js, it just isn't acceptable for it to take over a widely used file type like .yaml without asking and then add a warning message when the user tries to open yaml files. That produces a regression in the behaviour of the core eclipse platform, which previously handled .yaml files perfectly well (with the generic text editor) without needing node.js. 

I think what we need here is a better solution for how this plugin downgrades when the required node.js isn't available - either suppress the warning message, or don't even register your plugin as supporting .yaml files if the node.js dependency isn't met. There should be no warningmessages  unless someone is actually using the specific functionality unique to this plugin. 

Currently this plugin (which we don't even need) is blocking my company's adoption of eclipse 4.15, which isn't ideal. Hope we can find a solution here. Thanks :)
