### ISSUE TITLE
[feature request] JSON schema association via extension point

### ISSUE THREAD

**Issue by zulus** [eclipse/wildwebdeveloper#429]
I would like to replace WTP JSON by WildWebDeveloper in Eclipse PDT Composer editor (eclipse/pdt#54). Only feature I miss is no ability to associate composer.json with correct schema.

In `JSonLanguageServer.java` I found only TODO tag. I'll be happy to have something similar to `org.eclipse.wst.json.core.schemaCatalogContributions`.

Example from WTP:

```XML
<extension
         point="org.eclipse.wst.json.core.schemaCatalogContributions">
         <schemaCatalogContribution id="http://schemastore.org/">
            <schema name="composer.json"
                  description="%schema.description"
                  fileMatch="composer.json"
                  url="http://json.schemastore.org/composer"
                  uri="schemastore/composer" />
         </schemaCatalogContribution>
</extension>
```

**Comment by mickaelistria** [comment]
See also https://github.com/eclipse/wildwebdeveloper/pull/316

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/pull/430
