### ISSUE TITLE
Improve Quick Outline UX

### ISSUE THREAD

**Issue by nitind** [eclipse/wildwebdeveloper#431]
The Quick Outline is currently anchored to the upper right corner of the editor pane. It should appear in the center of the workbench, like in most other editors, and be user-resizable.

**Comment by mickaelistria** [comment]
This is https://bugs.eclipse.org/bugs/show_bug.cgi?id=566995 , so installing latest lsp4e snapshots from https://ci.eclipse.org/lsp4e/job/lsp4e-snapshot/ should get it fixed.
