### ISSUE TITLE
 I need help with the autocomplete function

### ISSUE THREAD

**Issue by haejehaeje** [eclipse/wildwebdeveloper#432]
![image](https://user-images.githubusercontent.com/65376163/82986891-9f9e1300-a031-11ea-8b9f-2c6a7fa8385c.png)

how do i enable  content assist(JQuery, browser) in javascript

could you please let me know

I'm sorry that my English grammar is wrong.

**Comment by mickaelistria** [comment]
JSP support is not provided by Wild Web Developer. This is most likely some other plugin contributing it.
