### ISSUE TITLE
Not good enough

### ISSUE THREAD

**Issue by humphreygao** [eclipse/wildwebdeveloper#434]
用户体验一点都不好，代码补全功能甚至没有原先的HTML Editor来的好。
1). 必须打出`<`，才能开始进行代码提示
2). 不能自动显示代码提示，必须按 `Alt+/`
3). 代码补全的优先级问题一直没有解决
4). 一些基于HTML Editor的插件，都不能使用了。
5).打开文件的速度明显下降，LSP的存在似乎拖慢了文件打开速度

首先，为什么不内置Node.js呢，很多初学者都在抱怨为什么一打开文件就弹出对话框说缺少Node.js。

用VS Code和Eclipse IDE编写Typescript代码，可以明显发现，Eclipse IDE和VS Code的差距。说实话，本插件来源于Microsoft还有诸多厂商提供的LSP，不说青出于蓝而胜于蓝，体验上却做不到与之持平，实在是不应该。

此外，插件的图标实在是太丑了，小的看不清，能不能用点扁平化的图标呢？
![QQ截图20200530151059](https://user-images.githubusercontent.com/52394598/83322137-ceadc200-a287-11ea-91ad-0c688c39b380.png)
![QQ截图20200530151134](https://user-images.githubusercontent.com/52394598/83322139-d0778580-a287-11ea-9039-a452f3bbe2d6.png)

最后，本插件不如Genuitec家的CodeMix好用，感觉定位十分尴尬，只不过本插件不要钱罢了。

最近本插件的开发处于停滞状态。所以有感而发。

If I have time, I will translate my issue into English.

**Comment by mickaelistria** [comment]
Please post your issues in English, and 1 ticket per issue, with focused and precise comments, not general feelings which are not easily actionable.
