### ISSUE TITLE
Angular language server error whenever I open a html file

### ISSUE THREAD

**Issue by mbooth101** [eclipse/wildwebdeveloper#438]
When I open a HTML file I see this in the console view:

```
[Info]	Angular language server process ID: 19928
[Info]	Using @angular/language-service v9.0.0-rc.4 from /app/eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.5.202002262342/language-servers/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info]	Using typescript v3.8.2 from /app/eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.5.202002262342/language-servers/node_modules/typescript/lib/tsserverlibrary.js
[Info]	Log file: undefined
[Error]	No config file for /home/mbooth/workspace/path/to/file.html
```
Is the error talking about Angular config? It's just plain html/css file, no Angular involvement whatsoever.

I have these bundles installed into Eclipse for Committers 4.15 from Flathub:

```
	0.9.0.v20200229-1009	org.eclipse.lsp4j
	0.13.1.202003021135	org.eclipse.lsp4e
	0.4.0.201911211357	org.eclipse.tm4e.core
	0.5.5.202002262342	org.eclipse.wildwebdeveloper
	0.6.1.202003111701	org.eclipse.wildwebdeveloper.xml
```

**Comment by AObuchow** [comment]
Potentially the same issue described here https://github.com/eclipse/wildwebdeveloper/issues/400#issuecomment-608419016

**Comment by mickaelistria** [comment]
LSP4E was fixed by @vrubezhny to improve how it handles the logMessage LSP command (basically not showing it the UI as it's already the role of showMessage). Using latest snapshots of LSP4E from https://download.eclipse.org/lsp4e/snapshots should fix it.
