### ISSUE TITLE
Toggle CSS Color

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#44]
@mickaelistria if you accept my PR https://github.com/mickaelistria/eclipse-bluesky/pull/43 which support CSS color, I would like to provide a **Toggle CSS Color** like we have for mark occurrences **Toggle Highlight**

I think it could be good to have this feature if my work with CSS color have some bugs, to disable it.

**Comment by mickaelistria** [comment]
> I think it could be good to have this feature if my work with CSS color have some bugs, to disable it.

Or better, if it has some bugs, we fix them ;)
Except for bugs, I don't see any good reason why a user would want to turn off color preview and use this yet-another-toolbar-item, so I don't think it's a good topic to spend effort on at the moment.

**Comment by angelozerr** [comment]
> Or better, if it has some bugs, we fix them ;)

Yes sure:) But I fear that if there are bugs, user will give up bluesky. I know the user (I'm an user), if it's slow or if there are rendering bugs, I give up the toolings.

I have created this issue because:

 * VSCode provides this settings
 * If there are bugs or performance bugs, user can disable it.

> so I don't think it's a good topic to spend effort on at the moment.

I think it's not difficult to do that, no? (more now we have a sample with Toggle Highlight).

**Comment by mickaelistria** [comment]
@angelozerr shouldn't this work out-of-the-box when using a recent LSP4E?

**Comment by angelozerr** [comment]
Do you mean my contribution for supporting ls color https://bugs.eclipse.org/bugs/show_bug.cgi?id=533322 ? If it that, no, this issue is to provide a toggle command for enable/disable color provider like highlight. But if you like this idea, now it's LSP4é which should support that.

**Comment by mickaelistria** [comment]
I'm closing this as the need for it seems really small.
If it becomes an actual issue at some point, we can try to fix it in LSP4E (disabling the code mining reconciler), but I doubt it's useful at the moment.
