### ISSUE TITLE
How do I start using it?

### ISSUE THREAD

**Issue by mfgabriel92** [eclipse/wildwebdeveloper#446]
Hi,

I installed the plugin but I seem not to be understanding how to start using it. I imported an Angular project into Eclipse and opened with the suggested editor, but it doesn't autocomplete anything, nor I can click on a file, variable, etc., to go directly to them. It is only possible to type and erase, nothing more.

Did I miss something?

**Comment by AObuchow** [comment]
Do you have Node.JS installed? And are you using the Generic Editor? (I
imagine you are?

**Comment by mfgabriel92** [comment]
Hi,

Yes, I am for both. I've set up Node in my PATH like this:

`export PATH="$PATH:/usr/bin/node"`

Then the error message saying it couldn't be found hasn't opened again, so I assume I did it right.

**Comment by jabby** [comment]
@mfgabriel92 The error message appears only once per launch of Eclipse IDE. 
Can you verify after a restart?

**Comment by mfgabriel92** [comment]
@jabby didn't know that. It still appears...

**Comment by AObuchow** [comment]
@mfgabriel92 what OS are you using by the way?

**Comment by mfgabriel92** [comment]
@AObuchow apologies, it is the latest Ubuntu LTS. I have Node installed through NVM, at `/home/gabriel/.nvm/versions/node/v12.16.3/bin/node`.
