### ISSUE TITLE
Change syntax highlighting?

### ISSUE THREAD

**Issue by mfgabriel92** [eclipse/wildwebdeveloper#447]
I use Eclipse on dark mode and for Java programming, I have a stylized Nord color pallette. But upon installing the plugin I noticed the color scheme will be different and I find no way to modify it. The "Switch theme" option is the only thing closest to it, but I don't think it's the syntax highlighting.

Is there a way I can import my theme when developing in Angular?

**Comment by mickaelistria** [comment]
The 'Switch to theme..." context-menu entry allows to change theme. Did you try Monokai with a Dark theme for instance?
Windows > Preferences > TextMate > Theme allows more control on themes; and Windows > Preferences > TextMate > Grammar allows associating a specific grammar to a specific file type.

**Comment by mfgabriel92** [comment]
Interesting. The "Theme" option seems to allows me to add new themes, but the buttons are grayed out. Is there a way to enable them?

**Comment by mickaelistria** [comment]
Currently no, see https://github.com/eclipse/tm4e/issues/249 . Contributions are welcome!

**Comment by mfgabriel92** [comment]
What about the location of the files? Maybe they can be edited?

**Comment by mickaelistria** [comment]
No, they shouldn't be edited manually, the IDE caches some files so manual edition may not work. Efforts need to be directed towards improving TM4E to better handle this user-story.
