### ISSUE TITLE
 "generic editor" always gets precedence over *.js file association settings in preferences

### ISSUE THREAD

**Issue by level420** [eclipse/wildwebdeveloper#448]
- Eclipse IDE for JavaScript and Web Developers 2020-06 (4.16.0) Build id: 20200615-1200
- wild web developer 0.10.0.202006021616
- openjdk 14.0.1.7
- windows 10 ltsc 2019 (latest patches applied)

I'm in need of using another javascript editor, not the wwd one. Currently with wwd version 0.10.0.202006021616 when clicking on a javascript file, the "generic editor" always gets precedence, even if I've configured the other javascript editor as default under Preferences -> Editors -> File Associations -> *.js.

Of course I can use "Open with" for every *.js file, but that's annoying.

The faulty behaviour was not present in (I think) wwd 0.9.x

This issue may have been introduced with #401

**Comment by akurtakov** [comment]
This has been introduced due to jsdt ancient js editor. As JSDT is fixed we should probably drop this one. 
Btw., would you please let us know what is the other editor you using providing more than wwd one?  Not questioning the need for that just curious so we can improve our.

**Comment by level420** [comment]
@akurtikov the "other" javascript editor is from the aptana studio plugin (http://preview.appcelerator.com/aptana/studio3/plugin/update/nightly/)  where the javascript editor and especially its outline view is aware of the class definition structure of qooxdoo framework class files (see https://github.com/qooxdoo/qooxdoo):

![image](https://user-images.githubusercontent.com/210674/85020734-10d47000-b171-11ea-910c-3181dff1c12e.png)
