### ISSUE TITLE
Error while computing completion

### ISSUE THREAD

**Issue by debjava** [eclipse/wildwebdeveloper#453]
Hi All, I tried to use Eclipse Javascript with Wildwebdeveloper, I face the issue related **"Error while computing completion**". It looks like a bug. Besides, do I have to make any change in the setting so that intellisence will work? Find the attached image here. I am using the latest version of Eclipse Javascript ie Eclipse 2020-6. Please suggest me.

<img width="649" alt="Err-1" src="https://user-images.githubusercontent.com/8937578/85230206-45b02380-b40c-11ea-9185-686777a87288.png">

**Comment by AObuchow** [comment]
Hi, what OS & version of Node.JS do you have installed?

**Comment by debjava** [comment]
> Hi, what OS & version of Node.JS do you have installed?

I am using **Windows 10** and Node Js version **v10.19.0**

**Comment by debjava** [comment]
Computing proposals also takes more time to come up, in most of the cases, it fails to load.

**Comment by debjava** [comment]
Hi All, any update on this?

**Comment by mickaelistria** [comment]
Please look into the Eclipse workspace .metadata/.log file to see if there are more hints. If not, please enable Language Server Logs for JavaScript (in Window > Preferences > Language Servers > Logs), process with the minimal steps to reproduce the issue, and then attach here the generated log file.

**Comment by AObuchow** [comment]
@debjava its a bit difficult to determine what’s going on with the current information we have.

Is there anything in Eclipses error log view? @mickaelistria might have some better diagnostic suggestions.

**Comment by debjava** [comment]
I get the following errors from eclipse logs.

> !ENTRY org.eclipse.lsp4e 4 0 2020-06-28 22:41:06.997
> !MESSAGE 
> !STACK 0
> java.util.concurrent.TimeoutException
> 	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
> 	at java.util.concurrent.CompletableFuture.get(Unknown Source)
> 	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverRegion(LSPTextHover.java:201)
> 	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverRegion(CompositeTextHover.java:101)
> 	at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:128)
> 	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
> 	at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:511)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4213)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4030)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
> 
> !ENTRY org.eclipse.lsp4e 4 0 2020-06-28 22:41:07.501
> !MESSAGE 
> !STACK 0
> java.util.concurrent.TimeoutException
> 	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
> 	at java.util.concurrent.CompletableFuture.get(Unknown Source)
> 	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:107)
> 	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
> 	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)

**Comment by debjava** [comment]
I have posted the error details, please check and let me know about it so that I can provide more details.

**Comment by AObuchow** [comment]
@debjava I don't think the error details posted will provide enough to identify the issue. They're just describing that a hover request to the JS language server timed out.

I suggest turning on logging of the JS language server & giving steps to reproduce as described by @mickaelistria:
>  If not, please enable Language Server Logs for JavaScript (in Window > Preferences > Language Servers > Logs), process with the minimal steps to reproduce the issue, and then attach here the generated log file.

**Comment by debjava** [comment]
I have enabled the logs. I provide below the code fragments and the intellisence is not working.

```
proms.push(this.boilMilk()); // Takes 5 seconds
proms.push(this.cleanUtensils()); // Takes 13 seconds

const allPromises: any = await Promise.all(proms);
allPromises.map((value: any) => {
      allSummary.push(...value);
 });
```

I attach the following log files.
[angular-language-server.log](https://github.com/eclipse/wildwebdeveloper/files/4842933/angular-language-server.log)
[.log](https://github.com/eclipse/wildwebdeveloper/files/4842934/default.log)

**Comment by AObuchow** [comment]
@debjava you seemed to have provided angular language server logs. Is your issue JS or angular related? Are there any JS language server logs generated?

**Comment by mickaelistria** [comment]
Can you please try latest release of Wild Web Developer (which was released yesterday) and report whether this works for you or if it's still failing?

**Comment by debjava** [comment]
> Can you please try latest release of Wild Web Developer (which was released yesterday) and report whether this works for you or if it's still failing?

Sure Sir, I will try and let you know.

**Comment by debjava** [comment]
Sir, I have updated the Wild Web Developer and it looks fine for me.

**Comment by mattcoz** [comment]
I'm getting this same error on the latest version of WWD. Recently got into a loop and I had to end Eclipse, losing some work.

Eclipse Web Developer Tools	3.28.0.v202211200019

**Comment by nitind** [comment]
The Web Developer Tools and Wild Web Developer are different projects and installable Features. Which version of WWD are you using?

**Comment by mattcoz** [comment]
Oh, sorry, copied the wrong one.

 Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	1.0.1.202211231523

**Comment by vrubezhny** [comment]
@mattcoz Are you still using WWD v.1.0.1?
 Could you please try updating to the latest release - https://download.eclipse.org/wildwebdeveloper/releases/1.0.5/ ?

Also, could you please provide a minimal project configuration which allows to reproduce the issue and steps to reproduce?. Eclipse log files, Language Server logs and hs_err_pidXXX.log crash logs attached to the issue may also be helpful.

**Comment by mattcoz** [comment]
Ahh, I was checking for updates with the standard Eclipse update site, which was saying there were no updates. I added that one, now updated to 1.0.5. It seems to be working a little better, maybe. Still not working in some cases. I'll attach my log file, which looks like it might have some stack traces that are related. Where would the language server logs be?

[eclipse.log](https://github.com/eclipse/wildwebdeveloper/files/11410807/eclipse.log)

**Comment by vrubezhny** [comment]
@mattcoz First - you have to enable the language server logs for "JavaScript-TypeScript Language Server" in "Window -> Preferences -> Language Servers -> Logs" preference page.
If you select "Log to File", the log files will be stored in "<Your Workspace Folder>/languageServers-log" directory which can be imported as an eclipse project.
