### ISSUE TITLE
Latest release won't install in updated Eclipse due to C++ clashes

### ISSUE THREAD

**Issue by davydnorris** [eclipse/wildwebdeveloper#454]
Just got a notification that 0.10 was available to install and tried to update, and it failed due to multiple packages that are installed as part of the CDT. Been working my way through them and uninstalling what I don't need but this is the latest affected by the clash:

```
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 1.6.0
  Software currently installed: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
  Cannot satisfy dependency:
    From: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tools.templates.freemarker.java11 [1.1.100.202001140305,1.1.100.202001140305]
  Cannot satisfy dependency:
    From: Template Engine Freemarker Support (Java 11) 1.1.100.202001140305 (org.eclipse.tools.templates.freemarker.java11 1.1.100.202001140305)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))
```

Other packages with exactly the same clash included Meson and CMake Previews

**Comment by akurtakov** [comment]
Solution is described in https://www.eclipse.org/lists/cdt-dev/msg34492.html . Also I strongly recommend updating to Java 11 now as the September release will have a hard requirement on it.
As this is not wildwebdeveloper issue and solution is known I'm closing this one.

**Comment by davydnorris** [comment]
Many thanks - will follow through the article
