### ISSUE TITLE
Selected text almost invisible

### ISSUE THREAD

**Issue by qtxo** [eclipse/wildwebdeveloper#456]
In Eclipse 2020-06 upgraded from older versions.
When I select any text in a Generic editor with JS, HTML, CSS, etc, the selected block of text is almost invisible, in the screenshot I selected the text "clearArrays" which is barely readable:

![image](https://user-images.githubusercontent.com/9822844/85934923-91872f00-b91c-11ea-8dcd-f7a89c7f1b3e.png)

The text selection works fine in the non wwwd editors. 
When I go to Preferences / Editor / Text Editors and change the "Selection foreground color" then the problem goes away BUT it comes back again after Eclipse restart! I have to force some change in "Selection foreground color" to fix the selection every time.

 I used to have DevStyle installed in previous versions and it may have left some things... but afaik it is all removed.

**Comment by qtxo** [comment]
**Problem solved** by cleaning the file `workspace\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.eclipse.ui.editors.prefs`
Old contents:

```
AbstractTextEditor.Color.Background.SystemDefault=false
AbstractTextEditor.Color.SelectionBackground.SystemDefault=false
AbstractTextEditor.Color.SelectionForeground.SystemDefault=false
eclipse.preferences.version=1
lineNumberRuler=true
overviewRuler_migration=migrated_3.1
predarkestdark.AbstractTextEditor.Color.Background.SystemDefault=false
predarkestdark.AbstractTextEditor.Color.SelectionBackground.SystemDefault=false
predarkestdark.AbstractTextEditor.Color.SelectionForeground.SystemDefault=false
spacesForTabs=true
textDragAndDropEnabled=false
```

New
```
eclipse.preferences.version=1
lineNumberRuler=true
overviewRuler_migration=migrated_3.1
spacesForTabs=true
textDragAndDropEnabled=false
```

**Comment by AObuchow** [comment]
@qtxo thanks for the update! Glad your issue is resolved :)

**Comment by mickaelistria** [comment]
Comments highlight that the issue was caused by the Darkest Dark Theme.
