### ISSUE TITLE
WWD in Eclipse with WDT ignores custom syntax highlighting

### ISSUE THREAD

**Issue by LigH-de** [eclipse/wildwebdeveloper#460]
With the update to 2020-06, Eclipse removed the JSDT, I was told in IRC; so I installed the Web Development Tools from the Marketplace, including Wild Web Developer to support JavaScript development with syntax highlighting.

In my Eclipse Preferences I still have the branch: Web > HTML Files > Client-side JavaScript > Editor > Syntax Coloring; custom styles are still available.

But the displayed syntax coloring in an opened editor for a separate *.js file is not at all like the custom styles I defined.

My "Installation Details" still list:
>  JavaScript Development Tools	2.2.0.v202005251709	org.eclipse.wst.jsdt.feature.feature.group	Eclipse Web Tools Platform

Not sure if this is a mistake...

**Comment by mickaelistria** [comment]
This syntax highlighting settings come for WTP/JSDT and affect the JavaScript inside HTML file when using the HTML Editor from WTP. This is not something Wild Web Developer can change.
To change the highlighting in Wild Web Developer with the Generic Editor, either try right-click > Switch Theme... on the editor, or go to Preferences > TextMate > Themes.

**Comment by LigH-de** [comment]
So if I don't like the syntax coloring the themes provide, may it be possible to edit the associated CSS files (or even add my own)?

**Comment by mickaelistria** [comment]
Ideally yes, that's the topic of https://github.com/eclipse/tm4e/issues/249 (and other related issues in tm4e). Contributions there would be really welcome!

**Comment by LigH-de** [comment]
Unfortunately, these themes are archived in the `org.eclipse.tm4e.ui_{version}.jar` file. To allow customization, it would be necessary for TextMate to accept directly accessible CSS files to override or add a style, or customizations would be lost at the next update of this component...
