### ISSUE TITLE
JS formatting and syntax checking does not work in mixed content source files.

### ISSUE THREAD

**Issue by trenshaw** [eclipse/wildwebdeveloper#466]
JSDT formerly packaged with PDT prior to Eclipse 2020-06 would format and syntax check JavaScript within mixed content source files e.g. PHP view templates containing PHP code and JS within <script></script> blocks.

WWD packaged with PDT in Eclipse 2020-06 no longer provides JS highlighting, formatting or syntax checking in mixed PHP and JS source files.

**Comment by mickaelistria** [comment]
This seems like an issue in PDT or in the PHP package, please report it to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EPP&component=php-package or https://github.com/eclipse/pdt/issues
