### ISSUE TITLE
Upgrade Yaml Language Server to 0.9.0

### ISSUE THREAD

**Issue by apupier** [eclipse/wildwebdeveloper#475]
currently 0.8.0 https://github.com/eclipse/wildwebdeveloper/blob/a68554cfef70c8dc0f465e48e7fe206352667bbc/org.eclipse.wildwebdeveloper/pom.xml#L126

see changelog https://github.com/redhat-developer/yaml-language-server/blob/master/CHANGELOG.md#090

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/commit/7362293f6bc2bd741916f1e7858e2d0c1fb39275
