### ISSUE TITLE
What's the purpose for Wild Web Developer's XML content type?

### ISSUE THREAD

**Issue by nitind** [eclipse/wildwebdeveloper#481]
It's not possible to have a running configuration without the Platform's type, so is it needed? How is it handled differently?

**Comment by mickaelistria** [comment]
Good question ;) I cannot recall one particular reason why not using the platform's content-type. So +1 for trying to switch t it.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/wildwebdeveloper/commit/e2fdc5f70cd03619ad2ff8b9a37960da1342bac2 , and soon  available at https://download.eclipse.org/wildwebdeveloper/snapshots/ for testing.

**Comment by nitind** [comment]
@mickaelistria Looks like a typo was introduced in https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.xml/plugin.xml#L17 , possibly breaking your presentation reconciling.

**Comment by mickaelistria** [comment]
Damn. I tried it and found it working, but I was maybe in some intermediate state... Would you like to submit a PR? Just editing the file with GitHub should allow to build a PR trivially.

**Comment by nitind** [comment]
Submitted https://github.com/eclipse/wildwebdeveloper/pull/486 . It did require cloning in order to do the sign-off.

**Comment by mickaelistria** [comment]
Thanks a lot @nitind ! For the Signed-Off-By, I usually type it manually in the comment when creating the commit with GitHub UI, and it works for me.
