### ISSUE TITLE
Update from 0.10.0 to 0.10.1: JS files lost integration

### ISSUE THREAD

**Issue by LigH-de** [eclipse/wildwebdeveloper#487]
After the recent update to Wild Web Developer 0.10.1.202007101231, the *.js files in a PHP website project are not recognized as JavaScript source files anymore and loaded as plain text files, TextMate does not highlight their syntax anymore.

PS: In the Editor definitions for content types, a "JavaScript" node exists in the WWD supported types branch, but it is only assigned to generic text editor types. And I am not sure which other editor types I could add instead.
![eclipse_WWD_editors](https://user-images.githubusercontent.com/5917225/88032042-b3e82300-cb3d-11ea-8496-e89e782b3efb.png)

**Comment by jabby** [comment]
Hello @LigH-de 

You should use Generic Editors for all files supported by Wild Web Developer.  Can you try and comment if it works for you?

**Comment by LigH-de** [comment]
The Content Type for JavaScript source files has "Generic Text Editor" and "Text Editor" associated.

In the Project Explorer, *.js files have the "Text editor" icon, the Editor tab handle has the "Text editor" icon as well.

**Comment by jabby** [comment]
Can you check what is the file association in General > Editors > File Associations
You should have the following configuration. If you don't make Generic Editor the default one for `*.js` files.

![js-file-association](https://user-images.githubusercontent.com/1883932/88055379-2a494d00-cb5f-11ea-8ad9-cf5c84b78b89.png)

**Comment by LigH-de** [comment]
I made "Generic Text Editor" the default for *.js and restarted Eclipse. Now *.js files have the [JS] icon in the Project explorer and are opened with a TextMate highlighted editor.
