### ISSUE TITLE
Integrate eslint language server

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#49]
ESLint is very used in JavaScript word. It seems that VSCode provides an eslint language server https://github.com/Microsoft/vscode-eslint/blob/master/server/src/server.ts

I think it should  be interesting to integrate it but activate with some condition like:

 * search if it exists an eslint.json in the project root
 * force the activation of the eslint language server with a preferences.

In other words:

 * BlueSky could be attractive for JavaScript developers.
 * It's a new use case to activate language server with some conditions.

**Comment by mickaelistria** [comment]
Sounds like a good idea! Do you know which kind of features is provided by the eslint server? Is there more than diagnostics?
If it's only about diagnostic, I think it could be a separate bundle, that we could suggest as addition to JSDT later (and consume in BlueSky).

**Comment by angelozerr** [comment]
> Is there more than diagnostics?

Never played with it. But you can see feature support at https://github.com/Microsoft/vscode-eslint/blob/master/server/src/server.ts#L591

**Comment by angelozerr** [comment]
For the moment vscode-eslint doesn't support --stdio

We must wait for https://github.com/Microsoft/vscode-eslint/issues/290

**Comment by mniewrzal** [comment]
> For the moment vscode-eslint doesn't support --stdio

But does it have LSP support? Maybe it supports TCP/IP communication?

**Comment by angelozerr** [comment]
According https://github.com/Microsoft/vscode-eslint/blob/master/server/src/server.ts#L289 it supports IPC

`let connection = createConnection(ProposedFeatures.all, new IPCMessageReader(process), new IPCMessageWriter(process));`

I have tried to replace this code with 

`let connection = createConnection()`

like JSON, CSS Language server does (it search for instance if stdio is in the args), but it failed at https://github.com/Microsoft/vscode-eslint/blob/master/server/src/server.ts#L303

`resultPromise = connection.workspace.getConfiguration({ scopeUri: uri, section: '' }).then((settings: TextDocumentSettings) => {
`
because connection.workspace is null (it's not a standars LSP connection).

**Comment by mickaelistria** [comment]
LSP4E doesn't require stdio and can work with any stream. However, AFAIK,
there is no good Java client for IPC that would allow to easily build a
stream.

**Comment by mickaelistria** [comment]
We're now using typescript-language-server from Typefox/Theia. Is ESLint still useful with this language server?

**Comment by angelozerr** [comment]
> Is ESLint still useful with this language server?

Typefox/Theia can support tslint by using the plugin https://github.com/angelozerr/tslint-language-service

So you can define lint rules with tslint. Some user could prefer ESLint which works only with JS if I remember.

**Comment by mickaelistria** [comment]
I'm closing it in favor of #145
