### ISSUE TITLE
Missing preferences for fromatting JavaScript source files

### ISSUE THREAD

**Issue by Fred-Feuerstein** [eclipse/wildwebdeveloper#492]
In the preferences of Eclipse 2020-06 there is no way to define the formatting rules for JavaScript source file in the generic editor. 

The HTML-Editor has such preferences, but they do not apply to plain JavaScript source files.
![grafik](https://user-images.githubusercontent.com/69150953/89182072-3ab4eb00-d595-11ea-98cf-bdbb4c5f13fd.png)

I think it's an important feature to customize the formatting of JavaScript files. Otherwise I cannot adhere the coding styleguide for my project and I can't use this editor.

**Comment by mickaelistria** [comment]
This formatter comes from the Eclipse WebTools project that is not part of Wild Web Developer (and its preferences are ignored by the Generic Editor with Wild Web Developer).
Formatting is provided by the language server ( https://github.com/theia-ide/typescript-language-server ).

**Comment by Fred-Feuerstein** [comment]
Thanks for the answer. I don't know the details of the communication between Eclipse and the language server. As far as I understand, the formatting is done by the language server, but the file and the formatting options are sent from the client (Eclipse) to language server. Here is an extract of the the language server log, where I can see the formatting options that are sent to the server:

[t=1596459275476] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"8","method":**"textDocument/formatting**","params":{"textDocument":{"uri":"file:///D:/usr/gasx/core30vm_oracle/src/dialogs/gulpfile.js"},**"options":{"tabSize":4,"insertSpaces":false}**}}

So from my point of view there must be some way to configure the formatting options in Eclipse. I think I cannot configure the formatting options on the Language server side.

**Comment by mickaelistria** [comment]
Those default preferences are defined in WIndow > Preference > Editor > Text Editor.
Currently, there is no way to define indentation preferences per file/content-type.

**Comment by mbratch** [comment]
Using general Text Editor settings to set indentation size for a language seems very broad. Any other language-sensitive editor, such as Visual Studio Code, allows settings specific to any language since user preferences can vary between languages. Eclipse is an otherwise very powerful IDE supporting a small variety of programming languages. It seems odd that it can't support a different indentation for formatting for each language. Do all such feature requests just get closed?

**Comment by norbertroamsys** [comment]
I have the same opinion than @mbratch : There SHOULD be an extra settings block for JavaScript language!
In general the editor is a good alternative to Visual Studio Code. But this feature is still missing any may lead to using MS product instead. We also had some frustration for getting the formatter to do what is needed for our coding standards.
