### ISSUE TITLE
Number of org.eclipse.lemminx.XMLServerLauncher increases after branch switch 

### ISSUE THREAD

**Issue by thomasulllrich** [eclipse/wildwebdeveloper#493]
Hi!
Everytime I switch in Eclipse 2020-06 to another branch and open an arbitrary xml file there are more java processes with the main class org.eclipse.lemminx.XMLServerLauncher started(1,3,9,14 number of Java processes). I can close the xml-file before the switch and open it afterwards or keep it open while the switch happens, it always ends up with the same number of processes. Is there a workaround or a configuration option because I don't want to restart after each branch switch my Eclispe again.
Best regards,
Thomas

**Comment by ranezu** [comment]
Every time I open Maven pom.xml files, I get lots of new XMLServerLauncher processes. Opening the file takes minutes, and if I open lots of them, my entire Ubuntu 18.04 gets overloaded (100% CPU) and all applications are really sluggish. Currently I have 84 of these processes running after opening maybe 5 pom.xml files, and the system is completely unusable.

My Eclipse version is 2020-06.

**Comment by mickaelistria** [comment]
Can you please try upgrading to latest m2e from https://download.eclipse.org/technology/m2e/releases/latest/ ? It does include a newer release of lemminx-maven, which might have fixed it. Installation may also require a newer version of org.eclipse.wildwebdeveloper.xml bundle, that you can get by adding https://download.eclipse.org/wildwebdeveloper/releases/latest/ to the known sites.

**Comment by dcheung2** [comment]
I've `$ ps ax | grep XMLServerLauncher | wc -l`  
112

Is there a way to workaround or turn it off ?

**Comment by mickaelistria** [comment]
See comment above. Please first try upgrading to latest release of Wild Web Developer.

**Comment by dcheung2** [comment]
I believe I am on latest stable. 
Eclipse 2020-06
Wild Web Developer, 0.10.2.202008281220

**Comment by dcheung2** [comment]
The link https://download.eclipse.org/wildwebdeveloper/releases/latest/ is already the known list. and update eclipse tell me I am up to date. 

I press the update it quite often, what I could to do force it update ?

**Comment by mickaelistria** [comment]
Try installing manually from the p2 repo as you were installing for the 1st time, you'll see the cause of why it doesn't install.
I guess it's the older m2e release still tied to older Wild Web Developer, so you may also want to update m2e as advised in https://github.com/eclipse/wildwebdeveloper/issues/493#issuecomment-690907115 .

**Comment by dcheung2** [comment]
While I am still finding a way to upgrade it.

But I should let you know what I was not editing any XML file, nor edited any XML file in last few hours.
It happened to me suddenly when I am compiling a GWT project which as a lots of ui.xml files.

**Comment by dcheung2** [comment]
I open https://download.eclipse.org/wildwebdeveloper/releases/latest/, https://download.eclipse.org/wildwebdeveloper/releases/latest/features/ in browser.
It seem only have 10.2.202008281220

Is there another repo /update site ?

**Comment by dcheung2** [comment]
found it https://download.eclipse.org/wildwebdeveloper/releases/

**Comment by dcheung2** [comment]
https://download.eclipse.org/wildwebdeveloper/releases/0.11.1/ still point me to 0.10.2

**Comment by mickaelistria** [comment]
Sorry about the confusion, bundle 0.10.2 is actually the latest version (project version = 0.11.1) != (bundle verison = 0.10.2).
The hint about generated XML files is very useful and can indeed lead us to the source of this bug! Would you be able to build a very minimal project to reproduce the issue with such generated XML?

**Comment by thomasulllrich** [comment]
Today I updated to Eclipse 2020-09. Tried to change some of the xml-files and again a lot of Java processes pop up. Do you have any idea how to solve this problem?

**Comment by mickaelistria** [comment]
No idea at the moment. We need clear deterministic steps to reproduce the issue so we can investigate. If you can share a minimal project , the necessary Eclipse IDE configuration and steps to reproduce the issue; then we'll be able to make progress.

**Comment by thomasulllrich** [comment]
I have deleted my Eclipse projects metadata and created all my Eclipse projects new. Since then it is working without problem
