### ISSUE TITLE
Disable GenericEditor for JavaScript

### ISSUE THREAD

**Issue by p-bakker** [eclipse/wildwebdeveloper#494]
Hi,

I'm trying to use Wild Web Developer mainly for TypeScript support in an Eclipse instance that also has DLTK installed for JavaScript support.

Unfortunately I cannot use WWD for JavaScript as my js usage is a DSL which has tailored support in Eclipse utilizing DLTK.

No the problem is that I'm trying to prevent .js files from opening in the Generic Editor that WWD uses for JS and instead keep using the DLTK Editor, but cannot get this to work...

I tried through File Associations, setting the DLTK Editor as default, tried removing the the mapping for .js files completely and creating a new one etc etc, but when I doubleclick a .js file, for example in the Search view or Call Hierarchy view, it keeps opening in the Generic Editor of WWD.

Now, don't know if I'm missing something in my config attempts (although I tried many things and scoured the web) or maybe that this is an Eclipse issue and not WWD-specific, but raising it here in case it is WWD specific or at least to get some insight

**Comment by jabby** [comment]
Which version of WWD do you use? I guess you faced the problem fixed with thie following commit. 
https://github.com/eclipse/wildwebdeveloper/commit/3372c5e3eea86bd392d54543b28709b8b56bd557

Can you upgrade to the latest version of WWD?

**Comment by p-bakker** [comment]
Tnx for your response. That indeed looks like the same issue.

Am using WWD   0.10.0.202006021616 on Eclipse 2020-06

Got WDD through the https://download.eclipse.org/releases/2020-06/ update site.

Prior to that I tried to install the WWD snapshot through http://download.eclipse.org/wildwebdeveloper/snapshots, but that didn't work due to conflicts

**Comment by jabby** [comment]
Can you try with this updatesite? https://download.eclipse.org/wildwebdeveloper/releases/0.11.0/

**Comment by p-bakker** [comment]
Same problem, but I doubt it is due to an issue with WWD. Its more an issue of me depending on another feature addon in Eclipse which dependencies clash with WWD dependancies:

 `Cannot complete the install because of a conflicting dependency.
  Software being installed: Wild Web Developer 0.10.1.202007101231 (org.eclipse.wildwebdeveloper.feature.feature.group 0.10.1.202007101231)
  Software currently installed: Servoy Developer 2020.6.0.3582 (servoy.product 2020.6.0.3582)
  Only one of the following can be installed at once: 
    Core Runtime 3.17.100.v20200203-0917 (org.eclipse.core.runtime 3.17.100.v20200203-0917)
    Core Runtime 3.18.0.v20200506-2143 (org.eclipse.core.runtime 3.18.0.v20200506-2143)`

**Comment by mickaelistria** [comment]
I believe this is fixed in latest Wild Web Developer release. So I'm going to close this issue as there is nothing more Wild Web Developer can do there.

**Comment by mickaelistria** [comment]
I believe this is fixed in latest Wild Web Developer release. So I'm going to close this issue as there is nothing more Wild Web Developer can do there.
