### ISSUE TITLE
Launch NPM run configuration does not work on windows

### ISSUE THREAD

**Issue by kascaks** [eclipse/wildwebdeveloper#495]
When launching NPM run configuration, launcher tries to execute command utility `npm` from node installation. However, on windows, the command utility is named `npm.cmd`. Launching fails with error stating that `"C:\Program Files\nodejs\npm" is not a valid Win32 application`

It is possible to work around the problem by renaming the `npm` to e.g. `npm.x`. After this, `where npm` will locate only the `npm.cmd` in PATH and launching runs OK.

However, with version 0.11.0, embedded node.js is introduced and since npm in embedded node installation is not found by `where npm`, it is not possible to use embedded node.js on windows even with workaround.

**Comment by mickaelistria** [comment]
Do you have the node.js embedder feature and windows-specific fragment installed? Does the issue hapen with or without it?

**Comment by kascaks** [comment]
I'm not sure how to answer.
I have `eclipse 2020-06 (4.16.0)` and I used Help -> Install new software... with `repository https://download.eclipse.org/wildwebdeveloper/releases/latest/` to upgrade wild web developer. In plugins directory of my workspace I see `<workspace>\.metadata\.plugins\org.eclipse.wildwebdeveloper.embedder.node\node-v12.16.1-win-x64`. In eclipse Help -> About Eclipse IDE -> Installation Details -> Installed Software I see `Wild Web Developer 0.10.1.202007101231` (and `Wild Web Developer XML tools 0.10.1.202006201747`)

**Comment by mickaelistria** [comment]
Was it working with 0.10.0?

**Comment by kascaks** [comment]
Not really. I had to use a workaround mentioned above where I renamed file `npm` (in standalone node installation) to e.g. `npm.x`

**Comment by mickaelistria** [comment]
So do I get it right that, on Windows, we should just have Wild Web Developer look for `npm.bat` if `npm` is not found?

**Comment by mickaelistria** [comment]
I recently merged a patch that should fix that. Can you please try to install snapshot from https://download.eclipse.org/wildwebdeveloper/snapshots/ and report whether things work better for you now?

**Comment by mickaelistria** [comment]
I'm going to close the issue to track that as far as we know, not further work is required here. Feel free to reopen after testing if this is not fixed with latest snapshot! Thanks in advance

**Comment by kascaks** [comment]
I confirm that it works now as expected. I tested with embedded node.js as well as with standalone installation (without workaround by renaming npm to npm.x). Thanks for fixing the issue.
