### ISSUE TITLE
Update site has different version to releases

### ISSUE THREAD

**Issue by a1dutch** [eclipse/wildwebdeveloper#510]
Hi,

The latest eclipse snapshot update site is showing version 0.10.2 but the latest tag/release in github shows 0.11.1.

Is this as expected?  it seems very confusing and maybe they could be aligned.

Cheers

Andy

**Comment by mickaelistria** [comment]
Yes, it is expected.
To ensure long term sustainability, Wild Web Developer uses semantic versioning for individual bundles (similarly to Eclipse Platform). And while different bundles (wildwebdeveloper vs wildwebdeveloper.xml) do evolve separately, it doesn't bring anything to align the versions of both bundles and the "marketing" version of the project with the "technical" version of the bundles.
