### ISSUE TITLE
Missing Format command in TypeScript files.

### ISSUE THREAD

**Issue by 4javier** [eclipse/wildwebdeveloper#515]
I apologize in advance because I'm quite sure this is not a bug, but just my lack of knowledge, thus it's more an info request than a bug ticket.
My system doesn't show Format command nor Source submenu in context menu for .ts files.
I got at least one of them for HTML, JS, CSS, righ-clicking on filename in package explorer, or inside the generic text editor they're open with.
I think this got something to do with WDT: can I uninstall it, or it's still deeply bound to Eclipse core?
Another question:
these are the Language Servers on my system
![immagine](https://user-images.githubusercontent.com/459381/92411060-a5ce8000-f146-11ea-8e4c-2e5e710132ed.png)
The two ones which I disabled in the picture, are garbage from the Angular plugin that I uninstalled some times ago, or come from your project?

**Comment by mickaelistria** [comment]
Which version of Eclipse IDE and Wild Web Developer are you using?
Are you opening your files with the Generic Editor or some other editor?
You can install whatever you want, the IDE will tell you if this also remove other components and then you can decide whether it's OK for you or not.
The Angular Language Server comes from Wild Web Developer too, but if you don't use Angular, it's a good thing to disable it and this should be related to your issue.

**Comment by 4javier** [comment]
Spring Tool Suite Eclipse Version: 4.7.1.RELEASE Build Id: 202007271558
Wild Web Developer	0.10.2.202008281220	
I open the files with Generic Text Editor
I'm actually working on Angular, thus I'll re-enable those two language servers.

AND NOW I GOT CONTEXT MENU INSIDE EDITOR AGAIN. 

I don't know what the problem was. Sorry for wasting your time.
Anyway, this is the prompt when I try to uninstall WDT
![immagine](https://user-images.githubusercontent.com/459381/92414135-2a270000-f153-11ea-9fa7-dea28082a90d.png)

**Comment by mickaelistria** [comment]
Thanks for reporting it works. Closing.
