### ISSUE TITLE
[XML] Formatting preferences page

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#516]
LemMinX provides several formatting settings (see https://github.com/redhat-developer/vscode-xml/wiki/Formatting but I need to update this page because it misses some settings).

We have the intention to improbe formatting again like xsi:schemaLocation content formatting https://github.com/eclipse/lemminx/issues/825 or formatting settings for spaces, mixed content, etc

IMHO I think this XML formatting preferences page is very important to provide the same (and more) features than WTP XML Editor about format features.

**Comment by mickaelistria** [comment]
Dup of #139
