### ISSUE TITLE
Upgrade Yaml Language Server to 0.10.1

### ISSUE THREAD

**Issue by apupier** [eclipse/wildwebdeveloper#518]
https://github.com/redhat-developer/yaml-language-server/releases/tag/0.10.1

https://github.com/redhat-developer/yaml-language-server/blob/0.10.1/CHANGELOG.md#0101

noticeably feature:
Allows to declare a schema inside the yaml file through modeline # yaml-language-server: $schema=<urlOfTheSchema>

**Comment by mickaelistria** [comment]
Note that in such case, it's fine if you just send the PR without filing an issue.

**Comment by mickaelistria** [comment]
CQ opened at https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22581 , I don't think there is further action to take from Wild Web Developer perspective, so let's close.
Thanks a lot for the contribution!
