### ISSUE TITLE
wich()?

### ISSUE THREAD

**Issue by ilg-ul** [eclipse/wildwebdeveloper#525]
In the README associated with the org.eclipse.wildwebdeveloper.embedder.node project:

https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.embedder.node/README.md

I read:

```js
NodeJSManager.wich("node")
```

Is this spelling intentional? As far as I know, the English spelling is _which_.

**Comment by akurtakov** [comment]
It's a typo in the README file, method name is correct. Fixed now.

**Comment by ilg-ul** [comment]
Ok, thank you.
