### ISSUE TITLE
HTML Formatting Greyed Out

### ISSUE THREAD

**Issue by adamhenderson** [eclipse/wildwebdeveloper#528]
Hi,

I hope this is just user error but is there a reason why the HTML formatting command is greyed out and not available.

Fresh install of 2020-09 Mac & Windows, same behaviour.

**Comment by nitind** [comment]
A screenshot of this might be helpful.

**Comment by mickaelistria** [comment]
The cause is that something changed recently in the LS and the formatting support needs to be explicitly enabled in initialization options: https://github.com/microsoft/vscode/blob/58bb7b2331731bf72587010e943852e13e6fd3cf/extensions/html-language-features/server/src/htmlServer.ts#L158

**Comment by AmigaAbattoir** [comment]
This happens for me not only if using Generic Editor for HTML, but also on JS and JSON files. When I open files, everything that should be black is greyed out. If I switch themes, it appears fine until the file gets saved:

If I switch themes back to Eclipse Dark, everything looks fine:
![Screen Shot 2020-09-22 at 9 11 30 AM](https://user-images.githubusercontent.com/6256023/93886987-17b0d880-fcb4-11ea-88de-aaa00e9d617a.png)

Hit save and then everything goes grey:
![Screen Shot 2020-09-22 at 9 11 37 AM](https://user-images.githubusercontent.com/6256023/93886992-1a133280-fcb4-11ea-940b-b7e510876026.png)

Is this related, or should this be another ticket?

**Comment by mickaelistria** [comment]
Now I'm unsure about the purpose of the initial comment. @adamhenderson where you talking about the "Format" command, or about the color scheme?
@AmigaAbattoir your theme seems to be non standard. Does it work with default themes?

**Comment by AmigaAbattoir** [comment]
> @AmigaAbattoir your theme seems to be non standard. Does it work with default themes?

Sorry, after re-reading @adamhenderson initial marks, I realize that it's a different issue. I opened a new issue #536 for this.

**Comment by adamhenderson** [comment]
Yes, I'm reporting that the formatting command is non functional and 'greyed out' as in 'not available', my issue is not related to theming.
