### ISSUE TITLE
WWD does not support Source menu options Format and Comment

### ISSUE THREAD

**Issue by KlaasBonnema** [eclipse/wildwebdeveloper#529]
Eclipse PDT users have been cut off from using the JSDT javascript editor since 2020-06. The recommendation is to use WWD instead where WWD has much better support for recent javascript language features. 
However WWD is lacking a number of features that make life easier for a programmer. Specifically these are the options found under the Source menu with other editors, including JSDT. (The Generic Text Editor that WWD is using does not have a Source menu.)
The various Comment options used to quickly comment or uncomment a block of code are missing.
The Format options to nicely format javascript code according to user preferences are missing.

**Comment by mickaelistria** [comment]
Can you please open distinct issues for each item?

**Comment by mickaelistria** [comment]
I can see a "Source" context-menu with various comment options and format in it as well. I think it got fixed in LSP4E with https://git.eclipse.org/c/lsp4e/lsp4e.git/commit/?id=dacb83fcc81e05db42b16a3ead5077704f38fb9a
Please try latest release, and open specific issues for each thing you find missing.

**Comment by KlaasBonnema** [comment]
WWD has a context (right click) menu Source. However there is no top level menu Source as there is for other Eclipse editors. 
I have no idea where I need to direct a bug report to get that fixed.
Please also note that the Source->Format context menu command is present but beware if you use it, Your source code will be screwed instead of formatted.
I get confused by "Please try latest release" above. My Eclipse system gets regular updates for WWD but they don't seem to be the "latest". I just applied the Eclipse update for 2021-03 and it does not seem to have a new WWD component. In general I will not update a separate component in my Eclipse system unless I have very clear instructions about how and why. I will not risk an unfunctional system.

**Comment by mickaelistria** [comment]
> However there is no top level menu Source as there is for other Eclipse editors.

This is https://bugs.eclipse.org/bugs/show_bug.cgi?id=567247

> Your source code will be screwed instead of formatted.

Please open a dedicated ticket for this issue.

>  get confused by "Please try latest release" above. My Eclipse system gets regular updates for WWD but they don't seem to be the "latest".

Which version of `org.eclipse.wildwebdeveloper` do you see in Help > About > Installation details > Plugins. Latest one is 0.5.14.202102181620 as you can see in https://download.eclipse.org/wildwebdeveloper/releases/latest/plugins/

**Comment by KlaasBonnema** [comment]
Help > About > Installation details > Plugins:
Eclipse Wild Web Developer project	Wild Web Developer: web development in Eclipse IDE	0.5.15.202103050806	org.eclipse.wildwebdeveloper.

       Help > About > Installation details > Installed software:
  Wild Web Developer	0.10.7.202103081410	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project.

I did not guess I need to look at Plugins when the first available entry is at Installed software. 
Thanks for clarifying this.

**Comment by mickaelistria** [comment]
Since Wild Web Developer use semantic versioning, bundles and features can have different versions. It can be a source of confusion when you're unaware of it, but the value on quality and update/download is huge: it allows to not rebuild/redeliver/reship/redownload another version of the plugin if there has been no change.
