### ISSUE TITLE
WWD does not have options to comment or uncomment a block of code

### ISSUE THREAD

**Issue by KlaasBonnema** [eclipse/wildwebdeveloper#532]
WWD is lacking a number of features that make life easier for a programmer. 
Specifically these are the options found under the Source menu with other editors, including JSDT. (The Generic Text Editor that WWD is using does not have a Source menu.)
Comment options used to quickly comment or uncomment a block of code are missing.

**Comment by mickaelistria** [comment]
You can use Ctrl+Shift+C to comment multiple lines at once.

**Comment by KlaasBonnema** [comment]
That is a usefull comment. You can also use Ctrl+Shift+C to uncomment multiple lines.
I would not know how to find this shortcut...

Other Eclipse Editors use Ctrl+7 to Toggle comments for multiple lines. They also have Ctrl+Shift+/ to add a block comment (/*  */) or remove it with Ctrl+Shift+\
Also available is Generate Element Comment: Alt+Shift+J
All of these are easy to find in the Source dropdown menu.

**Comment by mickaelistria** [comment]
> I would not know how to find this shortcut...

Window > Preferences > General > Keys would help.
Also, at least on Linux, shortcut is visible via context-menu/right-click on editor > Source > Toggle Comments.
Ctrl+Shift+C is the most standard shortcut, as it also works for languages that comments with `#` or other.
Block comment support is indeed missing, but to be honest, it's low priority.

**Comment by KlaasBonnema** [comment]
Window > Preferences > General > Keys mentions 17 times Toggle Comment with three variations: Ctlr+/, Ctrl+7 and Ctrl+Shift+C.
It also has about the same amount for other Comment actions like Block comment.

I don't know about Linux but the editor context menu does not directly give the Toggle Comment shortcut but it does have a Source option. And here I find the Toggle Comment but also the Add and Remove Block Comment. And the Add Block comment actually adds /* and */ around the code block.

I think the question now becomes - why don't we see the a top menu Source as with the other editors.

**Comment by mickaelistria** [comment]
Let's close the issue as there are context menus and shortcuts for comments. I don't think there is need for more.
Can you please report the issue about missing "top-bar" menu for Source to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform&component=Text ?

**Comment by KlaasBonnema** [comment]
Done
Reference: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567247
