### ISSUE TITLE
Outline sort order cannot be changed

### ISSUE THREAD

**Issue by KlaasBonnema** [eclipse/wildwebdeveloper#534]
The WWD Outline displays items in the same order as in the source code. It would be valuable to be able to change the outline sort order to alphabetic. This option is available in other editors such as JSDT.

**Comment by fujiokae** [comment]
I have the same problem. Alphabetic order is a must for a long JS file. There are more icons (Hide Vars, Collapse All etc) in the Outline View in JSDT, all of which are very useful. Please upgrade the WWD Outline View as now JSDT is outdated and I will have to switch to WWD completely in a near future.

**Comment by IraNostraEst** [comment]
👍 (+1)

**Comment by mickaelistria** [comment]
Recent versions of LSP4E have a feature to sort alphabetically, see https://github.com/eclipse/lsp4e/pull/1 . To leverage it, please install a more recent version of LSP4E and click the button to sort alphabetically.

**Comment by KlaasBonnema** [comment]
Can you help us out here to clarify "install a more recent version of LSP4E".
I just upgraded Eclipse to the 2012-12 release. I looked at installed components but I did not find LSP4E listed.
I would not know how to upgrade LSP4E to a higher version even if I had found it and I doubt it is a good decision to upgrade a single component of an Eclipse release based on "get a higher level".
A practical answer might be to confirm that the new LSP4E will be included in the 2022-03 release of Eclipse.
If it is a sensible action to upgrade just LSP4E for Eclipse 2021-12 then please add instructions on how to do that.

**Comment by mickaelistria** [comment]
>  I doubt it is a good decision to upgrade a single component of an Eclipse release based on "get a higher level".

Upgrading to newer versions is almost always a good decision. The Eclipse Platform and most projects use semantic versioning well enough to not make upgrade of individual components an issue.

Unfortunately, I admit that in the current state, p2 is not really good at encouraging those upgrades of transitive dependencies and taking care of them when necessary is a non-trivial task for most users. Let's hope things will improve in the future.

> A practical answer might be to confirm that the new LSP4E will be included in the 2022-03 release of Eclipse.

It will be.

>  please add instructions on how to do that.

README file https://github.com/eclipse/lsp4e/ contains instructions where to find latest release.

**Comment by KlaasBonnema** [comment]
Looking more closely I found that there is now a "Sort Outline" button (A|Z) in the outline window when a javascript file is open in Eclipse 2021-12. Clicking it does what you want - toggle between alphabetic and file order.

As a note - when you open a different file type (php) then there are two A|Z buttons, the second one called "Sort". It is the second A|Z button that works for php and the first one seems non-functional.

I looked at the LSP4E readme and found the repository link that you can use to install the latest version in Eclipse. The current release version is 0.20.1 (Nov 21) and the previous version 0.20.0 (Nov 9). 
I cannot find a reference in the changelog about adding the sorted outline feature.
Now I go to Eclipse and look at Help-> About-> Installation details. LSP4E is not to be found in the installed software list. In the Plugins list I find a reference for LSP4E with version 0.13.8.202111241523. That gives me nothing to relate to the release versions mentioned in the LSP4E changelog. I other words - I cannot tell which version of LSP4E was integrated in my version of Eclipse.
