### ISSUE TITLE
Editor color wrong on opening or saving. correct when applying theme

### ISSUE THREAD

**Issue by ProfPollati** [eclipse/wildwebdeveloper#536]
When I'm using the Generic Editor for HTML, JS and JSON and I open files, regular text that should be black is a light grey. If I switch themes, the black text appears fine until the file gets saved:

If I switch themes back to Eclipse Dark, everything looks fine:
![Screen Shot 2020-09-22 at 9 11 30 AM](https://user-images.githubusercontent.com/6256023/93886987-17b0d880-fcb4-11ea-88de-aaa00e9d617a.png)

Hit save and then everything goes grey:
![Screen Shot 2020-09-22 at 9 11 37 AM](https://user-images.githubusercontent.com/6256023/93886992-1a133280-fcb4-11ea-940b-b7e510876026.png)

Both screenshots are with the **Switch to Theme... -> Eclipse Dark** selected. I haven't added any themes to under **Preferences -> Textmate -> Theme**

I'm using **General -> Appearance** *Theme:* Dark.

I also have under **Preferences -> General -> Editors -> Text Editors** have different colors for *Appearance color options*

![Screen Shot 2020-09-22 at 10 25 40 AM](https://user-images.githubusercontent.com/13973323/93901951-0a501a00-fcc5-11ea-84dd-14a117639d85.png)

_Originally posted by @AmigaAbattoir in https://github.com/eclipse/wildwebdeveloper/issues/528#issuecomment-696719232_

**Comment by mickaelistria** [comment]
That's a quite confusing setup: the general theme seems dark (according to property page screenshot) and set the background color for the text editor to be white, but the actual background color in your editor screenshot is grey... I think TM4E (which provides the syntax highlighting) gets confused with this configuration, and applies a Dark highlighting while your editor background is mostly light.
This issue should be reported to TM4E, the culprit line is probably https://github.com/eclipse/tm4e/blob/f52ef37e230bd339df145a0b1bf8883e7f67af4c/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/internal/themes/AbstractThemeManager.java#L92 which doesn't take the actual editor background into account but instead relies on not so relevant theme id.

**Comment by mickaelistria** [comment]
Can you please open the issue to TM4E?

**Comment by ProfPollati** [comment]
Done: https://github.com/eclipse/tm4e/issues/256
