### ISSUE TITLE
[Question] Method to get the path to Embedded Node Instance

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/wildwebdeveloper#537]
There is a method that almost does what I need: `NodeJSManager.getNodeJsLocation()`. However, this call may return Node specified with `-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=<location>` or may return node from `/use/local/bin/` while i desire to get a node instance of some guaranteed version, i.e. 12.x that is embedded in **org.eclipse.wildwebdeveloper.embedder.node** plugin currently.

The reason for this is I'm planning to have an Eclipse plugin with embedded Node JS app (Terminal app - XtermJS from and node-pty backend). Don't want to run `npm install` when my plugin activates since internet connection may not be available. Don't want to package Node JS app into executable because it is 45Mb.
Idea is to run `npm install node-xterm` on Node 12.x (same as WWD embedded node) on Win/Mac/Linux and package the result into plugin fragments since **node-pty** install results is platform specific and generates different files on different platforms. Then, i just need to ensure that node used to compile my **node-xterm** package is compatible with the embedded Node from WWD (i.e version 12 currently)

Any chance `NodeJSManager.getEmbeddedNodeJsLocation()` method can be added?

**Comment by mickaelistria** [comment]
> Any chance NodeJSManager.getEmbeddedNodeJsLocation() method can be added?

Yes, feel free to submit a PR.
