### ISSUE TITLE
YAML editor: when press ENTER, cursor goes to the start of next line

### ISSUE THREAD

**Issue by asfernandes** [eclipse/wildwebdeveloper#538]
Using YAML editor in Eclipse 2020-09, when pressing ENTER the cursor goes to the start of the next line.

This is not expected. It's expected it smart indents at least to the same column it was.

**Comment by mickaelistria** [comment]
This is https://github.com/eclipse/tm4e/issues/264 , please install newer TM4E snapshots to get this fixed in your IDE.
