### ISSUE TITLE
Can't unbind shortcut 'ctrl+/'

### ISSUE THREAD

**Issue by AlexLuya** [eclipse/wildwebdeveloper#539]
Within the WWD,pressing 'ctrl+/' will popup a drop list,but under shortcut configuration of eclipse,this binding can't be found.Even changing all 'ctrl+/' to match with 'toggle comment',then back to WWD to press 'ctrl+/',still get that drop list.How to unbind this hotey?

**Comment by mickaelistria** [comment]
Wild Web Developer doesn't define such a `Ctrl+/` shortcut. This is coming from another plugin.
The shortcut to comment code is `Ctrl+Shift+C`.
Can you please try the "Eclipse IDE for Web and JavaScript developers" to verify whether you can reproduce the issue? If not, you'll need to investigate which other plugin brings this and report the issue to its tracker.

**Comment by AlexLuya** [comment]
The latest version of Eclipse IDE for Web and JavaScript developers has a strartup error:

`Missing Constraint: Bundle-RequiredExecutionEnvironment: CDC-1.1/Foundation-1.1,J2SE-1.4`

Something is too old

**Comment by mickaelistria** [comment]
> The latest version of Eclipse IDE for Web and JavaScript developers has a strartup error:

OK, but do you reproduce the issue?
