### ISSUE TITLE
Code-Folding command keys on Javascript not working.

### ISSUE THREAD

**Issue by mugener** [eclipse/wildwebdeveloper#540]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567425

Ever since when Eclipse 2020-06 adapt Wild Web Developer
and abandon Javascript Development Tools,

Keyboard Code-Folding command keys are no longer working on Javascript.

This issue still remains on Eclipse 2020-09.

You can still use mouse to click the Add/Sub folding symbols,
but that is time-wasting compare with using keyboard command keys.

My personal workaround for now is re-installed Eclipse 2020-03 JSDT
and choose js file to open with old Javascript Editor,
because keyboard code-folding command keys are working here.

I really hope this can be fixed soon,
or is it possible for me to fix it by myself?

**Comment by mickaelistria** [comment]
I think it's an issue either upstream in Platform or in LSP4E.
Can you please elaborate about which extact shortcuts/keystrokes you're missing?

**Comment by mugener** [comment]
Collapse(Ctrl+'-'), expand(Ctrl+'+'),
Collapse All(Ctrl+Shift+'-'), expand All(Ctrl+Shift+'+').

This four keys are the most-used,
and I hope we can fix these four first.

**Comment by mickaelistria** [comment]
Do I get it right those are numeric keypad keys only? I don't have such numeric keypad here at the moment and couldn't verify it.

**Comment by mugener** [comment]
> Do I get it right those are numeric keypad keys only? I don't have such numeric keypad here at the moment and couldn't verify it.

Yes it is.
But you can go to window>preferences>general>keys
and filter search 'collapse' and 'expand',
then custom bind the keys you are avaiable on your keyboard.

And you will find that code-folding command keys are working
on others language editors(Java, html, etc),
but not working on Javascript.

**Comment by mickaelistria** [comment]
This is caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=569701

**Comment by mickaelistria** [comment]
I'm closing this one as there is nothing to do in Wild Web Developer to fix it. Please follow https://bugs.eclipse.org/bugs/show_bug.cgi?id=569701 about resolution in Eclipse Platform.

**Comment by mugener** [comment]
After update Eclipse to 202012, the bug 569701 still remains.

But it's Status show RESOLVED FIXED.

What step do I need to get this bug fixed?

**Comment by jabby** [comment]
Hello @mugener 
The status is `RESOLVED/FIXED` on master. It means the bug is fixed but the fix is not released yet. 

Can you try the latest snapshot? The lsp4e update site for snapshot is: http://download.eclipse.org/lsp4e/snapshots/
If you don't want to try the snapshot, you should wait the next release.
