### ISSUE TITLE
Refactor doesn't work across different module files

### ISSUE THREAD

**Issue by robmoffat** [eclipse/wildwebdeveloper#545]
I have some ES6 modular javascript like so:

```
import { parseInfo, getContainerChildren } from "/public/bundles/api.js";
import { getSVGCoords, getElementPageBBox, getMainSvg } from '/public/bundles/screen.js';
```

If I do "Find References" it only seems to find them in the current file.  

Similarly, if I do Refactorings -> Rename, it will only rename in the current file.

Is this a bug, or am I missing some configuration?

thanks,
Rob

**Comment by mickaelistria** [comment]
Can you please elaborate with exact steps to reproduce (a miminal project, and which symbol are you using to "find references" or "refactor") ?

**Comment by mickaelistria** [comment]
No feedback for 1.5 month, let's close.
@robmoffat feel free to reopen with more details if you're still interesting in getting it fixed.

**Comment by silb** [comment]
I stumbled on the same issue. It is related to using absolute imports.

I have created an example project at <https://github.com/silb/wildwebdeveloper/tree/issue-545-absolute-imports/issue-545/wildwebdeveloper-imports> to reproduce it.

See <https://github.com/silb/wildwebdeveloper/blob/issue-545-absolute-imports/issue-545/wildwebdeveloper-imports/public/app/main.js> where on can comment in / out relative and absolute imports.

For this example project, is there any way to configure Wild Web Developer such that it knows that the root for absolute imports is [`public`](https://github.com/silb/wildwebdeveloper/tree/issue-545-absolute-imports/issue-545/wildwebdeveloper-imports/public)?

**Comment by mickaelistria** [comment]
Wild Web Developer uses https://github.com/typescript-language-server/typescript-language-server for that. Please report the issue there.
