### ISSUE TITLE
eslint not working on Eclipse 2020-09

### ISSUE THREAD

**Issue by robmoffat** [eclipse/wildwebdeveloper#546]
I've downloaded the new eclipse, installed wildwebdeveloper and added your test module, `wildwebdeveloper/org.eclipse.wildwebdeveloper.tests/testProjects/eslint/`

<img width="635" alt="Screenshot 2020-10-12 at 10 11 53" src="https://user-images.githubusercontent.com/568673/95728388-60383200-0c73-11eb-8a37-9fee918699df.png">

However, ESLint functionality doesn't seem to work out-of-the-box.  What do I need to do?  Is this a known problem?

thanks,
Rob

**Comment by mickaelistria** [comment]
I think you first need to run `npm install` before eslint kicks in.

**Comment by robmoffat** [comment]
This fixes matters for typescript, but not javascript.  Any further ideas?  

Also, while I have node on my system, lots of people going forward could be using your embedded node language server, so they might not be able to issue the command.

**Comment by mickaelistria** [comment]
I think the JavaScript support is already the topic of #338 , so I'm closing this one.
