### ISSUE TITLE
New plugin updates don't install - Cannot satisfy dependency

### ISSUE THREAD

**Issue by blacklord049** [eclipse/wildwebdeveloper#547]
Hi,

I'm using Eclipse SDK 2020-06 (4.16) provided by IBM and it's running under JRE 8
WWD 0.12.0 is installed however I'm unable to update it anymore

Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 1.6.0
  Software being installed: Wild Web Developer 0.10.5.202009300548 (org.eclipse.wildwebdeveloper.feature.feature.group 0.10.5.202009300548)
  Cannot satisfy dependency:
    From: Wild Web Developer: web development in Eclipse IDE 0.5.13.202009300548 (org.eclipse.wildwebdeveloper 0.5.13.202009300548)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))
  Cannot satisfy dependency:
    From: Wild Web Developer 0.10.5.202009300548 (org.eclipse.wildwebdeveloper.feature.feature.group 0.10.5.202009300548)
    To: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper [0.5.13.202009300548,0.5.13.202009300548]

Does it mean Eclipse needs to run with a JRE version 11?

Thanks

**Comment by mickaelistria** [comment]
> Does it mean Eclipse needs to run with a JRE version 11?

Yes. You can install JustJ from https://download.eclipse.org/justj/sandbox/jres/latest/ (use this URL as a repository in Install New Software wizard) so you get a newer Java version installed just for Eclipse IDE.

**Comment by blacklord049** [comment]
Thank you but as I said in my e-mail we need to run Eclipse with an IBM Java SDK to be able to communicate with the local Websphere server (currently we're working with Websphere 9) and for some specific JVM parameters only available with it.

**Comment by mickaelistria** [comment]
I did a quick search and it indeed looks like there is no Java 11-friendly IBM SDK you could use instead.
This restriction basically forces you to stick to older Eclipse IDE version (2020-06 or older) and there is no way to run newer ones (and newer Wild Web Developer) with Java 8.
The only (not so comfortable) alternative would be that you setup a 2nd Eclipse IDE installation to become your main one for development that doesn't require the IBM JDK specific features; and switch to the older version when necessary; or that you move from WebSphere to another server ;)
