### ISSUE TITLE
Angular keyvalue pipe return considered null

### ISSUE THREAD

**Issue by 4javier** [eclipse/wildwebdeveloper#549]
The output of keyvalue pipe inside Angular template on a correctly instantiated object gets considered null, marking access to any array's property as an error. Obviously it builds and run correctly.

`<div *ngIf="(obj | keyvalue).length ===0">/div>`
> - Identifier 'length' is not defined. 'null' does not contain such a member

**Comment by mickaelistria** [comment]
Can you please share a minimal project to reproduce the issue?

**Comment by 4javier** [comment]
It seems that upgrading to Angular 11 solved the issue.
Don't ask me why.
