### ISSUE TITLE
Warn missing or incompatible node.js

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#55]
If a user does not have a compatible version of node.js instalked, there should be a popup  to notify them about the issue.

**Comment by mickaelistria** [comment]
Note that #23 would be more interesting to fix.

**Comment by angelozerr** [comment]
> Note that #23 would be more interesting to fix.

It was one reason whey I do that in typescript.java. I'm sure that the embed nodejs works with the embed typescript version.

**Comment by brychcy** [comment]
I cannot find a setting for specifing the node location.

Am I overlooking something?

I have node installed it below my home directory.

Putting it in the PATH is not an option on macOS, as PATH cannot be changed for Apps launched from the Finder and is "PATH=/usr/bin:/bin:/usr/sbin:/sbin".

**Comment by mickaelistria** [comment]
There is currently no user setting (preference page) for Node.js location. A contribution to add this and manage node.js installation (as a preference page) would be a good contribution.
There is a developer setting to control the location of node.js, it's about setting the system property `org.eclipse.wildwebdeveloper.nodeJSLocation`.
To work around the limitations of your OS, you can put a symbolic link from /usr/bin to to your local node installation.

**Comment by brychcy** [comment]
Thanks, that works.

I'm using a quite old version (v6.10.1) because newer versions are not compatible with our build files, but it seems to work.

As a suggestion, it would be nice to have at least some documentation on the marketplace page what node version is actually required.

**Comment by mickaelistria** [comment]
FWIW, I think documentation is a bad smell and a very not optimal approach.
The story of node.js detection must be improved inside the code and the
plugin, that's the only thing that will concretely improve the user
experience.

**Comment by mickaelistria** [comment]
@jabby on #190 you mentioned you'd like to fix it. That would be welcome ;)

**Comment by exabrial** [comment]
How do I disable this popup? I don't want to use or install node on my system

**Comment by mickaelistria** [comment]
In this case, you can simply uninstall Wild Web Developer: Help > Intallation Details > Software Tab > Uninstall.

**Comment by AObuchow** [comment]
> How do I disable this popup? I don't want to use or install node on my system

You shouldn’t be able to disable it (with Wild Web Developer installed).

Wild Web Developer ships with Language Servers which need to be run with Node. 
Without Node, most features provided with Wild Web Developer are missing.

In the near future, Wild Web Developer will ship with Node so that users don’t have to manually install it (similar to what VSCode does).

**Comment by pluess** [comment]
> In this case, you can simply uninstall Wild Web Developer: Help > Intallation Details > Software Tab > Uninstall.

I had to search for a while. To disable you have to do the following:

1. Main Menu ==> Help ==> About Eclipse IDE
2. Click on the "Installation Details" button
2. Find "Wild Web Developer" in the "Installed Software" tab.
3. Mark it and click the "Uninstall ..." button.

**Comment by mickaelistria** [comment]
Or, you can simply install the node embedder and update Wild Web Developer from http://download.eclipse.org/wildwebdeveloper/releases/latest ; this would make things work without having to install node on your system.

**Comment by nobbih** [comment]
There are people who do not like node.js at all and do not want ot use it for anything

**Comment by jabby** [comment]
> There are people who do not like node.js at all and do not want ot use it for anything

Most of language servers in Wild Web Developer are developed as Node.js process. So you need a Node.js runtime to run the language server. 
As you can see [here](https://microsoft.github.io/language-server-protocol/implementors/servers/), there is more than 30 language servers written with TypeScript / JavaScript. For all of them you need a Node.js runtime. We use some of them into Wild Web Developer. So end user like you and me need a Node.js runtime.

To focus on the node embedder. As maintainers, we decided to ease the use of Wild Web Developer and to avoid the need for end-user to download and install a Node.js runtime. For that purpose we created a node embedder. 

Now it's up to you. Do you want completion for HTML, CSS, Less, SaSS, JavaScript, JSON, TypeScript, YAML? If so, I see 2 solutions.

1. You install a compliant Node.js runtime for Wild Web Developer. You should update this runtime if Wild Web Developer requirements evolved.
2. You install the node embedder into your Eclipse IDE. When a new version is available, the node embedder will be updated accordingly. It won't polutte your path or your dev environment. If you remove Eclipse IDE, the runtime will be removed too.

I think the last solution is the best for end users but as I said it's up to you.

**Comment by nobbih** [comment]
Well, I do not want any node.js on my system. Because from my point of view it is unsecure by design. I think I look for another solution to support my work which does not need node.js installed on my machine

**Comment by exabrial** [comment]
We used to have auto-completion on documents because there existed language schemas and formal specifications... Now we have to have a node.js installation. I guess when all you have is a hammer... lots of nails lying around

**Comment by nobbih** [comment]
For me using node.js is a nogo. I deinstalled wildwebdev now.  If eclipse will not run properly without wildwebdev then I will stop using Eclipse after 15 years of using it. It is quite simple.  I do not want to be forced to use software I do not believe in. Perhaps I just downgrade to an older version. Eclipse did his job with autocompletion before - I see no reason why node.js is needed now - other that the responsible developers have been prefering it. It is just bad programming ...

**Comment by akurtakov** [comment]
I definitely not believe that node.js (and JS ) is the way to write development tools. But I do believe that LSP is the way forward for development tooling. The way WildWebDeveloper is created doesn't give preference to any programing language but rather to a communication protocol (LSP) and it's a coincidence that the web language servers are implemented with node.js. Eclipse Rust plugin uses RLS (Rust Language server) which is written in Rust. Eclipse C# plugin uses Omnisharp which is written in C#. Whenever someone comes up with better language server for html/css/js... written in java/c/rust.... WildWebDeveloper will switch to it. 
I totally disagree with the statement that we(WildWebDeveloper committers) perfer node.js - we just use the best tool for the job.  And if someone was happy with the old pure Java stuck at ancient EcmaScript 5 JS or with HTML editor without any JS/CSS cross reference that would be surprise to me if they haven't seen the shortcomings in the editing capabilities.

**Comment by nobbih** [comment]
Thanks, Alexander, for your statement.   
I have a simple policy: no node.js on my machine and on any of my servers. And no chrome and chromium also.  
You have been choosing node.js because it does the job from your point of view - it is fine. But then I prefer the good ancient pure Java stuff or use another product which has sophisticated editing capabilities without using node.js.

**Comment by exabrial** [comment]
https://www.zdnet.com/article/malicious-npm-package-opens-backdoors-on-programmers-computers as if you needed another reason to not need/want this software on your computer
