### ISSUE TITLE
Eclipse: Problems occurred while performing provisioning operation: operation plan must be resolved

### ISSUE THREAD

**Issue by SaFi2266** [eclipse/wildwebdeveloper#550]
I have Eclipse Committers

Version: 2020-09 (4.17.0)
Build id: 20200910-1200

Every time open the eclipse marketplace it says there's an update regarding wild web, when hit update I encounter an error with these details

**Severity:** ERROR
**Plugin:** org.eclipse.epp.mpc.ui
**Message:** Problems occurred while performing provisioning operation: operation plan must be resolved
**Exception Stack Trace:**
java.lang.IllegalStateException: operation plan must be resolved
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCurrentJREOperation(ProvUI.java:338)
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCompabilityWithCurrentJREProvisioningPlan(ProvUI.java:325)
	at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceWizard.lambda$5(MarketplaceWizard.java:872)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
**Session Data:**
eclipse.buildId=4.17.0.I20200902-1800
java.version=11.0.9
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.committers.product

Remove and update both failed

**Comment by mickaelistria** [comment]
I think it's more an issue to report to Eclipse Marketplace Client; please submit it at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=MPC .
