### ISSUE TITLE
Progress bar sticks at 37%

### ISSUE THREAD

**Issue by dudenessbcn** [eclipse/wildwebdeveloper#551]
Hello, 

On Eclipse  Version: 2020-09 (4.17.0), after downloading latests wildwebdeveloper as image shows
![wildwebdeveloper_installed](https://user-images.githubusercontent.com/73742820/97778258-63d61f00-1b76-11eb-8726-9f60a9ec003a.PNG).
Node JS version  Node.js v14.15.0 installed on Windows 10 the run nodejs Application runs good though the progress bar sticks at 37% this seems to be a bug.

Please if someone could fix it 

Thanks a lot

**Comment by mickaelistria** [comment]
Is node.js visible in your PATH from the Eclipse IDE process?
Have you tried to install the "node.js embedder" feature form the wild Web Developer installation repository?

**Comment by dudenessbcn** [comment]
hello @mickaelistria,

Thanks for reply, 
yes the embedder is installed, not sure how to check if IDE process is checking the nodejs PATH
![nodejs_embedder](https://user-images.githubusercontent.com/73742820/97797822-760c9780-1c20-11eb-9b3e-b3f4bdc8227f.PNG)

I fixed setting up and external tool and selecting the nodejs.exe location

Thanks

**Comment by mickaelistria** [comment]
Can you list the running subprocess of Eclipse IDE?

**Comment by dudenessbcn** [comment]
hi @mickaelistria,

It seems there is an error while processing the Launching Nodejs Server
![launching_server_nodejs](https://user-images.githubusercontent.com/73742820/97800051-41a1d700-1c32-11eb-9ec9-fe782d5fcc3d.PNG)
![launching_server_nodejs_02](https://user-images.githubusercontent.com/73742820/97800052-423a6d80-1c32-11eb-85e2-4de315b6f0be.PNG)
might be this causing the problem,

Don't know how to list all subprocess of eclipse, sorry

Thanks a lot!

**Comment by mickaelistria** [comment]
I admit the code here isn't really expected to send an NPE at that point, so the error is confusing.
Can you please try to run Eclipse IDE with Java 14 and set `-XX:+ShowCodeDetailsInExceptionMessages` in eclipse.ini after `-vmargs` to get richer error messages?

> Don't know how to list all subprocess of eclipse, sorry

This is typically done by the OS, for example with `ps` in Linux. I don't know an equivalent command for Windows.

**Comment by jabby** [comment]
I think `ps` command works in Powershell.

**Comment by mickaelistria** [comment]
This should be fixed with newer snapshots of LSP4E. Please install the Debug Adapter support from https://download.eclipse.org/lsp4e/snapshots/.

**Comment by acarstoiu** [comment]
It finally works properly, thank you!
