### ISSUE TITLE
Angular directives marked as undefined while doc shown into the same popup

### ISSUE THREAD

**Issue by 4javier** [eclipse/wildwebdeveloper#552]
Every angular directive inside any template gets marked as undefined, but at the same time, its doc gets correctly shown on hover.
![Schermata da 2020-11-01 00-06-46](https://user-images.githubusercontent.com/459381/97791850-163dce80-1bd7-11eb-9760-79251eac2ab7.png)

**Comment by mickaelistria** [comment]
Can you please provide a minimal project to reproduce the issue?

**Comment by 4javier** [comment]
@mickaelistria 
Simply clone, import and validate this basic project
https://github.com/4javier/angular-ivy-base
You'll be notified of 4 warnings in html, all due to to unknown tags (custom selectors) and undefined attributes (i.e. *ngIf directive)

**Comment by mickaelistria** [comment]
Can you please try to install snapshot build from https://download.eclipse.org/wildwebdeveloper/snapshots/ ? It uses some more recent language server for Angular. I tried it locally and couldn't reproduce the issue you mention.

**Comment by 4javier** [comment]
Unfortunately SpringToolSuite doesn't let me upgrade the plugin. Maybe they blocked the version when they choose to include your software as default into their distribution.
I tried the new snapshot on a fresh installation of vanilla Eclipse, and it seems to not mark angular directives as unrecognized anymore, but I didn't manage to find the exact version used by STS to cross check.
If you agree I'd leave this ticket open until new language server lands on STS.

**Comment by mickaelistria** [comment]
I prefer we close the ticket as it's been tested on vanilla Eclipse IDE; if issues happen in STS which don't happen in Eclipse IDE, those will have to be reported to STS.

**Comment by 4javier** [comment]
I don't know if you're willing to re-open the issue, but I just managed to install latest snapshot, and the problem is still the same.
![immagine](https://user-images.githubusercontent.com/459381/100524436-7c0e7d80-31b8-11eb-84ed-b9053e1eddba.png)
