### ISSUE TITLE
Feature request - edit JSON values using the "Properties" view

### ISSUE THREAD

**Issue by basinilya** [eclipse/wildwebdeveloper#556]
I'm using Eclipse 2020-06 and WWD 0.10.0.202006021616

I have to deal with JSON files with pretty long strings that have escaped characters. Normally, I would expect the "Properties" view to display and allow edit the property on which the caret is currently positioned (just like the XML editor does).

However, I couldn't find  this in the "Properties" or any other view. Even the tooltip that is shown on hovering the value does not unescape it. Also, I'd like to see the unescaped values in the "Outline" view like in the XML editor Outline

So I have to switch to my browser and paste the strings as an argument to console.log().

![json-editor](https://user-images.githubusercontent.com/1749243/98439330-48cd5700-2102-11eb-945b-f34afa6a77b0.png)
![xml-editor](https://user-images.githubusercontent.com/1749243/98439334-4e2aa180-2102-11eb-80b3-131c0b300967.png)

**Comment by mickaelistria** [comment]
This JSon Editor doesn't seem to be the one provided by Wild Web Developer; it's coming from another plugin.
