### ISSUE TITLE
Integrates YAML language server

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#56]
As bluesky provides a YAML support, it should be very cool to Integrate YAML Language server https://github.com/redhat-developer/yaml-language-server

**Comment by mickaelistria** [comment]
I think we already have this integration working for Red Hat Developers Studio. I did bootstrap it months ago for Kubernetes: http://www.screencast.com/users/mistria/folders/Default/media/b66f72b7-445d-4675-900a-aab3f484be79 and I think some other developers inside Red Hat have continued to work on it. I'll investigate and try to get this migrated to BlueSky.

**Comment by mickaelistria** [comment]
So this was merged.
I already edited the marketplace entry to associate Wild Web Developer with .yaml and .yml files, so the number of installation should grow naturally.
@yanxi0830 Do you want to take care about adding your video to README and twitting about it (linking to video I guess would be best) ?
