### ISSUE TITLE
wildwebdeveloper creates a .design folder that makes problems with GIT push. why and how to solve?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/wildwebdeveloper#562]
why and how to solve?

screenshot here:

![tzju](https://user-images.githubusercontent.com/42765391/99508490-f2bfa580-2984-11eb-8435-ff026dcc5065.jpg)

thx for feedback.

regards,
jan

**Comment by mickaelistria** [comment]
Can you please provide a minimal example project and steps to reproduce the issue?

**Comment by jayjupdhig** [comment]
it occured on an existing project, after i imported it as an eclipse project...

**Comment by mickaelistria** [comment]
If you cannot provide an example project with steps to reproduce, we'll close the issue.

**Comment by jmar83** [comment]
this is my personal account; i try to reproduce it with another project, but i can't post the projects of our sw development department here. thx for understanding.

**Comment by jayjupdhig** [comment]
Problem was not caused by WWD, it was caused by another Angular Eclipse Plugin:
https://marketplace.eclipse.org/comment/7247#comment-7247
