### ISSUE TITLE
Invalid syntax coloring when using : in a multiline value in a yaml file

### ISSUE THREAD

**Issue by apupier** [eclipse/wildwebdeveloper#563]
```
usingmultiline: |
  should be green
  should also be: green
```

![Screenshot from 2020-11-18 11-58-43](https://user-images.githubusercontent.com/1105127/99522046-73869d80-2995-11eb-8192-f161aaff06b8.png)

**Comment by apupier** [comment]
also with `>`

```
usingmultiline: >
  should be green
  should also be: green
```

![Screenshot from 2020-11-18 12-01-29](https://user-images.githubusercontent.com/1105127/99522345-d0825380-2995-11eb-90ab-c4cb1aff29fd.png)

**Comment by apupier** [comment]
reference for yaml multiline https://yaml-multiline.info/

**Comment by mickaelistria** [comment]
We may need to uprade the yaml TextMate grammar that's included in Wild Web Developer. We usually pick the one from latest VSCode release and open a CQ for it. Would you mind trying that and submitting a PR?

**Comment by mickaelistria** [comment]
So I tried upgrading to latest TextMate grammar included in VSCode 1.51.1 but that doesn't change the behavior. So it's probably a bug in TM4E. We should try to reduce the textmate grammar to the bare minimum to reproduce the issue, and then open an issue to TM4E about it.

**Comment by mickaelistria** [comment]
I also tried putting the current grammar from Wild Web Developer into VSCode locally to see how it likes it or not, and while I could see some other changes I did to verify the grammar was correctly used by VSCode, the current grammar form Wild Web Developer should multi-line properly in VSCode without modification.
So it's definitely an issue in TM4E more than in the grammar. I've opened https://github.com/eclipse/tm4e/issues/266

**Comment by sebthom** [comment]
@apupier this should be fixed with the latest tm4e release.
