### ISSUE TITLE
wwd or lsp4e  should not call finding declaration twice or filter it.

### ISSUE THREAD

**Issue by jcompagner** [eclipse/wildwebdeveloper#573]
Problem is that "F3" or ctrl-click on typescript/angular types will always result in a popup because of duplicate declarations found.
I find this a bit annoying because you have always an extra handling instead of directly going to it.

But it seems that this is not directly a problem of WWD but more a problem of the lsp4e project?

because in OpenDeclarationHyperlinkDetector Olsp4e code) the code in the method detectHyperlinks is:

CompletableFuture.allOf(
				LanguageServiceAccessor
					.getLanguageServers(textViewer.getDocument(), capabilities -> Boolean.TRUE.equals(capabilities.getDefinitionProvider()))
					.thenAcceptAsync(languageServers ->
						languageServers.stream().map(ls -> ls.getTextDocumentService().definition(LSPEclipseUtils.toDefinitionParams(params))).forEach(allFutures::add)
					),
				LanguageServiceAccessor
					.getLanguageServers(textViewer.getDocument(), OpenDeclarationHyperlinkDetector::isTypeDefinitionProvider)
					.thenAcceptAsync(languageServers ->
						languageServers.stream().map(ls -> ls.getTextDocumentService().typeDefinition(LSPEclipseUtils.toTypeDefinitionParams(params))).forEach(allFutures::add)
					)
			)

and then in the end returns for "Definition" and "typeDefinition" both the exact same links

this is because the angular/typescript language services says that it is a DefinitionProvider and it is also a TypeDefinitonProvider

(node_modules/typescript-language-server/lib/lsp-server.js i think where that is defined)

if i disable 1 of the above in that code, then it kind of works, i see different behavior

lets say i have 3 things

MyOwn TS files (class/superclass and so on)
Angluar classes (like SimpleChanges)
ESx classes (like completions of Object.keys() and opening "keys")

if i disable the "definition" part

my own TS file stuff (opening super class, or jumping to a function declaration) is working fine
Angular classes don't open (you don't jump to the definition files)
Object show still a list of 3 items (and those are really different because it matches on es5.d.ts, es2015.core.d.ts and 2017.d.ts)
Object.keys jumps directly to the 2017 but i guess that is something that is not in 2015 or es5..

if i disable the typeDefinition part
then my own are still fine and also angular classes open just fine
Object and Object.keys now shows a list of 2 items point to the same file (es5) but they are on 2 different locations

if i compare it with VisualStudioCode then it works like the second one (so disabling the typeDefintion part)

if i quickly patch the code of OpenDeclarationHyperlinkDetector so use a map to filter/distinct stuff based on the location:

Map<Either<Location, LocationLink>,LSBasedHyperlink> allLinks = Collections.synchronizedMap(new HashMap<>());

synchronized (allLinks) {
	links.forEach(link -> allLinks.put(link.getLocation(), link));
}

return allLinks.values().toArray(new IHyperlink[allLinks.size()]);

then it always works, then it is kind of if i had disabled the typeDefinition part.

maybe it is nicer to let LSBasedHyperlink have an equals and hashcode impl thatj just redirects it to the location (which has equals/hashcode)
then you can use in the method toHyperlinks of OpenDeclarationHyperlinkDetector  in the streaming i guess 1 call (distinct())

**Comment by mickaelistria** [comment]
This looks like an issue in LSP4E, as the class and package name suggest. Can you please report it to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=lsp4e ?

**Comment by jcompagner** [comment]
i wil report it there.

by the way ;)

lsp4j (the base) is github: https://github.com/eclipse/lsp4j

lsp4e (the "middle") is eclipse 

wwd (the "end") is github again...

sounds like somebody wanted to confuse people ;)
