### ISSUE TITLE
Eclipse  Glass Fish

### ISSUE THREAD

**Issue by KheireddineAzzez** [eclipse/wildwebdeveloper#576]
Eclipse doesn't support Glass Fish SERVER !!! 
Solution ...........

**Comment by jabby** [comment]
Hello @KheireddineAzzez 

Eclipse Wild Web Developer is an eclipse plugin about web development. It's focused on html, css, json, JS, yml and other text editing. There is no support for Jakarta EE platform application server in this plugin. 

About Glassfish support in Eclipse IDE, I suggest to test the JEE official support in Eclipse IDE with the following plugin: https://marketplace.eclipse.org/content/eclipse-enterprise-java-developer-tools
If it's not what you want, you can search on [Eclipse marketplace](https://marketplace.eclipse.org/search/site/glassfish). Maybe the first result will be sufficient.

As all the previous mentionned plugins are not managed in this repository, I close the issue.
