### ISSUE TITLE
Add support for tests with Mocha

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#578]
It looks like Mocha is the most popular JS lib for testing. Wild Web Developer should try to have support for it (via the generic Test Result view).

**Comment by jabby** [comment]
Hello @mickaelistria 

I'm not sure mocha is the most populare JS lib for testing anymore. According to state of JS 2019, jest is now the most popular test framework. 

See https://2019.stateofjs.com/testing/

The 2020 survey started few days ago. I don't know when the results will be published.

**Comment by mickaelistria** [comment]
see @fbricon , that's exactly the kind of things that support of this or that JS library really discouraging. Rust got it right ;)

**Comment by jabby** [comment]
State of JS 2020 is out. https://2020.stateofjs.com/en-US/technologies/testing/ 
As you can see there is now 2 new challengers 😏

**Comment by vito-detullio-finconsgroup** [comment]
do jest / mocha have some "hooks" to make it possible to attach eclipse? it's there some standard communication channel?
what is needed for eclipse to integrate the run into the UI?
do eclipse need a custom test runner or something like that?

**Comment by mickaelistria** [comment]
The are certainly some ways to monitor test execution, at least looking at standard output. No specific runner is needed on node side, but eclipse IDE would need to be instructed about how to run tests (which command to run) and track progress. This is some not trivial development to integrate some test framework into the generic test report view.

**Comment by mickaelistria** [comment]
No real interest for it in a while, let's close.
