### ISSUE TITLE
AngularJS autocomplete is not working

### ISSUE THREAD

**Issue by SethupathiTSP** [eclipse/wildwebdeveloper#580]
I am trying to do some angularjs operations in .html file, but the content assist does not provide autocomplete for it.

![image](https://user-images.githubusercontent.com/10921299/101598928-e88e4580-3a1e-11eb-993d-85369f705aa2.png)

Also the editor shows "undefined attribute name" for all the angular tags that I use. Please provide a solution to fix this!!!

**Comment by mickaelistria** [comment]
You're not using the right editor. What we see here is the legacy HTML editor, that's somehow deprecated and not able to support angular. Instead just right-click on the file > Open With > Generic Editor; and you'll get the capabilities provided by Wild Web Developer.

**Comment by angelozerr** [comment]
Even with WWD, you will not have a good support for AngularJS (Angular 1). WWD provides a good support for only Angular (Angular >=2).

The best Eclipse plugin for AngularJS is https://marketplace.eclipse.org/content/angularjs-eclipse-outdated-use-wild-web-developer-instead but I have no time to maintain it and as AngularJS is an old JS framework (compare to Angular 2), I'm not sure that it's interesting to work on AngularJS support inside WWD.
