### ISSUE TITLE
Tooltip displays markup instead of contents

### ISSUE THREAD

**Issue by pascalheraud** [eclipse/wildwebdeveloper#583]
If i let mouse over a method, a tooltip appears but seems to contain HTML markup instead of the help itself : 
![image](https://user-images.githubusercontent.com/4538416/102025834-cdaf2e80-3d9a-11eb-87ae-ec92fa1f31f0.png)

I'm running debian 10 with Eclipse 2020-09

Version installed : 
  Wild Web Developer	0.10.4.202009212151	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project

**Comment by mickaelistria** [comment]
It most likely means that your Eclipse IDE is not properly configured to use an internal web browser. Please make sure the right version of libwebkitgtk is installed on your machine.

**Comment by pascalheraud** [comment]
You're right, it works like a charm since (debian buster/10):
`apt-get install libwebkit2gtk-4.0-37`

I'm using Eclipse since decades and never noticed that !

**Comment by mickaelistria** [comment]
> I'm using Eclipse since decades and never noticed that !

you probably missed a bunch of small niceties here and there then ;)
