### ISSUE TITLE
Opening an *.css file does not suggest to install wild web developer

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#584]
IIRC the marketplace client was extended in the past to suggest fitting solutions for file extensions. But if I open a .css file the system default editor is loaded without suggesting any Eclipse marketplace solution like Wild Web Developer.

Can you register for this extension? IIRC @mickaelistria was the driver of this solution so he might know how to do this.

**Comment by mickaelistria** [comment]
fileExtension_css tag is present already. Is the marketplace checker working in general on your side? Is the preference properly set? Can you reproduce this issue with some EPP package that doesn't have Wild Web Developer built-in?

**Comment by vogella** [comment]
I used the SDK with the Marketplace installed. What preference needs to be set? I see the marketplace query for some extensions, so I assumed it is set.

**Comment by mickaelistria** [comment]
The preference is in General > Window > Editor > File Association > Open Associated files with ...
But if it's working for some extensions, it means Marketplace is OK.
Are you sure the the system editor isn't configured as default for that file, or for CSS in general? On a fresh EPP for Rust developer, I do see MPC querying Marketplace when opening a .css file, and then Wild Web Developer suggested as possible candidate (together with CodeMix, WebTools and others).
Anyway, I'm closing this ticket here as it's clearly not related to Wild Web Developer in particular.

**Comment by vogella** [comment]
Thanks Mickael, the preference setting was wrong in my case. Sorry for the noise.
