### ISSUE TITLE
wildwebdeveloper.xml includes copies of JSoup and Xerces

### ISSUE THREAD

**Issue by nitind** [eclipse/wildwebdeveloper#585]
Orbit has versions of both, it's both wasteful and architecturally unclean to package additional copies. It looks like parts of LSP4J are in there, too.

**Comment by mickaelistria** [comment]
We decided to take an approach of uber-jar for the language server runtime. We tried to turn it into proper OSGi and it became too expansive. The benefit of uber-jar is that it's actually the single delivery that properly tested by Lemminx project, and used by alternative projects; so the artifact and the packaging we use is tested and working; unlike OSGi-fying everything here.
Unless someone is willing to do the work of actually making the packaging rely on OSGi and provide the necessary amount of testing to prevent from packaging-related issues, we won't change WIld Web Developer to package LemMinX differently.
