### ISSUE TITLE
Highlight "objects" within the scope of their declaration

### ISSUE THREAD

**Issue by aaFn** [eclipse/wildwebdeveloper#589]
At the time of JSDT, there was a very very very handy function of highlighting where is an "object" used (a variable, a function ..) in the code within the containing braces where it is in scope, by simply placing the edition cursor within the "object" name, or at its beginning or at at its end.

E.g. in (stupid code, just to illustrate .. 😁 ):
```
function foo (a) {
  let b;
  if (a == 1) {
    let a = 2;
    b = a;
  }
  else {
    b = foo(a>1 ? a-1 : a+1);
  }
  return(b);
}
```

placing the edition/insertion cursor on:
1. any of `foo` will highlight all occurrences of `foo` including its declaration
2. `a` parameter in the `foo` function declaration will highlight all occurences of `a` in `foo` except within the `if` body (but it will highlight it in its condition)
3. any `a` inside the `if` body will highlight only all `a` occurences inside that body
4. any `b` inside `foo` will highlight all occurences of `b` inside it, but no occurence of `b` at global level or inside any other function

This feature was very useful to verify the scope of a variable, to verify we do not have mis-typing / spelling errors in it, to verify where it is declared ... and that was saving a lot of time since we were not obliged to run the code to find such common errors at interpretation time.

For now, the only workaround is to press Ctrl+Shift+G to "Find References", which is a bit slow, clumsy to do, and not as dynamic.

Is that something that WWD can consider to add ?
Or is there another way to get that feature back ?

Thank you much in advance, and thank you for the good work, it is really a progress to have correct ES2015 support 👍

**Comment by nitind** [comment]
That functionality appears present to me with 0.10.5.202012011111. Turning it _off_, on the other hand, doesn't seem possible.

**Comment by aaFn** [comment]
Hello @nitind , thank you for the answer.

Well, it seems this is also the version I have, as part of my Eclipse IDE for Web and JavaScript Developers, Version: 2020-12 (4.18.0), Build id: 20201210-1552):
```
  Wild Web Developer	0.10.5.202012011111	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
    Node.js embedder from Wild Web Developer	0.2.1.202011222154	org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group	Eclipse Wild Web Developer project
    Wild Web Developer XML tools	0.10.3.202011132012	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project
```

However, the functionality is either not present on my install or not active / not functioning properly.

=> Is there anything I can do to debug / trace, or get other config info to confirm ?

**Comment by lorenzodallavecchia** [comment]
Apparently, the problem happens only *on Windows* because of differing file separators.
It should be fixed by including the new TypeScript language server (#607).

**Comment by mickaelistria** [comment]
Thanks for the feedback @lorenzodallavecchia . Can someone try latest snapshots from https://download.eclipse.org/wildwebdeveloper/snapshots and report whether this issue is fixed or not?

**Comment by aaFn** [comment]
If there is an easy way to come back to the earlier "official" version after that, I am ready to test on my side (Windows).

Just not sure how to roll back from installing the latest snapshot when done, if someone would be kind enough to indicate to me ? (sorry, I am not an Eclipse advanced user, but ready to try and learn)

**Comment by aaFn** [comment]
Never mind, I found how to do it I believe, so I tested your latest snapshot with my Windows Eclipse 2020-12 (4.18.0)
Build id: 20201210-1552,

and your snapshot level
```
  Wild Web Developer	0.10.6.202102022303	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
    Node.js embedder from Wild Web Developer	0.2.2.202102022303	org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group	Eclipse Wild Web Developer project
    Wild Web Developer XML tools	0.10.4.202101251129	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project

```
and I confirm the problem is corrected 😀 .

Small question is whether I can keep the snapshot and it will get updated by next official release, or if I should roll back ?
Thanks much, aaFn.

**Comment by mickaelistria** [comment]
Thanks for the feedback.

> Small question is whether I can keep the snapshot and it will get updated by next official release, or if I should roll back ?

No need to rollback. Using snapshot doesn't prevent upgrading to last release. And as we're usually careful and rarely introduce regressions thanks to a solid enough test suite, snapshots are almost always better than release, so sticking to them and upgrading from snapshots to snapshots should provide more happiness.

**Comment by aaFn** [comment]
Thank you @mickaelistria.

Now, I just edited my previous post because I have better news, but it seems something is interfering, depending on whether I am on the initial open editor tab focused at Eclipse start, or an another editor tab I focus on later.

Loos like something else / additional is running on that initially focused tab which is perturbing things, or adding to them.
Read the edited version of my previous post to see what I mean.

=> maybe you want me to open another issue to close that one ? I presume this is a different problem / interference, and that my issue here is fully addressed in itself. Let me know.

**Comment by aaFn** [comment]
Update: I had to reinstall my Javascript latest release, and the above interference is no more here
=> there was probably a remnant of past JSDT or other in my previous install, producing that effect.

All is good now, closing the issue, thank you for the support.

**Comment by nitind** [comment]
> => there was probably a remnant of past JSDT or other in my previous install, producing that effect.

I can't fathom how it would.

**Comment by aaFn** [comment]
Well, I remember having WST in my old list of plugins in my previous install, and it's not showing anymore in the new install.
=> might be it ??
