### ISSUE TITLE
Opening additional TS files is slow

### ISSUE THREAD

**Issue by nicolas-albert** [eclipse/wildwebdeveloper#591]
Hi,
I'm working on a big project and I have to open/close many TS files.
Opening performance isn't good, even if a TS file is already opened on the same project.
VS Code is faster in this case.

## Reproduction
Clone [this repository](https://github.com/nicolas-albert/SlowWWD
), perform a `npm install` and then:
 - add it as Eclipse project
 - add it as VS Code folder

On both, open and compare the time to open TS files, like:
 - src/pages/dataPage/datapage.ts
 - src/pages/dropFilePage/dropfilepage.ts
 - src/pages/dropFilePage/loginPage.ts
 - ...

## Observations

WWD opens the first page is quite normal (**5 sec**), but lint (like import warnings) and code completion take many seconds (**12 sec**). Open the 2nd page take too much pending time (**20-30 sec**), but once opened, lint and completion are already ok. Always true for other TS files.

VS Code opens the first page is quite normal (**2 sec**), lint and code completion take many seconds (**12 sec**). Open the 2nd page is fast and lint + completion are fast too (**3 sec**).

It's like WWD don't reuse the static analyze of the first page but do it again for each pages.

## Expected

The first page opening is quite long but acceptable (because of initialization process, etc) but other page opening should be faster.

I also take any idea or tricks to speed-up TS file loading.

Thanks!

## Configuration

 - Dell XPS 15
 - i7-6700HQ (2.6 Ghz)
 - 16 Go ram
 - SSD
 - Win10 64bit
 - Eclipse 2020-12 up-to-date
 - Java 15
 - NodeJS 14

**Comment by nicolas-albert** [comment]
The hang for the 2nd+ page loading is due to a theme engine manipulation in a tier plugin.
I 've removed this part and now it's acceptable but still not fast as VS Code.

**Comment by mickaelistria** [comment]
Thanks for the followup and closing!
