### ISSUE TITLE
Search for JVM to start XML LS

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/wildwebdeveloper#592]
Currently the JVM search to start XML LS does the following:
1. Check PATH env variable if it points to a JVM
2. Use Java from `System.getProperty("java.home")` which is the Java used to start Eclipse (only if 1 fails)

Why is 1. needed? Should just always be started with whatever JVM launched Eclipse.

In my case (and not just mine) PATH points to Java 8 but Eclipse started with Java 14. XML LS needs Java 11 minimum.

I propose to keep lines 161-165 from here https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java#L154 and remove the rest (the PATH variable support)

**Comment by mickaelistria** [comment]
No objection. Feel free to submit a PR. Note that ProcessHandle.current().info().command() might be better than the current approach relying on java.home.
