### ISSUE TITLE
Extension point for Node.js path

### ISSUE THREAD

**Issue by lorenzodallavecchia** [eclipse/wildwebdeveloper#594]
Hi, I'm replacing the old TypeScript.IDE with WWD in our Eclipse product.
We already have a way of managing Node.js and with TypeScript.IDE we could provide our own Node.js paths using the `ts.eclipse.ide.core.nodeJSInstalls` extension point.

In WWD the embedded Node.js is retrieved by downloading and unpacking an archive and the only way to override that is using a system property. A system property is not good for enforcing a path programmatically (it would be sensitive to plugin start order, among other problems).

I think it would be great if the `org.eclipse.wildwebdeveloper.embedder.node` plugin provided an extension point for a "resolver" class that could supply a Node.js path using custom logic. What do you think?

**Comment by mickaelistria** [comment]
We're basically not able to guarantee the language server and debug adapters shipped inside Wild Web Developer are compatible with any version of Node.js. So we prefer not opening this for customization unless there are people committing to extra testing and maintenance against different Node.js versions.
What is your reason against using the embedded Node.js in Wild Web Developer ?

**Comment by lorenzodallavecchia** [comment]
Thanks for the quick reply @mickaelistria.
TBH I was not expecting the lack of an extension point to be deliberate, so I would have preferred to salvage our Node.js management, without having to migrate code to use `NodeJSManager`. However, I see your point about ensuring compatibility.

On investigating `NodeJSManager` I had the impression that it downloaded the archive on demand, but I see now that it is downloaded during the build and only expanded on demand. I should have investigated better, sorry.

The last resistance I have is that we would like to keep control of the Node version, even if it means looking out for incompatibilities. I think we can work around that by providing our own fragments: a bit unorthodox but should work.
