### ISSUE TITLE
New line in comment should show comment prefix

### ISSUE THREAD

**Issue by p-bakker** [eclipse/wildwebdeveloper#599]
Hi,

Not sure if this is an issue in WWD or some downstream project or config, but when I'm in a multiline comment and hit enter, I expect the new line to automatically get an indent + space + asterisk + space. However, I just get an empty line

### Example 
before hitting enter:
```
    /**
     * %%cursorPosition%%
     * 
     */
``` 
currently after hitting enter:     
```
    /**
     * 
%%cursorPosition%%
     * 
     */
``` 
expected after hitting enter:     
```
    /**
     * 
     * %%cursorPosition%%
     * 
     */
```

**Comment by p-bakker** [comment]
Eclipse says I run this version:
Wild Web Developer	0.10.6.202101141739	org.eclipse.wildwebdeveloper.feature.feature.group

**Comment by mickaelistria** [comment]
I think this should be provided by the language server as an auto-edit action. Can you please report it to https://github.com/theia-ide/typescript-language-server ?

**Comment by predragnikolic** [comment]
> I think this should be provided by the language server as an auto-edit action. 

What exactly do you mean by auto-edit action? 
Do you mean additionalTextEdits? 🙂
Still, I don't see how this could be implemented on the server. There is no way a server can detect that a user pressed enter, to apply additional text edits.

Thus I do not think that this behavior should be provided by the langage server, but rathar the text editor itself. (VS Code and Sublime Text, dont suffer from this issue because they handle this behavior out of the box.)

**Comment by mickaelistria** [comment]
> Still, I don't see how this could be implemented on the server. There is no way a server can detect that a user pressed enter, to apply additional text edits.

The language server does listen to `textDocument/didChange` and receives notifications about what did actually change; so it's totally possible to detect that user has added a new-line. Reacting to this newline in a document area, the language server could then send a `workspace/applyEdit` to add the indentation (spaces and asterisk) to the new line.
It's a usual pattern already leveraged by some language server.

> Thus I do not think that this behavior should be provided by the langage server, but rathar the text editor itself. (VS Code and Sublime Text, dont suffer from this issue because they handle this behavior out of the box.)

None of them does use a language server (they use tsserver + a lot of typescript-specific logic in the client). Their typescript support is actually anterior to LSP publication.
Implementing it in the client can of mean that the client has to start parsing the document to know whether the edit is in a comment area. That's a bad smell: with LSP, everything that requires parsing should take place in the LS, not in the client.

**Comment by p-bakker** [comment]
Any thoughts on this, given that the likelihook of this being implemented in typescript-language-server isn't great?

**Comment by p-bakker** [comment]
FYI: tried to see what I can do with 'onEnterRules' in the TextMate > Language Configuration section, but that didn't go anywhere:
while the 'onEnterRules' code seems to get parsed and run (as the editor bombs out if I put for example a bad regex in the 'beforeText' property), no matter what I put as config in there it doesn't seem to do anything in the editor.

Try for example this simple config:
```
	"onEnterRules": [
		{
			"beforeText": "^\\s*hello",
			"action": { 
				"indent": "indent",
				"appendText": "hello"
			}
		}
	]
```
The 'appendText' value is never appended.

But I don't think one could create a great Dx in the editor using the onEnterRule, but at least I wanted to try to see how far I could get

**Comment by mickaelistria** [comment]
I agree `onEnterRules` can be the right place for this.
Support for language-configuration.json is provided by https://github.com/eclipse/tm4e/ . You may want to try writing a test case to TM4E to verify whether this can work, and contribute it to TM4E so we can know better how to make it work in Wild Web Developer.

**Comment by mickaelistria** [comment]
I don't see a test case using onEnter in TM4E. I've spent some time on it and a test is definitely missing. I submitted https://github.com/eclipse/tm4e/pull/436 . Then it becomes clear that TM4E has some bug that prevents from properly dealing with indent. I think it tries to be too smart, even in basic case, computing an indent from other viewer info instead of just copying indent of the previous line. That topic should be reported to TM4E (contributions welcome!)
For Wild Web Developer, some `onEnter` are currently missing in the various language-configuration files. https://github.com/eclipse/tm4e/blob/972061af2add6231c5667e31f83d393c102bdf9b/org.eclipse.tm4e.languageconfiguration.tests/language-configurations/language-configuration.json#L29..L34 can be used as an example of what is supposed to work. Adding those would already slightly improve Wild Web Developer, and once TM4E is fixed, it should work as expected. Contributions welcome as PR in Wild Web Developer too!

**Comment by p-bakker** [comment]
This is the onEnterRules test I saw in TM4E: https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.languageconfiguration/src/test/java/org/eclipse/tm4e/languageconfiguration/internal/model/OnEnterSupportTest.java

**Comment by p-bakker** [comment]
> That topic should be reported to TM4E

Meaning an issue should be filled with tm4e, in addition to your PR with the testcase?

**Comment by mickaelistria** [comment]
> This is the onEnterRules test I saw in TM4E

This does validate how onEnterRules are parsed, but not really how they're applied.

> an issue should be filled with tm4e, in addition to your PR with the testcase?

I don't think it's worth opening a new issue if there is already a PR.

**Comment by angelozerr** [comment]
> The 'appendText' value is never appended.

Please note that there were a bug to load language configuration which didn't respect the language configuration specification. I fixed with https://github.com/eclipse/tm4e/pull/438/files#diff-8ea1b94a04d7dfa972f1916f2f1b2576214e37d9fe49a542c7d8bc9f0a8cd5a8R66

If you want to test your on enter values with the current tm4e, I suggest that you try to replace `"indent": "indent"` with `"indentAction": "Indent"`

**Comment by angelozerr** [comment]
@p-bakker there are some bug in TM4E to cover this issue. I think I have a fix to support the comments for ts and js. But let me some time to write some tests.

**Comment by mickaelistria** [comment]
@p-bakker can you please submit a PR adding the onEnterRules to the JS and TS lanaguage-configuration files?

**Comment by angelozerr** [comment]
@mickaelistria I have the intention to do that, please wait because there are some error in the vscode language config.

But it will not work,it need some fix to support correctly on enterrule for comments. I will create a PR for that in TM4e.

**Comment by angelozerr** [comment]
> can you please submit a PR adding the onEnterRules to the JS and TS lanaguage-configuration files?

done in https://github.com/eclipse/wildwebdeveloper/pull/863

**Comment by angelozerr** [comment]
@mickaelistria @p-bakker I create a dragt PR for TM4e https://github.com/eclipse/tm4e/pull/439

You can see a demo with TS comments at https://github.com/eclipse/tm4e/pull/439#issuecomment-1239290355

**Comment by mickaelistria** [comment]
@angelozerr Can I merge this patch now? I gave it a try, and although the state is wrong internally (a lot of `null` for regexpRules), nothing is logged and no bad effect is visible. So this change doesn't seem to do anything wrong.

**Comment by angelozerr** [comment]
> @angelozerr Can I merge this patch now? 

If you wish, but we need to write more tests.

**Comment by p-bakker** [comment]
@angelozerr video in https://github.com/eclipse/tm4e/pull/439#issuecomment-1239290355 looks great!

Did it also work if you start the comment indented, straight above the indented function?

Afraid I'm not in the position to try it all myself atm

**Comment by p-bakker** [comment]
ON a sidenote, while I hope I have your attention: Once this would get merged, should I be able to try it out using the snapshot update url (http://download.eclipse.org/wildwebdeveloper/snapshots)?

Asking because I've had trouble using the snapshot url so far: when I use the snapshot url, it shows up as version 0.11 (under Help > About > Installation Details), when I open a .js file, it opens in the generic editor, but without any syntax highlighting or anything. When I look under Preferences > TextMate > Language Configrations, there aren't any. On disk (in \plugins\org.eclipse.wildwebdeveloper_0.6.1.202209071334\language-configurations\javascript) I think I see the updated javascript-language-configuration.jsonc though

**Comment by mickaelistria** [comment]
The bundle and feature versions are technical versions according to semantic versioning. They usually don't match the project "marketing" version. You don't need to care much about it as long as you're upgrading frequently.

**Comment by p-bakker** [comment]
Am seeing these errors in the log when Eclipse starts:
```
!ENTRY org.eclipse.wildwebdeveloper 4 0 2022-09-07 17:58:18.783
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper [466]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.eclipse.wildwebdeveloper.xml 4 0 2022-09-07 17:58:18.786
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper.xml [467]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by mickaelistria** [comment]
Wild Web Developer require to run Eclipse IDE with Java 17.

**Comment by p-bakker** [comment]
right, that seems to get things going a bit :-) Maybe #685 is a similar issue?

While the language configs are now there and when opening a .js file I'm getting syntax highlighting, the onEnterRules logic that got added doesn't seem to be there or in effect. When I do the same as in https://github.com/eclipse/tm4e/pull/439#issuecomment-1239290355, I'm just getting empty lines when hitton enter, instead of ` * `....

Should th enew stuff be available in the snapshot?

**Comment by angelozerr** [comment]
@p-bakker have you some OnEnterRules in UI preferences:

![image](https://user-images.githubusercontent.com/1932211/189067397-5439bfb0-0300-4b40-87e9-987826ffee4c.png)

If you have that, it will require last version (not released) of tm4e, @mickaelistria could you help us for that please.

**Comment by angelozerr** [comment]
> I don't see a test case using onEnter in TM4E. 

See existing tests for OnEnterRules at 
https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.languageconfiguration/src/test/java/org/eclipse/tm4e/languageconfiguration/internal/model/OnEnterSupportTest.java which are the same than vscode.

**Comment by p-bakker** [comment]
Nope, don't see them there, only see them when I looks in the .jsonc files on disk

**Comment by mickaelistria** [comment]
You can already install latest TM4E release, which was just published and includes the desired fix.

**Comment by p-bakker** [comment]
I tried the snapshot url, but while that gave me an updated tm4e (more language configurations), the onEnterRules don't show nor do I get the expected behavior

Tried to install a non-snapshot release, but while my Eclipse recognizes https://download.eclipse.org/tm4e/snapshots/, it complains when I try https://download.eclipse.org/tm4e/releases/. Give me an error: `Could not find https://download.eclipse.org/tm4e/releases/`

**Comment by angelozerr** [comment]
> I tried the snapshot url, but while that gave me an updated tm4e (more language configurations), the onEnterRules don't show nor do I get the expected behavior

The language configuration of JS is hosted in WWD an dnot in TM4e. I think you should try to replace language configuration with yours from WWD to have that:

![image](https://user-images.githubusercontent.com/1932211/189067397-5439bfb0-0300-4b40-87e9-987826ffee4c.png)
