### ISSUE TITLE
All formatting is gone when using the TypeScript compare 

### ISSUE THREAD

**Issue by p-bakker** [eclipse/wildwebdeveloper#600]
When I'm in my git perspective and double-click on a unstaged .ts file, the Compare Editor opens and for me it opens using as compare mode `TypeScript Compare`.

However, in that mode, all leading whitespace on each line is completely removed. If I switch over to use `Text Compare`, the leading white space is should properly, but of course I loose all TypeScript goodies like syntax highlighting and contextual tooltips

**Comment by p-bakker** [comment]
Eclipse says I run this version:
Wild Web Developer	0.10.6.202101141739	org.eclipse.wildwebdeveloper.feature.feature.group

**Comment by mickaelistria** [comment]
I can reproduce some of the issues. Something is definitely wrong with compare in general. We'll investigate.

**Comment by mickaelistria** [comment]
This is an instance of https://bugs.eclipse.org/bugs/show_bug.cgi?id=570745

**Comment by mickaelistria** [comment]
I'm closing here as there is no action to take from Wild Web Developer perspective. Upgrading to newer Eclipse Platform once https://bugs.eclipse.org/bugs/show_bug.cgi?id=570745 is fixed would immediately resolve that.
