### ISSUE TITLE
Eclipse keeps on starting new instances of itself

### ISSUE THREAD

**Issue by PyvesB** [eclipse/wildwebdeveloper#601]
Hello! 👋🏻 

I've just updated from Wild Web Developer XML tools 0.10.3.202011132012 to Wild Web Developer XML tools 0.10.4.202101050902. Each time I open a _pom.xml_ file in a Maven project, a new Eclipse IDE instance is started on top of the running one.

I'm able to reproduce the problem on both my Windows and macOS machines.

**Comment by mickaelistria** [comment]
Can you please try latest snapshot of Wild Web Developer and m2e and report whether you can reproduce or not? If I'm not mistaken, it was a bug in LemMinX-Maven causing that.

**Comment by PyvesB** [comment]
What is the update site to get the latest M2E snapshots? The README (https://github.com/eclipse-m2e/m2e-core) only seems to indicate the releases update site.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md#-trying-latest-builds

**Comment by PyvesB** [comment]
As far as I can tell, I am using the latest versions of all bundles:
* Wild Web Developer 0.10.6.202101141739
* Wild Web Developer XML tools 0.10.4.202101050902
* POM Editor using LemMinX language server (includes Incubating components) 1.17.0.20201203-1258

**Comment by mickaelistria** [comment]
I have the same versions and cannot reproduce. Can you please provide some more details?

**Comment by PyvesB** [comment]
Unsure what else to add. On both my Window and macOS machines, when updating Wild Web Developer XML tools 0.10.3.202011132012 to Wild Web Developer XML tools 0.10.4.202101050902 (and not other dependency updates), the problem started happening. I can reproduce even in a brand new Maven project created through the new project wizard.

Looking through the changes from Wild Web Developer XML tools 0.10.3.202011132012 to Wild Web Developer XML tools 0.10.4.202101050902, there is only a single commit: https://github.com/eclipse/wildwebdeveloper/commit/9f4895055b1bce28b016a100e6af9a6ba1f6f049

**Comment by mickaelistria** [comment]
I tried downloading Eclipse SDK 4.19.M1, Installed m2e Lemminx support from the staging 2021-03 repo, and opened 2 pom files. I saw only 1 LemMinX instance started.
* POM Editor using LemMinX language server (includes Incubating components)	1.17.0.20201203-1258
* (bundle) Eclipse Wild Web Developer project	XML support using Language Server	0.10.0.202011132012	org.eclipse.wildwebdeveloper.xml

Then I updated to Wild Web Developer snapshot (bundle) Eclipse Wild Web Developer project	XML support using Language Server	0.10.0.202011132012	org.eclipse.wildwebdeveloper.xml

And still I get 1 single language server instance started.

There could be some bug in LemMinX or extension causing it to not answer properly and then LSP4E assumes it's disconnected and restarts it. Can you reproduce it with the simplest pom files?

**Comment by PyvesB** [comment]
> Can you reproduce it with the simplest pom files?

Yes.

Looking at the commit https://github.com/eclipse/wildwebdeveloper/commit/9f4895055b1bce28b016a100e6af9a6ba1f6f049, the bug seems pretty obvious to me. The old code was computing the path to Java. The new code is computing `ProcessHandle.current().info().command()`, which will return the path to the currently running Eclipse executable (`/some-path/Eclipse.app/Contents/MacOS/eclipse` on macOS, `C://some-path/ecplise.exe` on Windows). Wild Web Developer will therefore try to launch the language server with Eclipse itself instead of Java

**Comment by mickaelistria** [comment]
Thanks for the analysis. Can you please submit a PR to fix that?

**Comment by PyvesB** [comment]
My PR would consist of a full revert of that commit. Probably best to first ping @BoykoAlex to see what his intent was on the problematic commit in the first place.

**Comment by BoykoAlex** [comment]
@PyvesB well... starting new eclipse instance was not the intent of course. The fix was for #592 - you can find the original intent of the fix there. I'd probably switch the computation of the JVM running eclipse to **java.home** sys property.

**Comment by BoykoAlex** [comment]
@PyvesB i can provide the PR for the problem i've caused if you like

**Comment by PyvesB** [comment]
@BoykoAlex sure, go for it! Busy start of the year for me, I'm not finding much time for open-source development at the moment. :)

**Comment by wimjongman** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=570607
