### ISSUE TITLE
NullPointerException: serverHTML Language Server

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#608]
I get this error sporadically and a few seconds before, the fan of my machine goes wild and the Eclipse IDE does respond very bad. The fan does not stop until I kill Eclipse and restart again. It's not the fault of eclipse, but of this plugin:

```
An internal error occurred during: "Setting watch projects on serverHTML Language Server (VSCode)".
java.lang.NullPointerException
```

I have to kill eclipse IDE and restart again to run normally.

_Eclipse IDE for Enterprise Java Developers
Version: 2020-12 (4.18.0)
Wild Web Developer (v0.10.6.202101221720)_

**Comment by mickaelistria** [comment]
Do you have more details in the log?

**Comment by nimo23** [comment]
My log does not contain the term "Setting watch projects on serverHTML" but other things which are unrelated to this and happened before. When this happens again, I will look in my log and let u know.

**Comment by nimo23** [comment]
The error happens just again:

![Screenshot at Feb 02 23-28-43](https://user-images.githubusercontent.com/3045549/106671817-584c2700-65af-11eb-9df9-8fadd97c1cc1.png)


The fan goes wild and does not stop, so I have to restart eclipse again. The log does **not** show any error. Only the popup is shown.

**Comment by mickaelistria** [comment]
I looked at the code and may have found 2 possible causes:
* Either 1 project is "virtual" and doesn't resolve to a filesystem location, or
* the file is closed shortly after it's opened, so the job to update the watched folder gets triggered after the LS is stopped, causing to go into an unstable state.

Both are addressed with https://git.eclipse.org/r/c/lsp4e/lsp4e/+/175677 . I'll merge it later and then will ask you to try the newer LSP4E snapshots to verify they fix the issue.

**Comment by mickaelistria** [comment]
Snapshots of LSP4E are now available for testing at https://download.eclipse.org/lsp4e/snapshots/

**Comment by nimo23** [comment]
updating solves this issue so far. thanks.
