### ISSUE TITLE
Reference from an Angular component to another is a separate source folder gives red crosses

### ISSUE THREAD

**Issue by Lucas3oo** [eclipse/wildwebdeveloper#613]
I have a pretty advanced setup where a "page" component called UserSettingsPageComponent"" references a shared component in the same "project" but different top folder.

I have checked all the exports on the shared components and also all  the imports on the "page" component.
On the UserSettingsPageComponent I point to a template and in the template I reference the shared component.
But I get the below error:
_Multiple annotations found at this line:
	- Unknown tag (lib-user-settings).
	- 'lib-user-settings' is not a known element:
1. If 'lib-user-settings' is an Angular component, then verify that it is part of this module.
2. If 'lib-user-settings' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of 
 this component to suppress this message._

And yes "lib-user-settings" is an Angular component but defined in its own module in the shared folder.
Not in the UserSettingsPageComponent.

E.g
```
import { ChangeDetectionStrategy, Component } from '@angular/core';


@Component({
  templateUrl: './user-settings-page.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UserSettingsPageComponent {
}

```
File user-settings-page.component.html which has the error looks like:
`<lib-user-settings></lib-user-settings>`

The shared component's definitions:
```
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
@Component({
  selector: 'lib-user-settings',
  templateUrl: './user-settings.component.html',
  styleUrls: ['./user-settings.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UserSettingsComponent {
<snip>
```

I suspect that the cross references do not work.
However I can command-click on UserSettingsComponent in 
`import { UserSettingsModule } from 'shared';`
and I will jump to right file.

I am using 
Version: 2020-12 (4.18.0)
Build id: 20201210-1552
The JEE version which comes with build in the wild web plugin.

**Comment by Lucas3oo** [comment]
I did also tried version 0.10.6.202102022303 from the snapshot repo.
Same error.


Logs from language server:
[t=1612535512566] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":4,"uri":"file:///Users/lpersson/src/c360/c360-admin/web/src/app/pages/user-settings/user-settings-page.component.html"},"contentChanges":[{"range":{"start":{"line":0,"character":39},"end":{"line":0,"character":39}},"rangeLength":0,"text":" "}]}}

[t=1612535512802] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/lpersson/src/c360/c360-admin/web/src/app/pages/user-settings/user-settings-page.component.spec.ts","diagnostics":[]}}

[t=1612535512803] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/lpersson/src/c360/c360-admin/web/src/app/pages/user-settings/user-settings-page.component.html","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":39}},"message":"'lib-user-settings' is not a known element:\n1. If 'lib-user-settings' is an Angular component, then verify that it is part of this module.\n2. If 'lib-user-settings' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.","severity":1,"code":0,"source":"ng"}]}}

**Comment by mickaelistria** [comment]
Can you please build the most minimal project that reproduce the issue and provide detailed steps to reproduce?
I think it's caused by https://github.com/theia-ide/typescript-language-server/issues/66 .

**Comment by Lucas3oo** [comment]
Yeah, I will try to create a minimal project.

I checked the issue you mention. But the setup I have is like one Eclipse project but inside I have several folders with typescript code.

In Eclipse project's root folder I have e.g. the angular.json, package.json, tsconfig.json etc 


tsconfig.json looks like this:
`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
    "plugins": [
      {
        "name": "typescript-eslint-language-service"
      }
    ],
    "paths": {
      "@environment": [
        "src/environments/environment"
      ],
      "core": [
        "dist/core/core",
        "dist/core",
        "projects/core/src"
      ],
      "shared": [
        "dist/shared/shared",
        "dist/shared",
        "projects/shared/src"
      ]
    }
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}`

**Comment by Lucas3oo** [comment]
The html file for my component looks like this:

```
<lib-user-settings
  [currentUser]="currentUser$ | ngrxPush"
  (userSave)="saveUser($event)"
  (passwordChange)="changePassword()"
  (discardChanges)="discardChanges()"
>
</lib-user-settings>
```

Are you suppose to be able to COMMAND-click on the tag and then jump to the definition?

**Comment by Lucas3oo** [comment]
I am not sure what's going on. I have another mac with which I believe is the exact same setup when it comes to Eclipse version WWD version and node versions.
But here it works. Logs from the Eclipse -> LS when I can COMMAND-click on the html/angular tag in the html file:
[t=1613678676379] LSP4E to org.eclipse.wildwebdeveloper.angular:
{"jsonrpc":"2.0","id":"441","method":"textDocument/definition","params":{"textDocument":{"uri":"file:///xxxx/web/src/app/pages/user-settings/user-settings-page.component.html"},"position":{"line":6,"character":12}}}

[t=1613678676382] org.eclipse.wildwebdeveloper.angular to LSP4E:
{"jsonrpc":"2.0","id":"441","result":[{"originSelectionRange":{"start":{"line":0,"character":0},"end":{"line":6,"character":20}},"targetUri":"file:///xxxx/web/projects/shared/src/lib/user-settings/user-settings.component.ts","targetRange":{"start":{"line":12,"character":0},"end":{"line":148,"character":1}},"targetSelectionRange":{"start":{"line":12,"character":0},"end":{"line":148,"character":1}}}]}

**Comment by Lucas3oo** [comment]
It seems to randomly work as it should. I suppose it is more how often and to what extent the Generic editor is invoking the LS  to resolve these things.
Just like it takes a couple of seconds after you have commas/control-clicked on tag before the "hyper link" gets enabled so you can jump to  the definition.

**Comment by mickaelistria** [comment]
Thanks for the feedback. Let's close.
