### ISSUE TITLE
@angular/language-service is removed but as far as i can see it really still needs it.

### ISSUE THREAD

**Issue by jcompagner** [eclipse/wildwebdeveloper#625]
when i update the the latest sources and make sure i build the plugin once (to get all the latest node_modules)

i get:

Error: Failed to resolve '@angular/language-service' with minimum version '11.1' from [
  "C:\\Users\\jcomp\\git\\wildwebdeveloper\\org.eclipse.wildwebdeveloper\\node_modules\\@angular\\language-service"
]
    at resolveWithMinVersion (C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:1677:12)
    at Object.resolveNgLangSvc (C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:1697:13)
    at C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:1787:30
    at createCommonjsModule (C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:197:36)
    at C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:1761:15
    at define (C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:174:5)
    at Object.<anonymous> (C:\Users\jcomp\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\node_modules\@angular\language-server\index.js:179:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

i think this is because of:

https://github.com/eclipse/wildwebdeveloper/commit/26c8c68faadf1afda0d8d7632faa826e008f0898#diff-09dff695c5eae7e732efb7584b2d574ca21c431f100d483992c8e7686a4e177eL155

which removed one.

i updated it locally to the latest 11.2 and added the "service" back:

								<arg>@angular/language-service@11.2.0</arg>
								<arg>@angular/language-server@11.2.0</arg>

and it started working again.

**Comment by jcompagner** [comment]
https://github.com/eclipse/wildwebdeveloper/pull/629

**Comment by mickaelistria** [comment]
Can you please provide steps to reproduce this issue? Ideally capturing it in some automated test?

**Comment by jcompagner** [comment]
ah
i do run mvn clean generate-resources in org.eclipse.wildwebdeveloper

but if you don't delete node_modules then it merges stuff in
So i already had i guess a language-service so it didn't upgrade this transitive dependency 
i guess npm already thought it was there..

i guess in this scenario "mvn clean" should really also clean out "node_modules" so it just updates it

![image](https://user-images.githubusercontent.com/3274268/107990776-749b8b00-6fd5-11eb-9df4-2e10f2200e26.png)


you can see in the above picture i run twice mvn clean generate-resources

the first time i deleted node_modules, the second time i did not
as you can see it only updated the second time the server, it kept the service

so this is tricky when updating it, if anything is changed your really need to make sure the node_modules is deleted first..

**Comment by jcompagner** [comment]
ahh now i understand why it fails
the clean plugin is not correct, that needs to be:

**	<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<configuration>
					<filesets>
						<fileset>
							<directory>node_modules</directory>
						</fileset>
						<fileset>
							<directory>.</directory>
							<includes>
								<include>package-lock.json</include>
							</includes>
						</fileset>
					</filesets>
				</configuration>
			</plugin>

because the current one 

<filesets>
						<fileset>
							<directory>node_modules</directory>
							<includes>
								<include>package-lock.json</include>
							</includes>
						</fileset>
					</filesets>

means delete the file package-lock.json in the dir node_modules (and only that file)

**Comment by jcompagner** [comment]
@mickaelistria do you need a pull request for this change in the pom.xml to fix the cleaning?
Or can you just apply the above code snippet?

This way the next time it is build its not that an older version of @angular/language-service is left there because it seems that transitive dependencies are not upgraded when there is already a version of it.. (at least that happens for me)

**Comment by mickaelistria** [comment]
> do you need a pull request for this change in the pom.xml to fix the cleaning?

Sure, that would be welcome.
