### ISSUE TITLE
Highlighter color for .css files in dark theme looks wrong

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#631]
See screenshot, the highlighter color in the dark theme for CSS files is too light.

![EugXseHXIAEXg9M](https://user-images.githubusercontent.com/139910/108358029-8441ec00-71ee-11eb-806e-5acc77522fac.png)

**Comment by mickaelistria** [comment]
Can you please verify this issue happens or not with other file formats in the Generic editor (eg JS, TS, HTML, JSON, XML, RS...)? I suspect this is an issue in LSP4E and should be reported there.

**Comment by mickaelistria** [comment]
No news for a while. Let's close.
