### ISSUE TITLE
[XML] Preferences page for validation XML

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#634]
To fix some XML validation errors described in https://github.com/eclipse/wildwebdeveloper/issues/557, WWD should provide the capability to customize XML LemMinx validation. To do that WWD should provide the UI preferences to customize those settings.

**Comment by angelozerr** [comment]
Thanks @mickaelistria !

**Comment by mickaelistria** [comment]
Everything is merged. you can now try this new validation page.
