### ISSUE TITLE
Custom CSS Properties and Warnings in Editor

### ISSUE THREAD

**Issue by felixdo** [eclipse/wildwebdeveloper#638]
Maybe I go against all the web rules here, but I use non-standard custom css properties in combination with the E4 CSS engine to style parts of my RCP application. When I edit such css files, I get warnings "unknown property:...". Is there any good way I can integrate the CSS editor so that my custom properties don't trigger warnings?

**Comment by mickaelistria** [comment]
Wild Web Developer uses the CSS Language Server from VSCode. I'm not sure this language server provides options to deal with such custom properties, or whether some convention exist about custom properties name to get them ignored by the LS...

**Comment by felixdo** [comment]
Ok no worries

**Comment by angelozerr** [comment]
The CSS language server supports that and my PR provides an UI table to add/remove those custom properties https://github.com/eclipse/wildwebdeveloper/pull/925#issuecomment-1292923816
