### ISSUE TITLE
Is there support to convert from JSON to YAML?

### ISSUE THREAD

**Issue by jlczuk** [eclipse/wildwebdeveloper#639]
There are plenty of online tools, sure.  But when working on a project for your employer, that is considered proprietary, one can't just go pasting stuff into online converters.

Thanks for this great plugin!

**Comment by jabby** [comment]
There is no support to convert json to yaml. If your are a Java developer, you can easily create a little main to convert json to yaml through jackson. Here is a little sample of code to introduce how to do : https://stackoverflow.com/a/41899647

I don't think we will implement such conversion as yaml support and json support are provided by 2 distinct language servers.

**Comment by mickaelistria** [comment]
This is not planned in Wild Web Developer. I imagine there are decent CLI tools that would perform such operation well and would be easier to use than an IDE.
