### ISSUE TITLE
Move to Eclipse.org

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#64]
We should move BlueSky to Eclipse.org to grow user and contributer pool and to start placing BlueSky as a real competitor to WebTools/JSDT.

**Comment by PhaserEditor2D** [comment]
This will be great.

**Comment by mickaelistria** [comment]
Process started: https://dev.eclipse.org/mhonarc/lists/tools-pmc/msg04473.html
I authored the proposal and it should be published soon.

**Comment by mickaelistria** [comment]
We'll need to:
* Open a CQ for the code
* Open CQ for the dependencies (node modules I guess) one by one...

**Comment by mickaelistria** [comment]
Done.

**Comment by PhaserEditor2D** [comment]
Where is the repo now?

**Comment by mickaelistria** [comment]
The p2 repo is currently still on JBoss Nexus. It'll move to Eclipse.org when build is migrated.

**Comment by PhaserEditor2D** [comment]
Sorry, I mean, the source repo. Is it going to be on Eclipse Gerrit?

**Comment by mickaelistria** [comment]
>
> Sorry, I mean, the source repo. Is it going to be on Eclipse Gerrit?
>
Nope, you're on it, it's an Eclipse GitHub repo.
