### ISSUE TITLE
How to enable autocomplete?

### ISSUE THREAD

**Issue by paulgureghian** [eclipse/wildwebdeveloper#640]
In the Eclipse JavaScript IDE ? it wasn't there out of the box. 
I created a .js file association and .js content type for the generic editor and it still wont autocomplete for .js source code files.

**Comment by mickaelistria** [comment]
Can you please download an IDE from https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/ and report whether this one does work for you?

**Comment by mickaelistria** [comment]
No news for a while, let's close.
