### ISSUE TITLE
Installing Latest Version in Existing IDE

### ISSUE THREAD

**Issue by allan-shoup** [eclipse/wildwebdeveloper#649]
What's the best way to install the latest version into an existing Eclipse IDE? It looks like version 0.10.6 is available in the [marketplace](https://marketplace.eclipse.org/content/wild-web-developer-web-development-eclipse-ide-experimental) and 0.10.7 is available via the [update site](http://download.eclipse.org/wildwebdeveloper/snapshots). As far as I can tell, the only way to get 0.11.5 is to install the [standalone IDE](https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs).

**Comment by mickaelistria** [comment]
Using marketplace or update site should give latest version.
Note that feature/bundle versions are different from project version. Features/bundles use some semantic versionong which makes that they're only bumped according to their internal changes, while project version is more a "marketing version".
