### ISSUE TITLE
Jsdoc view

### ISSUE THREAD

**Issue by PhaserEditor2D** [eclipse/wildwebdeveloper#65]
Hi,

Any plan to implement a **Jsdoc** view, like the **Javadoc** view in JDT?

Is it a concern of the LSP4E framework or a BlueSky concern?

**Comment by mickaelistria** [comment]
A dedicated view for documentation isn't really generic and would be a specific feature for BlueSky more than a feature for generic editor.
Doesn't BlueSky already show Jsdoc as hover? Isn't it enough?

**Comment by PhaserEditor2D** [comment]
My point is that BlueSky is more about an IDE than a text editor (like VSCode), and I think an IDE should provide a Documentation view. I agree it is not to be used often, but there are cases where you would like to show the docs in a view and not in a popup, for example, if you are studying a third-party code. Or for example, if you are browsing types and members in a Hierarchy view, or an Outline view, the doc could be shown in the Documentation view.

I think one of the difference between an IDE and a text editor is that an IDE provides solutions for the common tasks but also for specific, no so often tasks. Even if it is about to show a nicer picture in a Power Point presentation. Text editors in Eclipse can change its font to a bigger size, and I remember an argument to implement that was that it is helpful when you are doing a presentation :)

By the way, BlueSky has a Quick Outline command, but also an Outline view. I think is a similar situation.

**Comment by mickaelistria** [comment]
> By the way, BlueSky has a Quick Outline command, but also an Outline view. I think is a similar situation.

The Outline view is a "default" view shipped by Eclipse Platform and there is a dedicated LSP operation (Symbols) for that. So it's easy to push content from language server to a standard view.
But AFAIK, there is no standard Documentation view, and the mapping with Hover is not immediate as Hover is likely to contain other information than documentation (things like a preview or static analysis feedback...), so it's not so trivial to bind.

**Comment by PhaserEditor2D** [comment]
In understand. I will close this issue. I will experiment with "my own" Documentation view. If in the future BlueSky or LSP4E gets a view like this then I will migrate.

Thanks.

**Comment by mickaelistria** [comment]
Feel free to keep the issue open.
BlueSky would welcome a patch adding such a documentation view if you wish to contribute.
If we see that several *DT have a documentation view (like JDT or others) then we can even consider trying to add this view definition to Platform and let plugins contribute to it, just like the outline view.

**Comment by angelozerr** [comment]
> BlueSky would welcome a patch adding such a documentation view if you wish to contribute.

Indeed @PhaserEditor2D I think we should replace JSDT by BlueSky, but to do that we need the same important feature of JSDT.

**Comment by PhaserEditor2D** [comment]
I reopen then.

**Comment by mickaelistria** [comment]
Would the JSDoc be filled with the same information as hover?
I'm wondering whether this shouldn't be a generic LSP4E issue to get the hover doc available as a view?
