### ISSUE TITLE
no formatting and code completion with generic editor after upgrading eclipse

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#653]
After I upgraded to eclipse 2021-03, I have some issues regarding the **generic editor**. When opening js, css, html, jsx, tsx files with generic editor, no theme is shown and code completion does not work anymore. I already deinstalled wwd and installed current snapshot release again, but it does not help. Any ideas?

**Comment by mickaelistria** [comment]
Can you look in Prefrences > TextMate and Preferences > Language Servers to verify Wild Web Developer is properly registered in those registries?

**Comment by nimo23** [comment]
I have:

![Screenshot at Mar 20 19-41-32](https://user-images.githubusercontent.com/3045549/111882397-9eb9e180-89b5-11eb-8d32-488e1860ce84.png)


and

![Screenshot at Mar 20 19-41-51](https://user-images.githubusercontent.com/3045549/111882417-bd1fdd00-89b5-11eb-8a87-bb45274fe402.png)

**Comment by mickaelistria** [comment]
Only XML support of Wild Web Developer is installed properly. Please ensure that Wild Web Developer in general is properly installed.

**Comment by nimo23** [comment]
This is my current installation:


![Screenshot at Mar 20 20-31-34](https://user-images.githubusercontent.com/3045549/111883580-8a2d1780-89bc-11eb-9102-a830302857d8.png)






I already had wwd installed correctly. After upgrading eclipse, this issue happend. I then re-installed but does not help. I will try to re-install again and use -clean.

**Comment by nimo23** [comment]
I tried it again and it does NOT work.

I did the following:

1. deinstalled all wwd components
2. restart with -clean
3. restart again without -clean
4. installed wwd (snapshot-version) again. 

![Screenshot at Mar 20 21-13-42](https://user-images.githubusercontent.com/3045549/111885236-e137ea00-89c6-11eb-891d-c6219827139a.png)

5. Then restart again and, as you see, wwd **is** installed:

![Screenshot at Mar 20 21-48-03](https://user-images.githubusercontent.com/3045549/111885328-66bb9a00-89c7-11eb-8432-cfd51f457c51.png)


However, generic editor does not recognise any files. What should I do now? @mickaelistria Can you check that wwd snapshot version works with eclipse 2021-03?

**Comment by nimo23** [comment]
I deleted the following files by myself and installed it again. Uninstalling by "Eclipse->Uninstall" did not delete the following files:

org.eclipse.wildwebdeveloper_0.5.14.202102181620
org.eclipse.wildwebdeveloper.embedder.node
org.eclipse.wildwebdeveloper.embedder.node_0.2.2.202102092209.jar
org.eclipse.wildwebdeveloper.embedder.node.macos.x86_64_0.1.2.202102091935.jar
org.eclipse.wildwebdeveloper.xml
org.eclipse.wildwebdeveloper.xml_0.11.0.202102250843.jar


However, after deleting, I tried to install it again and now I get this error:

```
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.15.202103050806
```

**Comment by nimo23** [comment]
I **downgraded** to 2020-12, now it works. Would be nice if wwd takes care of upgrading issues before a new final eclipse release.

**Comment by mickaelistria** [comment]
I just installed Eclipse IDE for Enterprise Java developers 2021-03, which includes latest release of Wild Web Developer. I had to do "Open With > Generic Editor", and after that, everything works as expected. I then upgraded to latest snapshots, and things kept working.
Are you sure you're using the Generic Editor? Have you tried the IDE shipped by Wild Web Developer directly?

**Comment by nimo23** [comment]
Yes, I used "Open With > Generic Editor" (definitly!). I don't know why it did not work for me. I will close this issue.

**Comment by nimo23** [comment]
FYI: I tried it again: I downgraded to 2020-12 (with the help of Installation History->Revert installation). Then I installed the latest wwd snapshot. Then I restart and wwd was correctly installed as you see:


![Screenshot at Mar 22 16-26-53](https://user-images.githubusercontent.com/3045549/112024559-9d62f300-8b34-11eb-9938-bf2b1e23755b.png)


After that, I did a upgrade to 2021-03 (by Eclipse->Update) and nothing else. After restart, I get this:

<img width="691" alt="Screenshot at Mar 22 17-27-51" src="https://user-images.githubusercontent.com/3045549/112024949-fa5ea900-8b34-11eb-9440-bc9cafbc9708.png">

And after that, wwd seems be corrupted..

**Comment by mickaelistria** [comment]
Can you please look at `<worksapce>/.metadata/.log`? It may tell more about some dependency resolution issue.

**Comment by nimo23** [comment]
>Can you please look at <worksapce>/.metadata/.log

Yes, I found this:


```
!ENTRY org.eclipse.wildwebdeveloper 4 0 2021-03-22 19:27:40.131
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper [1026]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wildwebdeveloper [osgi.identity; type="osgi.bundle"; version:Version="0.5.15.202103050806"; osgi.identity="org.eclipse.wildwebdeveloper"; singleton:="true"] because it is exposed to package 'com.google.gson.annotations' from resources com.google.gson [osgi.identity; type="osgi.bundle"; version:Version="2.8.6.v20201231-1626"; osgi.identity="com.google.gson"] and com.genuitec.eclipse.codetogether.core [osgi.identity; type="osgi.bundle"; version:Version="3.2.0.202101272043"; osgi.identity="com.genuitec.eclipse.codetogether.core"; singleton:="true"] via two dependency chains.

Chain 1:
  org.eclipse.wildwebdeveloper [osgi.identity; type="osgi.bundle"; version:Version="0.5.15.202103050806"; osgi.identity="org.eclipse.wildwebdeveloper"; singleton:="true"]
    require: (&(osgi.wiring.bundle=com.google.gson)(bundle-version>=2.8.2))
     |
    provide: osgi.wiring.bundle: com.google.gson
  com.google.gson [osgi.identity; type="osgi.bundle"; version:Version="2.8.6.v20201231-1626"; osgi.identity="com.google.gson"]

Chain 2:
  org.eclipse.wildwebdeveloper [osgi.identity; type="osgi.bundle"; version:Version="0.5.15.202103050806"; osgi.identity="org.eclipse.wildwebdeveloper"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.lsp4j)(bundle-version>=0.5.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="0.10.0.v20201105-1103"; osgi.wiring.bundle="org.eclipse.lsp4j"
  org.eclipse.lsp4j [osgi.identity; type="osgi.bundle"; version:Version="0.10.0.v20201105-1103"; osgi.identity="org.eclipse.lsp4j"]
    import: (&(osgi.wiring.package=com.google.gson.annotations)(&(version>=2.8.0)(!(version>=3.0.0))))
     |
    export: osgi.wiring.package: com.google.gson.annotations
  com.genuitec.eclipse.codetogether.core [osgi.identity; type="osgi.bundle"; version:Version="3.2.0.202101272043"; osgi.identity="com.genuitec.eclipse.codetogether.core"; singleton:="true"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.jboss.tools.quarkus.lsp4e 4 0 2021-03-22 19:27:40.338
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.jboss.tools.quarkus.lsp4e [1313]
  Unresolved requirement: Require-Bundle: org.eclipse.wildwebdeveloper
    -> Bundle-SymbolicName: org.eclipse.wildwebdeveloper; bundle-version="0.5.15.202103050806"; singleton:="true"
       org.eclipse.wildwebdeveloper [1026]
         No resolution report for the bundle.  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.jboss.tools.quarkus.lsp4e [osgi.identity; type="osgi.bundle"; version:Version="1.3.0.v20201125-1723"; osgi.identity="org.jboss.tools.quarkus.lsp4e"; singleton:="true"] because it is exposed to package 'com.google.gson.annotations' from resources com.google.gson [osgi.identity; type="osgi.bundle"; version:Version="2.8.6.v20201231-1626"; osgi.identity="com.google.gson"] and com.genuitec.eclipse.codetogether.core [osgi.identity; type="osgi.bundle"; version:Version="3.2.0.202101272043"; osgi.identity="com.genuitec.eclipse.codetogether.core"; singleton:="true"] via two dependency chains.

Chain 1:
  org.jboss.tools.quarkus.lsp4e [osgi.identity; type="osgi.bundle"; version:Version="1.3.0.v20201125-1723"; osgi.identity="org.jboss.tools.quarkus.lsp4e"; singleton:="true"]
    require: (osgi.wiring.bundle=com.google.gson)
     |
    provide: osgi.wiring.bundle: com.google.gson
  com.google.gson [osgi.identity; type="osgi.bundle"; version:Version="2.8.6.v20201231-1626"; osgi.identity="com.google.gson"]

Chain 2:
  org.jboss.tools.quarkus.lsp4e [osgi.identity; type="osgi.bundle"; version:Version="1.3.0.v20201125-1723"; osgi.identity="org.jboss.tools.quarkus.lsp4e"; singleton:="true"]
    require: (osgi.wiring.bundle=org.eclipse.lsp4j)
     |
    provide: osgi.wiring.bundle; bundle-version:Version="0.10.0.v20201105-1103"; osgi.wiring.bundle="org.eclipse.lsp4j"
  org.eclipse.lsp4j [osgi.identity; type="osgi.bundle"; version:Version="0.10.0.v20201105-1103"; osgi.identity="org.eclipse.lsp4j"]
    import: (&(osgi.wiring.package=com.google.gson.annotations)(&(version>=2.8.0)(!(version>=3.0.0))))
     |
    export: osgi.wiring.package: com.google.gson.annotations
  com.genuitec.eclipse.codetogether.core [osgi.identity; type="osgi.bundle"; version:Version="3.2.0.202101272043"; osgi.identity="com.genuitec.eclipse.codetogether.core"; singleton:="true"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)












```

**Comment by nimo23** [comment]
Thanks @mickaelistria. I uninstalled the plugin "codetogether" and after restart wwd with its generic editor works again:) Maybe wwd can isolate its own libs so that it does not conflict with other plugins.

**Comment by mickaelistria** [comment]
The issue is really codetogether exporting some packages of libs that are actually not his instead of consuming them from official bundles.
