### ISSUE TITLE
How to disable autocomplete?

### ISSUE THREAD

**Issue by alderg** [eclipse/wildwebdeveloper#655]
How to disable autocomplete for JavaScript in the Eclipse JavaScript IDE?

**Comment by mickaelistria** [comment]
Why do you want to disable autocompletion?

**Comment by alderg** [comment]
I'm using a MacBook with Intel CPU which would be completely silent, but the autocompletion triggers the fan and slows down the typing. Hover is also not really needed. I'd only need formatting and coloring.

**Comment by mickaelistria** [comment]
Wild Web Developer doesn't support disabling completion, but you may want to play with Window > Preference > Help > Language Server to disable the JS/TS language server. It should disable a bunch of things, including completion.
