### ISSUE TITLE
eclipse shortcuts for toggle comments not fully work in js/jsx/ts/tsx

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#658]
The default eclipse shortcut methods for commenting line(s) in js files are as follows:

![Screenshot at Mar 26 09-24-24](https://user-images.githubusercontent.com/3045549/112604531-8bc06a80-8e16-11eb-840f-175662c666ca.png)

However, when toggling comments in, for example, tsx files, then "Cmd+7" or "Cmd+/" does not work.

Expected Behaviour: **all eclipse shortcut methods for "js"-files** should remap to "jsx, ts, tsx".

**Comment by mickaelistria** [comment]
Those "Editing JavaScript Source" shortcuts are for the legacy/WTP JavaScript editor and are not related to Wild Web Developer.
On Linux, with Wild Web Developer (WTP JS editor not even installed) I can use the generic Ctrl+Shift+C and Ctrl+Shift+/ shortcuts to comment block/lines without issue. Please try it.

**Comment by nimo23** [comment]
Yes, `Ctrl+Shift+C` works. However, it's a little umcomfortable in compare to `CMD+7` (which is also the default for on/off java comments). Maybe wwd can provide its own shortcuts which remaps the shortcuts from legacy/WTP JavaScript editor (as default)?
