### ISSUE TITLE
jsdoc generation for js/jsx/ts/tsx

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#659]
When creating the jsdoc comment above a method, constructor, etc. then it does not include the return type or the properties in this jsdoc. 

```
// When including jsdoc, props and return type should be included.
/** 
*/
constructor(item: Item){
}
```

Should be:

```
/** 
 * @param item
*/
constructor(item: Item){
}

/**
* @return item
*/
get getItem(): Item{
    return this.item;
}
```

Would be nice to include this information automatically in jsdoc.

**Comment by mickaelistria** [comment]
This is a feature that should be provided by the language server. Can you please report it to https://github.com/theia-ide/typescript-language-server/issues/ ?

**Comment by nimo23** [comment]
Ok, did it: https://github.com/theia-ide/typescript-language-server/issues/194
