### ISSUE TITLE
Which config file is used for formatting rules for html files?

### ISSUE THREAD

**Issue by Lucas3oo** [eclipse/wildwebdeveloper#662]
Wild web developer is using VSCode LS for html and VSCcode saves html formatting rules in .vscode/settings.json but it doesn't seems like Wild web developer is reading that.

**Comment by mickaelistria** [comment]
Indeed, the .vscode/settings.json file ignored at the moment.
Which specific formatting settings are you willing to override?

**Comment by Lucas3oo** [comment]
It is hard to tell. But for now I suppose  "html.format.wrapAttributes": "force-expand-multiline" is the one that we want most.
VSCode does it slightly differently compared to Eclipse WST which is why I was looking into using WWD for formatting.
We have teams that have both "full stack" developers which uses Eclipse and WWD and frontend developers that are using VSCode. I want some way to share formatting rules between the two IDE/editors.

**Comment by mickaelistria** [comment]
Reading .vscode/settings.json and passing it as intiailizeOptions wouldn't be too difficult I guess, and I expect it would be enough for the LS to consider those settings (I'm not certain though). I have doubts about how does VSCode deal with formats when one has multiple projects & .vscode/settings.json files. Does it start a separate language server for each project or does it reuse the same one? And, if the later, how does it pick the right settings?

The HTMLLanguageServer class in Wild Web Developer would be the entry point for passing the settings as initializationOptions.
