### ISSUE TITLE
Missing About dialog data in product

### ISSUE THREAD

**Issue by akurtakov** [eclipse/wildwebdeveloper#665]
Open About dialog and look at Version and Build id fields having {1} and {0} respectively . 
Go to plugins tab and search for wildweb - 	Eclipse IDE for JavaScript and Web Development - branding	0.11.5.202102102309	org.eclipse.wildwebdeveloper.product.branding has Provider column with pluginVendor.

**Comment by mickaelistria** [comment]
I removed {0} and {1} from the about text. Details about the version can be found in installation details.
