### ISSUE TITLE
Support Javascript code in a PHP file

### ISSUE THREAD

**Issue by fujiokae** [eclipse/wildwebdeveloper#668]
I know WWD uses Generic Text Editor. The problem is that I sometimes insert Javascript codes in PHP files (.php) and WWD does not support such codes in PHP files. Is it possible to have WWD take care of Javascript codes in PHP files?

I'm requesting this as I have been using Eclipse with JSDT for a long time and JSDT supports the JS codes in PHP files (e.g. auto-completion works and codes are colored as in a js file).

**Comment by akurtakov** [comment]
For PHP you might want to look into https://github.com/eclipselabs/lsp4e-php and trying to bring it back to live. IIRC it was started by the people working on PDT. The underlying layer https://github.com/felixfbecker/php-language-server is where such js integration should happen in the LSP world.

**Comment by mickaelistria** [comment]
You can maybe hack it by going to content-types and make the `*.php` files match the HTML Content Type so the HTML Language Server would kick in with some JS support. But it probably has glitches.
FWIW, PHP is not in the scope of Wild Web Developer. As @akurtakov mentions, other plugins should be used for that.

**Comment by akurtakov** [comment]
I'm closing this one as it's out of scope for the project.
