### ISSUE TITLE
label TODO in generic editors

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#671]
Please provide the following:

Adding a comment with keyword TODO

`// TODO refactor`

should place a TODO entry in Eclipse IDE.

Eclipse IDE does already use TODO-keyword, but wwd cannot handle it.

**Comment by akurtakov** [comment]
What file type are you editing?

**Comment by nimo23** [comment]
The common files "js, jsx, ts, tsx, css". 

The generic editor does not understand the `// TODO` marker.

**Comment by mickaelistria** [comment]
This feature requires the file to be parsed, to distinguish what's in comments vs what's not. The IDE/client doesn't parse files, nor even knows what the comment characters are.
That would probably require some operation to provide that on the language server side.

**Comment by mickaelistria** [comment]
This was implemented some time ago in TM4E and has been available for Wild Web Developer since then.
