### ISSUE TITLE
Jakarta

### ISSUE THREAD

**Issue by BalchaTemesgenSemu** [eclipse/wildwebdeveloper#678]
I really did not like what you did with Javax by substituting it with Jakarta. It is a really bad move. No back ward compatibility. It is really annoying!!!!!

**Comment by akurtakov** [comment]
Can you be more specific what exactly the problem is for you?

**Comment by akurtakov** [comment]
You're reporting against wrong project - there is no JPA and Javax functionality in this project. Your issue is with Eclipse WTP project  which is entirely different project, please move your issue to it  https://bugs.eclipse.org/bugs/enter_bug.cgi?classification=WebTools

**Comment by nitind** [comment]
Uh, please do NOT do that as WTP has no influence on the specification projects, we only try to provide tooling for them.
