### ISSUE TITLE
Wrong install ?

### ISSUE THREAD

**Issue by Thierry58** [eclipse/wildwebdeveloper#685]
Hello
I can't seem to use your extension :(
Found it and installed it from eclipse market place, i even updated it and a few other plugins, but still when I double click a .js or .yml file, nothing happens.
No errors, no warnings, but no editor opens up.
When I try to open an xml in the "generic editor", it opens in a text editor, without colours.

I could not find any entry for Wild Web Developer in Window -> Preferences nor in the menus.
I did not find any log neither ( where should they be located  ? )

I have eclipse IDE for java developpers version 4.16 (2020-06) with plugins for Maven, RAP/RAP tooling, drools and Git.
Is it compatible ?
Any ideas welcome.
Thank you in advance

**Comment by mickaelistria** [comment]
It looks like Wild Web Developer was not properly installed.
Can you see it listed in Help > About > Installation Details > Installed Software?
Do you have anything related in eclipse-workspace/.metadata/.log ?

**Comment by mickaelistria** [comment]
No news for a while, let's close.
