### ISSUE TITLE
Provide macOS/aarch64 embedded node

### ISSUE THREAD

**Issue by nitind** [eclipse/wildwebdeveloper#686]
The Eclipse Platform now has a macOS/aarch64 build. There should be a node embedder for that platform as well.

**Comment by mickaelistria** [comment]
+1, however neither I nor my colleagues have such a aarch64 machine at hand to try it. Do you have one? If yes, would you be able to test, or even to write the patch?

**Comment by mickaelistria** [comment]
I started drafting https://github.com/eclipse/wildwebdeveloper/pull/688 , that one can already try. However it will require to move to node 16.x, doing CQs, adapting a few other things and so on before we can merge it.

**Comment by mickaelistria** [comment]
With 3357dcb272be76b70b50fe038159fb7035051cbe , the current macosx.x86_64 node embedder can also be used on macosx.aarch64. Using the Rosetta x86_64->M1 translation, it should work.
However, that's only theorical, I didn't try it. So anyone please have a look at the dedicated package from https://download.eclipse.org/wildwebdeveloper/snapshots/IDEs/ for macosx/aarch64 when it's available and report whether this works as expected.

A more proper and better performing solution would be to use a dedicated aarch64 Node installation; but as mentioned in previous comment, this first requires moving to node 16.x.

**Comment by nitind** [comment]
> +1, however neither I nor my colleagues have such a aarch64 machine at hand to try it. Do you have one?
I do not, I'm just guessing we'll have packages for it next time and that non-native performance will be suboptimal.
