### ISSUE TITLE
Javascript Content Asist doesn't work in JSP page

### ISSUE THREAD

**Issue by AfshinParhizkari** [eclipse/wildwebdeveloper#702]
I 've installed latest version of eclipse but Javascript Content Asist doesn't work in JSP page.

**Comment by mickaelistria** [comment]
JSP is not in the scope of Wild Web Developer. Some other plugin could probably use parts of Wild Web Developer, or better, of underlying language servers to add support for HTML/JS in JSP files. See #394 which is related, or on user side, you can try playing with content types to make JSP on extension or child content type of HTML

**Comment by AfshinParhizkari** [comment]
thanks for reply
I want  to use content assist for Jscript, css  in JSP file on Eclipse but I can't.
In HTML page, I am using Jscript and css content assist but i don't know Why not use it at JSP?
shall I install some plugin for that? or maybe I have to config something!
