### ISSUE TITLE
Problem reported in YAML files with Ansible vault values

### ISSUE THREAD

**Issue by Amenel** [eclipse/wildwebdeveloper#703]
The Eclipse **Problems** view reports an error of type "Language Servers" when a variable is defined as a vault-encrypted value. I think this should not happen.

The description of the error is "unknown tag <!vault>". And I haven't found a way to ignore such errors (there's no Quick Fix action, and I have disabled all validators but I still get the errors). As a result of one error, the entire file is underlined in the editor, including otherwise valid lines, which makes the edition of the file impossible in practice.

Example contents of such a file, in which I have encrypted the string "Hello" using "Hello" as vault password:
```
---

vault_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34333637346430323237653137613038336166363934626164363833393166333663653131653266
          3864353932613035663361356632613664386461353363310a623262613466613663393832396663
          61323839363163623431353761636534376466633631333536373532383830653335613039626561
          3361613137386162370a303961346332613933623234646565663036623266653163373938373164
          3030

validkey: value
```

I'm running version 0.10.9.202107011614 in Eclipse 2021-06 (4.20.0).
Many thanks.

**Comment by mickaelistria** [comment]
The schema associated with this file seems to be partly incorrect. I assume this schema comes from https://www.schemastore.org/json/ as mentioned in https://github.com/redhat-developer/yaml-language-server . Can you please verify the schema first? If schema seems correct, please consider reporting the issue to https://github.com/redhat-developer/yaml-language-server.

**Comment by jan-z** [comment]
I've also got this problem. As a workaround to stop these errors I've disabled the YAML language server.

As indicated in https://github.com/VSChina/vscode-ansible/issues/194 the solution is to add ` "yaml.customTags" : [ "!vault" ]` in the options for the yaml-language-server.

But where can I set options for language servers in Eclipse? I could not find a way to do so.

**Comment by mickaelistria** [comment]
There are currently no way to configure those language server options from Eclipse IDE.

**Comment by mickaelistria** [comment]
Closing this issue as #930 covers it.
