### ISSUE TITLE
Remove color support for JSON and CSS

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#71]
Once  https://bugs.eclipse.org/bugs/show_bug.cgi?id=533322 will be merged in LSP4E, we must remove the color support https://github.com/mickaelistria/eclipse-bluesky/tree/master/org.eclipse.bluesky/src/org/eclipse/bluesky/colors

**Comment by mickaelistria** [comment]
See PR https://github.com/eclipse/wildwebdeveloper/pull/76

**Comment by mickaelistria** [comment]
Done.
