### ISSUE TITLE
Mass network traffic when installed on a network drive.

### ISSUE THREAD

**Issue by bradhuang9999** [eclipse/wildwebdeveloper#711]
Because my workspace is in network drive.
So if Eclipse access workspace too much will produce mass network traffic.

My Environment:
Window 10 with network drive.
Eclipse 2103

EX:
I just create a static web project
Put jquey in there and open it with Generic Text Editor.
https://code.jquery.com/jquery-3.6.0.js
![image](https://user-images.githubusercontent.com/32221703/130205184-ad772c2f-b91e-41c6-8527-df3d41d3089c.png)

Eclipse will produce periodic mass network traffic 
![image](https://user-images.githubusercontent.com/32221703/130205633-124f4d34-fdbe-4d29-afc0-b5cbafc36987.png)

Once I uninstall wildwebdeveloper from Eclipse, the network traffic will downgrade to normal level again.

**Comment by mickaelistria** [comment]
That's not really expected. Can you please drill down into network traffic analysis and find which resources are requested?

**Comment by bradhuang9999** [comment]
I guess it's because the embedded node.js is in workspace.
position: .metadata\.plugins\org.eclipse.wildwebdeveloper.embedder.node
I try to set org.eclipse.wildwebdeveloper.nodeJSLocation in eclipse.ini
EX: 
-org.eclipse.wildwebdeveloper.nodeJSLocation=c:/node-v14.15.4-win-x64
But it's not working.

What is the proper way to not using the embedded node.js in workspace?

**Comment by mickaelistria** [comment]
Why would this embedded node.js generate more network traffic than another installation?

**Comment by bradhuang9999** [comment]
Because wild web editor use node.js
If node.js is in network drive (default position is in the workspace).
I think it's reasonable to generate more network traffic when invoking node.js.

**Comment by mickaelistria** [comment]
Ah OK, I now understand.
You can set the system property described in https://github.com/eclipse/wildwebdeveloper/blob/master/TIPS_and_FAQ.md#use-embedded-nodejs , this can be done by editing the eclipse.ini, adding `-DpropertyName=propertyValue` after the `-vmargs` entry, and then by restarting Eclipse fully (ie close and then start, not restart).

**Comment by mickaelistria** [comment]
Note that there is nothing Wild Web Developer can change about the fact that network drives cause network traffic. So I'm closing the issue. But we can still discuss it anyway.

**Comment by bradhuang9999** [comment]
@mickaelistria 
so I should have these settings in eclipse.ini?
-vmargs
-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=c:/node-v14.15.4-win-x64

do i still need -DNODSJS_HOME ?

**Comment by bradhuang9999** [comment]
@mickaelistria
Now I get the message Node.js version could not be determined. Please make sure a supported version.
But I copy the node js from workspace\.metadata.plugins\org.eclipse.wildwebdeveloper.embedder.node
