### ISSUE TITLE
Formatting: Line width

### ISSUE THREAD

**Issue by JensGabe** [eclipse/wildwebdeveloper#715]
Where can I specify the maximum line width used by the formatter?

**Comment by mickaelistria** [comment]
For which kind of files? The format command comes from the underlying language server, and different language server may use different approaches to customize formatting.

**Comment by JensGabe** [comment]
JavaScript, typescript, Json, xml and xml

**Comment by JensGabe** [comment]
Specifically where do I define the line length to use in the HTML editor.
The default way it breaks lines when formatting is not ideal for me.

**Comment by mickaelistria** [comment]
I'm not sure which specific settings or configuration the HTML language server honors. This should be investing by auditing how format is provided in https://github.com/microsoft/vscode/tree/main/extensions/html-language-features/server ; as it's the same languaeg server we're using, same settings should work.

**Comment by angelozerr** [comment]
For HTML,once WWD will be released you will able to configure that 

![image](https://user-images.githubusercontent.com/1932211/198133180-8c0c0b10-a917-4150-afd3-4d34e0192436.png)

**Comment by mickaelistria** [comment]
Fixed with #925; this is already available in snspahots that you can try as described in https://github.com/eclipse/wildwebdeveloper/blob/master/CONTRIBUTING.md#-trying-latest-builds
