### ISSUE TITLE
javascript highlighting on custom file extension.

### ISSUE THREAD

**Issue by myshkin-uk** [eclipse/wildwebdeveloper#718]
I have installed WWD. If I open a .js file I see syntax highlighting.

I use .jst as n extension for 'javascript-that-needs-translating'

I have added a file association for it, and it seems to select the same editors as for .js

But when I open a .jst file I get no syntax highlighting.

Also I see we no longer have:
     Window | Preferences | JavaScript | Editor | Syntax Coloring.

but I can't find the modern equivalent.

Where do I start please?

**Comment by mickaelistria** [comment]
Have you defined a new content-type for it in the Content Type preference page, making the new content-type a child of the Wild Web Developer > JavaScript content-type.

**Comment by myshkin-uk** [comment]
Well... I don't want a new content type - I just want a second file extension to work the same way as .js

And if I look on the content type page for javascript, both .js and .jst are in the box. Which is a good start.

But if I open .js files I get syntax coloring, and if I open .jst ones I don't.

If I close the file, alter the file extension to .js, and re-open it I get the colors - put it back to jst and they go away.

**Comment by mickaelistria** [comment]
I tried the following:
1. If have a `hello.js` file > Open With > Generic Editor => Syntax Highlighting works
2. I copy `hello.js` into `hello.jslol`
3. I go to Preferences > Content-Types > Text > Wild Web Developer > JavaScript, and add `*.jslol` to the extensions
4. I open `hello.jslol` and get syntax highlighting.

So it seems like what you're trying does work for me. Can you please verify?

**Comment by myshkin-uk** [comment]
I follow that exact process for jslol and do NOT get colors :-(
So there is some genuine gotcha going on.

**Comment by mickaelistria** [comment]
No news for a while, let's close.
