### ISSUE TITLE
I'd like to disable the css warning 'do not use empty rulesets'

### ISSUE THREAD

**Issue by myshkin-uk** [eclipse/wildwebdeveloper#719]
Can anyone please tell me where and how to disable this check ?

**Comment by mickaelistria** [comment]
I don't know a direct answer; but this warning comes from the CSS language server; it's the same one as the one from VSCode. So maybe try investigating how to disable this warning in VSCode and same trick may work for wild web developer.

**Comment by myshkin-uk** [comment]
Well googling "vscode configure css lint" doesn't get you anything obviously useful on the first two google pages :-)

I'll reconsider when I come back from my holiday !

**Comment by angelozerr** [comment]
CSS language server can be configured to manage sseverty of this error  (ignore, warning, error) with this setting https://github.com/microsoft/vscode/blob/a68f9da5fe7019f52f52c4ad3d2e613470e08d68/extensions/css-language-features/package.json#L122

WWD should provide UI preferences to customize those all CSS settings.

**Comment by angelozerr** [comment]
@vrubezhny I think you can close this issue.
