### ISSUE TITLE
HTML Editor not applying syntax highlighting of javascript code inside <script> tag.

### ISSUE THREAD

**Issue by ludionisio** [eclipse/wildwebdeveloper#722]
Doing a clean install of Eclipse for PHP Developers 2021-06 and then opening a .html file with javascript code inside a <script> tag does not highlight the javascript code, when the editor is the HTML Editor.

If I change the Editor to Generic Text Editor, then all code gets highlighted.

**Comment by mickaelistria** [comment]
The Generic Editor is the one used by Wild Web Developer. Other editors are not related to this project.
