### ISSUE TITLE
Parsing a JavaScript code snippet

### ISSUE THREAD

**Issue by dinkoivanov-gepard** [eclipse/wildwebdeveloper#723]
Hi,

We're building an Eclipse RCP product based on 2019 version, where we use the org.eclipse.wst.jsdt.core.dom.ASTParser to obtain the AST from a code snippet, then traverse and get variable names.
Here's an example:
```
ASTParser parser = ASTParser.newParser(AST.JLS3);
parser.setSource("// some JavaScript code here");
ASTNode ast = parser.createAST(new NullProgressMonitor());
ast.accept(visitor);
```

We're planning to migrate to the latest Eclipse and I saw the Wild Web developer tools are now used instead of JSDT and the ASTParser class is no longer available.

What is the recommended approach to do the equivalent operation/JS parsing with the new tooling?

Thanks,
Dinko

P.S. Great job on the new tools, the JS autocomplete is the real thing!

**Comment by mickaelistria** [comment]
org.eclipse.wst.jsdt.core.dom.ASTParser belongs to JSDT, not to Wild Web Developer.
Wild Web Developer doesn't maintain a dedicated parser per se; all assistance comes from the typescript-language-server which itself delegates to tsserver, which itself... I don't really know and it doesn't matter much from this project perspective ;)

If you still need to parse JavaScript, then you'll have to use JSDT or whichever other parser of your choice, but Wild Web Developer won't provide one.
