### ISSUE TITLE
JS syntax highlight and auto-complete in a SWT Text area

### ISSUE THREAD

**Issue by dinkoivanov-gepard** [eclipse/wildwebdeveloper#724]
Hi,

We're building an Eclipse RCP product and we're planning to include JS editing capabilities in the product by utilizing the Wild Web developer tools.
Besides the JS Syntax highlight and auto-complete in the standard Eclipse Editors, is there a way to apply those features for an SWT Text Area (or some other JFace class)?

Thanks,
Dinko

**Comment by mickaelistria** [comment]
Wild Web Developer per se just binds the editor/viewer with underlying language server (using LSP4E project) and TextMate grammars (using TM4E project).  Please get in touch with those projects -via mailing-list or issues- to find out how to hook their capabilities to a plain viewer without an editor.
