### ISSUE TITLE
js validation hint error if new line before async function

### ISSUE THREAD

**Issue by workhours** [eclipse/wildwebdeveloper#725]
async function bb(){
	reject(1);
}
//above code hint error "Semi-colon expected"

**Comment by mickaelistria** [comment]
I'm not seeing this issue. Are you sure you're using the Generic Editor? Can you look in the "Problems" view what's the "Type" of this problem?

**Comment by workhours** [comment]
![screenshot](https://user-images.githubusercontent.com/1269588/133418025-4b932310-b806-4f5c-924a-c13fb4e07565.png)

**Comment by workhours** [comment]
![screenshot2](https://user-images.githubusercontent.com/1269588/133418439-44cfa02e-1e4d-4a52-962b-370f87888fc2.png)

**Comment by workhours** [comment]
I just noticed if remove first empty line, error marker disappeared but list in Problems view

**Comment by mickaelistria** [comment]
So this issue is not coming from Wild Web Developer, it most likely comes from JSDT. Both are separate projects, so report his issue to JSDT (or maybe even just uninstall JSDT if you don't need it)
