### ISSUE TITLE
Auto-formatting embed JavaScript in php file

### ISSUE THREAD

**Issue by movs21** [eclipse/wildwebdeveloper#728]
Why auto-formatting (by Ctrl-Shift-F) of embed JavaScript inside .php file is not working in my Eclipse? I mean formatting of the block like this:

```
//php code here
?>
<script type="text/javascript">function test(){
console log( a);
        console.log   ('b');}
</script>
<?php
//php code here
```

At the same time  JavaScript colorer works, so the block seems to be recognized as  JavaScript.
If I put the same javascript code inside .js file JavaScript autoformatting works as expected.
I have clean insallation of Eclipse for PHP 2021-06 and WildWebDeveloper.

**Comment by mickaelistria** [comment]
Wild Web Developer is not responsible for what happens in the PGP editor. Please report it to your PHP plugin.
