### ISSUE TITLE
Formatting via ESLint

### ISSUE THREAD

**Issue by acarstoiu** [eclipse/wildwebdeveloper#739]
Hello,

I'm trying to use Wild Web Developer within a project where source code formatting is done via ESLint (what on Earth is that?!). I suppose that this is the equivalent of running
```
eslint --fix --fix-type layout
```
Could this be performed as a code action, i.e. not in _Source_ ->_Format_, but in _Code Actions_ -> _Fix formatting_ ? Make sure that the `--fix-type layout` arguments are provided to ESLint.
Or, if it's already available under some other form, please tell me what I've missed. Thanks!

**Comment by mickaelistria** [comment]
The format operation is provided by the Language Server. I don't know how format is implemented in the typescript-language-server that Wild Web Developer is using. Maybe there is a way to configure something so it delegates format to eslint ?

**Comment by mickaelistria** [comment]
Note that you don't need a code action for that, you can just configure a launch configuration that invokes the eslint command and run it whenever it suits you or on every save as a builder, a similar case is documented in https://github.com/eclipse/wildwebdeveloper/blob/master/TIPS_and_FAQ.md#automatically-compile-typescript-to-javascript-

**Comment by acarstoiu** [comment]
Thank you for your answers. Regarding the current formatting mechanism see [this comment](https://github.com/eclipse/wildwebdeveloper/issues/225#issuecomment-523807311).
I was hoping to avoid it using ESLint as an external tool.
