### ISSUE TITLE
Set up builds on https://jenkins.eclipse.org/wildwebdeveloper/

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#74]
We now have a Jenkins instance provided by the Eclipse Foundation.
We should move the build to https://jenkins.eclipse.org/wildwebdeveloper/ . Best would be to mimic and adapt the configuration of https://github.com/eclipse/aCute/blob/master/Jenkinsfile on https://ci.eclipse.org/acute/job/aCute/ .

**Comment by jabby** [comment]
If you agree, I will take this next week. I have time for this.

**Comment by mickaelistria** [comment]
Sure!

**Comment by mickaelistria** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539633 is a blocker for completion of this task. That said, it's not a blocker for edition of a Jenkinsfile.

**Comment by mickaelistria** [comment]
GitHub credentials are now configured so we can use the Build Pipeline strategy.

**Comment by mickaelistria** [comment]
Sorry, I don't know much about Jenikinsfile.
I suggest you create the multi-branch pipeline job and create a PR nd see
what Jenkins says when it tries.to build the branch with the Jenkinsfile in
your PR.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by jabby** [comment]
Ok I will do that.

**Comment by mickaelistria** [comment]
This is mostly done now.
I've struggled with finding some good docker image to configure the Kubernetes agent and then in having npm working well on a docker image (without user account being properly set, without being root).
Artifacts are signed.
Documentation and other files are updated.
What's missing now is the publication to download.eclipse.org, but I think it can be another topic.
