### ISSUE TITLE
FR for Autofix: Import all 

### ISSUE THREAD

**Issue by leomayer** [eclipse/wildwebdeveloper#743]
If I copy paste some code, e.g.

```
  @Input() ctrl: AbstractControl
```

I get an error since I won't have either `Input` nor `AbstractControl` imported yet. I can easily fix this by CTRL-Space and select the option. This has to be done on each of the statements.

It would be beneficial to have an option by which all the missing `import` would be inserted at once.

**Comment by mickaelistria** [comment]
This has to be requested to the underling language server: https://github.com/typescript-language-server/typescript-language-server

**Comment by mickaelistria** [comment]
Seems like this was implemented upstream, so Wild WEb Developer should have it since.
