### ISSUE TITLE
JS theme control not working

### ISSUE THREAD

**Issue by nexodex-dev** [eclipse/wildwebdeveloper#750]
Hi,

tested with an existing and fresh installation of JavaEE 2021-09
https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-09/R/eclipse-jee-2021-09-R-win32-x86_64.zip

All fine. Your are able to right click and handle the theme styles by context menu. The styles are going to be changed for JS files.

Go to marketplace and add ST4
https://marketplace.eclipse.org/content/spring-tools-4-aka-spring-tool-suite-4
After that, you cannot see the right click context menu inside the js file to load theme by "switch to theme" and the JS file color styles are killed.

![bug](https://user-images.githubusercontent.com/75066840/143560872-fd13a09c-704d-4b86-aa50-943f0b1dc78b.png)

Cheers

**Comment by mickaelistria** [comment]
If the issue happens when installing STS, then it should first be reported to STS.
