### ISSUE TITLE
java.net.URISyntaxException: Illegal character in path

### ISSUE THREAD

**Issue by Phillipus** [eclipse/wildwebdeveloper#752]
I'm getting lots of `java.util.concurrent.TimeoutException and java.net.URISyntaxException: Illegal character in path at index 33: <pathto>\xml.xsd`

In Eclipse 4.22:

1. Open a *.target file
2. Switch to "Source" tab
3. Start editing

Log attached
[errorlog.txt](https://github.com/eclipse/wildwebdeveloper/files/7685675/errorlog.txt)

Eclipse Version: 2021-12 (4.22)
Build id: I20211124-1800
Mac 10.15.7
java.version=11.0.13
org.eclipse.wildwebdeveloper.xml_0.13.1.202111081705

**Comment by kjsmita6** [comment]
Fixed by #757.
