### ISSUE TITLE
Modal dialog pops up out of nowhere with no reason given

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/wildwebdeveloper#764]
At various points in a freshly launched IDE (2021-06 in this case), an error dialog pops up: "Missing node.js".

This is problematic for several reasons:
* This happens with no obvious connection to what the user was doing.
=> Users have no idea how to *avoid* this error (without changing the global configuration of that machine).
* It speaks of "missing key features", but it doesn't give any hint about the kind of feature.
=> Users may get the impression that Eclipse is fundamentally broken, which is wrong.
* I repeatedly observed that this dialog popped up while I was working on something unrelated on a different desktop (likely the dialog actually popped _below_ a window I was working in). When I returned to Eclipse, I had never seen the dialog, yet Eclipse was not accepting any user input.
**=> Here users get the impression that Eclipse spontaneously froze, requiring to kill the process with potential data loss and long build times after the unclean shutdown + relaunch.**

I don't think it is *ever* a good idea to open a modal dialog from background work.

FWIW, this happened in an installation that was oomphed using a setup provided by another team. I didn't even have an idea that WWD was installed, nor did the dialog tell me.

Only jstack revealed:
`"main" #1 prio=6 os_prio=0 cpu=22578,06ms elapsed=58,84s tid=0x00007f533c016000 nid=0x663d runnable  [0x00007f5341489000]
   java.lang.Thread.State: RUNNABLE
        at org.eclipse.swt.internal.gtk.OS.Call(Native Method)
        at org.eclipse.swt.widgets.Display.sleep(Display.java:5504)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:824)
        at org.eclipse.jface.window.Window.open(Window.java:799)
        at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:394)
        at org.eclipse.jface.dialogs.MessageDialog.openWarning(MessageDialog.java:515)
        at org.eclipse.wildwebdeveloper.InitializeLaunchConfigurations.lambda$0(InitializeLaunchConfigurations.java:157)
        at org.eclipse.wildwebdeveloper.InitializeLaunchConfigurations$$Lambda$1047/0x00000008016cb440.run(Unknown Source)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)`

**Comment by stephan-herrmann** [comment]
When I saw `InitializeLaunchConfigurations` in the stack, I searched my existing launch configurations for anything that could possibly require node.js but I found *none*. If that's correct, then the workspace has no indication that node.js is needed. So in addition to the above problems, that error dialog is even unnecessary in my case.

**Comment by mickaelistria** [comment]
Do you have steps to reproduce it from an "official" installation? Can you please get in touch with the people who are providing this setup about their setup being dysfunctional (probably because of Wild Web Developer but it could be the setup itself and thus I think they should be told first).

**Comment by stephan-herrmann** [comment]
@mickaelistria let me clarify: I am not complaining about the fact, that this error (node.js not found) occurs. That's probably perfectly valid, and there are hints how to fix if desired (which is not my goal).

This issue is about the way how that error is reported.

I'm pretty sure, you know better than me how and why InitializeLaunchConfigurations can trigger this dialog, if node.js is missing indeed.

My initial description shows all the details of what i consider problematic, and oomph was mentioned only to set the context, that added to my surprise. Everybody ever ending in this (invalid?) configuration will likely be bewildered in a similar way.

**Comment by mickaelistria** [comment]
Missing node.js shouldn't be an issue anymore as Wild Web Developer embeds a compatible version of node.js.
