### ISSUE TITLE
Please provide a stand-alone installation version

### ISSUE THREAD

**Issue by bestv5** [eclipse/wildwebdeveloper#769]
Can you provide a separate installation version without installing through the Eclipse Plug-in market.

I want to be able to download the standalone plug-in version and install it in eclipse.

**Comment by mickaelistria** [comment]
Can you please submit your issues in English?

**Comment by mickaelistria** [comment]
A standalone version has been available for some time. See https://github.com/eclipse/wildwebdeveloper#as-full-ide-package
