### ISSUE TITLE
eclipse PDT 2021-12 (4.22.0) freezes when editing a JavaScript (*.js) source file

### ISSUE THREAD

**Issue by LigH-de** [eclipse/wildwebdeveloper#789]
Since I updated eclipse PDT to version 2021-12 (4.22.0), as soon as I try to edit a JavaScript source file in a PHP based project, the IDE freezes, Windows 7 displaying an AppHangB1 dialog (Application does not respond) when I close it.

Please request any more details you may need to know.

**Comment by mickaelistria** [comment]
Isn't it a duplicate of #753 ?

**Comment by LigH-de** [comment]
Possibly. I searched for "freeze" and "crash", but not for "hang".
