### ISSUE TITLE
Wildwebdeveloper publishes Eclipse 2021-12 (i.e. 4.22) on its update site

### ISSUE THREAD

**Issue by Yuri-Blankenstein-TNO** [eclipse/wildwebdeveloper#790]
Wildwebdeveloper publishes the whole Eclipse 4.22 PDE on its update site, see e.g. https://download.eclipse.org/wildwebdeveloper/releases/0.13.2/features/

Wildwebdeveloper should only deploy its own features and plugins on its update site. This is most likely caused by a missing setting in Maven Tycho.

**Comment by mickaelistria** [comment]
This is a requirement when publishing products (Wild Web Developer also ship a full IDE package). I don't think it's really an issue per se.

**Comment by bjmi** [comment]
Wildwebdeveloper update site publishes JustJ Hotspot JRE 17 too and leads to **unwanted** updates from e.g. JRE 11 to 17 who has already installed the feature _org.eclipse.justj.openjdk.hotspot.jre.full_ before.

**Comment by bjmi** [comment]
Today JRE **18** appears and will lead to a non-LTS JRE update for many people.
![image](https://user-images.githubusercontent.com/2063480/171806852-ea06912e-aa6b-4478-8f38-5c5bdd5a7bb9.png)

**Comment by mickaelistria** [comment]
Having the whole IDE in the p2 repo is technically mandatory in Tycho at the moment. But it is not a real issue for Wild Web Developer.
About JustJ being part of the site; users are not forced to install it if they don't want it. Moreover, this JustJ 18 doesn't come from Wild Web Developer latest release. Also non-LTS doesn't mean bad. So this is not a Wild Web Developer issue; users can control to install it or not according to their own criteria.

**Comment by bjmi** [comment]
> Moreover, this JustJ 18 doesn't come from Wild Web Developer latest release.

Wild Web Developer latest (0.3.15 atm) https://download.eclipse.org/wildwebdeveloper/releases/0.13.5/features/ does provide JustJ 18
([org.eclipse.justj.openjdk.hotspot.jre.full_18.0.1.v20220515-1614.jar](https://download.eclipse.org/wildwebdeveloper/releases/0.13.5/features/org.eclipse.justj.openjdk.hotspot.jre.full_18.0.1.v20220515-1614.jar)) or am I wrong?

**Comment by mickaelistria** [comment]
Sorry, you're right Wild Web Developer ships JustJ 18. I still had falsely in mind that it was still shipping JustJ 17.
Anyway, users don't have to install it. Usually, users are already running with a local Java or with an already installed JustJ; Wild Web Developer doesn't change it at all, it just has JustJ 18 available but not required.
