### ISSUE TITLE
[JS editor] Curly braces are not highlighted

### ISSUE THREAD

**Issue by Omcsesz** [eclipse/wildwebdeveloper#793]
Hello, Team!

I use JS editor, and the highlighting of the matching curly brace does not work (see attachment). Can you please fix this?

-- Configuration Details --
Product: Eclipse IDE 4.22.0.20211202-1200 
Win10 64-bit

[JSEditorBracesHighlightingDoesNotWork](https://user-images.githubusercontent.com/1839739/155160427-a3ce39e0-505e-4728-95e4-af7fccd288d4.jpg)

**Comment by vrubezhny** [comment]
Hello, 
Looking at your screenshot I don't see WildWebDeveloper JS Editor running. Do you have `Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools` (`org.eclipse.wildwebdeveloper.feature.feature.group`, `Eclipse Wild Web Developer project`)  installed in your Eclipse instance?

Could you please try opening the same file using `Right Click ->  Open With -> Generic Text Editor` - this should open Language Server based Generic Text Editor for JavaScript (if `WildWebDeveloper` is really installed)

**Comment by Omcsesz** [comment]
Isn't the tab marked with the arrow the JSEditor?

[JSEditorBracesHighlightingDoesNotWork](https://user-images.githubusercontent.com/1839739/155504322-4469a881-2606-4017-b772-ab2590b55ef0.jpg)

**Comment by vrubezhny** [comment]
JavaScript editor for me looks like this:
![Screenshot from 2022-02-24 11-29-02](https://user-images.githubusercontent.com/620781/155507632-cc6fdb38-d449-48df-bee5-723a77d675c5.png)
Sorry, at the moment, I can't show how could it look like on Win10, but I'm sure, the editor you see in your IDE is not the WildWebDeveloper's one.
Please try the steps to open `Generic Text Editor` for your JavaScript file I described above and check the version of WWD features are installed in your IDE: `Help -> About Eclipse IDE -> Installation details...` 
![Screenshot from 2022-02-24 11-41-00](https://user-images.githubusercontent.com/620781/155509252-fdb38590-636c-4fb8-8f21-1828f0028cda.png)

**Comment by jabby** [comment]
@vrubezhny for the record, it looks like this on Windows 10 with 

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2021-12 (4.22.0)
Build id: 20211202-1639
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 16.0.2+7-67
Java version: 16.0.2

and Wild Web Developer

![image](https://user-images.githubusercontent.com/1883932/155510298-d4fe9bd9-19ee-49b3-ad4a-40aa767aa87b.png)

**Comment by Omcsesz** [comment]
@vrubezhny If I use `Right Click -> Open With -> Generic Text Editor`, I get this:
[JSEditor](https://user-images.githubusercontent.com/1839739/155511324-d723651b-22a2-4d0a-8925-fd0c6a55e190.jpg)

**Comment by vrubezhny** [comment]
@Omcsesz Does it highlight pair braces? Does it allow you edit the JavaScript file (it case it's not read-only)? Does it provide any kind of content assist by Ctrl-Space and tooltips when hovering the mouse cursor over the JavaScript elements?

**Comment by Omcsesz** [comment]
@vrubezhny I'm sorry, I made a mistake. The JS Editor that creates the problem is connected to "Javascript development tools - chromium debugger".

**Comment by vrubezhny** [comment]
@Omcsesz  If it will be useful for you, I would suggest making `Generic Text Editor` the default one for JavaScript/TypeScript files by right clicking on a `*.js` and/or `*.ts` file, then selecting `Open With -> Other...`, then select `Generic Text Editor`, check `Use it for all :*.js" files` and press `OK`.
HTH
