### ISSUE TITLE
Eslint not working in Eclipse 2022-03

### ISSUE THREAD

**Issue by pestapever** [eclipse/wildwebdeveloper#804]
I downloaded Eclipse 2022-03 JEE zipped version from the official site (https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-03/R/eclipse-jee-2022-03-R-win32-x86_64.zip).

I tried following the video from your readme (▶️ [January 2020] Demo of ESLint in Wild Web Developer https://youtu.be/o-wI_niEz3E) but I cannot see Eslint problems in my markers/problems tab in Eclipse.
My project is in javascript, I have installed eslint local, the rules file, the tsconfig file, but I got no errors (only Javascript problems but not from Eslint). If I run eslint from cmd all is fine.

Is there a getting started or setup instruction to see javascript eslint problems in real time in Eclipse?
Thanx

**Comment by mickaelistria** [comment]
Wild Web Developer has some [unit tests covering ESLint](https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestESLint.java) support and those are currently passing; so I think it's not in a too bad shape and could be more an issue specific to your environment.
Can you please check the Eclipse Log (`<workspace>/.metadata/.log`) whether it does tell a bit more about some things that could go wrong?

**Comment by akurtakov** [comment]
Closing due to lack of interest. If you still face the issue and want to help us find out what/why goes wrong for you please reply to the question asked.
