### ISSUE TITLE
Node.js processes don't stop after the finishing of JUnit tests 

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/wildwebdeveloper#823]
After every run of mvn clean verify I see a number of Node processes (~10) running - some of them are continuing to consume up to 12% of CPU (by gnome-system-monitor ) and each consuming 2.2GB of virtual memory and 1.7GB of resident memory...
If I immediately try to run mvn clean verify again - most likely many tests will fail with the most common Diagnostics not published like failure.

**Comment by mickaelistria** [comment]
I could easiler reproduce it running TestDebug from the IDE. 2 processes remain alive for no good reason
```
mistria   600310  103  0.3 670584 99440 ?        Rl   00:14   0:08 /home/mistria/apps/node-v16.8.0-linux-x64/bin/node /home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/node_modules/node-debug2/out/src/nodeDebug.js
mistria   600420 70.6  0.2 726616 93224 ?        Rl   00:14   0:03 /home/mistria/apps/node-v16.8.0-linux-x64/bin/node /home/mistria/git/wildwebdeveloper/org.eclipse.wildwebdeveloper/node_modules/node-debug2/out/src/nodeDebug.js
```
I didn't yet figure out whether and how this scenario can be reproduced manually by user. My first attempts (hitting stop button while debugging) seem to make the related process stop.

**Comment by mickaelistria** [comment]
This is fixed in LSP4E  https://github.com/eclipse/lsp4e/commit/a340bcc6312ec41a832ea8290c80f14bf5a72bb2 + and a workaround has been implemented in Wild Web Deverloper https://github.com/eclipse/wildwebdeveloper/commit/3ad1f9cdcab5c2db9abb30aaae528ea451532e90
