### ISSUE TITLE
Syntax Coloring

### ISSUE THREAD

**Issue by SLH-Bin** [eclipse/wildwebdeveloper#828]
I would like to use Syntax Coloring in WWD in my *.js Code. In Preference -> Web -> JavaScript there is nothing to change the color (Unlike HTML and CSS). I also tried to use the Syntax Coloring in Client-side-JavaScript, but it doesn't change the color.
I also tried to change the theme in "TextMate", but it doesn't change the text coloring too.
How can I change the Editor Syntax Coloring for Eclipse in WWD?

Thanks

**Comment by mickaelistria** [comment]
Preference -> Web -> JavaScript has no implact on Wild Web Developer; it comes from legacy WTP JS editor.
The right way to change highlighting for Wild Web Developer is to deal with TextMate themes. Does right-click on the editor > Switch to Theme... work?

**Comment by SLH-Bin** [comment]
Thank you. Yes it changes the color from R-Click in Editor and switching to theme. I would like to customize the color for Variables and Strings, ...

**Comment by mickaelistria** [comment]
You'll need to create a textmate theme for that and have it registered in the preferences and associated with the JavaScript files..

**Comment by SLH-Bin** [comment]
I took the time to do this and tried to use some *.css theme as TextMate, but none of them worked. I have also tried to find and edit the exist theme file in TextMata but there is not e.g Monokai.css as a file in PC. 
Do you know maybe how can I find a right TextMate themes so I can edit and add it as theme?
Thanks

**Comment by mickaelistria** [comment]
Please bring this question to https://github.com/eclipse/tm4e/issues/ . I'm closing it here as it's not a question that is specific to Wild Web Developer.
