### ISSUE TITLE
[Angular] F3 - won't open data structure

### ISSUE THREAD

**Issue by leomayer** [eclipse/wildwebdeveloper#839]
Somehow F3 stopped working in some of the upgrades. It won't work any longer on elements which have worked quite well.

[vokoscreenNG-2022-07-06_11-08-20.webm](https://user-images.githubusercontent.com/2641128/177514354-ea0663c3-801e-4914-a9b3-2edbc51511a9.webm)

![Bildschirmfoto vom 2022-07-06 11-09-54](https://user-images.githubusercontent.com/2641128/177514607-0ff93113-00e8-4abb-b0dc-1a3427ef0881.png)

Anything to check or provide additional info?

**Comment by mickaelistria** [comment]
Does F3 work usually for other editors (eg plain .js file) ?

**Comment by leomayer** [comment]
On ts files I can e.g. open methods or variable definitions. But I cannot open the defined html file in the component definition.

**Comment by mickaelistria** [comment]
Can you please share a minimal project that can be used to reproduce the issue?
