### ISSUE TITLE
Memory Leak: huge number of IConsolePartitioner

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/wildwebdeveloper#84]
I have been trying wildwebdeveloper on a small project for a little while, but Eclipse frequently becomes unusable due to lack of Java heap space.

After capturing a heap dump MAT informs me about the following leak suspect:

> One instance of "org.eclipse.ui.internal.console.IOConsolePartitioner" loaded by "org.eclipse.ui.console" occupies 3,642,607,448 (89.82%) bytes. The memory is accumulated in one instance of "java.lang.Object[]" loaded by "<system class loader>".

As I had previously seen errors mentioning IConsoleUpdater, I closed the console view, launched some processes outside Eclipse and did not let the single remaining Eclipse launch allocate any console.

At this point I'm clueless what this heavy work on IOConsoles is all about.

FYI, I mostly edited typescript files in Eclipse.

**Comment by stephan-herrmann** [comment]
This is all that MAT has to say on who holds on to those objects:

![pathstogcroots](https://user-images.githubusercontent.com/24587985/47227901-34f01480-d3c4-11e8-9ab6-7c8a8f833f02.png)

**Comment by stephan-herrmann** [comment]
I found a mildly related https://bugs.eclipse.org/519944 but that was fixed in Photon (and also backported in 4.7.x).

I'm seeing this bug in
- Version: Photon Release (4.8.0)
- Build id: 20180619-1200

with
-  Wild Web Developer - Web edition in Eclipse IDE (Experimental)	0.1.0.201809111841

**Comment by stephan-herrmann** [comment]
Just for the entertainment factor: since installing Wild Web Developer, Eclipse keeps accumulating more and more buttons "Toggle Highlight". Currently I have twelve instances of that button, which all work in lock step, i.e., (de)selecting one also (de)selects all others.

While this looks like a leak of sorts, too, I wouldn't blame this for the memory leak ...

**Comment by mickaelistria** [comment]
Do you still have the .hprof memory dump file? If yes, could you please share it ?

**Comment by mickaelistria** [comment]
In latest build, another language server is used, which seems to log about nothing. Can you please try upgrading and tell whether it seems to improve the memory consumption?

**Comment by mickaelistria** [comment]
This seems to be a bug in LSP4E. Can you please report the bug there?

**Comment by mickaelistria** [comment]
I'm marking this as resolved because it's fixed upstream. You'll need to install a recent build of LSP4E (no ready yet, should be in a few minutes) to take advantage of the fix.
Don't hesitate to reopen if this seems to still happen with more recent lsp4e.
