### ISSUE TITLE
Angular editor integration is not working.

### ISSUE THREAD

**Issue by Artur51** [eclipse/wildwebdeveloper#842]
I have downloaded the package from https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/
running on the Windows 10 PC. I unpacked it and opened the angular project I had. None of the features except text highlighting is working for me. What is the reason?

**Comment by Artur51** [comment]
Something is wrong with my workspace. when I have created a new one the features for the code navigation and rename are working.

**Comment by mickaelistria** [comment]
Thanks for verifying and closing!
