### ISSUE TITLE
Eclipse core dumps after upgrade to webkit2gtk 2.36.5

### ISSUE THREAD

**Issue by 4javier** [eclipse/wildwebdeveloper#843]
Eclipse crashes dumping core when trying to edit some scss code.
```
Module java with build-id a66934894cccfbd0e5876e4fb647b4511b98712f
Stack trace of thread 15917:
#0  0x00007f0e9f28e36c n/a (libc.so.6 + 0x8e36c)
#1  0x00007f0e9f23e838 raise (libc.so.6 + 0x3e838)
#2  0x00007f0e9f228535 abort (libc.so.6 + 0x28535)
#3  0x00007f0dcbc413f6 n/a (libwebkit2gtk-4.0.so.37 + 0x6413f6)
#4  0x00007f0dcbf94df1 n/a (libwebkit2gtk-4.0.so.37 + 0x994df1)
#5  0x00007f0dcbfc7947 n/a (libwebkit2gtk-4.0.so.37 + 0x9c7947)
#6  0x00007f0e71ac2c3c n/a (libgobject-2.0.so.0 + 0x23c3c)
#7  0x00007f0e71ac3d91 g_object_new_with_properties (libgobject-2.0.so.0 + 0x24d91)
#8  0x00007f0e71ac486a g_object_new (libgobject-2.0.so.0 + 0x2586a)
#9  0x00007f0dcbfa9a5c n/a (libwebkit2gtk-4.0.so.37 + 0x9a9a5c)
#10 0x00007f0e7164a777 g_once_impl (libglib-2.0.so.0 + 0x7f777)
#11 0x00007f0dcbfa9af6 webkit_web_context_get_default (libwebkit2gtk-4.0.so.37 + 0x9a9af6)
#12 0x00007f0dce805e8c Java_org_eclipse_swt_internal_webkit_WebKitGTK_webkit_1web_1context_1get_1default (/home/javier/.eclipse/org.eclipse.platform_4.24.0_155965261_linux_gtk_x86_64/configuration/org.eclipse.osgi/168/0/.cp/libswt-webkit-gtk-4952r11.so + 0x5e8c)
#13 0x00007f0e8140d4da n/a (n/a + 0x0)
#14 0x00007f0e814092fb n/a (n/a + 0x0)
#15 0x00007f0e8140922c n/a (n/a + 0x0)
#16 0x00007f0e8140922c n/a (n/a + 0x0)
#17 0x00007f0e81409340 n/a (n/a + 0x0)
#18 0x00007f0e81409385 n/a (n/a + 0x0)
#19 0x00007f0e814097d7 n/a (n/a + 0x0)
#20 0x00007f0e81409385 n/a (n/a + 0x0)
#21 0x00007f0e8140922c n/a (n/a + 0x0)
#22 0x00007f0e8140922c n/a (n/a + 0x0)
#23 0x00007f0e8140922c n/a (n/a + 0x0)
#24 0x00007f0e8140922c n/a (n/a + 0x0)
#25 0x00007f0e8140922c n/a (n/a + 0x0)
#26 0x00007f0e82b74124 n/a (n/a + 0x0)
ELF object binary architecture: AMD x86-64
```

> org.eclipse.platform.ide
4.24.0.I20220607-0700

> org.eclipse.wildwebdeveloper.feature.feature.group
0.10.14.202205271506

Gnome 42.3 on Arch Linux, for what it's worth.

**Comment by 4javier** [comment]
It looks like the issue is not limited to this plugin.
Eclipse core dumps even when trying to open javadoc view due to webkit.

**Comment by akurtakov** [comment]
Are other webkitgtk applications (e.g. epiphany) working for you?

**Comment by 4javier** [comment]
Yes. But it links webkit2gtk-4.1, 
```
[javier@ThinkArch ~]$ ldd /usr/bin/epiphany | grep webkit
	libwebkit2gtk-4.1.so.0 => /usr/lib/libwebkit2gtk-4.1.so.0 (0x00007ffb8e600000)
```
that's been the default since Gnome 42
https://discourse.gnome.org/t/webkit2gtk-4-1-added-to-gnome-sdk-webkit2gtk-4-0-deprecated/7053
While Eclipse still links webkit2gtk-4.0 as you can see in the log I posted in the first message.

**Comment by 4javier** [comment]
But if you were thinking about a bug in the binary itself, I launched devhelp and browsed some docs with no problem.
```
ldd /usr/bin/devhelp | grep webkit
libwebkit2gtk-4.0.so.37 => /usr/lib/libwebkit2gtk-4.0.so.37 (0x00007f759d800000)
```

**Comment by akurtakov** [comment]
Interesting, /usr/lib64/libwebkit2gtk-4.0.so.37 is shipped in webkit2gtk3-2.36.5-1.fc36.x86_64 on Fedora 36. I wonder what caused the so version bump on Arch. And actually what is the "upstream" versioning for that version.

**Comment by 4javier** [comment]
Wait: 4.0.so.37 still link libsoup 2.x
```
ldd /usr/lib/libwebkit2gtk-4.0.so.37 | grep libsoup
libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007fc354988000)
```
It's 4.1 that links libsoup 3.x
```
ldd /usr/lib/libwebkit2gtk-4.1.so | grep libsoup
libsoup-3.0.so.0 => /usr/lib/libsoup-3.0.so.0 (0x00007f610915f000)
```

**Comment by 4javier** [comment]
Someone debugged the lib and found probable cause
https://bugs.archlinux.org/task/75453#comment209840
> Enabling debuginfod in gdb obtains a more useful backtrace:[ https://linx.marussy.com/obbv0az6.txt](https://linx.marussy.com/obbv0az6.txt)
It looks like the crash is due to this failed assertion:[ https://github.com/WebKit/WebKit/blob/webkitgtk/2.36/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp#L101](https://github.com/WebKit/WebKit/blob/webkitgtk/2.36/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp#L101)
While the files mentioned in the trace haven't been changed recently, the semantics of isMainThread have indeed been changed between 2.36.4 and 2.36.5: see[ https://github.com/WebKit/WebKit/commit/50d7bfe855ca043cc72ec09b3d3d75100015101b#r78597817](https://github.com/WebKit/WebKit/commit/50d7bfe855ca043cc72ec09b3d3d75100015101b#r78597817) and[ https://github.com/WebKit/WebKit/commit/6a1445596f978d93f7eafe50629115d896d3a22b](https://github.com/WebKit/WebKit/commit/6a1445596f978d93f7eafe50629115d896d3a22b)
I suspect this is either an upstream bug (the semantics of isMainThread are still off), or a bug in Eclipse, i.e., SWT is calling webkitgtk2 functions in a manner that is not thread-safe, but allowed by the previous (wrong) isMainThread semantics.

**Comment by 4javier** [comment]
Thanks for opening the right ticket.

**Comment by akurtakov** [comment]
NP, if only it was that easy to come with a fix too !

**Comment by 4javier** [comment]
Concurrent programming is out of my league.
That's why I pinged the user who debugged it.

**Comment by akurtakov** [comment]
> @akurtakov Well, one way to fix this (temporarily) is to revert the commit in question locally, then rebuild webkitgtk2. But that might be _spectacularly_ slow, considering the size of the webkit codebase. slightly_smiling_face

And that would not help users as we can't expect each of them to rebuild webkitgtk.
