### ISSUE TITLE
Eclipse XSD catalog is not used for code completion

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/wildwebdeveloper#846]
This is a sample XML file - see the schema location mapping:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://some.invalid.host.com"
           version="12.1">
	<context-root>MyWeb</context-root>
</jboss-web>
```

I added an entry to the XSD catalog and point the schema location to a file of my local WildFly 26.1 installation:
![grafik](https://user-images.githubusercontent.com/138049/183305795-677f3945-e0ca-4832-9219-1051bfd2f8fa.png)

It seems the file validates, so my catalog entry is picked from somewhere (the screenshot shows a validation error in the "Generic Text Editor" on an invalid element).
But code completion does not seem to use the catalog:
![grafik](https://user-images.githubusercontent.com/138049/183305831-a54d72e4-918a-436f-b96e-85d1bb7206cf.png)

(actually, the schema location should be "http://www.jboss.org/schema/jbossas/jboss-web_12_1.xsd" - but it was a longer step from an error of mine to a reproduceable sample). 

More strange:
I use the "JBoss Tools" plugin, which adds this XSD with the schema location "http://www.jboss.org/j2ee/schema/jboss-web_12_1.xsd" to the XSD catalog - this was the naming scheme that was used until 12.0 and then changed.  
![grafik](https://user-images.githubusercontent.com/138049/183305982-3b565969-6dbc-4eff-8baa-8f0ad3b8cd79.png)

When using this schema location, there is a validation error:
`Error while downloading 'http://www.jboss.org/j2ee/schema/jboss-web_12_1.xsd' to 'C:\Users\USERNAME\.lemminx\cache\http\www.jboss.org\j2ee\schema\jboss-web_12_1.xsd'.`	
So it seems the catalog is not used here?

When using a HTTPS URL (http://www.jboss.org/j2ee/schema/jboss-web_12_1.xsd), no error/warning is shown at all - I thought invalid schema locations were fixed by [https://github.com/eclipse/lemminx/issues/1143]?

**Comment by angelozerr** [comment]
suggest that you install last version of WWD https://github.com/eclipse/wildwebdeveloper/releases/tag/0.15.0

**Comment by WolfgangHG** [comment]
Still testing with Eclipse 2022-6, as we had a discussion in issue eclipse/lemminx#1143 about an already fixed schema validation bug. I am awaiting your feedback...

My first problem is resolved I think: WildWebDeveloper has a custom XSD catalog, which seems to be populated only with the old style "Plugin specific entries". My "User specified entry" is not copied to the file.
I could make it work by adding a custom catalog file and adding my own url mapping:

![wildwebdeveloper_catalog](https://user-images.githubusercontent.com/138049/183990125-2747acaf-280d-4580-932e-85a393dd9922.png)


```
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">
<uri name="http://some.invalid.host.com" uri="http://www.jboss.org/schema/jbossas/jboss-web_12_1.xsd"/>
</catalog>
```

Could you confirm that this is the expected behaviour? One could argue that user specific entries of the old style catalog should also be migrated to a second WildWebDeveloper catalog?

**Comment by WolfgangHG** [comment]
And then (after some changes back and forth) problem 1 is back again and I cannot make my custom catalog entry work.  Maybe I will try it again tomorrow...

**Comment by angelozerr** [comment]
> I am awaiting your feedback...

See my answer at https://github.com/eclipse/lemminx/issues/1143#issuecomment-1211447535

> Could you confirm that this is the expected behaviour? One could argue that user specific entries of the old style catalog should also be migrated to a second WildWebDeveloper catalog?

I think it works like this. @vrubezhny @mickaelistria is there any reason why User WTP XML catalog is not migrated in XML catalog of LemMinx?

> And then (after some changes back and forth) problem 1 is back again and I cannot make my custom catalog entry work. Maybe I will try it again tomorrow...

I think your catalog should inlude other XSD (see the inlucde and import declared in the add XSD)

**Comment by WolfgangHG** [comment]
Today, it also does not work - don't know why it worked yesterday once ;-).

How should the catalog entries look like? This does not work / does not change the problem:

```
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">
<uri name="http://some.invalid.host.com" uri="http://www.jboss.org/schema/jbossas/jboss-web_12_1.xsd"/>
<uri name="http://www.jboss.org/schema/jbossas/web-app_3_1.xsd" uri="http://www.jboss.org/schema/jbossas/web-app_3_1.xsd"/>
<uri name="http://www.jboss.org/schema/jbossas/jboss-common_7_1.xsd" uri="http://www.jboss.org/schema/jbossas/jboss-common_7_1.xsd"/>

</catalog>
```

**Comment by angelozerr** [comment]
The uri/@uri attribute reference the same http uri than uri/@name. As it seems you have à pronlem with download because for instance with proxy problem xml catalog is a good solution for that. It means that you need to download xsd at hand in your computer and after that uri/@uri must reference the downloaded xsd and not the http xsd.

**Comment by WolfgangHG** [comment]
Nope, there is no download problem on my machine - no proxy involved and the regular urls for the files work as expected. And "some.invalid.host.com" is really invalid ;-).
To explain why I started here: the schema location changed beetween "jboss-web_12_0.xsd" (https://www.jboss.org/j2ee/schema/jboss-web_12_0.xsd) and 12.1 (http://www.jboss.org/schema/jbossas/jboss-web_12_1.xsd), but I did not noticed this first. So I started playing with the xml catalog. There is no actual requirement to remap this file as it is online, but in the past the JBoss folks sometimes forgot to publish XSD files to their website, so there was the need for the xml catalog.

I also tried to set a file location in my catalog file - which does not work either:

`<uri name="http://some.invalid.host.com/jboss-web_12_1.xsd" uri="file:///C:/Temp/wildfly-26.1.0.Final/docs/schema/jboss-web_12_1.xsd"/>
`

The old Eclipse XML editor seems to use my catalog entry as expected (see first screenshot of this issue), as code completion works with only this catalog entry.

Could you create a working wildwebdeveloper catalog entry for "jboss-web_12_1.xsd" that uses maps any invalid host to a local file and show me how it should look like? Maybe I have a misunderstanding on the usage of the xml catalog, but in the moment I think there is a bug somewhere.

The files can be found in a WildFly 26.1 download [https://github.com/wildfly/wildfly/releases/download/26.1.1.Final/wildfly-26.1.1.Final.zip](https://github.com/wildfly/wildfly/releases/download/26.1.1.Final/wildfly-26.1.1.Final.zip) in the "docs/schema" directory.

**Comment by angelozerr** [comment]
I read again your original issue and if you have jboss tools which provide a wtp catalog with http://www.jboss.org/j2ee/schema/jboss-web_12_1.xsd and if you have lemminx 0.21.0 you should be able to use http://www.jboss.org/j2ee/schema/jboss-web_12_1.xsd in your schemaLocation. Your error with download should not occur since it should use wtp catalog

**Comment by WolfgangHG** [comment]
Yep, it works if I use the "real" XSD url in the schemaLocation attribute of "jboss-web.xml". 
All my testing is just a theoretical approach - it should also work if the schemaLocation points to an invalid URI and is remapped through the XSD catalog ;-).

**Comment by angelozerr** [comment]
OK if understand yiu can benefit with completion based on xsd coming from wtp catalog.with jboss xsd. It should have none donwload (you  an check that by removing .lemminx cache folder and try completion again )

Is it that?

The usecase that it seems that it doesnt work is to use catalog to remap a given http uri to another http uri.

Could you create an issue in lemminx github project please. Thanks

**Comment by WolfgangHG** [comment]
Closing this issue, as I filed a new one as requested.
