### ISSUE TITLE
Validation error popup has wrong size

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/wildwebdeveloper#848]
This can be reproduced the setting "Enable schema based validation = Always" and this xml snippet:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://some.invalid.host.com"
           version="12.1">
</jboss-web>
```

The popup for the validation error is too small (but my screen is wide enough at 1920x1280) - the error message is not shown completely, and the popup does not have a horizontal scrollbar:
![validationerror](https://user-images.githubusercontent.com/138049/184534091-8a244c88-3d12-4147-8360-c04174a037b8.png)

It took me some time until I noticed that the popup can be resized. When making it large enough so that the full text is shown, a vertical scrollbar appears.
![validationerror_resized](https://user-images.githubusercontent.com/138049/184534162-61ef4bf1-b20f-492e-8d06-829f5db025e3.png)

Seems there is a resizing issue.

**Comment by WolfgangHG** [comment]
Done.

**Comment by mickaelistria** [comment]
Thank you. Let's close the issue here.
