### ISSUE TITLE
Invalid "schemaLocation" is not reported if "Enable schema validation = In valid schema"

### ISSUE THREAD

**Issue by WolfgangHG** [eclipse/wildwebdeveloper#849]
This is a followup to eclipse/lemminx#1143 and eclipse/lemminx#1272: this xml file has an invalid schema location URL:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web xmlns="http://www.jboss.com/xml/ns/javaee"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee http://some.invalid.host.com"
           version="12.1">
</jboss-web>
```

The invalid schema url is only reported if the setting "Enable schema based validation" is set to "Always".

![validation](https://user-images.githubusercontent.com/138049/184703115-d5acda6b-186a-4302-8602-83aa02e7faef.png)

This is the error:
![error](https://user-images.githubusercontent.com/138049/184703177-10084214-3730-4e1c-bf99-4378b1914f5c.png)

But the default "In valid schema" does not report this error.

I consider this a bug: if a schema location is specified, the user should be informed in case this location is invalid. Otherwise, the user could think that the xml file is valid as no errors are shown. And code completion will not work, but the user will not see the reason.

In eclipse/lemminx#1143, @angelozerr suggested to change the default value for this setting to "Always".

**Comment by mickaelistria** [comment]
I agree with you and @angelozerr here. Would you be willing to submit a patch that change the default value of the preference?

**Comment by WolfgangHG** [comment]
@mickaelistria Sorry, I don't have enough time to dig into WildWebDeveloper. And you probably want to seduce me to do more coding after this first issue ;-).
