### ISSUE TITLE
not able to download gwt 3.0.0 plugin in eclipse 2202.06 software

### ISSUE THREAD

**Issue by NikithaSiddesh** [eclipse/wildwebdeveloper#867]
Getting this error when I try to install GWT from eclipse market place
![image](https://user-images.githubusercontent.com/93253560/189808323-949996bd-9e5f-455c-98c9-838c5f8c4e92.png)

**Comment by akurtakov** [comment]
Looks like you filed against wrong project. Most likely you have to file this report in https://github.com/gwt-plugins/gwt-eclipse-plugin .
