### ISSUE TITLE
Update site of releases is very large

### ISSUE THREAD

**Issue by guw** [eclipse/wildwebdeveloper#870]
Mirroring https://download.eclipse.org/wildwebdeveloper/releases/latest/ takes a long time and I noticed this is mostly because WildWebDeveloper brings in a whole release train repository by itself.

Is it possible to provide a "light" site with just the WWD release without the additional IDE content?

**Comment by mickaelistria** [comment]
If you need to mirror a subset of the site, you totally can do it on your end; using the available options of the p2 mirror application/tasks. From Wild Web Developer perspective, there is no benefit in building a trimmed p2 repository.
