### ISSUE TITLE
No syntax color and check on Generic Text Editor for Javascript

### ISSUE THREAD

**Issue by mugener** [eclipse/wildwebdeveloper#894]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=580823

I update my Eclipse from 3.26(2022-06) to 3.27(2022-09).

And Javascript files on Geneirc Text Editor have no syntax color and check,
just like when you open Javascript file with Text Editor.

The code folding function is still working,
but without syntax color and check,
it made me almost impossible to work with Javascript.

I really need someone to check it out, thanks.

**Comment by mickaelistria** [comment]
Please share the content of your log file (in <eclipse-workspace>/.metadata/.log)

**Comment by akurtakov** [comment]
And make sure you run using Java 17 as TM4E (responsible for highlighting) requires it.

**Comment by mugener** [comment]
> Please share the content of your log file (in /.metadata/.log)

Here it is:
[log.txt](https://github.com/eclipse/wildwebdeveloper/files/9667557/log.txt)

> And make sure you run using Java 17 as TM4E (responsible for highlighting) requires it.
This is in my eclipse.ini:
-vm
C:/Program Files/Java/jdk-14.0.2/bin/server/jvm.dll

I want to make sure, does it means only I encounter this problem,
and both of your Javascript syntax work fine on eclipse 3.27(2022-09)?

**Comment by mickaelistria** [comment]
JavaScript development (and other things that are not working for you according to your log file) does work correctly using 2022-09, and running it with Java 17. Java 17 is usually embedded in the IDE, so this `-vm` option seems a bit strange.

**Comment by mugener** [comment]
> JavaScript development (and other things that are not working for you according to your log file) does work correctly using 2022-09, and running it with Java 17. Java 17 is usually embedded in the IDE, so this `-vm` option seems a bit strange.

But how does that explain that other file lik .java or .html have no problem for me
on syntax color and check, but only .js files got this problem?
And why is it happen on 2022-9, but not on old eclipse like 2022-06?

if I remove that -vm option in eclipse.ini, I can't even start eclipse with error:
![error](https://user-images.githubusercontent.com/72055699/193217151-2ef1f03d-234c-40db-a8e3-cd8fb6fadd87.png)

Here is my eclipse.ini:
[eclipse.ini.txt](https://github.com/eclipse/wildwebdeveloper/files/9681824/eclipse.ini.txt)

Please enlighten me what should I do to fix it, thank you.

**Comment by mickaelistria** [comment]
Not everything in Eclipse IDE does require Java 17; everything that does require Java 14 or older does work with Java 14. That's the case of eg .java support; but it's not the case of javascript.
I think it's better if you just download a new IDE from https://www.eclipse.org/downloads/packages/ (take the packages instead of the installer, it's usually simpler), as it should come with a Java Runtime embedded on the right version and also upgradablel; and then open your new IDE using existing workspace location.
Or, if you really need to stick to your current IDE, just change the path after `-vm` to point to Java 17.

**Comment by mugener** [comment]
> Or, if you really need to stick to your current IDE, just change the path after `-vm` to point to Java 17.

If Java 17 is in eclipse IDE, where is the path, features or plugin folder?

**Comment by mickaelistria** [comment]
> If Java 17 is in eclipse IDE, where is the path, features or plugin folder?

I can't tell from your installation, it doesn't seem to be a recent vanilla installation. Hence why I suggest to restart from a fresh installation where you wouldn't have any problem.

> Please help me to change that -vm option with more detail, thank you.

Just look at how it was set initially, and adapt from it.

**Comment by mugener** [comment]
> Just look at how it was set initially, and adapt from it.

Where can I find that orignal eclipse.ini?

Sorry to bother you with those question, I just want to slove it as soon as possible.

The reason that I want to stick whit my IDE is because I changed lot of setting
for my personal use, hope you can understand.

**Comment by mickaelistria** [comment]
>  I changed lot of setting for my personal use

Those are usually stored in your workspace area; so opening a newer IDE on the same workspace will preserve those.

**Comment by mugener** [comment]
> > I changed lot of setting for my personal use
> 
> Those are usually stored in your workspace area; so opening a newer IDE on the same workspace will preserve those.

But what about server with databae?

I use Tomcat as server and Derby as database, it took me times to set them up on IDE,
how should I adopt them on new IDE?

**Comment by mugener** [comment]
OK, I use an new IDE 2022-09, and this .js problem is solved.

I shall try to figure out how to merge it into my old IDE.

Thanks for your help.
