### ISSUE TITLE
Fix target platform in master

### ISSUE THREAD

**Issue by jabby** [eclipse/wildwebdeveloper#90]
As you can see on the latest build for master branch, there is a problem about target platform. 
https://jenkins.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/master/16/ 

I will provide a fix in few minutes. 

@mickaelistria should I increment the version number of Wild Web Developer?

**Comment by mickaelistria** [comment]
Thanks!

**Comment by mickaelistria** [comment]
We do not increment version numbers for TP change. We may increment version numbers when we modify the version range for depedencies in MANIFEST.MF.

**Comment by jabby** [comment]
OK thanks for the explanation.

**Comment by jabby** [comment]
There is a problem on the ci. 
I get the following error. Should I ask the 
```
[ERROR] Failed to resolve target definition /home/jenkins/workspace/Wildwebdeveloper_master-ROJ4BPCU4Q5VTI7VBBSR4KWQVLVOSBZHJPOZ6FPJL3JEULICJSWQ/target-platform/target-platform.target: Failed to load p2 metadata repository from location http://download.eclipse.org/eclipse/updates/4.9/: Unable to read repository at http://download.eclipse.org/eclipse/updates/4.9. Unable to read repository at http://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/content.xml.xz. Read timed out -> [Help 1]
```

Should I create a ticket on [Community/CI-Jenkins](https://bugs.eclipse.org/bugs/buglist.cgi?component=CI-Jenkins&list_id=18028498&product=Community&resolution=---)?

**Comment by mickaelistria** [comment]
Yes, please open a ticket.

**Comment by mickaelistria** [comment]
Build is back to green!

**Comment by jabby** [comment]
Yes!
