### ISSUE TITLE
tsserver et al cannot be executed

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/wildwebdeveloper#95]
After installing wildwebdeveloper via Oomph none of the language server functionality worked.
All I got was a log message essentially saying: `[ERROR: spawn EACCES]`. No hint at what was tried to access.

After a lot of aimlessly poking around, I first found, that some "executables" didn't have executable permission (on linux), so I ran `chmod u+x` for them: 
- `vscode-languageserver/bin/installServerIntoExtension`
- `typescript-language-server/lib/cli.js`
- `typescript/bin/tsserver`
- `typescript/bin/tsc`
- `vscode-json-languageserver/bin/vscode-json-languageserver`

Still no luck.

Much later I found the directory `language-servers/node_modules/.bin` and inside I found some broken text files. From comparison with a checked out workspace of wildwebdeveloper I learned, that those files were supposed to be symbolic links, but instead they were just files containing the target file name padded with several trailing null-bytes.

BTW, I couldn't see, what unpacked the wwd jar file, since the feature says `unpack="false"`. Is it actually the `FileLocator.toFileURL()` call in `JSTSLanguageServer` that triggers this unpacking? Anyway, either the build process needs to avoid symbolic links or the unpack routine must restore them as links.

**Comment by stephan-herrmann** [comment]
BTW, I only mentioned Oomph, because that was the only difference between working and not-working installation that I could think of. Take it as a wild guess - might be totally unrelated.

**Comment by jabby** [comment]
Thanks for your report. 
I'm not familiar with Oomph. How did you install a plugin through Oomph?

**Comment by stephan-herrmann** [comment]
Also in that fresh install mentioned above I need to do (at least) these commands to get any typescript support in the IDE:
```
$ cd eclipse/plugins/org.eclipse.wildwebdeveloper_0.1.0.201811161652/language-servers/node_modules/.bin
$ rm tsserver
$ ln -s ../typescript/bin/tsserver
$ rm tsc
$ ln -s ../typescript/bin/tsc
$ chmod u+x tsserver tsc
```

Then restart Eclipse.

Certainly not a procedure that I can expect of those colleagues whom I try to convince to migrate towards Eclipse for their JS/TS development ;p

**Comment by mickaelistria** [comment]
Maybe this works for us because`tsserver` and `tsc` are available in other locations as well and uses them? We definitely need automated tests for Wild Web Developers to spot those issues.

**Comment by mickaelistria** [comment]
By the way, you know OSS,it's not «your» build. It's everyone's.

**Comment by stephan-herrmann** [comment]
> Maybe this works for us because`tsserver` and `tsc` are available in other locations as well and uses them?

If you look into `LspServer.findTserverPath()` you'll see a bunch of options where `tserver` can be found. This could explain why it works on some machines not on others. It still doesn't explain, why it stopped working on a machine where previously it worked -- but then I'm not 100% sure it hadn't accidentally found a tserver in, say, `<workspaceroot>/node_modules`.

More constructively, if I saw correctly, that part of the plugin structure is created by `npm install` at build-time, right? Given that symlinks are fragile when packaged, can npm be stopped from creating symlinks in the first place? (I am completely illiterate concerning npm).

**Comment by jabby** [comment]
I did not realize that npm install create symlinks. The symlinks are for vscode language server I guess. 
We should ask some guys at microsoft to add vscode language servers to npm instead of using relative path in package.json. 
Actually I am quite busy at work and about personnal stuffs. I hope I can do some check next friday but I'm not sure.

**Comment by mickaelistria** [comment]
Are all language servers affected or only the JS/TS one?
I think the change that cause that is https://github.com/eclipse/wildwebdeveloper/commit/06debb004842f80a927b6f6614b495153dbeb50d

**Comment by stephan-herrmann** [comment]
This does the trick for me (tested only for typescript, none of the other language servers):

[issue-95.txt](https://github.com/eclipse/wildwebdeveloper/files/2669664/issue-95.txt)

**Comment by mickaelistria** [comment]
With automation and addition of test performed in #96 / #97, this error in now surfacing elegantly as test failures on CI: https://jenkins.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/master/29/
@stephan-herrmann Would you be able to submit your patch as a Pull Request?

**Comment by stephan-herrmann** [comment]
Three steps towards a pull request:

1. I need to learn how to create a pull request (not sure why people deem that easier than working with patches, or gerrit ...). Is creating a public fork really necessary? Hmmm..
2.  I want to fix using language servers also on windows by adding missing .cmd files
3.  To be sure I'm not breaking anything, I'd like to run the build on windows.

Currently, (3) fails for me with
```
npm ERR! path C:\Users\sherrmann\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\language-servers\node_modules\.staging\vscode-json-languageserver-87fa5769\node_modules\agent-base
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\sherrmann\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\language-servers\node_modules\.staging\vscode-json-languageserver-87fa5769\node_modules\agent-base' -> 'C:\Users\sherrmann\git\wildwebdeveloper\org.eclipse.wildwebdeveloper\language-servers\node_modules\.staging\agent-base-7dc2fc85'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sherrmann\AppData\Roaming\npm-cache\_logs\2018-12-15T14_44_53_553Z-debug.log
[ERROR] Command execution failed.
```

I have no idea what `npm` is trying to tell me and why.

**Comment by mickaelistria** [comment]
This can actually be improved in the Language Server directly: https://github.com/theia-ide/typescript-language-server/issues/93

**Comment by stephan-herrmann** [comment]
> This can actually be improved in the Language Server directly: [theia-ide/typescript-language-server#93](https://github.com/theia-ide/typescript-language-server/issues/93)

This is very good news! Cool.

**Comment by mickaelistria** [comment]
This should now be fixed and some automated tests are checking language servers startup well and send diagnostics, so there is much less risk for such issues to happen now.
