### ISSUE TITLE
Quick Fix to disable eslint rule for file uses ineffective comment syntax

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/wildwebdeveloper#956]
When editing a TypeScript file with an eslint rule violation, the editor provides a Quick Fix action on the violating line to disable the rule for the entire file.  Doing so adds a comment like this to the top of the file:
```
/** eslint-disable <rule-name> */
```
But, after doing this, the violations that should be ignored remain present.

Looking at [eslint's documentation](https://eslint.org/docs/latest/user-guide/configuring/rules#using-configuration-comments-1), it appears that file-wide `eslint-disable` comments must use a single leading star in the comment block, not two:
```
/* eslint-disable <rule-name> */
```
Indeed, manually editing any file-wide disable comment added by the Quick Fix action to use a single leading star causes rule violations to be ignored as intended.

From this, if the Quick Fix action is a custom-built feature of WWD and isn't coming from a language server or something, and the single-star requirement isn't a hard-to-predict version-dependant behaviour of eslint, then the Quick Fix should generate its file-wide disable comments to use one leading star, not two, so they won't get ignored.

**Comment by mickaelistria** [comment]
Should be fixed is https://github.com/microsoft/vscode-eslint/pull/1553 is approved and when Wild Web Developer incorporates a version of vscode-eslint with the fix
