### ISSUE TITLE
Can't launch/debug *.cjs files

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/wildwebdeveloper#958]
Trying to launch a *.cjs file hangs indefinitely, and trying to debug it fails with this error:
> Unexpected exception
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Cannot launch program '{path}'; configuring source maps might help.

That comment about source maps suggests that WWD/lsp4j doesn't realize that *.cjs files are CommonJS modules, which are just JavaScript files with a specific module system, and thus don't need source maps.

A workaround is to simply rename a *.cjs file to *.js, which also proves that there isn't anything inherent about *.cjs files that WWD can't handle.

Maybe this is a lsp4j issue, but the fact that WWD can't even run a *.cjs file at all seems unrelated to language servers, so I filed it here.

**Comment by mickaelistria** [comment]
Can you please share a minimal project and minimal steps to reproduce?

**Comment by AndrewFerr** [comment]
All that's needed is a general project with a `*.cjs` file containing any content at all.

The following project structure is sufficient:
```
myProject
- .settings
- .project
- index.cjs
```
where `index.cjs` is a trivial "Hello World" program.

If it makes a difference, I'm using a system-installed version of `node`, not the one provided by WWD.  Running `node index.cjs` in a terminal works fine, and so does renaming it to `index.js` and running it in Eclipse.

**Comment by mickaelistria** [comment]
I can reproduce the issue. The issue is caused by the vscode-node-debug2 debug adapter that is used by Wild Web Developer. This one doesn't understand *.cjs as being executable/debug-able by default.
There seems to be a possible hack setting `__debuggablePatterns` in the args params; but I'm afraid this can cause issue later on.
