### ISSUE TITLE
Enable license-check on package.json

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#965]
Now that Wild Web Developer uses a package.json. we have dependabot upgrade proposals, and that's a great thing.
To ensure we don't merge to eagerly (like I did in #964 ), we should have the Dash license tool processing this package.json file as well.

**Comment by mickaelistria** [comment]
@HannesWell Are you aware of any example of a project enabling that; mixing some reviews from Maven deps and from npm deps?

**Comment by HannesWell** [comment]
Unfortunately not. 
And I'm not familiar with NPM.

**Comment by mickaelistria** [comment]
Attempting it at https://github.com/eclipse/wildwebdeveloper/pull/967

**Comment by mickaelistria** [comment]
So #967 works!
But Wild Web Developer using npm packages from vscode archive, which are not published to npmjs doesn't make the automatic license check succeed... I think the dash-license tool can be improved on that matter.

**Comment by mickaelistria** [comment]
I opened https://github.com/eclipse/dash-licenses/issues/192 which is related (not a solution, but at least makes the issue more explicit)

**Comment by mickaelistria** [comment]
Check is now available.
We may improve it later to add automatic creation of IP reviews, but the current state is already good enough to close this ticket.
