### ISSUE TITLE
Feature request: Allow `tsconfig.json` to have trailing commas

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/wildwebdeveloper#971]
WWD cannot start a debug session for a `*.ts` file unless its corresponding `tsconfig.json` is free of trailing commas & comments (i.e. it must be "true" JSON).  In contrast, `tsc` and the TypeScript language server (or at least recent versions of them) have no trouble with dealing with that.  It must be they allow the `tsconfig.json` to use the syntax of a `*.jsonc` / "JSON with comments" file.

This means it may be possible to build & run a TypeScript project in a terminal, but not debug it in WWD (unless attaching to a running instance), because WWD's requirements on what constitutes a valid `tsconfig.json` are stricter than `tsc`'s.

To save the effort of having to edit a `tsconfig.json` just to make it compatible with WWD, it would be nice if WWD could be more lax in its parsing of the `tsconfig.json` file, to parse only the bare minimum of what it needs to start a debug session.

**Comment by mickaelistria** [comment]
I think the entry point where to read the tsconfig.json file with higher tolerance is NodeRunDAPDebugDelegate.readJSonFile . Would you be interested in trying to contribute a fix?

**Comment by mickaelistria** [comment]
You may want to try replacing `new Gson()` by `new GsonBuilder().setLenient().create()`.

**Comment by mickaelistria** [comment]
OK, thanks for testing! If there is another JSON parsing library that can be used to fix it, I believe it's OK for Wild Web Developer to use it instead of GSON.

**Comment by AndrewFerr** [comment]
Actually, a simple fix would be to just strip out end-of-line commas in the file before passing it to GSON.

It may still be a good idea to migrate from GSON since it's in maintenance mode (though I can't imagine how much continuous development a JSON parser would need), but for now handling this parsing issue locally should be sufficient.

I intend to provide a contribution for this.
