### ISSUE TITLE
Usage with Eclipse Platform Runtime Binary

### ISSUE THREAD

**Issue by mlocati** [eclipse/wildwebdeveloper#981]
AFAIK, Eclipse Platform Runtime Binary is the most basic distribution of Eclipse.

I'm trying to use WildWebDeveloper with it.

Here's what I did:

1. go to https://download.eclipse.org/eclipse/downloads/drops4/R-4.25-202208311800/#PlatformRuntime and download Eclipse Platform Runtime Binary
2. in Eclipse: `Help` > `Install New Software`
3. add the http://download.eclipse.org/wildwebdeveloper/snapshots p2 repository
4. install `Eclipse Wild Web Developer - Web Dev in Eclipse IDE`

With these steps, it seems we don't have any new feature.
For example, if I create a new empty project and add a `test.json` file, if I ask Eclipse to edit it, it opens my default system editor (Visual Studio Code for me).
If I open it with the Eclipse *Generic Text Editor* I don't notice any particular feature (it's like editing a plain text file).
And I don't see any other relevant editor:

![immagine](https://user-images.githubusercontent.com/928116/204756563-5eecb3c9-f17a-484f-9026-9562d63a6d84.png)

Am I missing something?

**Comment by akurtakov** [comment]
WildWebDeveloper and some of it's dependencies require Java 17+ while Eclipse Platform requires 11+ so make sure that you run Eclipse with 17+.

**Comment by mlocati** [comment]
Yep, that was the issue! Thanks!

PS: isn't it possible to add a check about it?

**Comment by akurtakov** [comment]
> Yep, that was the issue! Thanks!
> 
> PS: isn't it possible to add a check about it?

It is possible but needs someone to put the needed work in https://github.com/eclipse-equinox/p2/ . 
Personally, I've embraced "use latest unless there are problems" mantra and don't face these problems ;) .

**Comment by mickaelistria** [comment]
p2 is supposed to have a check about it. I suspect that installing Wild Web Developer did also install a Java 17 runtime, but the configuration of Eclipse IDE wasn't changed to use it. It would indeed be most likely a bug in p2.
